### ISSUE TITLE
thanks for the project ❤ list from GitHub search "ComfyUI" maybe helps 

### ISSUE THREAD

**Issue by camenduru** [Comfy-Org/ComfyUI-Manager#1]
https://github.com/WASasquatch/was-node-suite-comfyui
https://github.com/atlasunified/Templates-ComfyUI-
https://github.com/wyrde/wyrde-comfyui-workflows
https://github.com/camenduru/comfyui-colab
https://github.com/xXAdonesXx/NodeGPT
https://github.com/pythongosssss/ComfyUI-Custom-Scripts
https://github.com/ltdrdata/ComfyUI-Impact-Pack
https://github.com/Davemane42/ComfyUI_Dave_CustomNode
https://github.com/comfyanonymous/ComfyUI_tutorial_vn
https://github.com/BlenderNeko/ComfyUI_Cutoff
https://github.com/LucianoCirino/efficiency-nodes-comfyui
https://github.com/WASasquatch/comfyui-plugins
https://github.com/YanWenKun/ComfyUI-Docker
https://github.com/lilly1987/ComfyUI_node_Lilly
https://github.com/diontimmer/ComfyUI-Vextra-Nodes
https://github.com/ModelSurge/sd-webui-comfyui
https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92
https://github.com/canisminor1990/kitchen-comfyui
https://github.com/biegert/ComfyUI-CLIPSeg
https://github.com/hnmr293/ComfyUI-nodes-hnmr
https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb
https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node
https://github.com/Fannovel16/FN16-ComfyUI-nodes
https://github.com/diontimmer/Sample-Diffusion-ComfyUI-Extension
https://github.com/BadCafeCode/masquerade-nodes-comfyui
https://github.com/m957ymj75urz/ComfyUI-Custom-Nodes
https://github.com/wyrde/ComfyResources
https://github.com/lilly1987/ComfyUI-workflow
https://github.com/adodge/ComfyLib
https://github.com/jug-dev/hordelib
https://github.com/EllangoK/ComfyUI-post-processing-nodes
https://github.com/diffus3/ComfyUI-extensions
https://github.com/guoyk93/yk-node-suite-comfyui
https://github.com/LEv145/images-grid-comfy-plugin
https://github.com/Jcd1230/rembg-comfyui-node
https://github.com/BlenderNeko/ComfyUI_Noise
https://github.com/gamert/ComfyUI_tagger
https://github.com/comfyanonymous/ComfyUI_experiments
https://github.com/lilly1987/ComfyUI-node
https://github.com/tekakutli/comfy-workflows
https://github.com/HoonWi/comfyui
https://github.com/bmad4ever/ComfyUI-Bmad-Custom-Nodes
https://github.com/YinBailiang/MergeBlockWeighted_fo_ComfyUI
https://github.com/trojblue/trNodes
https://github.com/WASasquatch/comfyui-colab-was-node-suite
https://github.com/szhublox/ambw_comfyui
https://github.com/asd417/tomeSD_for_Comfy
https://github.com/aaronlockhartdev/comfyui-docker
https://github.com/lilly1987/ComfyUI_script2
https://github.com/city96/ComfyUI_NetDist
https://github.com/Kaharos94/ComfyUI-Saveaswebp
https://github.com/chenbaiyujason/sc-node-comfyui
https://github.com/SLAPaper/ComfyUI-Image-Selector
https://github.com/BlenderNeko/ComfyUI_TiledKSampler
https://github.com/lilly1987/ComfyUI-script
https://github.com/derek-inc-git/Easy-ComfyUI-Config
https://github.com/ltdrdata/ComfyUI-Manager
https://github.com/ailex000/ComfyUI-Extensions
https://github.com/c0x63c/comfyui-wsl-docker
https://github.com/lilly1987/ComfyUI_script3
https://github.com/flyingshutter/As_ComfyUI_CustomNodes
https://github.com/rock-land/graphNavigator
https://github.com/star-power-storm/comfyui--install-with-conda-bat
https://github.com/AlekPet/comfyui_translate_clip_text_encode_node

**Comment by ltdrdata** [comment]
Thank you.
