### ISSUE TITLE
stderr: 'fatal: Authentication failed for 'https://github.com/comfyanonymous/ComfyUI/''

### ISSUE THREAD

**Issue by laurentopia** [Comfy-Org/ComfyUI-Manager#10]
That's after authentication succeeded
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/26075468/30e6f833-3a65-4c2d-ba38-b0ce74c19273)

**Comment by ltdrdata** [comment]
This is an issue that arises from the mixed GitHub authentication token in the initial ComfyUI portable version. For now, it is necessary to remove the existing version and reinstall the latest portable version.

**Comment by laurentopia** [comment]
I just did that, different error message.
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/26075468/440f88c9-768f-444b-bd76-1cf93a3b1f6c)
