### ISSUE TITLE
'models/checkpoints/put_checkpoints_here' is beyond a symbolic link

### ISSUE THREAD

**Issue by DarkAlchy** [Comfy-Org/ComfyUI-Manager#1000]
error: 'models/checkpoints/put_checkpoints_here' is beyond a symbolic link
fatal: Unable to process path models/checkpoints/put_checkpoints_here
Cannot save the current worktree state

Similar issue to #761 but for my models folder.  I have 200 gigs and don't wish to have to have the same files twice taking up 400 gigs of space.

How can I fix this?

**Comment by ltdrdata** [comment]
You should not use symoblic link.
Use `extra_model_paths.yaml`.

https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example

(Copy and modify it. Don't rename it.)

**Comment by DarkAlchy** [comment]
> You should not use symoblic link. Use `extra_model_paths.yaml`.
> 
> https://github.com/comfyanonymous/ComfyUI/blob/master/extra_model_paths.yaml.example
> 
> (Copy and modify it. Don't rename it.)

Perfect, as that is exactly what I needed as I didn't know how to set it up for ComfyUI but have it set for a1111 where all my old stuff is at.

Thank you. :)

**Comment by DarkAlchy** [comment]
![image](https://github.com/user-attachments/assets/a19f1a35-0bcc-4792-9785-be7ad880f5d9)

I can't seem to get this.

![image](https://github.com/user-attachments/assets/ba657b9b-9bc2-4907-bfae-3990e4404364)

I even tried DZ-FaceDetailer to no avail.  those three refuse.

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/10561690/361192233-a19f1a35-0bcc-4792-9785-be7ad880f5d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NzI3NDYsIm5iZiI6MTcyNDU3MjQ0NiwicGF0aCI6Ii8xMDU2MTY5MC8zNjExOTIyMzMtYTE5ZjFhMzUtMGJjYy00NzkyLTk3ODUtYmU3YWQ4ODBmNWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA3NTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOTUyNmJjM2VmODVlMzliZjY5ZDk2MDExNDQ5NGI4NmM5OGY4ZDljZmRkZjFlMzExMjExODc2YzdhYWQ1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n-R3Qk3xphiksygC-RVYMl1M_AThiWa8RROlfyhnyOM)
> 
> I can't seem to get this.
> 
> ![image](https://private-user-images.githubusercontent.com/10561690/361192246-ba657b9b-9bc2-4907-bfae-3990e4404364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NzI3NDYsIm5iZiI6MTcyNDU3MjQ0NiwicGF0aCI6Ii8xMDU2MTY5MC8zNjExOTIyNDYtYmE2NTdiOWItOWJjMi00OTA3LWJmYWUtMzk5MGU0NDA0MzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA3NTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZWNiYjkzNWUzYjViMTU2ZWRlNjQ2NjRjNzZlYTI3NTZmM2Y0YTY2YmJjYzhmMzAyMmEzY2IxYTE0YzllM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1E8XONCshkdnqpXKUm6etlsb9CDfI7aLwy_tr9Ej55A)
> 
> I even tried DZ-FaceDetailer to no avail. those three refuse.

You should not make `models` as symoblic link. 
Because it is part of  ComfyUI repository file.
But you can convert custom model directory to symbolic link.

**Comment by DarkAlchy** [comment]
In other words any folder not a part of the list it knows I can convert to a sym link?

In other words all these from various nodes I can symlink?

![image](https://github.com/user-attachments/assets/01769158-dc28-4d6b-b703-2f98ae28169c)

**Comment by ltdrdata** [comment]
> In other words any folder not a part of the list it knows I can convert to a sym link?
> 
> In other words all these from various nodes I can symlink?
> 
> ![image](https://private-user-images.githubusercontent.com/10561690/361195760-01769158-dc28-4d6b-b703-2f98ae28169c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1ODI2MTUsIm5iZiI6MTcyNDU4MjMxNSwicGF0aCI6Ii8xMDU2MTY5MC8zNjExOTU3NjAtMDE3NjkxNTgtZGMyOC00ZDZiLWI3MDMtMmY5OGFlMjgxNjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEwMzgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5OTc2YmMyNjgyNDU4NDYwZTdlMDM2ODcwMWVjZjllMzU5ZGJkMmFlOWFlMGU1ZGQ2ZmE4ZmYxYzAxYzZiYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aA2JpUEkRVCW2fsBEutJJkIceVRfu15bZsbi2tU58pY)

yup
