### ISSUE TITLE
May I ask Why is the interface and examples of my installed comfyui-manager so different?

### ISSUE THREAD

**Issue by gmf1982** [Comfy-Org/ComfyUI-Manager#1003]
Why is the interface and examples of my installed comfyui-manager so different?I have upgraded to the latest version.

examples
![PixPin_2024-08-26_12-59-39](https://github.com/user-attachments/assets/dfeb57a9-afb2-4cf2-8981-7fa59a3084bd)

my installed
![PixPin_2024-08-26_12-58-10](https://github.com/user-attachments/assets/879f3402-dd17-4717-a064-728f12f25a62)

**Comment by ltdrdata** [comment]
That is very outdated version.

It's usually one of two things: either you mistakenly thought "Fetch Updates" meant "update" and were updating incorrectly, or you should have installed using the `git clone` method but instead downloaded a zip file and installed by extracting it, which is the wrong way.

Personally, I recommend safely uninstalling and then reinstalling.
https://github.com/ltdrdata/ComfyUI-Manager#installation
