### ISSUE TITLE
Removing ID602 Custom Node - Comfyui_image2prompt

### ISSUE THREAD

**Issue by DeepSeaCatz** [Comfy-Org/ComfyUI-Manager#1004]
I'm not sure if this is the right place to ask this, but there's currently a custom node in the manager ID602 named [Comfyui_image2prompt ](https://github.com/zhongpei/Comfyui_image2prompt) that force downgrade to Non-CUDA Torch when installing.

This makes ComfyUI not opening at all and it's a real bummer to re-set the right files going. Is it possible to remove them from the manager until it is repaired? It's pretty invasive and brutal if someone just wants to try it out.

**Comment by ltdrdata** [comment]
oh.. yeah... That reinstall `torchvision`. I need to move it to dev channel.

**Comment by ltdrdata** [comment]
Done.
