### ISSUE TITLE
Windows - download models gives me partial downloads

### ISSUE THREAD

**Issue by willsmithorg** [Comfy-Org/ComfyUI-Manager#101]
When I try to download models on Windows, each model appears to succeed, but later they are reported as corrupt.  On closer inspection, **the model is not fully downloading each model file, it gets to 80/90/99% then is marked as succeeded.**  

When I look at the filesize of the downloaded file in windows, it is indeed not quite the expected filesize.

I don't get this issue when downloading the files directly in chrome and saving.

I am using the bitdefender antivirus.  If I manage to disable it I'll report whether this helps.

**Comment by willsmithorg** [comment]
ComfyUI revision : 1426
ComfyUI manager version : 0.26.2

**Comment by willsmithorg** [comment]
Example download:

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/907059/fd94e171-a19f-4e5d-a3b9-7567e56ecebe)

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/907059/f045be41-1ede-4f54-b465-d63be5826309)

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/907059/a7bc61d0-3228-4f69-852b-a90777d92a27)

**Comment by willsmithorg** [comment]
Turning off bitdefender didn't help.  And every time I delete, refresh and re-download, I get a slightly different filesize, always slightly too small:

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/907059/ca94fd42-582f-437b-b66a-052e19dbe97c)

**Comment by ltdrdata** [comment]
Is there no issue when downloading the model through the browser?
