### ISSUE TITLE
Badge/Nickname Missing from GUI

### ISSUE THREAD

**Issue by Orenji-Tangerine** [Comfy-Org/ComfyUI-Manager#1018]
It is enabled but missing from the node workspace, and only the sequence # can be seen.

![image](https://github.com/user-attachments/assets/bd9aab5a-8340-4f7c-b8fb-96c99f882c22)

![image](https://github.com/user-attachments/assets/76b984a5-f4ec-4161-991f-13c4cf7a77fc)

**Comment by ltdrdata** [comment]
They are built-in nodes.
