### ISSUE TITLE
When attempting to "Install Custom Nodes" The prompt "The custom node DB is currently being updated, and updates to custom nodes are being checked for. NOTE: Update only checks for extensions that have been fetched."

### ISSUE THREAD

**Issue by CasparTheKeeper** [Comfy-Org/ComfyUI-Manager#102]
The terminal ends with

"  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host raw.githubusercontent.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]"

**Comment by ltdrdata** [comment]
Can you open this url in browser?

https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by CasparTheKeeper** [comment]
> 

Yes

**Comment by StringTheories** [comment]
Would love to know the solve here? getting the same error

**Comment by ltdrdata** [comment]
What is your ComfyUI environment?

If you're not using the ComfyUI-Portable version, run `python -m pip list` in the Python environment where you are running ComfyUI to display the list of installed packages.

**Comment by StringTheories** [comment]
Running ComfyUI on OSX M1 Mac

**Comment by ltdrdata** [comment]
> Running ComfyUI on OSX M1 Mac

The aiohttp or OpenSSL version might be outdated.
Try update them.

**Comment by santiespinel** [comment]
I am having the same exact issue!!

**Comment by santiespinel** [comment]
> > Running ComfyUI on OSX M1 Mac
> 
> The aiohttp or OpenSSL version might be outdated. Try update them.

this didn't work for me

**Comment by santiespinel** [comment]
OK. I FINALLY SOLVED IT. Just go to Applications/Python[version you're using] and double-click "Install Certificates.command". Let the file run and it is done my friend.
<img width="790" alt="Screenshot 2023-09-27 at 11 00 52 AM" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/81175161/160fd1b4-1068-4524-8f73-e6cd7c5ac126">

**Comment by CasparTheKeeper** [comment]
> OK. I FINALLY SOLVED IT. Just go to Applications/Python[version you're using] and double-click "Install Certificates.command". Let the file run and it is done my friend. <img alt="Screenshot 2023-09-27 at 11 00 52 AM" width="790" src="https://user-images.githubusercontent.com/81175161/271042978-160fd1b4-1068-4524-8f73-e6cd7c5ac126.png">

This worked for me. Thank you so much [santiago038912](https://github.com/santiago038912)

**Comment by miaoerduo** [comment]
hi, there is a fix: https://github.com/ltdrdata/ComfyUI-Manager/pull/140

maybe we can merge it? @ltdrdata

**Comment by miaoerduo** [comment]
it works for me: https://github.com/ltdrdata/ComfyUI-Manager/pull/140

**Comment by ltdrdata** [comment]
> it works for me: #140

This is merged. Thx.

**Comment by RenNgu** [comment]
any solution for windows user?

**Comment by ltdrdata** [comment]
> any solution for windows user?

Manager to the latest version and add the `bypass_ssl = True` option in `ComfyUI-Manager/config.ini`.

**Comment by pdbarma** [comment]
> > any solution for windows user?
> 
> Manager to the latest version and add the `bypass_ssl = True` option in `ComfyUI-Manager/config.ini`.

There is not config.ini file in the comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Please help

**Comment by pdbarma** [comment]
Okay I found the solution for windows users:
The problem is surely with the proxy settings and for some reason there is not config.ini file mentioned by the user.
on the left side of Comfy manager, open it and just select use DB local

All credits to this user on reddit: 
https://www.reddit.com/r/comfyui/comments/15gjbkp/comment/jygkmxc/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by ltdrdata** [comment]
> > > any solution for windows user?
> > 
> > 
> > Manager to the latest version and add the `bypass_ssl = True` option in `ComfyUI-Manager/config.ini`.
> 
> There is not config.ini file in the comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Please help

The `config.ini` file should be automatically generated when you run the Manager for the first time or manipulate options in the Manager menu.

**Comment by unreliable-boy** [comment]
> > > > any solution for windows user?Windows 用户有什么解决方案吗？
> > > 
> > > 
> > > Manager to the latest version and add the `bypass_ssl = True` option in `ComfyUI-Manager/config.ini`.管理到最新版本并在 `ComfyUI-Manager/config.ini` 中添加 `bypass_ssl = True` 选项。
> > 
> > 
> > There is not config.ini file in the comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ManagercomfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager 中没有 config.ini 文件
> > Please help 请帮忙
> 
> The `config.ini` file should be automatically generated when you run the Manager for the first time or manipulate options in the Manager menu.当您第一次运行管理器或操作管理器菜单中的选项时， `config.ini` 文件应该自动生成。

I just run the Manager but there was still not a  `config.ini in the `ComfyUI\ComfyUI-Manager

**Comment by ltdrdata** [comment]
> > > > > any solution for windows user?Windows 用户有什么解决方案吗？
> > > > 
> > > > 
> > > > Manager to the latest version and add the `bypass_ssl = True` option in `ComfyUI-Manager/config.ini`.管理到最新版本并在 `ComfyUI-Manager/config.ini` 中添加 `bypass_ssl = True` 选项。
> > > 
> > > 
> > > There is not config.ini file in the comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ManagercomfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager 中没有 config.ini 文件
> > > Please help 请帮忙
> > 
> > 
> > The `config.ini` file should be automatically generated when you run the Manager for the first time or manipulate options in the Manager menu.当您第一次运行管理器或操作管理器菜单中的选项时， `config.ini` 文件应该自动生成。
> 
> I just run the Manager but there was still not a `config.ini in the `ComfyUI\ComfyUI-Manager

Change any option in Manager Menu. It will generate that file.

**Comment by Jellyfish4** [comment]
> > 有针对 Windows 用户的解决方案吗？
> 
> 管理器升级到最新版本，并添加`bypass_ssl = True`选项`ComfyUI-Manager/config.ini`。

Its worked

**Comment by d-tool** [comment]
I found this file in ComfyUI/user/default/ComfyUI-Manager
