### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by solesbeedude** [Comfy-Org/ComfyUI-Manager#1021]
It's been a while since I updated everything.  After going through with everything, ComfyUI kept freezing the UI when I would boot up.
After removing all custom node packs and adding one by one, this pack consistently produces this error pasted below.  When I then remove the pack, everything starts up just fine.

	{
		"source": "window",
		"type": "error",
		"timestamp": "2024-08-28T22:41:46.879Z",
		"message": "ReferenceError\napp is not defined\nReferenceError: app is not defined\n    at HUD.update (http://127.0.0.1:8188/extensions/image_chooser/image_chooser_hud.js:29:9)\n    at LGraphCanvas.draw (http://127.0.0.1:8188/extensions/image_chooser/image_chooser.js:40:21)\n    at LGraphCanvas.renderFrame (http://127.0.0.1:8188/assets/index-CaD4RONs.js:50741:14)\n"
	},
	{
		"source": "window",
		"type": "error",
		"timestamp": "2024-08-28T22:41:46.880Z",
		"message": "ReferenceError\napp is not defined\nReferenceError: app is not defined\n    at HUD.update (http://127.0.0.1:8188/extensions/image_chooser/image_chooser_hud.js:29:9)\n    at LGraphCanvas.draw (http://127.0.0.1:8188/extensions/image_chooser/image_chooser.js:40:21)\n    at _bg_img.onload (http://127.0.0.1:8188/assets/index-DkvOTKox.js:679:14)\n"
	}
]
[comfyui-logs-1724884946220.json](https://github.com/user-attachments/files/16789795/comfyui-logs-1724884946220.json)

**Comment by ltdrdata** [comment]
Remove `ComfyUI/web/extensions/image_chooser/`.
Some extensions implemented in the old way are implemented in the form of copying files, so even if disabled, they leave behind some residue that causes problems.

**Comment by solesbeedude** [comment]
You are a beautiful person, thank you!  I didn't realize stuff also got stored there, I thought image_chooser was something within your pack.

Thank you :)
