### ISSUE TITLE
installed comfy from scratch on my pc and the minute i open it manager says its out of date

### ISSUE THREAD

**Issue by rachelcenter** [Comfy-Org/ComfyUI-Manager#1022]
I'm on a PC and i've installed comfyui from scratch on my SSD external hard drive (and i'm getting pretty good at it too, this is like a weekly occurrence having to reinstall from scratch due to a hard drive going bad or a bad custom node bricking me from being able to get back into the program.....)._ i downloaded the "direct link" for comfyui portable from the official git hub page https://github.com/comfyanonymous/ComfyUI/releases/latest/download/ComfyUI_windows_portable_nvidia.7z and I unzip it, and the only folder I added to the custom nodes was "manager" (i cloned it from github into the custom nodes folder) and then the minute I open comfyui and open manager it tells me its out of date. and if i try to hit update it says failed. how is it outdated when I literally just installed from scratch? 

E:\Comfyui MOVE THIS\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-29 19:18:24.119922
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI
** Log path: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.1 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 10240 MB, total RAM 32471 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\web
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)

Import times for custom nodes:
   0.0 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: E:\Comfyui MOVE THIS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
Update ComfyUI
ComfyUI update fail: Cmd('git') failed due to: exit code(128)
  cmdline: git remote show origin
  stderr: 'fatal: detected dubious ownership in repository at 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI'
'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI''
Update ComfyUI
ComfyUI update fail: Cmd('git') failed due to: exit code(128)
  cmdline: git remote show origin
  stderr: 'fatal: detected dubious ownership in repository at 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI'
'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI''

**Comment by ltdrdata** [comment]
First of all, external drives and Git don't get along very well. This may have interfered with Git's operation.
And because ComfyUI-Manager recognizes versions through git, if git is interfered with, it will determine that it's outdated.

Have you tried executing this?
```
    git config --global --add safe.directory 'E:/Comfyui MOVE THIS/ComfyUI_windows_portable/ComfyUI''
```

**Comment by rachelcenter** [comment]
no i havent tried that command because i dont know what that does and wasnt listed in any of the instructions. turns out the issue is not with the comfy installation, the solution came from installing a different version of manager that wasnt the normal github repo. please update github repo for manager

**Comment by ltdrdata** [comment]
> no i havent tried that command because i dont know what that does and wasnt listed in any of the instructions. turns out the issue is not with the comfy installation, the solution came from installing a different version of manager that wasnt the normal github repo. please update github repo for manager

What manager did you install?
