### ISSUE TITLE
As you can see, the display is strange.

### ISSUE THREAD

**Issue by Enchante503** [Comfy-Org/ComfyUI-Manager#1026]
![2024-09-01_17h13_51](https://github.com/user-attachments/assets/bdb57a6c-c2a3-44b9-bfc3-7f66a8c942c3)
As you can see, the display is strange.
The list is displayed behind the panel.

Windows11  WSL2   Ubuntu 22.04.4 LTS
Browser Chrome

**Comment by ltdrdata** [comment]
This was caused by a conflict with comfyui-custom-scripts. A PR has been submitted at present.

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/333
