### ISSUE TITLE
how come your installation instructions exclude Mac computers?

### ISSUE THREAD

**Issue by rachelcenter** [Comfy-Org/ComfyUI-Manager#1029]
how come your installation instructions exclude Mac computers? i see installation instructions for windows and linux but not Apple.

**Comment by dstults** [comment]
Doesn't this include Mac? From the root `README.md` (the main repo page):

> To install ComfyUI-Manager in addition to an existing installation of ComfyUI, you can follow the following steps:
> 
> goto `ComfyUI/custom_nodes` dir in terminal(cmd)
> `git clone https://github.com/ltdrdata/ComfyUI-Manager.git`
> Restart ComfyUI

**Comment by ltdrdata** [comment]
As mentioned in the above comment, you can use the standard method for installing custom nodes. The other instructions are merely additional guides for specific environments.
