### ISSUE TITLE
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

### ISSUE THREAD

**Issue by wangsvip** [Comfy-Org/ComfyUI-Manager#103]
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

you have to remove the .* at line18
E:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchsde-0.2.5.dist-info\METADATA

Requires-Dist: numpy (>=1.19) ; python_version >= "3.7"

https://github.com/google-research/torchsde/issues/131

**Comment by ltdrdata** [comment]
This is an issue related to the packaging of ComfyUI portable version. 
You should inquire about it on the official repository.

https://github.com/comfyanonymous/ComfyUI
