### ISSUE TITLE
Updated frontend, missing ComfyUI manager button, missing load/unload model buttons on menu bar

### ISSUE THREAD

**Issue by RikkB** [Comfy-Org/ComfyUI-Manager#1035]
Expected Behavior
After ComfyUI front end update (v1.2.40) and switching to beta menu system, expected Manager button, model load & unload buttons on menu bar.
![Screenshot 2024-09-04 193247](https://github.com/user-attachments/assets/d1865ee1-f2df-4ad5-8625-cdfe4ee3600e)

Actual Behavior
ComfyUI Manager button, model load button & model unload button missing. Win 11, Chrome browser, updated
![Screenshot 2024-09-04 193226](https://github.com/user-attachments/assets/75396f52-d76e-4139-b4cf-468922bdde3d)

Restarted comfy, refreshed browser, enabled/disabled beta menu, Manager button never appears on menu bar. Switching back to old menu system, Manager button reappears.

Comfy Logs:
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

Chrome logs:
ComfyUI Front-end version: 1.2.40
:8188/api/userdata/workflows%2F.index.json:1 
        
Failed to load resource: the server responded with a status of 404 (Not Found)  http://127.0.0.1:8188/api/userdata/workflows%2F.index.json

Skipping invalid node definition: ImpactLogger. See debug log for more information.  api.ts:282 

Empty components: policy ignored   components-manager.js:767 
Skipping LinkRenderMode as core extension found   linkRenderMode.js:9 [🐍 pysssss] 

Failed to load resource: the server responded with a status of 404 (Not Found)   http://127.0.0.1:8188/api/userdata/workflows%2F.index.json

Failed to load resource: the server responded with a status of 404 (Not Found)   http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon-active.user.ico

Failed to load resource: the server responded with a status of 404 (Not Found)   http://127.0.0.1:8188/api/pysssss/autocomplete

Failed to load resource: the server responded with a status of 404 (Not Found)  http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon.user.ico

**Comment by ltdrdata** [comment]
The log doesn't contains information about manager.
Please upload full log.

**Comment by RikkB** [comment]
Shift+Ctrl+J to open console logs, and that's all that's there.  Am I missing some control or tab to open?
![Screenshot 2024-09-05 194926](https://github.com/user-attachments/assets/54cbce54-530e-4a1d-8fd1-13437e87c0f0)

**Comment by ltdrdata** [comment]
1. Does it appear when it's not the beta UI?
2. Please show the startup log of the terminal.

**Comment by RikkB** [comment]
![image](https://github.com/user-attachments/assets/30624b47-d672-4639-aeed-3a2764ae0f86)

Comfy startup logs:
C:\Users\**********>cd ComfyUI

C:\Users\**********\ComfyUI>call venv/Scripts/activate
** ComfyUI startup time: 2024-09-05 19:40:50.098429
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: C:\Users\**********\ComfyUI\venv\Scripts\python.exe
** Log path: C:\Users\**********\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.4 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 4096 MB, total RAM 32439 MB
pytorch version: 2.2.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\**********\ComfyUI\web
### Loading: ComfyUI-Impact-Pack (V4.85.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.12)
### ComfyUI Revision: 2648 [c7427375] | Released on '2024-09-04'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ReActor] - STATUS - Running v0.5.1-a6 in ComfyUI
Torch version: 2.2.2+cu118
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\**********\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

Import times for custom nodes:
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\gcLatentTunnel.py
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\**********\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
   0.6 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI-Manager
   1.9 seconds: C:\Users\**********\ComfyUI\custom_nodes\comfyui-reactor-node
   8.4 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
  11.3 seconds: C:\Users\**********\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by RikkB** [comment]
Oh, forgot to mention, same issue with MS Edge or Chrome.   I don't use/have other browsers.

**Comment by ltdrdata** [comment]
Your ComfyUI-Manager is too outdated. Update to latest version.
Recent version is 2.50.3.
