### ISSUE TITLE
Bad request error in model manager for diffusers inpaint models

### ISSUE THREAD

**Issue by vilanele** [Comfy-Org/ComfyUI-Manager#1047]
With the newest version of ComfyUI-Manager and ComfyUI, I receive a Bad Request error when trying to install either of this two models  in model manager :

1. diffusers/stable-diffusion-xl-1.0-inpainting-0.1 (diffusion_models/fp16) with id 52
2. diffusers/stable-diffusion-xl-1.0-inpainting-0.1 (UNET) with id 53

**Comment by ltdrdata** [comment]
This is fixed.
