### ISSUE TITLE
Support for running ComfyUI-Manager in an internal network environment

### ISSUE THREAD

**Issue by shydow** [Comfy-Org/ComfyUI-Manager#1055]
I'm writing to request a feature that would allow ComfyUI-Manager to run in an internal network environment. In my organization, direct access to external resources like GitHub and Hugging Face is restricted. However, it might be possible to access these resources through an HTTP proxy or other proxy mechanisms. thanks.

**Comment by ltdrdata** [comment]
I plan to support a feature that can utilize reverse proxy in this manner in the future.
https://github.com/ltdrdata/ComfyUI-Manager/pull/795

**Comment by ltdrdata** [comment]
This will be handled in manager-core.

**Comment by ltdrdata** [comment]
This is implemented.

https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#environment-variables

**Comment by BoosterCore** [comment]
> This is implemented.
> 
> https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#environment-variables

Do I add these variables in config.ini?

**Comment by ltdrdata** [comment]
> > This is implemented.
> > https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#environment-variables
> 
> Do I add these variables in config.ini?

No, this is something you need to set in your environment variables of your OS.
