### ISSUE TITLE
Node name conflicts

### ISSUE THREAD

**Issue by kijai** [Comfy-Org/ComfyUI-Manager#1065]
Hey,

I'm raising this issue here as the author of the pack that is using conflicting names for my Florence2 -node pack, after they copied the nodes, is ignoring my request to rename the nodes: 

https://github.com/un-seen/comfyui-tensorops/issues/1

I keep getting issue reports and contacts about this, latest here:

https://github.com/kijai/ComfyUI-Florence2/issues/73#issuecomment-2354985670

Can't something be done about this? It's causing a lot of confusion.

**Comment by Torcelllo** [comment]
The repo is named Tensorops; but the nickname reads only Tensorop?

C o n f u s i n g ! ! !

**Comment by ltdrdata** [comment]
This is fixed.
