### ISSUE TITLE
help me please i can't "(IMPORT FAILED) ReActor Node for ComfyUI"

### ISSUE THREAD

**Issue by margo2130** [Comfy-Org/ComfyUI-Manager#1079]
hello,
i want to install this model on my comfy ui:
https://github.com/ShmuelRonen/ComfyUI_wav2lip?tab=readme-ov-file

i need to install  ReActor Node for ComfyUI but it always get me this error:
![image](https://github.com/user-attachments/assets/46525aeb-9979-4529-a5f5-4745504e7fba)

i do whatere i can.
even i did this:
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild
but i couldn't solve it. every time i face this error. i select "fix" button but not solve. please help me.

**Comment by ltdrdata** [comment]
The `Try Fix` button is a feature that only addresses simple installation issues. For cases like `insightface` installation issues, which may require very complex installation environments depending on the system, the Manager does not provide support.

Installation issues for each custom node should be inquired about in their respective repositories.
