### ISSUE TITLE
How to rollback to older version? Current one cause Batch count function extremely slow (unsuable)

### ISSUE THREAD

**Issue by CocoPuffLeo** [Comfy-Org/ComfyUI-Manager#1085]
Recently I have accidentally updated comfyui, and it has caused me a lot of issues. I successfully rolled back Comfyui itself, but it seems like the problem is not from them as the batch count feature still works extremely slow. I searched around but it doesn't seem like you have provided a solution to roll back the manager to a specific version I want, I tried Snapshot Manager, but it did not work as well. 
If it is impossible to do this, is there a way for me to make it easy to load all the batch counts first and then start processing the image? Because right now the moment I click the queue prompt it loads one and then immediately starts processing, causing the rest of the batch to become extremely slow.
I hope there is a solution to this I really do, I have been searching around for a while but this is possibly my last resort.  Thank you for reading this.

**Comment by ltdrdata** [comment]
goto ComfyUI dir in cmd
And execute 
```
git checkout v0.2.2
```
