### ISSUE TITLE
Request: live search in node list

### ISSUE THREAD

**Issue by laurentopia** [Comfy-Org/ComfyUI-Manager#11]
filters out as you type
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/26075468/1a7cf167-2313-4cf6-bde2-289567a3bed1)

**Comment by ltdrdata** [comment]
The feature is planned for development.

**Comment by ltdrdata** [comment]
this feature added.

**Comment by laurentopia** [comment]
Thanks!
It would be better and more consistent with a live one: as you type filtering happens.
