### ISSUE TITLE
still old UI

### ISSUE THREAD

**Issue by inspire-boy** [Comfy-Org/ComfyUI-Manager#1104]
![image](https://github.com/user-attachments/assets/b1ea8336-adef-428c-aa2b-f1ec53ab2c94)
![image](https://github.com/user-attachments/assets/662626c0-9a9d-44ba-845c-67465a8b5975)
![image](https://github.com/user-attachments/assets/9cbe428b-4a95-4fd1-b7b8-bfbd10d34663)

Both Comfy and Comfy-manager have updated. but manager still show old UI.

**Comment by doggeddalle** [comment]
> ![image](https://private-user-images.githubusercontent.com/112338987/372324877-b1ea8336-adef-428c-aa2b-f1ec53ab2c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTUzNjYsIm5iZiI6MTcyNzc5NTA2NiwicGF0aCI6Ii8xMTIzMzg5ODcvMzcyMzI0ODc3LWIxZWE4MzM2LWFkZWYtNDI4Yy1hYTJiLWYxZWM1M2FiMmM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNTA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODVhMWJlNTRlNDUxNjY3YmI5Y2I5ZTI4NzgxOTU3ZDczYTY1OWMxYmY0Mzc1MTA4NzVmZDMxM2QzYjcyZjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cGoOy5q2_V-v3A9XgzxTadc9ikphp-1GkE_Es8k8y88) ![image](https://private-user-images.githubusercontent.com/112338987/372325016-662626c0-9a9d-44ba-845c-67465a8b5975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTUzNjYsIm5iZiI6MTcyNzc5NTA2NiwicGF0aCI6Ii8xMTIzMzg5ODcvMzcyMzI1MDE2LTY2MjYyNmMwLTlhOWQtNDRiYS04NDVjLTY3NDY1YThiNTk3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNTA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTM2OGQ5OWNmNzI5MTJiNjE3ZDZmYjMxZDY2YmJiYmY0NGNlMDdlY2JlN2VkMThhZjdjZWM1ZTFkYTY3MTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Zrrdsbe74HiHkaYBGaVB1B9u8aOIfQ-NYYOvs40_8NQ) ![image](https://private-user-images.githubusercontent.com/112338987/372325205-9cbe428b-4a95-4fd1-b7b8-bfbd10d34663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTUzNjYsIm5iZiI6MTcyNzc5NTA2NiwicGF0aCI6Ii8xMTIzMzg5ODcvMzcyMzI1MjA1LTljYmU0MjhiLTRhOTUtNGZkMS1iN2I4LWJmYmQxMGQzNDY2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNTA0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGM0MDI2Nzc2ZWFiZGVhMTUxNDA1OWZjNjU1YzljMjYwYWM4NDU4ZDliZDhlZGRmMGM4YzM5YzA1ZWY3ZDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iQuSQko07kZquzyt7rFdUfT99asruV4v8DMkVvYt7u0)
> 
> Both Comfy and Comfy-manager have updated. but manager still show old UI.

Cope

**Comment by ltdrdata** [comment]
Check the `ComfyUI/custom_nodes`.
It seems that you have installed ComfyUI-Manager redundantly.

**Comment by inspire-boy** [comment]
> Check the `ComfyUI/custom_nodes`. It seems that you have installed ComfyUI-Manager redundantly.

Thanks! 
I clone  ComfyUI GIT repository a pure copy and move custom_nodes&python_embeded folders into it. It solved.
