### ISSUE TITLE
Components system failing: Fixed

### ISSUE THREAD

**Issue by Aenon1** [Comfy-Org/ComfyUI-Manager#1108]
What happened to the components? I can no longer save group nodes as a component. I can load the ones that I had already saved but I can not save a workflow with one of them in it.

**Comment by ltdrdata** [comment]
The component functionality of the Manager has recently been updated to align with the latest ComfyUI front-end.

**Comment by Aenon1** [comment]
I am up to date and it is not working. It is doing what I described above.

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by Aenon1** [comment]
Thank you!
