### ISSUE TITLE
MIXLAB superceding Manager on JSON load/png drop workflow

### ISSUE THREAD

**Issue by Duemellon** [Comfy-Org/ComfyUI-Manager#1114]
When I drop a PNG to load the workflow instead of the Comfy Manager prompt allowing me to go past & load red boxes MIXLAB prompts me with the missing nodes & values.

Unfortunately MIXLAB won't let me load the workflow without installing those items
While Comfy Manager would still let me load that workflow so I could replace the nodes

I don't want to load every niche node the previous workflow author installed. I want to know what items they were so I can replace them. Like, I don't need a 4th version of a checkpoint loader -- I don't!

Is anyone else experiencing this since the latest update?
Anyone got a way to get rid of that problem?

**Comment by ltdrdata** [comment]
Unfortunately, this issue needs to be resolved within MIXLAB.
