### ISSUE TITLE
Double-Click to "Copy All Connections" also also copies node shape and color

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI-Manager#1118]
_**EDIT:** I changed the issue name, once I understood the cause of the problem ( see next posts )._

---

Some nodes change shape if I double click the header / title area.

![b1](https://github.com/user-attachments/assets/5849d33e-b50e-4be4-b558-71f6dee20bb2)

---

The nodes seem to assume the color and shape of the previous node that had this issue.

This `Float Constant` node ( from ComfyUI-KJNodes ) is green by default, but when I double clicked, it assumed the shape and color of the `Load ControlNet Model` node ( in the image above ).

This last shape and color is "stored" even if Comfy UI is re-started. 

![b2](https://github.com/user-attachments/assets/0c76585d-33b6-4ef8-a86e-5b3cfcbca403)

---

Initially I thought this was some sort of node re-scaling issue.
I only noticed this pattern after installing the ComfyUI-KJNodes, because some of them seem to have color by default.
 
Look at this !

This `Pad Image for Outpainting` ( from ComfyUI-KJNodes ) assumed the shape and color ( green ) of the `Float Constant` node, when I double clicked the title area.

![bug3](https://github.com/user-attachments/assets/0d9535e3-9b2b-4a1e-9174-abcd6af2d936)

---

If I start Comfy UI with  `--disable-all-custom-nodes` it fixes the issue. 
So I disabled all custom nodes in the Manager, to find out where the problem comes from. 

But after disabling all nodes, this issue is still there !
I only have the Manager and this `websocket_image_save.py` thing.

```
C:\Cui\cu_121_2\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-06 18:13:10.367134
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Cui\cu_121_2\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.9 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager


Total VRAM 8192 MB, total RAM 32727 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints d:/ComfyUI/models/checkpoints/
Adding extra search path clip d:/ComfyUI/models/clip/
Adding extra search path configs d:/ComfyUI/models/configs/
Adding extra search path controlnet d:/ComfyUI/models/controlnet/
Adding extra search path embeddings d:/ComfyUI/models/embeddings/
Adding extra search path loras d:/ComfyUI/models/loras/
Adding extra search path unet d:/ComfyUI/models/unet/
Adding extra search path upscale_models d:/ComfyUI/models/upscale_models/
Adding extra search path vae d:/ComfyUI/models/vae/
### Loading: ComfyUI-Manager (V2.51.3)
### ComfyUI Revision: 2741 [7d2467e8] | Released on '2024-10-05'

Import times for custom nodes:
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.3 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by JorgeR81** [comment]
Also, when I double click a new node it takes not only the shape of the previous node, but also its connections !

![bug](https://github.com/user-attachments/assets/b097bd1e-f0c7-4a60-9dce-ddfc58952489)


![bug1](https://github.com/user-attachments/assets/e880579a-32e7-4493-ae4b-625baa37d354)

**Comment by JorgeR81** [comment]
OK, it was this feature !

It seems Double-Click to "Copy All Connections" also also copies node color and shape !

If I set this to "None", it fixes the issue.

![set](https://github.com/user-attachments/assets/d1ad91d6-0d3f-47f3-b899-9a92b3c17706)

**Comment by ltdrdata** [comment]
Fixed.
