### ISSUE TITLE
Preventing Crashes Due to CPU RAM Limitations: Optimizing VRAM Usage for Reactor and LivePortrait

### ISSUE THREAD

**Issue by Amit30swgoh** [Comfy-Org/ComfyUI-Manager#1123]
I need a way to avoid crashes due to lack of CPU RAM. Could you create an argument to help with this? For example, Reactor and LivePortrait don't use my high VRAM (L4 22.5GB VRAM) and instead rely on the CPU. I want to know how to prevent crashing.
![image](https://github.com/user-attachments/assets/1ce2bf73-6e06-4288-b4cc-c3338203218d)

**Comment by ltdrdata** [comment]
Issues for each custom node should be inquired about in the respective custom node repository.
