### ISSUE TITLE
My ComfyUI stoped working (I get a blank page)

### ISSUE THREAD

**Issue by CrimoMX** [Comfy-Org/ComfyUI-Manager#1124]
My ComfyUI stoped working after I installed ComfyManager, please help me, I've traied updating and It didnt solve my Issue

C:\Users\roman\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-07 14:14:11.266123
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Users\roman\ComfyUI\python_embeded\python.exe
** ComfyUI Path: C:\Users\roman\ComfyUI\ComfyUI
** Log path: C:\Users\roman\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.9 seconds: C:\Users\roman\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 10240 MB, total RAM 49071 MB
pytorch version: 2.4.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\roman\ComfyUI\ComfyUI\web
Adding extra search path checkpoints C:\Users\Crimo\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\Users\Crimo\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\Users\Crimo\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\Users\Crimo\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\Users\Crimo\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\Users\Crimo\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\Users\Crimo\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\Users\Crimo\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\Users\Crimo\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\Users\Crimo\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\Users\Crimo\stable-diffusion-webui\models/ControlNet
C:\Users\roman\ComfyUI\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### ComfyUI Revision: 2745 [8dfa0cc5] | Released on '2024-10-07'

Import times for custom nodes:
   0.0 seconds: C:\Users\roman\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.3 seconds: C:\Users\roman\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by ltdrdata** [comment]
Move all custom nodes in the ComfyUI/custom_nodes directory to another location and test.
If there are no issues, try restoring some of them and restarting to identify which custom node is causing the problem.

**Comment by thinkluck** [comment]
I also encountered the same problem, when I installed ComfyUI Manager, the page became blank and I couldn't perform any operations

**Comment by CrimoMX** [comment]
> I also encountered the same problem, when I installed ComfyUI Manager, the page became blank and I couldn't perform any operations

Thank you for reply; I've noticed it that it stopped working on chrome only, I tried in a different explorer and it works! I Haven't found a solution tho

**Comment by CrimoMX** [comment]
> Move all custom nodes in the ComfyUI/custom_nodes directory to another location and test. If there are no issues, try restoring some of them and restarting to identify which custom node is causing the problem.

It didnt work, I've just found that ComfyUI is working (and extension manager also) in other explorer that is not chrome, It's like a Google Chrome Issue i think, I'll try to reinstall it, thank you!

**Comment by ltdrdata** [comment]
> > I also encountered the same problem, when I installed ComfyUI Manager, the page became blank and I couldn't perform any operations
> 
> Thank you for reply; I've noticed it that it stopped working on chrome only, I tried in a different explorer and it works! I Haven't found a solution tho

It seems that one of your chrome extension is blocking.
