### ISSUE TITLE
About extension-node-map.json config

### ISSUE THREAD

**Issue by yaosheng216** [Comfy-Org/ComfyUI-Manager#1126]
Hi, author.
I have a question, the extension-node-map.json file whether support configuring GitHub projects subfolders.
Wish your answer.

Thanks.

**Comment by ltdrdata** [comment]
It doesn't matter if it's a subfolder or a submodule; we collect as much as possible.
If you want to explicitly provide information, offering a `node_list.json` would be helpful.

https://github.com/ltdrdata/ComfyUI-Manager#custom-node-support-guide

**Comment by yaosheng216** [comment]
@ltdrdata Thanks your solution. I still have about model-list.json file's question. That file config whether support pull model from ModelScope.

**Comment by ltdrdata** [comment]
> @ltdrdata Thanks your solution. I still have about model-list.json file's question. That file config whether support pull model from ModelScope.

That configuration only requires it to be downloadable via the web, but it needs to be publicly accessible.
In other words, it should be a link that can be easily downloaded through wget.
