### ISSUE TITLE
I can't install the plugin, and I always fail.

### ISSUE THREAD

**Issue by vjoo** [Comfy-Org/ComfyUI-Manager#1127]
![screenshot-20241008-144238](https://github.com/user-attachments/assets/a8c2dbdb-d946-4118-a48d-adff18773b35)

**Comment by vjoo** [comment]
VPN Internet access normally，How to fix it, please help

**Comment by ltdrdata** [comment]
The part you've marked with a red circle is functioning normally without any issues.
