### ISSUE TITLE
Error using the CLI

### ISSUE THREAD

**Issue by axelblaze88** [Comfy-Org/ComfyUI-Manager#1130]
I'm getting this error when I run `python cm-cli.py fix all`

Traceback (most recent call last):
  File "/main/ComfyUI/custom_nodes/ComfyUI-Manager/cm-cli.py", line 507, in <module>
    typer.Option(
TypeError: Option() missing 1 required positional argument: 'default'

**Comment by ltdrdata** [comment]
What is your `typer` pip packageversion?

**Comment by axelblaze88** [comment]
Right. It was a problem with the typer version. Thanks!
