### ISSUE TITLE
Publish my pack of nodes on the comfyUI Manager

### ISSUE THREAD

**Issue by yvann-ba** [Comfy-Org/ComfyUI-Manager#1133]
Hi, 
Two weeks ago, I set my repository to private because the code wasn't ready for v1.

 I didn't realize this would remove my pack from the ComfyUI manager oops! Now that the code is working and my repository is public again, could you please republish it on the ComfyUI manager? 
 
 By the way, my repo is also available on the ComfyUI registry: https://registry.comfy.org/publishers/yvann/nodes/comfyui_yvann-nodes

here the github link: https://github.com/yvann-ba/ComfyUI_Yvann-Nodes

**Comment by ltdrdata** [comment]
This is restored.
