### ISSUE TITLE
ComfyUI Manager not working

### ISSUE THREAD

**Issue by CxR0b505** [Comfy-Org/ComfyUI-Manager#114]
When I attempt to run ComfyUI with the manager I get the following below. Then it just loads normally without the manager. Anyone know how I could resolve this?

D:\Stable Diffusion\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-09-20 19:23:32.550287

Prestartup times for custom nodes:
   0.0 seconds: D:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 31895 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
## ComfyUI-Manager: installing dependencies
Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 30, in <module>
    import git
ModuleNotFoundError: No module named 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 37, in <module>
    run_script([sys.executable, '-s', '-m', 'pip', 'install', '-r', requirements_path])
  File "D:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 15, in run_script
    process = subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, bufsize=1)
NameError: name 'subprocess' is not defined

Cannot import D:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: name 'subprocess' is not defined

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): D:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

**Comment by CxR0b505** [comment]
UPDATE: Just use installation method #2 and it works fine.

**Comment by alenknight** [comment]
i get the same issue. looks like config.ini was no longer getting created

in your comfyui-manager folder - create a config.ini file
with the following

```
[default]
preview_method = latent2rgb
badge_mode = none
channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
channel_url_list = 
```

**Comment by ltdrdata** [comment]
> i get the same issue. looks like config.ini was no longer getting created
> 
> in your comfyui-manager folder - create a config.ini file with the following
> 
> ```
> [default]
> preview_method = latent2rgb
> badge_mode = none
> channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
> channel_url_list = 
> ```

Try update again
