### ISSUE TITLE
Can run in win 8?

### ISSUE THREAD

**Issue by lazezo2** [Comfy-Org/ComfyUI-Manager#1142]
AS title saide can work in win 8?
core i3 2250m, built in ati 1g, 8g ram?

**Comment by ltdrdata** [comment]
Windows 8 is such an outdated environment that I honestly can't guarantee its operation.
Especially in the case of ATI, GPU mode is absolutely impossible.
Instead, using the lightest model, SD1.5, in CPU mode (run_cpu.bat) might be barely possible.

Additionally, this is the repository for ComfyUI-Manager, not ComfyUI. Such inquiries should be directed to the ComfyUI repository.
