### ISSUE TITLE
badge变成了default

### ISSUE THREAD

**Issue by qkhhssyvw** [Comfy-Org/ComfyUI-Manager#1145]
badge变成了default
![微信图片_20241014172523](https://github.com/user-attachments/assets/b4efb138-60c7-47e2-b62b-3584f8f1b123)

**Comment by qkhhssyvw** [comment]
badge缺少了

**Comment by ltdrdata** [comment]
Now the badge feature is integrated into ComfyUI core.

![image](https://github.com/user-attachments/assets/ab2f280d-99f7-4c71-afbb-355331f5e3ae)
