### ISSUE TITLE
 custom node does NOT show up in the manager UI, despite it being installed? (Inference-Core-Nodes) - Cannot py setup.py (Access is denied.)

### ISSUE THREAD

**Issue by GPU-server** [Comfy-Org/ComfyUI-Manager#1149]
The custom node is inside the \custom_nodes\:
![image](https://github.com/user-attachments/assets/bb7c54ab-ed3f-49bc-b057-9c7c82c3f107)
When I open the Manager, I don't see in the list of "installed" filters:
![image](https://github.com/user-attachments/assets/2e96bb60-29ea-4025-9945-a3df87b7e802)

When I try to install it manually: it said "Access is denied"

![image](https://github.com/user-attachments/assets/f6a98385-6625-42e5-9a62-0e1ff26c73ef)

**Comment by ltdrdata** [comment]
You can find that node in dev channel.

![image](https://github.com/user-attachments/assets/1c53a858-a23b-4e0a-b267-34422487bd7c)
