### ISSUE TITLE
Unusual pop up window from comfyUI manager - Request message to install an extension during comfyUI run

### ISSUE THREAD

**Issue by GPU-server** [Comfy-Org/ComfyUI-Manager#1151]
Got this:
![image](https://github.com/user-attachments/assets/124882c7-f185-4a89-8ccd-4df16db09476)
I wonder if it's because of the "mapes" custom nodes who changes the UI overall or if this really unusual.

This happened during a "run" and not during a check for missing nodes.

**Comment by GPU-server** [comment]
Sorry if this is regular. It's the first time I get this "request" during a run.

**Comment by ltdrdata** [comment]
The installation request occurred because a node in your workflow depends on other custom nodes.

In the case of Impact Pack, some nodes depend on other custom nodes. If you don't use those nodes, you don't need their dependencies.
