### ISSUE TITLE
[Feature Request] Hover or Right click a node to show the python code associated to it.

### ISSUE THREAD

**Issue by GPU-server** [Comfy-Org/ComfyUI-Manager#1158]
It would be nice to be able to press some key and click a node to show a popup of the code associated to a node. Its description and 2 or 3 other scripts associated to it with some relevant part highlighted. All automatically.
Could be nice to:
- debug
- learn and understand.
- copy/mimic/ improve the code.

**Comment by ltdrdata** [comment]
Transmitting code to the front-end for display is not desirable from a security perspective.

**Comment by GPU-server** [comment]
Even if it's just a "string"?

Ok then what about allowing this only on a "restrictive mode", similar to security_mode = high etc.?
So in that mode, NO INSTALLATION can be done, only running known code, or something like that.
Just brainstrorming here

All in all, I want a way to see nodes "associated code" easily when reading a workflow, if you have another idea that can achieve this?

Maybe a separate "tool" or "tab" , sort of an "wiki" then ? A wiki where you can see on the left the node, and on the right , python code associated to it?

Of course, as I said, this is very helpful for:

- debug
- learn and understand.
- copy/mimic/ improve the code.

**Comment by ltdrdata** [comment]
This feature represents a security vulnerability in terms of information leakage.
Of course, in most cases it's not a problem because it's open source, but it's still not desirable.
Such a feature might be acceptable as a separate dev tool, but it's inappropriate to include in the manager.
