### ISSUE TITLE
extension-node-map ISSUE

### ISSUE THREAD

**Issue by fxtdstudios** [Comfy-Org/ComfyUI-Manager#1163]
node_db\tutorial\extension-node-map.json
Traceback (most recent call last):
  File "D:\WORKSPACE\ComfyUI\custom_nodes\ComfyUI-Manager\json-checker.py", line 23, in <module>
    main()
  File "D:\WORKSPACE\ComfyUI\custom_nodes\ComfyUI-Manager\json-checker.py", line 20, in main
    check_json_syntax(args.file_path)
  File "D:\WORKSPACE\ComfyUI\custom_nodes\ComfyUI-Manager\json-checker.py", line 7, in check_json_syntax
    json_str = file.read()
               ^^^^^^^^^^^
  File "C:\Users\iAhme\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1990: character maps to <undefined>

**Comment by fxtdstudios** [comment]
Fixed with changed the "json-checker.py"

import json

def check_json_syntax(file_path):
    try:
        # Open the file with 'utf-8' encoding
        with open(file_path, 'r', encoding='utf-8') as file:
            json_str = file.read()
            json.loads(json_str)  # This will raise an error if the JSON is invalid
            print("JSON is valid.")
    except UnicodeDecodeError as e:
        print(f"Unicode decode error: {e}")
    except json.JSONDecodeError as e:
        print(f"JSON syntax error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Check JSON syntax.")
    parser.add_argument('file_path', help="Path to the JSON file")
    args = parser.parse_args()

    check_json_syntax(args.file_path)

if __name__ == "__main__":
    main()

**Comment by ltdrdata** [comment]
This is fixed.
Thank you.
