### ISSUE TITLE
A little question about the Update buttons

### ISSUE THREAD

**Issue by tiptinker** [Comfy-Org/ComfyUI-Manager#1171]
![image](https://github.com/user-attachments/assets/2c34c726-b2db-4ee2-8b58-9d84a75d3c5e)

Update ComfyUI ==  go to comfyui directory and run cmd   `git pull`    ?
Update All == update comfyui and all custom nodes?

**Comment by ltdrdata** [comment]
Yeah. That's it, except it will reinstall from `requirements.txt`, not just do a `git pull`.
