### ISSUE TITLE
Windows unreadable in Chrome

### ISSUE THREAD

**Issue by deadman3000** [Comfy-Org/ComfyUI-Manager#1184]
When I open the manager in Chrome and click on Custom nodes or models etc it becomes unreadable. I have no such issue in Firefox. Example provided.
![chromeshit](https://github.com/user-attachments/assets/7b82066c-f877-40b7-ba19-bfb6801863e5)

**Comment by ltdrdata** [comment]
> When I open the manager in Chrome and click on Custom nodes or models etc it becomes unreadable. I have no such issue in Firefox. Example provided.
> ![chromeshit](https://github.com/user-attachments/assets/7b82066c-f877-40b7-ba19-bfb6801863e5)
> 

It's an issue with an extension that makes the elements you additionally installed in ComfyUI semi-transparent. 

Report this issue in the extension's repository.
