### ISSUE TITLE
DB option not persistent.

### ISSUE THREAD

**Issue by CheneyER08** [Comfy-Org/ComfyUI-Manager#1190]
ComfyUI Manager V2.51.8.

I changed DB option from "DB: Channel (1 day cache)" to "DB: Local". It restored back to "DB: Channel (1 day cache)" after restart.

**Comment by ltdrdata** [comment]
It was intentionally designed to not be persistent. 
By default, it is set to always use cache for updates, and local is generally used for fallback purposes.

**Comment by TernaryM01** [comment]
Does this mean that ComfyUI Manager updates things (nodes) at startup even if I check "Skip update check"?
Please please please, there should be an option to disable ALL automatic updates until I hit an "Update" button manually. Things break all the time. The other day I was playing with an IPAdapter workflow. The very next day it was broken, even with me re-running the very last output's workflow, despite me having disabled all updates and not having updated anything in ComfyUI.

**Comment by ltdrdata** [comment]
> Does this mean that ComfyUI Manager updates things (nodes) at startup even if I check "Skip update check"? Please please please, there should be an option to disable ALL automatic updates until I hit an "Update" button manually. Things break all the time. The other day I was playing with an IPAdapter workflow. The very next day it was broken, even with me re-running the very last output's workflow, despite me having disabled all updates and not having updated anything in ComfyUI.

The "Skip update check" option serves a completely different purpose. The "channel" refers to where the list is retrieved from, while "Skip update check" means that the Git update functionality for cloned custom nodes will not be performed.

The `git update` process only fetches the information needed for updates, and it uses this information to check if any actual updates are available. For the updates to be applied to the custom nodes, a `git pull` must be performed. The "Skip update check" option stops just before this step, leaving the updates unconfirmed.
