### ISSUE TITLE
Remove from workflow?

### ISSUE THREAD

**Issue by ClothingAI** [Comfy-Org/ComfyUI-Manager#1192]
First I get that suggestion:
![image](https://github.com/user-attachments/assets/47adaf83-5ee8-4cf6-bbae-870bbf54b83b)

Why, when does the suggestion occur and when does it not?
Should I click that?

**Comment by ltdrdata** [comment]
This is because the custom node called "Width/Height Literal" that is being used in the group node named "Size" added to your loaded workflow is missing.

And this issue is not related to ComfyUI-Manager.

**Comment by ClothingAI** [comment]
> This is because the custom node called "Width/Height Literal" that is being used in the group node named "Size" added to your loaded workflow is missing.
> 
> And this issue is not related to ComfyUI-Manager.

My question was about "REMOVE from workflow" message. It's the FIRST TIME I see it inside manager.

all other instances of "missing nodes" don't have this "remove from workflow" option. So I wonder what is the difference.
Of course the node is missing. (unless it has to do with being in a group)

**Comment by ltdrdata** [comment]
> > This is because the custom node called "Width/Height Literal" that is being used in the group node named "Size" added to your loaded workflow is missing.
> > And this issue is not related to ComfyUI-Manager.
> 
> My question was about "REMOVE from workflow" message. It's the FIRST TIME I see it inside manager.
> 
> all other instances of "missing nodes" don't have this "remove from workflow" option. So I wonder what is the difference. Of course the node is missing. (unless it has to do with being in a group)

`Remove from workflow` is a basic ComfyUI feature that appears when there is a missing node inside a group node
