### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by FishConsole** [Comfy-Org/ComfyUI-Manager#1199]
find an error：
-----------------------------------------------------------------

pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\BAPP\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
D:\BAPP\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### ComfyUI Revision: 2791 [669d9e4c] | Released on '2024-10-27'
Traceback (most recent call last):
  File "D:\BAPP\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\BAPP\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-2.50\__init__.py", line 6, in <module>
    from .glob import manager_server
ModuleNotFoundError: No module named 'ComfyUI-Manager-2'

Cannot import D:\BAPP\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-2.50 module for custom nodes: No module named 'ComfyUI-Manager-2'

----------------------------------------------------------------------------------------

操作系统名称	Microsoft Windows 11 家庭中文版
版本	10.0.22631 版本 22631
其他操作系统描述 	没有资料
操作系统制造商	Microsoft Corporation
系统名称	FISHCONSOLE
系统制造商	MECHREVO
系统型号	Yilong15Pro Series GM5HG0A
系统类型	基于 x64 的电脑
系统 SKU	0001
处理器	AMD Ryzen 7 8845H w/ Radeon 780M Graphics，3801 Mhz，8 个内核，16 个逻辑处理器
BIOS 版本/日期	American Megatrends International, LLC. N.1.08MRO15, 2024/7/30
SMBIOS 版本	3.5
嵌入式控制器版本	1.14
BIOS 模式	UEFI
主板制造商	MECHREVO
主板产品	GM5HG0A
主板版本	Standard
平台角色	移动
安全启动状态	关闭
PCR7 配置	需要提升才能查看
Windows 目录	C:\Windows
系统目录	C:\Windows\system32
启动设备	\Device\HarddiskVolume1
区域设置	中国
硬件抽象层	版本 = "10.0.22621.2506"
用户名	Fishconsole\Fishconsole
时区	中国标准时间
已安装的物理内存(RAM)	32.0 GB
总的物理内存	31.3 GB
可用物理内存	16.9 GB
总的虚拟内存	38.8 GB
可用虚拟内存	21.0 GB
页面文件空间	7.50 GB
页面文件	C:\pagefile.sys
内核 DMA 保护	启用
基于虚拟化的安全性	正在运行
基于虚拟化的安全性要求的安全属性	
基于虚拟化的安全性提供的安全属性	基本的虚拟化支持, DMA 保护, UEFI 代码只读, SMM Security Mitigations 1.0, 基于模式的执行控制
基于虚拟化的安全服务已配置	虚拟机监控程序强制执行的代码完整性, 安全启动
基于虚拟化的安全服务正在运行	虚拟机监控程序强制执行的代码完整性
Windows Defender 应用程序控制策略	已实施
Windows Defender 应用程序控制用户模式策略	关闭
设备加密支持	需要提升才能查看

----------------------------------------------------------------------

Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21)

**Comment by ltdrdata** [comment]
remove ComfyUI-Manager-2.50 dir.
And see this installation guide.

https://github.com/ltdrdata/ComfyUI-Manager#installation

**Comment by FishConsole** [comment]
Y U I J  -  自动回复邮件已经收到了,但是现在我有些事,没法回你.你等我一会儿,我看到就回.
