### ISSUE TITLE
(missing)

### ISSUE THREAD

**Issue by laurentopia** [Comfy-Org/ComfyUI-Manager#12]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/26075468/2175571f-89a6-436b-8cc4-d04b000d5a90)

**Comment by ltdrdata** [comment]
This feature is provided to facilitate easy installation of missing nodes. Normally, nothing appears, but when there are missing nodes, opening this menu displays an expanded list that includes the missing nodes.

**Comment by laurentopia** [comment]
Oh I see. Thanks.
