### ISSUE TITLE
Does not detect nor install missing nodes

### ISSUE THREAD

**Issue by andreszs** [Comfy-Org/ComfyUI-Manager#120]
I've just installed the plugin following [this post](https://civitai.com/articles/2345)'s advice, but it does not seem to work as intended. The attached workflow called [AloeVera_Insta-LoRA_workflow](https://civitai.com/api/download/attachments/201) cannot be loaded because of the missing node ImageBatch, and the **_Install Missing Custom Nodes_** dialog is blank.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/10298071/13626494-add8-45df-ab75-891b8c0bf09c)

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/10298071/98bed1c0-b15a-42d2-993d-cde7a934a0ec)

I have already installed the [Inspire Pack](https://github.com/ltdrdata/ComfyUI-Inspire-Pack) and the [Impact Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack) and restarted ComfyUI countless times. I have no ideas if the Inspire Pack is an extension or a replacement to the Impact Pack, or viceversa, or if it's a good idea to install both of them or are they mutually exclusive.

**Comment by ltdrdata** [comment]
It's a vanilla node. That means your ComfyUI is outdated.
