### ISSUE TITLE
About requirements.txt load

### ISSUE THREAD

**Issue by yaosheng216** [Comfy-Org/ComfyUI-Manager#1200]
Hi, author.
First, thanks for your contributions.
During of initialization loading requirements.txt, i met a problem.
Wish you can answer my question.
Below is my requirements.txt content.
<img width="759" alt="截屏2024-10-29 15 54 58" src="https://github.com/user-attachments/assets/c3e604e9-e7f8-44dc-b964-b68cd645c8b5">
But, during of ComfyUI-Manager loading my custom_node, below of following error message is generated with loading requirements.txt.
<img width="1440" alt="截屏2024-10-29 16 00 43" src="https://github.com/user-attachments/assets/878eb7b5-ab38-4e5e-acc9-78b61b8ae5a9">
Can you tell me about ComfyUI-Manager loading requirements.txt process or how to solve this problem.

Wish your answer. Thank you!

**Comment by ltdrdata** [comment]
This issue requires ComfyUI-Manager to be updated.
Until then, you need to install it manually from the command line.
Go to the custom node directory and install directly using: `pip install -r requirements.txt`

**Comment by yaosheng216** [comment]
Ok, thanks your solution.
Do you plan to support this installation in future versions？

**Comment by ltdrdata** [comment]
> Ok, thanks your solution. Do you plan to support this installation in future versions？

Yes. This improvement is not for the current version, but will be implemented in [manager-core](https://github.com/Comfy-Org/manager-core).
For the current version of manager, I am trying to minimize code changes from a maintenance perspective.

**Comment by yaosheng216** [comment]
Great, thanks for you work.
