### ISSUE TITLE
The interface froze, the buttons do not work

### ISSUE THREAD

**Issue by antey3195** [Comfy-Org/ComfyUI-Manager#1215]
The interface froze, the buttons do not work. Completely removed ComfyUI from my computer and installed a new version. But it did not help. I use Yandex browser, I thought there was an error in cookies. I installed a new browser Google Chrome, but it also did not help.  Has anyone encountered this problem?

![111111111](https://github.com/user-attachments/assets/f8e6c6b2-9fce-4b19-823f-badda712ab58)

**Comment by ltdrdata** [comment]
Is this issue occurring even with a clean install where no custom nodes are installed?
If so, press F12 in Chrome to access the browser console, take a screenshot of the logs, and submit it as an issue to the front-end repository.

https://github.com/Comfy-Org/ComfyUI_frontend

**Comment by lividhen** [comment]
Let me know if I should start a new issue or use this one. I have this same issue. It does not occur with no custom nodes.

**Comment by ltdrdata** [comment]
> Let me know if I should start a new issue or use this one. I have this same issue. It does not occur with no custom nodes.

If the issue doesn't occur when custom nodes are not used, please check if `mixlab` is installed. Recently, such issues have been reported to occur when using an outdated version of `mixlab`
