### ISSUE TITLE
ModuleNotFoundError: No module named 'manager_core'  in  glob\manager_server.py, line 16

### ISSUE THREAD

**Issue by dengsx18** [Comfy-Org/ComfyUI-Manager#1217]
There will be an error while setting the custom_nodes path to another place in the extra_modle_paths.yaml like that:

comfyui:
     base_path: path/to/comfyui/
     # You can use is_default to mark that these folders should be listed first, and used as the default dirs for eg downloads
     is_default: true
     custom_nodes: D:/ComfyUI/custom_nodes

Adding the following code lines copied from glob/manager_core.py can resolve this problem.

`
glob_path = os.path.join(os.path.dirname(__file__))  # ComfyUI-Manager/glob

sys.path.append(glob_path)
`

**Comment by ltdrdata** [comment]
This feature will be addressed in manager-core.
