### ISSUE TITLE
ComfyUI-moondream node list name incorrect

### ISSUE THREAD

**Issue by MakkiShizu** [Comfy-Org/ComfyUI-Manager#1231]
[https://registry.comfy.org/?nodes_index%5Bquery%5D=ComfyUI-moondream](https://registry.comfy.org/?nodes_index%5Bquery%5D=ComfyUI-moondream)
![image](https://github.com/user-attachments/assets/74b01735-36ee-4420-985b-cbb42bb5a9ff)
The `ComfyUI-moondream` 's name is incorrect.will become to [ComfyUI-Florence2](https://github.com/kijai/ComfyUI-Florence2)(Including its description)
And when I'm in manager to install [ComfyUI-Florence2](https://github.com/kijai/ComfyUI-Florence2),this ID 144 node will install[ComfyUI-moondream](https://github.com/kijai/ComfyUI-moondream):
![image](https://github.com/user-attachments/assets/eeba8412-c15e-4ca7-92be-770de8c9b1e9)

**Comment by ltdrdata** [comment]
I have submitted a correction request.
https://github.com/kijai/ComfyUI-Florence2/issues/96
