### ISSUE TITLE
Config Backup for Quick Re-Install

### ISSUE THREAD

**Issue by opensourcefan** [Comfy-Org/ComfyUI-Manager#124]
Would it be possible to create a config backup through Manager of all the models, nodes etc that we have installed; for an "install from backup" task?

I've found my setup is a little unwieldy and I'll probably never remember all the items I have installed. 

Obviously not a full backup, maybe just a csv or something.

**Comment by ltdrdata** [comment]
I plan to develop an export/import feature for installed packages in the future.

https://github.com/ltdrdata/ComfyUI-Manager/issues/84

**Comment by ltdrdata** [comment]
Currently, this feature is implemented in the form of a `Snapshot Manager`, and it can be managed through .json files in the snapshots directory.
