### ISSUE TITLE
UserWarning: Metric `InceptionScore` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.   warnings.warn(*args, **kwargs)  # noqa: B028 

### ISSUE THREAD

**Issue by chensyo** [Comfy-Org/ComfyUI-Manager#1246]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
C:\Users\Mingzhenwang\.conda\envs\comfyui\Lib\site-packages\torchmetrics\utilities\prints.py:43: UserWarning: Metric `InceptionScore` will save all extracted features in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)  # noqa: B028
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Loading weights from local directory

**Comment by ltdrdata** [comment]
That is an issue of the ComfyUI-PMRF.
https://github.com/2kpr/ComfyUI-PMRF

**Comment by chensyo** [comment]
> That is an issue of the ComfyUI-PMRF. https://github.com/2kpr/ComfyUI-PMRF

I looked for it, but didn't see any issues with the same problem as mine.
