### ISSUE TITLE
Missing Node Types "String to Integer" when fresh install

### ISSUE THREAD

**Issue by khoazero123** [Comfy-Org/ComfyUI-Manager#1250]
I got the error `Missing Node Types "String to Integer"` when fresh install ComfyUI and ComfyUI-Manager.

ComfyUI v0.2.7

![image](https://github.com/user-attachments/assets/21e59587-b9ec-4549-86d6-8421fd1f064f)

**Comment by ltdrdata** [comment]
That node is belongs to `comfyui_bmad_nodes`.

The custom node has been temporarily moved to the dev channel due to a security vulnerability. You can switch the channel to "dev" and search for it to install.

**Comment by khoazero123** [comment]
> That node is belongs to `comfyui_bmad_nodes`.
> 
> The custom node has been temporarily moved to the dev channel due to a security vulnerability. You can switch the channel to "dev" and search for it to install.

Ok, thank for you info.
