### ISSUE TITLE
This action is not allowed with this security level configuration. even when the config.ini is weak

### ISSUE THREAD

**Issue by darmikota** [Comfy-Org/ComfyUI-Manager#1259]
![Screenshot 2024-11-21 210848](https://github.com/user-attachments/assets/3fb45fc5-bc35-48bd-bf35-8ee985cd4f9f)

**Comment by ltdrdata** [comment]
What was the blocked action?

**Comment by darmikota** [comment]
> What was the blocked action?

install via GitHub URL
