### ISSUE TITLE
RuntimeError: <_overlapped.Overlapped object at 0x0000020A9F6E6AF0> still has pending operation at deallocation, the process may crash

### ISSUE THREAD

**Issue by chicco4life** [Comfy-Org/ComfyUI-Manager#1280]
Traceback (most recent call last):
  File "C:\Users\Chicco\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000020A9F6E6AF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "C:\Users\Chicco\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x0000020A9F6E6AF0> still has pending operation at deallocation, the process may crash

Whenever I try to launch comfyui, the process crashes due to this issue
If i remove comfyui manager from custom nodes, then comfyui runs successfully again

Could anyone help resolve this issue? i'd really appreciate it

**Comment by ltdrdata** [comment]
See troubleshooting section
https://github.com/ltdrdata/ComfyUI-Manager#troubleshooting

You need to set `windows_selector_event_loop_policy`

**Comment by chicco4life** [comment]
> See troubleshooting section https://github.com/ltdrdata/ComfyUI-Manager#troubleshooting
> 
> You need to set `windows_selector_event_loop_policy`

Thanks a lot! resolved!
