### ISSUE TITLE
Install failed: Doubiiu/ToonCrafter model checkpoint Bad Request

### ISSUE THREAD

**Issue by hieuck** [Comfy-Org/ComfyUI-Manager#1294]
I just checked the links and they are correct but I can't download them, can you help me find them?

**Comment by hieuck** [comment]
I just tried creating a folder manually and the command runs like this:
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json [DONE]
Install model 'Doubiiu/ToonCrafter model checkpoint' into 'F:\ComfyUI\custom_nodes\ComfyUI-ToonCrafter/ToonCrafter\ComfyUI-ToonCrafter/ToonCrafter/checkpoints/tooncrafter_512_interp_v1\model.ckpt'
Downloading https://cdn-lfs-us-1.hf.co/repos/2a/05/2a0530223b695fa2088b500b3691afa0ea31c9c1a5475008aef6d951ea2bf8a2/e4df5aecd9919af2f41a92912bb6391e03531b269785a7448d87e964462edf53?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.ckpt%3B+filename%3D%22model.ckpt%22%3B&Expires=1733579992&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTczMzU3OTk5Mn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy11cy0xLmhmLmNvL3JlcG9zLzJhLzA1LzJhMDUzMDIyM2I2OTVmYTIwODhiNTAwYjM2OTFhZmEwZWEzMWM5YzFhNTQ3NTAwOGFlZjZkOTUxZWEyYmY4YTIvZTRkZjVhZWNkOTkxOWFmMmY0MWE5MjkxMmJiNjM5MWUwMzUzMWIyNjk3ODVhNzQ0OGQ4N2U5NjQ0NjJlZGY1Mz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoifV19&Signature=i4JCN0ozoKobT4emvThep8kmk1Qu2NnZu2AnpcRYFQIXI4ms41crApwKCbT24xrif1sfDfXhlK959DoSveB4Lj8capS4PIY6FyKyW9sLtC2x1rBnZswnT4fq4Bw9AT3kYEzKaOcJ73fmupOx1HjkpyheL2vNVePAVl5P0ZmUOElTuQHY2hhsVogJEgjJzDfTUZSm%7ER51q1HlWwiRJTdULQoxmMclNJ0ZYReTTgmJlX8Jc5JS6%7E4Qhpm5nC6XuC7HTCNyruQGFYyugSCoSSpKlkY2mMmTKuXuLbuXa8q4Qmk1npb2wC%7EpaljrcRMaSxJypxJgzpnCHcJtyBUgGE6tCA__&Key-Pair-Id=K24J24Z295AEI9 to F:\ComfyUI\custom_nodes\ComfyUI-ToonCrafter/ToonCrafter\ComfyUI-ToonCrafter/ToonCrafter/checkpoints/tooncrafter_512_interp_v1\model.ckpt

**Comment by hieuck** [comment]
In the code, the path is custom_nodes/ComfyUI-ToonCrafter/ToonCrafter/checkpoints/tooncrafter_512_interp_v1
actually \custom_nodes\ComfyUI-ToonCrafter/ToonCrafter\ComfyUI-ToonCrafter/ToonCrafter/checkpoints/tooncrafter_512_interp_v1\

After the download is complete, should I set the correct code like this?
custom_nodes/ComfyUI-ToonCrafter/ToonCrafter/checkpoints/tooncrafter_512_interp_v1/model.ckpt
[model-list.json](https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json)

{
      "name": "Doubiiu/ToonCrafter model checkpoint",
      "type": "checkpoint",
      "base": "ToonCrafter",
      "save_path": "custom_nodes/ComfyUI-ToonCrafter/ToonCrafter/checkpoints/tooncrafter_512_interp_v1",
      "description": "ToonCrafter checkpoint model for ComfyUI-ToonCrafter",
      "reference": "https://huggingface.co/Doubiiu/ToonCrafter/tree/main",
      "filename": "model.ckpt",
      "url": "https://huggingface.co/Doubiiu/ToonCrafter/resolve/main/model.ckpt",
      "size": "10.5GB"
    },

**Comment by hieuck** [comment]
After doing this, return the folder path like this custom_nodes/ComfyUI-ToonCrafter/ToonCrafter/checkpoints/tooncrafter_512_interp_v1 is not currently installed
![image](https://github.com/user-attachments/assets/dbdc0d88-7f33-4bbc-b852-d0f40f419ff9)

**Comment by hieuck** [comment]
folder structure to be downloaded and recognized as downloaded
\CUSTOM_NODES\COMFYUI-TOONCRAFTER
└───ToonCrafter
    ├────checkpoints
    └────ComfyUI-ToonCrafter
        └──────ToonCrafter
            └───────checkpoints
                └───────tooncrafter_512_interp_v1
                 └────────model.ckpt

**Comment by ltdrdata** [comment]
This is fixed.
