### ISSUE TITLE
Manager 'Last Updated' is incorrect

### ISSUE THREAD

**Issue by Amorano** [Comfy-Org/ComfyUI-Manager#1298]
![image](https://github.com/user-attachments/assets/6e13167b-6eaf-4df8-9452-3509cb4aa1ec)
![image](https://github.com/user-attachments/assets/74b1e968-591b-4850-b0d5-0dd776ddc69b)

Getting a weird "non" update where I have updated a few times in the last week, yet the manager says the last update was 11/27.

I havent changed anything in either of my local comfyUIs and when I "update" from the manager it obviously is grabbing the latest, just doesnt reflect the last update date.

More of a "huh?" than critical, but figured you should know.

cheers

**Comment by ltdrdata** [comment]
It is about updating with information retrieved from the GitHub API. 
However, from my observation, it doesn't seem to be updated exclusively by commits.

**Comment by ltdrdata** [comment]
I'll take a look.
