### ISSUE TITLE
Standards & consistency

### ISSUE THREAD

**Issue by laurentopia** [Comfy-Org/ComfyUI-Manager#13]
It would be nice to have more consistency throughout the interface and follow node graph standards.

1. ctrl+d is usually duplicate node, never "load default graph"
2. link extremity usually snaps when the mouse cursor is a few pixels around #in
3. when pulling a link, all incompatible #in dim out
4. panning is usually middle mouse drag, because then it doesn't conflict with node move or link pull, also it's more consistent with scrollwheel zoom
5. when clicking on a number field, the common behavior is that field is selected, this allows overwrite of value without drag slide

**Comment by ltdrdata** [comment]
Perhaps you have mistakenly written the issue that should be posted on the official repository of ComfyUI.

This repository is simply provided to facilitate the management of extension nodes in ComfyUI.

https://github.com/comfyanonymous/ComfyUI

**Comment by laurentopia** [comment]
You're right. I'll close and move it.
