### ISSUE TITLE
Comfyui 0.37便携版，两种方法都无法安装manager，求解决

### ISSUE THREAD

**Issue by FengLeiDong** [Comfy-Org/ComfyUI-Manager#1304]
之前的comfyui便携版是可以用bat安装并正常使用的，下载了最新的comfyui 便携版，更新后，启动正常进入，但是无法安装manager，针对便携版的bat文件安装不行，通用方法的cmd安装也不行，求解决。

**Comment by ltdrdata** [comment]
Please attach the full error log.

**Comment by FengLeiDong** [comment]
D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s -m pip install gitpython
Requirement already satisfied: gitpython in d:\comfyui_windows_portable\python_embeded\lib\site-packages (3.1.43)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from gitpython) (4.0.11)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.1)

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -c "import git; git.Repo.clone_from('https://github.com/ltdrdata/ComfyUI-Manager', './ComfyUI/custom_nodes/ComfyUI-Manager')"

已经安装好了git程序，bat文件也放入comfyui便携版根目录了，然后启动bat文件，窗口显示的内容就是上面这些，同时会在ComfyUI\custom_nodes里面创建ComfyUI-Manager这个文件夹，并且一直是空的，但是网络显示有下载，等待几分钟后，cmd窗口自动关闭，这个文件夹也消失了，最后comfyui里面就没有安装上这个插件。

**Comment by ltdrdata** [comment]
I mean the startup terminal log of the ComfyUI.

**Comment by FengLeiDong** [comment]
D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 2048 MB, total RAM 16217 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce MX350 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188

Comfyui 的启动日志就是上面这个了。

**Comment by FengLeiDong** [comment]
2024.12.10，今天晚上我又测试了一下，现在安装上了，并且能够正常使用了。

**Comment by guowenbei-ux** [comment]
> 2024.12.10，今天晚上我又测试了一下，现在安装上了，并且能够正常使用了。

我更新最新的comfyui现在也装不上manager,手动和git都不行
