### ISSUE TITLE
Automatically install list of custom_nodes from config.ini or docker volume

### ISSUE THREAD

**Issue by TrevorSquillario** [Comfy-Org/ComfyUI-Manager#1327]
I'm trying to create a docker based install where custom_nodes are automatically installed from a docker volume mount when ComfyUI is started. Doesn't seem like this is a part of ComfyUI by default. The custom nodes are installed but their dependencies aren't. ComfyUI-Manager handles the auto install of custom node dependencies. What if instead of that we add an setting to config.ini that lets us provide a list of custom nodes and ComfyUI-Manager installs them by default. Would this be the best way to enable this functionality?

Related to https://github.com/comfyanonymous/ComfyUI/issues/6035

**Comment by ltdrdata** [comment]
You can utilize this:
https://github.com/ltdrdata/ComfyUI-Manager/blob/main/docs/en/cm-cli.md

You can use `install` or `restore-snapshot` command.
