### ISSUE TITLE
The search box is too laggy

### ISSUE THREAD

**Issue by lora-Z** [Comfy-Org/ComfyUI-Manager#1332]
Thank you very much for creating the node. I feel very relaxed using it, but I haven't had a good experience yet. The search box is very laggy to use，I'm not sure if this is because I'm using a Chinese plugin, but I'm in China and I'm used to using Chinese

**Comment by lora-Z** [comment]
That's why I used the Chinese plugin. Thank you again, thank you

**Comment by vjoo** [comment]
@lora-Z 怎么解决？最近不知道是更新版本还是和插件有冲突，搜索呼唤出来之后，输入第一个字母，然后会卡住一段时间，才能继续输入

**Comment by ltdrdata** [comment]
Please check if this issue only occurs when the translation plugin is enabled.

**Comment by vjoo** [comment]
切换成英文版本，卡顿依然存在,但是切换成旧版的搜索，输入时就不会卡一下，很奇怪

**Comment by cheukyinjarryd** [comment]
same issue

**Comment by huchenlei** [comment]
See https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/310

**Comment by vjoo** [comment]
> 参见 [AIGODLIKE/AIGODLIKE-ComfyUI-Translation#310](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/310)

谢谢，正解
