### ISSUE TITLE
Unet and Diffusion_models folder can't be detected when using Load Diffusion Model etc

### ISSUE THREAD

**Issue by CGMikeG** [Comfy-Org/ComfyUI-Manager#1337]
Load diffusion model node was showing flux yesterday but for some reason after I installed flux1-dev-Q4_K_S.guff using comfyui manager it will only show this model and won't show the other version that I downloaded manual. I have already tried adding unet and diffusion model manually on yaml file but didn't work. Something is telling comfyui manager changed how comfyui searches for unet files and now its messing up unet nodes, load diffusion model etc.
Are you able to assist on how to fix this?

**Comment by ltdrdata** [comment]
The download functionality via `ComfyUI-Manager` does not alter any directory-related settings.

Please upload the path where the file you downloaded manually is located, along with the `.yaml` file and the `.log` file.

**Comment by CGMikeG** [comment]
I found the issue, comfyui flow control node for some reason is causing this issue

**Comment by razv23** [comment]
> I found the issue, comfyui flow control node for some reason is causing this issue

Bless you, mate! This drove me crazy in the past 8 hours. I reinstalled everything because of it.

**Comment by haejar** [comment]
I'm having the same issue, how did you guys fix it?

**Comment by enricop9** [comment]
it's been since yesterday that I didn't understand why the unet folder was not detected.. for the moment uninstalling flow control node seems to solve the problem

**Comment by razv23** [comment]
> I'm having the same issue, how did you guys fix it?

Go to Manager > Custom Nodes Manager > search for _ComfyUI Flow Control node_ by krich-cto, and press **Disable**, restart Comfy

**Comment by pneumaticG** [comment]
> I found the issue, comfyui flow control node for some reason is causing this issue

OMG - this nearly drove me around the bend. Thanks a million!!!

**Comment by Mayaworldai** [comment]
Phew finally solved this, such a simple solution but the update could have been more careful. SOLVED and thanks a lot

**Comment by 361292623** [comment]
> flow control node

you are gorgeous！！！

**Comment by xxgram** [comment]
> I found the issue, comfyui flow control node for some reason is causing this issue

you are gorgeous！！！

**Comment by doggeddalle** [comment]
lol thanks guys, hate when a 3rd party muppet node dev decides to not test things. pathetic people like that need to apply some common sense in their brain workflow

**Comment by SIMECON** [comment]
> > I'm having the same issue, how did you guys fix it?
> 
> Go to Manager > Custom Nodes Manager > search for _ComfyUI Flow Control node_ by krich-cto, and press **Disable**, restart Comfy

This is the solution to solve the problem that stable diffusion does not read the UNET folder. PERFECT

**Comment by tensae-b** [comment]
i never installed ComfyUI Flow Control node but it still didn't work for me. what worked was i edited the extra_model_paths.yaml file and added diffusion_models: /diffusion_models/ to let the load diffusion node locate the models only in that folder. also you don't need to disable all custom nodes just ones related to gguf
