### ISSUE TITLE
[Bug][CNR] Installed nodes not being recognized

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/ComfyUI-Manager#1339]
## Master branch @https://github.com/ltdrdata/ComfyUI-Manager/commit/445affd609e5fb6970de04de2b0d5020dbbc8bc5

![Screenshot 2024-12-17 at 11 06 36 AM](https://github.com/user-attachments/assets/1fb843a2-768a-4165-aef6-dd86e98294ad)

## CNR branch @https://github.com/ltdrdata/ComfyUI-Manager/commit/f4442972bc38c8faa2ba2756c7877704c47e7c97
Nodes are recognized in the backend, and usable in the frontend
![Screenshot 2024-12-17 at 11 03 33 AM](https://github.com/user-attachments/assets/d6f745c3-4c9d-4f1d-b032-fde84a04664c)

Installed nodes filter shows nothing
![Screenshot 2024-12-17 at 11 04 39 AM](https://github.com/user-attachments/assets/bfc4167c-bf3b-49ca-a034-fc26ad9806cf)

**Comment by robinjhuang** [comment]
Slightly different but related issue: If I directly git clone a custom node (eg. ComfyUI-Essentials), the "Migrate to new node system" does not appear. 

Steps to reproduce: 

```
comfy --here install
cd ComfyUI/custom_nodes && git clone git@github.com:cubiq/ComfyUI_essentials.git
comfy --here launch

Migrate to new node system does not appear.
```

Is this by design?

**Comment by ltdrdata** [comment]
This commit was in an incomplete state. It should be fine now.
