### ISSUE TITLE
Xformers and Pytorch 2.1 issues on Colab

### ISSUE THREAD

**Issue by LukeOvermind** [Comfy-Org/ComfyUI-Manager#134]
lt.dr.Data

I was wondering if you can help with this issue https://github.com/comfyanonymous/ComfyUI/issues/1741? If possible ofcourse.

Its seems to effect a lot of the Colab users  and we  struggling

**Comment by ltdrdata** [comment]
I've updated the PyTorch in the manager's notebook to version 2.0.1. Try using it in the new notebook of the manager.

**Comment by LukeOvermind** [comment]
I saw thank you so much!
