### ISSUE TITLE
SANA "city96" nodes do not work for SANA, it needs "Efficient-Large-Model" nodes to work.

### ISSUE THREAD

**Issue by LockMan007** [Comfy-Org/ComfyUI-Manager#1342]
SANA: Gray/Black images due to city96's repo being broken for SANA.

Please update:
That is because it is using:
https://github.com/city96/ComfyUI_ExtraModels

WHEN IT HAS TO USE THIS INSTEAD:
https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels

I have NO IDEA if this is the code that would change it, but I figured I would give it a shot:

\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
    "https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels": [
        [
            "DiTCondLabelEmpty",
            "DiTCondLabelSelect",
            "DitCheckpointLoader",
            "EmptyDCAELatentImage",
            "EmptySanaLatentImage",
            "ExtraVAELoader",
            "GemmaLoader",
            "GemmaTextEncode",
            "HYDiTCheckpointLoader",
            "HYDiTSrcSizeCond",
            "HYDiTTextEncode",
            "HYDiTTextEncodeSimple",
            "HYDiTTextEncoderLoader",
            "MiaoBiCLIPLoader",
            "MiaoBiDiffusersLoader",
            "OverrideCLIPDevice",
            "OverrideVAEDevice",
            "PixArtCheckpointLoader",
            "PixArtCheckpointLoaderSimple",
            "PixArtControlNetCond",
            "PixArtLoraLoader",
            "PixArtResolutionCond",
            "PixArtResolutionSelect",
            "PixArtT5FromSD3CLIP",
            "PixArtT5TextEncode",
            "SanaCheckpointLoader",
            "SanaResolutionCond",
            "SanaResolutionSelect",
            "SanaTextEncode",
            "T5TextEncode",
            "T5v11Loader"
        ],
        {
            "title_aux": "Extra Models for ComfyUI"
        }
    ],

and
\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
        {
            "author": "Efficient-Large-Model",
            "title": "Extra Models for ComfyUI",
            "id": "extramodels",
            "reference": "https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels",
            "files": [
                "https://github.com/Efficient-Large-Model/ComfyUI_ExtraModels"
            ],
            "install_type": "git-clone",
            "description": "This extension aims to add support for various random image diffusion models to ComfyUI. FROM Efficient-Large-Model."
        },

**Comment by ltdrdata** [comment]
Since the original node pack is neither defective nor unmaintained, the node in question, which may cause conflicts, cannot be added to the default channel list.  
Because this node pack is a modified version, it has been added to the forked channel.
