### ISSUE TITLE
Show Text Nodes not working on CNR brach

### ISSUE THREAD

**Issue by nux1111** [Comfy-Org/ComfyUI-Manager#1357]
Any display text display node like **showtext|pysssss**  with the exception of **Display Any (rgthree)** are not working in the CNR branch
![CleanShot 2024-12-20 at 16 38 53](https://github.com/user-attachments/assets/6c77edee-724f-4861-a933-2fe271621e14)

**Comment by nux1111** [comment]
ComfyUl v0.3.7-44-ge4e1bff 
ComfyUl_frontend v1.6.3
manager version: commit 602d04e2369b80b0055c3aca380e4a955328864e (HEAD -> feat/cnr)
[Workflow (10).json](https://github.com/user-attachments/files/18215919/Workflow.10.json)
![CleanShot 2024-12-20 at 17 17 54](https://github.com/user-attachments/assets/3a2b1704-48ed-4c57-a520-09d529a8bffc)

**Comment by nux1111** [comment]
**Installed nodes**
   ComfyUI-Universal-Styler
   comfyui-kjnodes@nightly
    comfyui_llm_party@nightly

**Comment by huchenlei** [comment]
Fixed by https://github.com/comfyanonymous/ComfyUI/pull/6107
