### ISSUE TITLE
Not installed on latest ComfyUI portable v0.3.9

### ISSUE THREAD

**Issue by fafayqa** [Comfy-Org/ComfyUI-Manager#1360]
I went step-by-step as you mention [here](https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only), but then when I try to run ComfyUI I got this error in CMD window:

Z:\\\_PSTART\_\\\_APPS\_\\\_AI\_\\ComfyUI_windows_portable>.\python_embeded\python.exe -s -m pip install gitpython
Requirement already satisfied: gitpython in z:\_pstart_\_apps_\_ai_\comfyui_windows_portable\python_embeded\lib\site-packages (3.1.43)
Requirement already satisfied: gitdb<5,>=4.0.1 in z:\\\_pstart\_\\\_apps\_\\\_ai\_\\comfyui_windows_portable\python_embeded\lib\site-packages (from gitpython) (4.0.11)
Requirement already satisfied: smmap<6,>=3.0.1 in z:\\\_pstart\_\\\_apps\_\\\_ai\_\\comfyui_windows_portable\python_embeded\lib\site-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.1)

Z:\\\_PSTART\_\\\_APPS\_\\\_AI\_\\ComfyUI_windows_portable>.\python_embeded\python.exe -c "import git; git.Repo.clone_from('https://github.com/ltdrdata/ComfyUI-Manager', './ComfyUI/custom_nodes/ComfyUI-Manager')"
Traceback (most recent call last):
  File "Z:\\\_PSTART\_\\\_APPS\_\\\_AI\_\\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\__init__.py", line 296, in <module>
    refresh()
  File "Z:\\\_PSTART\_\\\_APPS\_\\\_AI\_\\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\__init__.py", line 287, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\\\_PSTART\_\\\_APPS\_\\\_AI\_\\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\cmd.py", line 631, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Z:\\\_PSTART\_\\\_APPS\_\\\_AI\_\\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\__init__.py", line 298, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

Z:\\\_PSTART\_\\\_APPS\_\\\_AI\_\\ComfyUI_windows_portable>pause
Press any key to continue . . .

**Comment by Eyion** [comment]
When ComfyUI is started, the following is displayed in my cmd console window (Manager is not displayed in ComfyUI) :

D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
Failed to execute startup-script: D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Prestartup times for custom nodes:
   1.5 seconds (PRESTARTUP FAILED): D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 2048 MB, total RAM 8101 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce MX150 : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\web
Traceback (most recent call last):
  File "D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\python_embeded\Lib\site-packages\git\__init__.py", line 296, in <module>
    refresh()
  File "D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\python_embeded\Lib\site-packages\git\__init__.py", line 287, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\python_embeded\Lib\site-packages\git\cmd.py", line 631, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\nodes.py", line 2073, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 8, in <module>
    import manager_server  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 13, in <module>
    import git
  File "D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\python_embeded\Lib\site-packages\git\__init__.py", line 298, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Cannot import D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Import times for custom nodes:
   0.0 seconds: D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): D:\Softwares\ComfyUI_windows_portable_nvidia_v0.3.9\ComfyUI\custom_nodes\ComfyUI-Manager
Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by ltdrdata** [comment]
Please install git standalone version.
https://git-scm.com/downloads/win

https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only

**Comment by fafayqa** [comment]
> Please install git standalone version. https://git-scm.com/downloads/win
> 


???
There is fully functional Git portable - what is the difference?
Also why did you closed this "just like that"? No explanation just stating "install git standalone"? I installed Git portable from their official web so that definitely cannot be the reason, I would say.
You could/should explain more what exactly you think is missing, cos Git it is not.

> https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only

Gee, in fact THAT IS EXACTLY WHAT I INSTALLED!!!!!

So how come this error then?

Besides the Manager itself works just fine, I just dont understand why there is such error in the log?

**Comment by Eyion** [comment]
I followed method 2 and installed the standalone version of Git. When I opened ComfyUI with the Iron Pot Launcher (https://pan.baidu.com/s/1qxny4sNtbj_KJC26rw6EOQ?pwd=2333#list/path=%2F), I could see the Manager, but when I opened ComfyUI with run_nvidia_gpu.bat, the above error occurred (I couldn't see the Manager). Yes, the problem that bothered me still exists.

**Comment by ltdrdata** [comment]
> > Please install git standalone version. https://git-scm.com/downloads/win
> 
> ??? There is fully functional Git portable - what is the difference? Also why did you closed this "just like that"? No explanation just stating "install git standalone"? I installed Git portable from their official web so that definitely cannot be the reason, I would say. You could/should explain more what exactly you think is missing, cos Git it is not.
> 
> > https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only
> 
> Gee, in fact THAT IS EXACTLY WHAT I INSTALLED!!!!!
> 
> So how come this error then?
> 
> Besides the Manager itself works just fine, I just dont understand why there is such error in the log?

1. First, make sure that the latest version is installed.
2. Check if the `git` command runs correctly in cmd.  
(It might not run in cmd if it was incorrectly set up during the installation process.)

**Comment by ltdrdata** [comment]
> I followed method 2 and installed the standalone version of Git. When I opened ComfyUI with the Iron Pot Launcher (https://pan.baidu.com/s/1qxny4sNtbj_KJC26rw6EOQ?pwd=2333#list/path=%2F), I could see the Manager, but when I opened ComfyUI with run_nvidia_gpu.bat, the above error occurred (I couldn't see the Manager). Yes, the problem that bothered me still exists.

In that case, the path environment variable may be applied differently in the two environments.  
In other words, in the environment where you run it with the `Iron Pot Launcher`, the `git` command is available, but in the environment where you run `run_nvidia_gpu.bat`, the `git` command is not set up to be available.

If you run `run_nvidia_gpu.bat` from cmd, check if the `git` command is available inside the cmd terminal.  
If you're running it by double-clicking in Explorer, make sure the path to `git.exe` is correctly set in the environment variable path.

**Comment by Eyion** [comment]
Yes, I'm running it by double-clicking in Explorer, but how can I correctly set the path to git.exe in the environment variable path?

**Comment by ltdrdata** [comment]
> Yes, I'm running it by double-clicking in Explorer, but how can I correctly set the path to git.exe in the environment variable path?

If you are using Windows, there is an environment variables editor dialog.
You can edit `PATH`

![EnvVars_SystemProperties](https://github.com/user-attachments/assets/e2325c44-dca5-43d5-b151-35150106bef8)
