### ISSUE TITLE
When the node names are identical, there should be a warning prompt.

### ISSUE THREAD

**Issue by hben35096** [Comfy-Org/ComfyUI-Manager#1362]
For example, in this case, only one "UnetLoaderGGUF" node is missing, but it is required to install:

![PixPin_2024-12-22_20-11-17](https://github.com/user-attachments/assets/5d79e2db-b2e9-4352-8cf6-e6cac8eb826b)

**Comment by LukeG89** [comment]
Many people are installing both nodes and experiencing this bug due to this issue:
- https://github.com/krich-cto/ComfyUI-Flow-Control/issues/1

**Comment by ltdrdata** [comment]
I am aware of the issue. I will move it to the dev channel with a warning message.
