### ISSUE TITLE
Deleting non-installed node deleted entire custom nodes directory 😡

### ISSUE THREAD

**Issue by tusharbhutt** [Comfy-Org/ComfyUI-Manager#137]
I do not have the node below installed, but it shows up when I choose the "recent" view

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/26264462/95d1dad8-c005-4700-bfff-ff87eb83a1eb)

It kept showing up, so I decided to uninstall it.  When I did, the program wiped out my _**entire**_ custom nodes folder.   They do not go to the recycle bin, they are just gone. I had some, but not all backed up, so it was not much fun trying to figure out which ones are missing.

I am not sure if it's that specific node, or if it's because it is the most recent one in the database.  Has anyone else experienced this?

I am using:

ComfyUI-Manager (V0.35)
ComfyUI Revision: 1575 [2231edec] | Released on '2023-10-14'

**Comment by ltdrdata** [comment]
This is fixed on ac948fb6b93bec06074e80ea23a698043ea544fb
