### ISSUE TITLE
[CNR] Installing ComfyUI-Gemini fails

### ISSUE THREAD

**Issue by robinjhuang** [Comfy-Org/ComfyUI-Manager#1376]
Steps to reproduce:
- Install ComfyUI-Gemini [ID 694] on `feat/cnr` branch. This node is by Visionatrix.
- Network tabs shows 400 error code: GET http://127.0.0.1:8188/api/customnode/versions/undefined

Why is it fetching an /undefined version?

**Comment by ltdrdata** [comment]
This is fixed.
