### ISSUE TITLE
[Bug]: ComfyUI-LTXVideo doesn't show up in Missing nodes

### ISSUE THREAD

**Issue by LukeG89** [Comfy-Org/ComfyUI-Manager#1378]
I just noticed that if you import a workflow that contains [ComfyUI-LTXVideo](https://github.com/Lightricks/ComfyUI-LTXVideo) missing nodes, "Install Missing Custom Nodes" doesn't show the node (I remember a couple of issues about this problem in the ComfyUI repo).

But you can still find the node if you search it.

https://github.com/user-attachments/assets/73889b3d-9c2d-420f-a3ba-18a16f53ef90

I also disabled all the other nodes, except for the manager; still the same problem.
```powershell
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@1.6.8
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-28 14:30:55.066484
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\python_embeded\python.exe
** ComfyUI Path: E:\ComfyUI
** Log path: E:\comfyui.log

Prestartup times for custom nodes:
   2.2 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.6.0.dev20241224+cu126
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch attention
Initializing frontend: Comfy-Org/ComfyUI_frontend@1.6.8, requesting version details from GitHub...
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.6.8
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Version: v0.3.10-8-g96697c4b | Released on '2024-12-28'

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI\custom_nodes\websocket_image_save.py
   0.3 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: E:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
```
Here's the workflow I used from LTXVideo repo:
[ltxvideo-i2v.json](https://github.com/user-attachments/files/18266286/ltxvideo-i2v.json)

**Comment by ltdrdata** [comment]
This is a current scanner limitation of ComfyUI-Manager.  
Nodes are registered using the @comfy_registry annotation, but these nodes are not collected.  

Soon, ComfyUI will embed information about custom nodes used in the workflow itself.  
ComfyUI-Manager will adapt to this by suggesting missing nodes based on this embedded information, rather than the node class name.

**Comment by LukeG89** [comment]
Ok, got it. This will also prevent "false" missing nodes like in this cases? (people just copy-pasting code from other custom nodes)
- https://github.com/ltdrdata/ComfyUI-Manager/issues/1362

And [comfyui-tensorops](https://github.com/un-seen/comfyui-tensorops) when you miss [ComfyUI-Florence2](https://github.com/kijai/ComfyUI-Florence2) or [ComfyUI-segment-anything-2](https://github.com/kijai/ComfyUI-segment-anything-2) (like in my video)

**Comment by ltdrdata** [comment]
When custom node information is included in the workflow, conflicts caused by names defined in `NODE_CLASS_MAPPINGS` can will be prevented.  

Of course, for workflows created in the old way without custom node information, the ComfyUI-Manager can only suggest missing nodes using the old fallback method.  

Gradually, workflows need to transition to the new format.

**Comment by LukeG89** [comment]
Ok, perfect! Thank you! 😄
