### ISSUE TITLE
Has the main menu been removed?

### ISSUE THREAD

**Issue by nefudev** [Comfy-Org/ComfyUI-Manager#1381]
Hello!
I am currently able to use the following environment without any problems, but the main menu is not displayed. Is it possible to use the main menu?

The cue operation in the main menu was very convenient.

## Current Environment
Manager: V2.55.5
ComfyUI v0.3.10

**Comment by firofame** [comment]
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Version: v0.3.10-10-ga618f76 | Released on '2024-12-29'

seems the latest version of comfyUI break the ComfyUI-Manager

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/3fa38592-3ddc-4d2d-9533-855544d2418f)

I have no problem with the latest version.

Please disable all custom nodes except for ComfyUI-Manager and run the test.   
If the same issue persists, please show me the browser console log.
(press F12 if chrome)

**Comment by nefudev** [comment]
It seems that the name of the function was incorrect. What I want to display is the function in the attached image.
I have disabled all custom nodes except MANAGER, but it is not showing up.

https://github.com/ltdrdata/ComfyUI-Manager/blob/main/misc/main.jpg

**Comment by ltdrdata** [comment]
> It seems that the name of the function was incorrect. What I want to display is the function in the attached image. I have disabled all custom nodes except MANAGER, but it is not showing up.
> 
> https://github.com/ltdrdata/ComfyUI-Manager/blob/main/misc/main.jpg

Oh.. It's not a part of ComfyUI-Manager.
It belongs to ComfyUI core. And it is the legacy frontend.

If you really want to use it, there is a way to enable the legacy frontend, but it is not recommended.  
The legacy frontend will no longer be maintained. Additionally, you will not be able to use any of the new features introduced in the new frontend.
