### ISSUE TITLE
INSTALLING COMFYUI MANAGER ON IMAC M1

### ISSUE THREAD

**Issue by luchoai** [Comfy-Org/ComfyUI-Manager#139]
Hey guys! Here running local with my Imac M1 I have installed local the comfyui with no problem, when i try to install ComfyUI Manager going to 
cd Custom_nodes and git clone the link show Git Clone complete but I dont see it in the menu after restart, any help? thank you!

**Comment by ltdrdata** [comment]
What is displayed on comfyui startup terminal log?

**Comment by YuanXia119** [comment]
MAC M1 I dont see it in the menu after restart, any help?

**Comment by ltdrdata** [comment]
> MAC M1 I dont see it in the menu after restart, any help?

If there's no information, I can't help.

**Comment by hashmil** [comment]
I'm having a similar issue. i'm getting the following: (i'm using a m2 macbook pro)

```
** ComfyUI start up time: 2023-11-10 19:50:31.929273
Failed to execute startup-script: /Users/hash.milhan/ComfyUI/custom_nodes/ComfyUI-Manager/prestartup_script.py / 'default'

Prestartup times for custom nodes:
   0.0 seconds (PRESTARTUP FAILED): /Users/hash.milhan/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 32768 MB, total RAM 32768 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
### Loading: ComfyUI-Manager (V0.43)
### ComfyUI Revision: 1667 [3e0033ef] | Released on '2023-11-10'

Import times for custom nodes:
   0.1 seconds: /Users/hash.milhan/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188

````

**Comment by hashmil** [comment]
Ok - i think i found a fix. don't know how or why, but this worked for me. 

in the folder `custom_nodes` there is a file called `example_node.py.example`. Just rename it to `example_node.py`. Then follow the normal instllation instructions for Comfy-ui Manager, and restart Comfy UI. That's it! hopefully this works for anyone who has an issue on their M1/M2 macs!

**Comment by ltdrdata** [comment]
> Ok - i think i found a fix. don't know how or why, but this worked for me.
> 
> in the folder `custom_nodes` there is a file called `example_node.py.example`. Just rename it to `example_node.py`. Then follow the normal instllation instructions for Comfy-ui Manager, and restart Comfy UI. That's it! hopefully this works for anyone who has an issue on their M1/M2 macs!

Due to a bug in the recent manager update (just fixed), there was an issue causing an error on the first run. It got resolved on the second run. This is an entirely different situation. Also, do not modify the `example_node.py.example` file.

**Comment by kulkovsky** [comment]
Hello, 

I am running Comfy UI on Mac Pro M1. I am struggling to get Comfy UI manger working, here is my error:

Total VRAM 32768 MB, total RAM 32768 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Traceback (most recent call last):
  File "/Users/mareku/Projects/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/mareku/Projects/ComfyUI/comfy_extras/nodes_upscale_model.py", line 2, in <module>
    from comfy_extras.chainner_models import model_loading
  File "/Users/mareku/Projects/ComfyUI/comfy_extras/chainner_models/model_loading.py", line 8, in <module>
    from .architecture.LaMa import LaMa
  File "/Users/mareku/Projects/ComfyUI/comfy_extras/chainner_models/architecture/LaMa.py", line 15, in <module>
    from torchvision.transforms.functional import InterpolationMode, rotate
ModuleNotFoundError: No module named 'torchvision'

Cannot import /Users/mareku/Projects/ComfyUI/comfy_extras/nodes_upscale_model.py module for custom nodes: No module named 'torchvision'
Loading: ComfyUI-Manager (V1.0.1)
Traceback (most recent call last):
  File "/Users/mareku/Projects/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/mareku/Projects/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 79, in <module>
    from torchvision.datasets.utils import download_url
ModuleNotFoundError: No module named 'torchvision'

Cannot import /Users/mareku/Projects/ComfyUI/custom_nodes/ComfyUI-Manager module for custom nodes: No module named 'torchvision'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /Users/mareku/Projects/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by ltdrdata** [comment]
> Hello,
> 
> I am running Comfy UI on Mac Pro M1. I am struggling to get Comfy UI manger working, here is my error:
> 
> Total VRAM 32768 MB, total RAM 32768 MB Forcing FP16. Set vram state to: SHARED Device: mps VAE dtype: torch.float32 Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention Traceback (most recent call last): File "/Users/mareku/Projects/ComfyUI/nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/Users/mareku/Projects/ComfyUI/comfy_extras/nodes_upscale_model.py", line 2, in from comfy_extras.chainner_models import model_loading File "/Users/mareku/Projects/ComfyUI/comfy_extras/chainner_models/model_loading.py", line 8, in from .architecture.LaMa import LaMa File "/Users/mareku/Projects/ComfyUI/comfy_extras/chainner_models/architecture/LaMa.py", line 15, in from torchvision.transforms.functional import InterpolationMode, rotate ModuleNotFoundError: No module named 'torchvision'
> 
> Cannot import /Users/mareku/Projects/ComfyUI/comfy_extras/nodes_upscale_model.py module for custom nodes: No module named 'torchvision' Loading: ComfyUI-Manager (V1.0.1) Traceback (most recent call last): File "/Users/mareku/Projects/ComfyUI/nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/Users/mareku/Projects/ComfyUI/custom_nodes/ComfyUI-Manager/**init**.py", line 79, in from torchvision.datasets.utils import download_url ModuleNotFoundError: No module named 'torchvision'
> 
> Cannot import /Users/mareku/Projects/ComfyUI/custom_nodes/ComfyUI-Manager module for custom nodes: No module named 'torchvision'
> 
> Import times for custom nodes: 0.0 seconds (IMPORT FAILED): /Users/mareku/Projects/ComfyUI/custom_nodes/ComfyUI-Manager
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188

In the case of `torchvision`, since it is a default dependency of ComfyUI, if it cannot be found, it seems that ComfyUI itself is not properly installed.

Read this:
https://github.com/comfyanonymous/ComfyUI#manual-install-windows-linux

**Comment by kulkovsky** [comment]
Thank you, after resolving the issue with torchvision it works fine.
