### ISSUE TITLE
Installing ComfyUI-Manager in StabilityMatrix

### ISSUE THREAD

**Issue by noembryo** [Comfy-Org/ComfyUI-Manager#143]
This is something of a support "issue" for a very niche situation, so I will understand if you don't want to get involved.
I was wondering if it was possible for me to use ComfyUI-Manager inside StabilityMatrix.

I use A1111 and everything works OK for now, but I wanted to check ComfyUI too, because I would like some more complicated setups that A1111 can't do.
So I also installed ComfyUI inside StabilityMatrix.
But the only way I found to install new "extensions"/nodes there, is ComfyUI-Manager (and there is no "Install from URL" feature in ComfyUI).

Now, the reason I use StabilityMatrix is because my system's Python is Python 2.7 (for development reasons) and I don't want to install anything else outside of it, system-wise (including newer versions of everything)
Looking at the [Installation methods](https://github.com/ltdrdata/ComfyUI-Manager#installation) I couldn't find a way that does not involve a system installation for git (although git is already installed inside StabilityMatrix).
Of course, I might be wrong and missing some simple way to do it, but I would be grateful if someone informed me of how (if its possible at all)

Thanks for your time.. 🙏

**Comment by ltdrdata** [comment]
I have plan to implement installation from git url.

**Comment by noembryo** [comment]
> I have plan to implement installation from git url.

This is great news!! 🍾 🎆 
I'll wait then.. 😃

**Comment by ltdrdata** [comment]
> > I have plan to implement installation from git url.
> 
> This is great news!! 🍾 🎆 
> I'll wait then.. 😃 

But you can install custom nodes manually.
(git clone to custom_nodes dir and pip install requirements.txt.. Several custom nodes provide install.py or install.bat)
I doubt my plan is much helpful.

**Comment by noembryo** [comment]
> But you can install custom nodes manually.
> (git clone to custom_nodes dir and pip install requirements.txt)

I think that this will try to install it in the system's Python..
I have try it with some A1111 extensions already..

**Comment by Void2258** [comment]
It would be nice if there was a git-free way to install this (ie just putting things in a folder), or at least one that doesn't have location assumptions. This would obviate the need to reinvent the wheel for every new way Comfy can be installed. Otherwise every unusual install method (like SM) will require maintaining a different git script to deal with the different folder structures.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/7b4872cd-5b5f-42de-9500-4fc529f98d40)

`Install via Git URL` feature is added on V0.42.

**Comment by pokerain** [comment]
where?

**Comment by brenry** [comment]
> where?

i tried installing from custom nodes dir and github still getting nowhere

**Comment by ltdrdata** [comment]
> > where?
> 
> i tried installing from custom nodes dir and github still getting nowhere

What steps did you attempt for the installation?
And what message was displayed?

**Comment by dapoh43** [comment]
> > > where?
> > 
> > 
> > i tried installing from custom nodes dir and github still getting nowhere
> 
> What steps did you attempt for the installation? And what message was displayed?

man, i understand. Matrix does not accept it thru this standat instalation, BUT! it can instal it even simplier. Inside Matrix there is menu to instal all addons. Its in "puzle button" near button to launch Comfy ui
