### ISSUE TITLE
(UI Suggestion) Better naming & color indicator for install state

### ISSUE THREAD

**Issue by aphaits** [Comfy-Org/ComfyUI-Manager#15]
Currently the Disable / Enable / Uninstall colors are really distracting to one another and the eye fatigue of seeing install & uninstall in similar bright competing colors are causing minor confusion. I suggest instead of just similar action buttons, it should represent the status of the extension itself.

For suggestion 1, I suggest renaming and recoloring:
- Disable to Active, change color to green to indicate it being active (make tooltip mousehover stating "click to deactivate")
- Enable to Deactivated, change color to muted gray / dark red (not bright red) to indicate it is not active currently (make tooltip mousehover stating "click to activate")
- Uninstall color to be just black because the red color is distracting and detracts the emphasis if the extension is actually active or not.
- Try Install color should be black / gray / diagonal light & dark gray but has tooltip: are you sure? / warning, experimental / known to cause issues, etc

For suggestion 2, I suggest just adding another column between Description and Install column, called the Status column:
- The Status column should indicate if its: Active (green), Deactivated (dark red, not bright red), or Not Installed (muted gray)
- The Status column should not be a button area, just indicator (probably color box without outline)
- The Install column  should indicate buttons: Install / Uninstall (normal black), Try install (diagonal light & dark gray, to indicate experimental build)

Again, having competing bright colors does not make usability great / friendly.

**Comment by ltdrdata** [comment]
The current color selection is chosen arbitrarily, taking care not to clash with the default color theme of **ComfyUI**. I am not a designer. If you provide an appropriate color palette, I will be happy to incorporate it.

In the case of "try install", it deviates from the typical **git clone** structure, so the **manager** cannot provide other additional functionalities such as updates. In other words, it cannot be managed by the **manager**, but it signifies that it will attempt to install if possible.
