### ISSUE TITLE
Install Models : Install failed

### ISSUE THREAD

**Issue by punittt** [Comfy-Org/ComfyUI-Manager#156]
It throws the error 
Install failed: undefined / SyntaxError: Unexpected end of JSON input
if I try to install any model from Install Models inside the ComfyUI manager. Is there a fix?

**Comment by ltdrdata** [comment]
> It throws the error Install failed: undefined / SyntaxError: Unexpected end of JSON input if I try to install any model from Install Models inside the ComfyUI manager. Is there a fix?

First, please confirm if the ComfyUI-Manager version is up to date (V0.36).

If it is up to date, please provide specific details about the issues you encountered when trying to download the which model. Also, share the terminal log messages.

**Comment by punittt** [comment]
So yes the comfyui manager is up to date I installed it like 20 minutes ago.

The terminal message is (I tried installing controlnet lineart model, animateddiff-evolved models, and tried installing all the models but running into the same error):

Install model 'ControlNet-v1-1 (lineart; fp16)' into 'C:\Users\Shadow\Downloads\ComfyUI_windows_portable\ComfyUI\models\controlnet\control_v11p_sd15_lineart_fp16.safetensors'
[ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

**Comment by punittt** [comment]
Im using shadow tech to run it sorry im not technically good at problem solving

**Comment by ltdrdata** [comment]
I'd patched. Update ComfyUI-Manager and try again.

**Comment by punittt** [comment]
Still the same issue

**Comment by ltdrdata** [comment]
Can you download the file from this link in your browser without any issues?

https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_v11p_sd15_lineart_fp16.safetensors

**Comment by punittt** [comment]
I did manually install all my custom nodes without any problems. But that issue still persists with the manager.

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager to version `V0.41`.
And edit `ComfyUI-Manager/config.ini` file.

Add `bypass_ssl = True` to that file like this.

```
[default]
preview_method = none
badge_mode = id_nick
git_exe = 
channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
channel_url_list = 
bypass_ssl = True
```

And restart ComfyUI.
It will work.

**Comment by gabrie** [comment]
Hello, it seems it's still available, I tried to download models from manager. All models prompt with error of "Install failed: undefined / SyntaxError: Unexpected end of JSON input". And I didn't find ComfyUI-Manager/config.ini file within Manager folder. I did try to change a file similar "__init__.py" with bypass_ssl = True, but it didn't help.

**Comment by ltdrdata** [comment]
> Hello, it seems it's still available, I tried to download models from manager. All models prompt with error of "Install failed: undefined / SyntaxError: Unexpected end of JSON input". And I didn't find ComfyUI-Manager/config.ini file within Manager folder. I did try to change a file similar "**init**.py" with bypass_ssl = True, but it didn't help.

That is totally different issue.
What is your ComfyUI-Manager version?

**Comment by gabrie** [comment]
> > Hello, it seems it's still available, I tried to download models from manager. All models prompt with error of "Install failed: undefined / SyntaxError: Unexpected end of JSON input". And I didn't find ComfyUI-Manager/config.ini file within Manager folder. I did try to change a file similar "**init**.py" with bypass_ssl = True, but it didn't help.
> 
> That is totally different issue. What is your ComfyUI-Manager version?

Just updated today, it should be the latest. Where to check the actual version code?

**Comment by ltdrdata** [comment]
> > > Hello, it seems it's still available, I tried to download models from manager. All models prompt with error of "Install failed: undefined / SyntaxError: Unexpected end of JSON input". And I didn't find ComfyUI-Manager/config.ini file within Manager folder. I did try to change a file similar "**init**.py" with bypass_ssl = True, but it didn't help.
> > 
> > 
> > That is totally different issue. What is your ComfyUI-Manager version?
> 
> Just updated today, it should be the latest. Where to check the actual version code?

You can see on startup message.

**Comment by gabrie** [comment]
> > > > Hello, it seems it's still available, I tried to download models from manager. All models prompt with error of "Install failed: undefined / SyntaxError: Unexpected end of JSON input". And I didn't find ComfyUI-Manager/config.ini file within Manager folder. I did try to change a file similar "**init**.py" with bypass_ssl = True, but it didn't help.
> > > 
> > > 
> > > That is totally different issue. What is your ComfyUI-Manager version?
> > 
> > 
> > Just updated today, it should be the latest. Where to check the actual version code?
> 
> You can see on startup message.

### Loading: ComfyUI-Manager (V1.16)

**Comment by ltdrdata** [comment]
> > > > Hello, it seems it's still available, I tried to download models from manager. All models prompt with error of "Install failed: undefined / SyntaxError: Unexpected end of JSON input". And I didn't find ComfyUI-Manager/config.ini file within Manager folder. I did try to change a file similar "**init**.py" with bypass_ssl = True, but it didn't help.
> > > 
> > > 
> > > That is totally different issue. What is your ComfyUI-Manager version?
> > 
> > 
> > Just updated today, it should be the latest. Where to check the actual version code?
> 
> You can see on startup message.

Upload your `comfyui.log` file. I need to take a look at that.

**Comment by gabrie** [comment]
To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /Users/gabrie/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json
Install model 'Inswapper-fp16 (face swap)' into '/Users/gabrie/ComfyUI/models/insightface/inswapper_128_fp16.onnx'
[ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
FETCH DATA from: /Users/gabrie/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json
Install model '8x_NMKD-Superscale_150000_G' into '/Users/gabrie/ComfyUI/models/upscale_models/8x_NMKD-Superscale_150000_G.pth'
[ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
FETCH DATA from: /Users/gabrie/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json
Install model 'ESRGAN x4' into '/Users/gabrie/ComfyUI/models/upscale_models/ESRGAN_4x.pth'
[ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
FETCH DATA from: /Users/gabrie/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json

**Comment by ltdrdata** [comment]
> To see the GUI go to: http://127.0.0.1:8188 FETCH DATA from: /Users/gabrie/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json Install model 'Inswapper-fp16 (face swap)' into '/Users/gabrie/ComfyUI/models/insightface/inswapper_128_fp16.onnx' [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> FETCH DATA from: /Users/gabrie/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json Install model '8x_NMKD-Superscale_150000_G' into '/Users/gabrie/ComfyUI/models/upscale_models/8x_NMKD-Superscale_150000_G.pth' [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> FETCH DATA from: /Users/gabrie/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json Install model 'ESRGAN x4' into '/Users/gabrie/ComfyUI/models/upscale_models/ESRGAN_4x.pth' [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> FETCH DATA from: /Users/gabrie/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json

Not the part of the log. I need full log.

**Comment by gabrie** [comment]
Oh sorry, attached and thanks a lot!
[Log.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/13763174/Log.txt)

**Comment by ltdrdata** [comment]
> Oh sorry, attached and thanks a lot! [Log.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/13763174/Log.txt)

It seems your `byapss_ssl` isn't enabled in `ComfyUI-Manager/config.ini`.

```
bypass_ssl = True
```

Still error persist. upload your `config.ini` to here.

**Comment by gabrie** [comment]
> > Oh sorry, attached and thanks a lot! [Log.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/13763174/Log.txt)
> 
> It seems your `byapss_ssl` isn't enabled in `ComfyUI-Manager/config.ini`.
> 
> ```
> bypass_ssl = True
> ```
> 
> Still error persist. upload your `config.ini` to here.

As I mentioned, I didn't find this config.ini file within ComfyUI-Manager folder. Attached all file within manager folder. And I searched all ComfyUI folders, no config.ini for manager node. But my installation seems fine, and I could update all nodes through manager.
![Snipaste_2023-12-25_19-59-59](https://github.com/ltdrdata/ComfyUI-Manager/assets/539991/c07ed028-e67a-43f1-8893-0a6120795aa6)

**Comment by ltdrdata** [comment]
> > > Oh sorry, attached and thanks a lot! [Log.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/13763174/Log.txt)
> > 
> > 
> > It seems your `byapss_ssl` isn't enabled in `ComfyUI-Manager/config.ini`.
> > ```
> > bypass_ssl = True
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Still error persist. upload your `config.ini` to here.
> 
> As I mentioned, I didn't find this config.ini file within ComfyUI-Manager folder. Attached all file within manager folder. And I searched all ComfyUI folders, no config.ini for manager node. But my installation seems fine, and I could update all nodes through manager. ![Snipaste_2023-12-25_19-59-59](https://private-user-images.githubusercontent.com/539991/292754359-c07ed028-e67a-43f1-8893-0a6120795aa6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MTk1ODcsIm5iZiI6MTcwMzUxOTI4NywicGF0aCI6Ii81Mzk5OTEvMjkyNzU0MzU5LWMwN2VkMDI4LWU2N2EtNDNmMS04ODkzLTBhNjEyMDc5NWFhNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQxNTQ4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDRhMjAyYWQ5ZTkxNTY1MjE3NTU1MzI2NDcxYmY3MzZiYmQ2N2Q1NWNmNzdmMWE4ZmU3MWU5OGZkYTIzY2ExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lyHMyxvu7piTVMunqO4VjEN_aS47GDS2AswLHdLwsnA)

Change any settings on Manager menu. It will create .ini file.

**Comment by gabrie** [comment]
Thanks a lot, it's working now!!

**Comment by Destroyer040** [comment]
Hey, sorry Im late and attempting to hijack this post, but Im having the exact same problem. I was following a ComfyUI etc install video (Vid: https://www.youtube.com/watch?v=9k-yb83ZHfc)  and got hung up on adding custom models ("Control Net - Open Pose" in the video, but all attempted model installs return the error : 

Install failed: undefined / SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Sequence of events: 
-Install ComfyUI   (Successful)
-Install ComfyUI Manager Add-On   (Successful)
-Install Custom Models   (UNSUCCESSFUL)
-Found your post, same issues as OP (no config file, attempted "bypass=True" advice), but the problem persists and it still returns [undefined / SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data]
-Any ideas?


Side Notes:
-Updated my version as per your advice (But also its a fresh install)
-Didnt originally have a [config.ini] file until you showed me how to find it (thank you)
-Tried [bypass=true] with no change (Restarted and tried again, no change).
-Cant seem to find the log file you mentioned.

Any advice would be very appreciated. I'm quite stuck.

**Comment by ltdrdata** [comment]
> Hey, sorry Im late and attempting to hijack this post, but Im having the exact same problem. I was following a ComfyUI etc install video (Vid: https://www.youtube.com/watch?v=9k-yb83ZHfc) and got hung up on adding custom models ("Control Net - Open Pose" in the video, but all attempted model installs return the error :
> 
> Install failed: undefined / SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
> 
> Sequence of events: -Install ComfyUI (Successful) -Install ComfyUI Manager Add-On (Successful) -Install Custom Models (UNSUCCESSFUL) -Found your post, same issues as OP (no config file, attempted "bypass=True" advice), but the problem persists and it still returns [undefined / SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data] -Any ideas?
> 
> Side Notes: -Updated my version as per your advice (But also its a fresh install) -Didnt originally have a [config.ini] file until you showed me how to find it (thank you) -Tried [bypass=true] with no change (Restarted and tried again, no change). -Cant seem to find the log file you mentioned.
> 
> Any advice would be very appreciated. I'm quite stuck.

Update ComfyUI-Manager. 
And try set `model_download_by_agent = True` in config.ini.

**Comment by jiuyong0** [comment]
@ltdrdata 你好，我也遇到了相同的问题，按照上面的方法都试了一下，但是都没有作用

**Comment by Spr-Peach** [comment]
1. 若要使用代理，凭经验lantern肯定是不行的，请用v2rayN。
2. 如果在系统环境变量中添加过“HTTPS_PROXY/http://127.0.0.1:<端口>”(如下图)：
![123](https://github.com/ltdrdata/ComfyUI-Manager/assets/124544885/05f0ae1d-657b-43b1-b164-cb3daeca940d)
请先删除它。
3. 执行下面之一：
选项一：在C盘查找“.gitconfig”这个文件，编辑并将里面[http]和[https]项下冒号后面的端口号替换成v2rayN里设置的端口号，当前使用的代理配置的端口可以在windows设置-网络和Internet-代理-使用代理服务器(编辑)中查看到；然后用ipconfig/flushdns命令清理dns缓存。
选项二：在CMD中执行下面的命令：
```python
#取消代理：
git config --global --unset http.proxy
git config --global --unset https.proxy
#清空dns：
ip config/flushdns
#配置代理：
git config --global http.proxy 127.0.0.1:<v2rayN中设置的端口号>
git config --global https.proxy 127.0.0.1:<v2rayN中设置的端口号>
``` 
接下来再启动comfyui就应该正常了

**Comment by xigua1213822** [comment]
> 更新 ComfyUI-Manager 至版本`V0.41`。 并编辑`ComfyUI-Manager/config.ini`文件。
> 
> 像这样添加`bypass_ssl = True`到该文件。
> 
> ```
> [default]
> preview_method = none
> badge_mode = id_nick
> git_exe = 
> channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
> channel_url_list = 
> bypass_ssl = True
> ```
> 
> 然后重新启动 ComfyUI。 它将正常工作。

Thanks, this is useful for me
