### ISSUE TITLE
## [WARN] ComfyUI-Manager: Your ComfyUI version (1) is too old. Please update to the latest version. ##

### ISSUE THREAD

**Issue by wolverine-174** [Comfy-Org/ComfyUI-Manager#157]
t=2023-11-02T12:51:36+0000 lvl=warn msg="ngrok config file found at legacy location, move to XDG location" xdg_path=/home/studio-lab-user/.config/ngrok/ngrok.yml legacy_path=/home/studio-lab-user/.ngrok2/ngrok.yml
NgrokTunnel: "https://4b15-3-136-172-40.ngrok-free.app/" -> "http://localhost:8188/"
/home/studio-lab-user/ComfyUI
** ComfyUI start up time: 2023-11-02 12:51:36.338295

Prestartup times for custom nodes:
   0.0 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 15110 MB, total RAM 15731 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
### ComfyUI Revision: 1 [dd116abf] | Released on '2023-11-02'
Traceback (most recent call last):
  File "/home/studio-lab-user/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/studio-lab-user/ComfyUI/custom_nodes/.ipynb_checkpoints/__init__.py'

Cannot import /home/studio-lab-user/ComfyUI/custom_nodes/.ipynb_checkpoints module for custom nodes: [Errno 2] No such file or directory: '/home/studio-lab-user/ComfyUI/custom_nodes/.ipynb_checkpoints/__init__.py'

Import times for custom nodes:
   0.0 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/SD-Latent-Upscaler
   0.0 seconds (IMPORT FAILED): /home/studio-lab-user/ComfyUI/custom_nodes/.ipynb_checkpoints
   0.0 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_NestedNodeBuilder
   0.0 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.3 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

Used this notebook https://github.com/Laft02/ComfyUI-notebook-for-SageMaker-Studio-Lab  was working fine until yesterday.

**Comment by ltdrdata** [comment]
You can ignore that warn. Just a warn. But you should remove `/home/studio-lab-user/ComfyUI/custom_nodes/.ipynb_checkpoint` directory. 
The directory is a file automatically created by the notebook when you make any modifications to a file within your notebook. The issue occurs when that path is created within custom_nodes, resulting in such an error.
