### ISSUE TITLE
Socket Closed, Exception on Fetch Model Updates, followed by hang when going to "Install Models" since a version early this morning

### ISSUE THREAD

**Issue by NeedsMoar** [Comfy-Org/ComfyUI-Manager#164]
LOG
```
FETCH DATA from: C:\Programs\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
Fetching done.
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Programs\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Programs\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Programs\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Programs\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
FETCH DATA from: C:\Programs\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
Start update check...
```
This is what I get when the usual fetch node updates finishes(?);  or at least it appears to have gone through all installed nodes at this point.  It takes maybe 3x longer than it used to, which was already a long time.  

After this attempting to "install custom nodes" just hangs on the update check, CTRL-C will no longer close comfy at that point.  Unfortunately I'm not even getting an appcrash event in windows event log over the force-close on the terminal.  No memory access or network errors either.

I manually updated the manager itself just now (git pull) but it's still happening.  Unfortunately that log output is practically useless for troubleshooting so I'm not sure what else I can give you to help track this one down.

**Comment by NeedsMoar** [comment]
"Update All" throws the same error at the end, but seems to successfully update all of the nodes.  CTRL-C still works after that reset connection error as long as nothing else is done.  On restart it looks like only impact-pack updated dependencies (I think it does this itself) instead of all updated nodes as usual so I'm guessing the startup script to re-run the requirements wasn't created which would mean either that code changed or the disconnect happens between printing "Update done." and whatever was supposed to be creating the startup scripts?  Maybe that helps a little more. 

Update done.
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)

**Comment by ltdrdata** [comment]
Try rolling back to a previous commit and see if the issue is resolved.

git checkout 74e1f624

**Comment by NeedsMoar** [comment]
I went back further to just before the snapshot stuff to 2d6633e since that was where it worked for me previously but also because I'm kinda an idiot with git and when checkout didn't remove the snapshots folder I assumed it didn't work, dug around online and found that: 
1.  Everybody likes to argue about the best way to do this in git;  checkout alone doesn't work if it isn't removing stray files as far as I'm concerned.  I didn't find any real working solution other than reset / clean or just deleting stuff by hand.  _(If I have a tracked file I kind of expect it to be removed if it didn't exist when checking something out, but I'm sure somebody had a good hit of angel dust... err I mean reason for making it like that.  I suspect they went on to greater things like naming the revisions of USB so no human can identify whether anything will ever work at the full speed of the device or the port, and in practice they never will... 
2. Nobody can agree on how to do anything in git and they all assume you have your own repo and can force push changes and create branches in it which doesn't help matters. 

Apologies for the barely-rant rant.  

Anyway, 2d6633e can fetch the nodes successfully (except ComfyUI-Manager because of the detached head status of course)  and didn't throw the connection error after doing the fetch nodes, and I'm able to go into install nodes and update.  I usually do it that way even though it's way slower because new nodes / features get added so fast that I like to scan the list and check for large changes on the various git repos and newly duplicated functionality (the 27 different SDXL prompters and resolution select nodes come to mind).   

Startup scripts go through and run the requirements again as before too. 

Notably the speed regression was gone and fetching the custom nodes takes maybe 5 minutes less than on head.  Dunno why, I couldn't see any changes that should have caused that issue.  

After I update everything again I'm going to try out 94cb2f8 since I kinda suspect the snapshot stuff is doing this somehow and the error is coming from one of those endpoints.  I also realized I had --dont-print-server specified because of the web server console spam bug from a while back so that's not specified now and maybe I'll get more info about exactly what page was messed up either on 94cb2f8 or HEAD.

**Comment by NeedsMoar** [comment]
94cb2f8 fails at the end of fetch nodes with the same error as the original post.   Since I had just updated them I'm pretty sure there wasn't even anything new.  I turned access logging back on in server.py (forgot about that part) and am running again to see if I get a URL out of it before the exception.

**Comment by NeedsMoar** [comment]
I disabled privacybadger and ublock origin and didn't get errors, but this was the first time no updated nodes were found so I'd take that with a grain of salt.  On my last attempt before that I could update the nodes after the fetch but it took roughly 5 minutes after node fetch completed before I could enter the install list when clicking on it, and the same between installing each node so there's something messed up with performance but I don't know what and I can't say that it's actually related to the manager.  In any case I got the current release updating nodes and itself and comfy properly even if it takes longer so I'm going to mark this as closed unless I find something that otherwise indicates that manager was the real cause.  The interaction of so many nodes in comfy is sort of a recipe for things like this from time to time.  

I noticed that the websocket attempts were returning 101 request different service.  In firefox developer console, the local http requests for websockets were being switched to https which I'm guessing the local server doesn't support (or the encryption methods weren't supported).  I have forced https / require https disabled because of the various web interfaces I can't be bothered to generate valid certs for like the hardware RAID controller on my old machine, the BMC on this one (during the 5 minutes I actually connect it when a BIOS update is released), and a Xerox laser printer.  Fallback to https is still turned on though, and I'm wondering if the UI spamming websocket requests while the server is busy eventually tries the fallback and fails because of some aiohttp config or other firefox security settings.  Something had changed recently that was causing CORS errors on some web merchants so that last item wouldn't be out of the question.

**Comment by NeedsMoar** [comment]
Here's what the logs looked like on the working run with 2 updated nodes just so you havve a reference because I'll lose this:
```

INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:32:24 +0000] "GET /manager/preview_method HTTP/1.1" 200 162 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:32:24 +0000] "GET /manager/badge_mode HTTP/1.1" 200 155 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:32:24 +0000] "GET /manager/channel_url_list HTTP/1.1" 200 623 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Fetching done.
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:32:31 +0000] "GET /customnode/fetch_updates?mode=url HTTP/1.1" 201 155 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:32:17 +0000] "GET /ws?clientId=c860cd1e97eb4ce4822bd4d965f0bb2e HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:32:17 +0000] "GET /ws?clientId=e73523497ce74729b83fe6281689aca5 HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:32:17 +0000] "GET /ws?clientId=ca3981dbd6e140e881e2bb916de5e580 HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Update check done.
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:37:32 +0000] "GET /customnode/getlist?mode=url HTTP/1.1" 200 111273 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Programs\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Programs\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Programs\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Programs\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:40:45 +0000] "GET /style.css HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:40:45 +0000] "GET /style.css HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:40:45 +0000] "GET / HTTP/1.1" 200 235 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:40:45 +0000] "GET /scripts/defaultGraph.js HTTP/1.1" 200 289 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:40:45 +0000] "GET /extensions/rgthree-comfy/rgthree_config.js HTTP/1.1" 200 287 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
Update custom node 'ComfyUI-Latent-Modifiers'
Update: ['https://github.com/Clybius/ComfyUI-Latent-Modifiers']
CUSTOM NODE PULL: True
Update was successful.
After restarting ComfyUI, please refresh the browser.
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:41:12 +0000] "POST /customnode/update HTTP/1.1" 200 159 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Update check done.
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:41:15 +0000] "GET /customnode/getlist?mode=url HTTP/1.1" 200 111271 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
Update custom node 'ComfyUI-Manager'
Update: ['https://github.com/ltdrdata/ComfyUI-Manager']
CUSTOM NODE PULL: True
Install: pip packages
Update was successful.
After restarting ComfyUI, please refresh the browser.
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:45:00 +0000] "POST /customnode/update HTTP/1.1" 200 159 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Update check done.
INFO:aiohttp.access:127.0.0.1 [05/Nov/2023:20:45:04 +0000] "GET /customnode/getlist?mode=url HTTP/1.1" 200 111269 "http://127.0.0.1:8188/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"

```

**Comment by ltdrdata** [comment]
Thank you for the detailed report.

**Comment by NeedsMoar** [comment]
No problem, I'd be lost trying to keep track of Comfy's custom nodes without your extension.  If I get bored enough and it starts acting up again I'll attach a debugger to python and see if I can get more information on the parameters, but from what I know of the parameter boxing and ref counting stuff that goes on in C / C++ code that python uses it might be more of a PITA than I want to deal with, and I'm in a quagmire of trying to build a pytorch-2.2.0-cu123 on Windows right now to see if it makes a difference since they added lazy loading;  it's just not clear whether that enhancement to the runtime can apply to anything built against 12.1 or if it needs rebuilds. 

I tried one more update earlier and there was no crash when doing "update all" with ~4 extensions updated.  I also didn't see any more of those odd websocket calls in the logs.  I'll re-open this if it happens again and it seems to be related.
