### ISSUE TITLE
New ComfyUI-Manager is slow.

### ISSUE THREAD

**Issue by Robson1970** [Comfy-Org/ComfyUI-Manager#166]
As the title say, the new Manager is very slow at the updates like 5-8  times slower !

**Comment by ltdrdata** [comment]
Go to the ComfyUI-Manager directory in the cmd.
Run `git checkout 214197a24d0`, and then restart ComfyUI to check its performance.

If it's still slow, similarly run `git checkout 2d6633ec6c` and restart ComfyUI to assess its performance.
After testing, you can revert to the original state by running `git checkout main`.

Please provide feedback on the performance for each test result.

**Comment by ltdrdata** [comment]
Based on my tests, in both Linux and Windows environments, the time it takes for the update to complete has become several times faster than before. Is it correct to say that it's not the message refresh but the overall elapsed time that has slowed down?

**Comment by Robson1970** [comment]
Thanks for the reply, "git checkout 214197a24d0"  "git checkout 2d6633ec6c "  update was still slow.
I made the video, the UPDATE NODE is still behind the ComfyUI Manager Menu.
https://files.catbox.moe/6pzbbh.mp4
The new ComfyUI Manager seems faster than before, thanks.
