### ISSUE TITLE
Update windows like "There is an update extension available" are appearing behind the ComfUI Manager menu

### ISSUE THREAD

**Issue by Vegansaregrassfed** [Comfy-Org/ComfyUI-Manager#168]
The windows for:

"There is an update extension available" "ComfyUI has been successfully updated" and "ComfyUI updated successfully"

are showing up hidden behind the ComfyUI Manager Menu. So the CMM has to be closed to see the message.

The "Db is currently being updated....." window appears normally.

I've restarted my computer, downloaded the latest Manager update (today), the problem persists, restarted computer again, problem still persists.

Everything is functioning normally, just those three pop ups are scared to come out from behind the manager menu.

**Comment by ltdrdata** [comment]
This is fixed on V0.40.1
