### ISSUE TITLE
.gitignore update

### ISSUE THREAD

**Issue by KeithHanson** [Comfy-Org/ComfyUI-Manager#173]
```
From https://github.com/ltdrdata/ComfyUI-Manager
   a4fb765..f30e5d6  main       -> origin/main
Updating a4fb765..f30e5d6
error: Your local changes to the following files would be overwritten by merge:
	extension-node-map.json
	node_db/dev/custom-node-list.json
	node_db/new/custom-node-list.json
	node_db/new/extension-node-map.json
Please commit your changes or stash them before you merge.
```

Can/should we .gitignore these?

**Comment by ltdrdata** [comment]
Those files are files that are updated to provide the latest information at all times. You should not modify those files locally.

**Comment by KeithHanson** [comment]
Hm. I'm not doing anything special to cause that I don't think. 

I do have a few custom_nodes I git clone into my ComfyUI - could that be causing these checked-in files to be modified after cloning ComfyUI Manager and using it?

**Comment by ltdrdata** [comment]
> Hm. I'm not doing anything special to cause that I don't think. 
> 
> I do have a few custom_nodes I git clone into my ComfyUI - could that be causing these checked-in files to be modified after cloning ComfyUI Manager and using it?

Try `git diff`.

What messages are displayed?
