### ISSUE TITLE
Custom Node Overlap Flagging System

### ISSUE THREAD

**Issue by BuildBackBuehler** [Comfy-Org/ComfyUI-Manager#174]
Now there are just so many custom nodes, I believe 270+ and I am finding it difficult to keep track of what I do/don't have. I'm sure I am not the only one who would like to avoid redundancies. 

I would figure something along the lines of this would suffice. I imagine this is something that would be best resolved by the community itself; I think it would be unfair or silly to ask custom node maintainers to standardize their nodes' utility/descriptors. However, it would be easy enough if there was some sort of capacity to have users comment on recognized node overlaps, or perhaps if they happen to know/notice that they have...

[RemBG custom node] 

And see there's a custom node with a description of "background eraser", they could then flag it for the overlapping utility. I would think it would be optimal if it required, akin to Github, that another user or a mod would review/confirm the new relational flagging before it were incorporated. Maybe to make life easier, if a user submits 5+ missing relations with a 100% confirm rate, it could give them "mod status" to also automatically flag and/or remove improper ones. 

I haven't thought through how it could be (easily) incorporated, but just wanted to submit the idea. I'd imagine it may be easiest to maintain a wiki hosted on GitHub. It'd also provide an opportunity to expand on/act as a hub for all ComfyUI/Manager-related information. Though, I don't know if this'd dramatically affect the Manager's performance. Could be included in the API fetching as-is, rather than do something live or ISR based. 

<img width="1594" alt="ComfyUIdea" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/116780517/ca68370f-742c-4076-9bf2-55c83820ca5b">

**Comment by ltdrdata** [comment]
I already have a system in mind for handling nodes with duplicate names. However, that is a temporary solution to some extent. Ultimately, I believe it would be desirable to go in the direction of ensuring that node names do not overlap by appending a unique postfix for each node pack.

Manager operates as a system without a central server, making it challenging to incorporate user reports. However, detecting duplicates is feasible through the current node database. I will consider improvements about this issue.

**Comment by BuildBackBuehler** [comment]
Sounds good to me, look forward to whatever you implement and thank you for such a magnificent manager =)

Also, this is totally random, off-topic, but didn't feel it was worth a discussion (but I'm glad to, if this should be discussed w/ the community). Just figured this was an important model to throw into the Models DB! https://huggingface.co/CiaraRowles/controlnet-temporalnet-sdxl-1.0

**Comment by ltdrdata** [comment]
> Sounds good to me, look forward to whatever you implement and thank you for such a magnificent manager =)
> 
> Also, this is totally random, off-topic, but didn't feel it was worth a discussion (but I'm glad to, if this should be discussed w/ the community). Just figured this was an important model to throw into the Models DB! https://huggingface.co/CiaraRowles/controlnet-temporalnet-sdxl-1.0

Just added this model.

**Comment by ltdrdata** [comment]
This feature is added on `V1.4`
