### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SorraTheOrc** [Comfy-Org/ComfyUI-Manager#18]
Could you add a preferred license to this code, it looks super useful. I'd hate to not be honoring your intended license.

**Comment by ltdrdata** [comment]
Actually, I've been contemplating which license to apply. I was initially leaning towards more permissive licenses like MIT or Apache, but as I started working on it, I realized that I have no choice but to depend on the codebase of ComfyUI. Therefore, I am considering following ComfyUI's license.
