### ISSUE TITLE
Manger not visible

### ISSUE THREAD

**Issue by azumbrunnen** [Comfy-Org/ComfyUI-Manager#182]
I followed the exact steps and cloned the git repo into my portable comfyui on macos but it's not showing up. any solve?

**Comment by ltdrdata** [comment]
> I followed the exact steps and cloned the git repo into my portable comfyui on macos but it's not showing up. any solve?

Please show the messages that appear in the terminal when ComfyUI starts.

**Comment by azumbrunnen** [comment]
`Cannot import /Users/azumbrunnen/ComfyUI_windows_portable/ComfyUI/comfy_extras/nodes_upscale_model.py module for custom nodes: No module named 'torchvision'
### Loading: ComfyUI-Manager (V1.1)
Traceback (most recent call last):
  File "/Users/azumbrunnen/ComfyUI_windows_portable/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/azumbrunnen/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 83, in <module>
    from torchvision.datasets.utils import download_url
ModuleNotFoundError: No module named 'torchvision'

Cannot import /Users/azumbrunnen/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Manager module for custom nodes: No module named 'torchvision'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /Users/azumbrunnen/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188`

**Comment by azumbrunnen** [comment]
Thanks @ltdrdata. For others to see if you face this, make sure you run pip install torchvision. It's working now. closing.

**Comment by jimonim** [comment]
"new_ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z"
I downloaded this file and overwrote it into the original ComfyUI_windows_portable folder and it fixed the problem.
