### ISSUE TITLE
Cannot display missing nodes

### ISSUE THREAD

**Issue by Unabcde** [Comfy-Org/ComfyUI-Manager#184]
Click to install the missing node, it does not show the missing node.

**Comment by ltdrdata** [comment]
1. Check if the channel is set to `recent`. Channel should be set to `default`.
2. Do not track if it is a ComfyUI vanilla node. Try updating ComfyUI.
3. If the code structure of the custom node is not written in a trackable format, tracking is not possible.
4. Nodes not yet registered with the manager are not tracked.
