### ISSUE TITLE
comfyui-reactor-node fails to import

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI-Manager#188]
Hi, 

I installed the comfyui-reactor-node, via the Manager.

But upon restarting Comfy UI, it fails to import the node.
The error persists after updating all, via the manager.

I'm on Windows 10. 
Do I need to install Visual Studio 2022?
https://github.com/Gourieff/comfyui-reactor-node#installation

The developer has an alternative to this, but I'm not sure if the Manager is supposed to do this automatically?
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

( or maybe it's a different problem ... )

**Here is the starting log:**

Prestartup times for custom nodes:
  54.9 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32727 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
### ComfyUI Revision: 1735 [5b37270d] | Released on '2023-11-25'
Traceback (most recent call last):
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1798, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_logger import logger
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
Using pytorch cross attention
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 198 nodes successfully.

        "Art is not what you see, but what you make others see." - Edgar Degas

Import times for custom nodes:
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds (IMPORT FAILED): C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.4 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.7 seconds: C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

**Comment by alexbofa** [comment]
Hello, use my [bat](https://github.com/alexbofa/BATNIKI/blob/main/ComfyUI/Insightface-ComfyUI.bat) file to install.

I think it's difficult for the Manager to determine which Python you have installed, you also need to understand whether you use Portable or Python in the system.

**Comment by JorgeR81** [comment]
Hi, 

I only have the Python that comes with the Comfy UI portable install. 

I'm kind of a noob, so first I'm going to see if it's possible to do this only with the manager. 

Also, this issue might be helpful, if it's necessary to put a note in the manager install section, about prerequisites needed for the install process to be completely successful. 

![manager](https://github.com/ltdrdata/ComfyUI-Manager/assets/72734038/db25c6b5-31fe-48fa-8af4-f55fc944c8ff)

**edit:** 

_SOLVED !_

_( Just saving you the trouble of reading my next posts.
They are a bit confusing, because I had some issues, since I was inexperienced with the command line. )_

I was able to solve the problem following the developer's instructions here.
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

Also, when FaceID came out, I just needed to update the IPAdapter, via Manager, and it also worked.

**Comment by JorgeR81** [comment]
Hi,

I'm trying to follow the node developer's instructions.
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

If they don't work perhaps it would be appropriate for me to open an issue there.

But, I think I made a basic mistake on the last command ... ( edit: skip to next post, I already figured this part )

Windows seems to be looking for the "insightface-0.7.3-cp311-cp311-win_amd64.whl" in the Desktop instead of the comfyui_windows_portable folder ...

![fold1](https://github.com/ltdrdata/ComfyUI-Manager/assets/72734038/efdbe190-6956-4446-b25e-674693fdd911)

**here are the cms:**

C:\Users\Desktop>C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\python.exe -V
Python 3.11.6

C:\Users\Desktop>C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\python -m pip install -U pip
Requirement already satisfied: pip in c:\cui\cu_121_2\comfyui_windows_portable\python_embeded\lib\site-packages (23.3.1)

C:\Users\Desktop>C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl
WARNING: Requirement 'insightface-0.7.3-cp311-cp311-win_amd64.whl' looks like a filename, but the file does not exist
Processing c:\users\desktop\insightface-0.7.3-cp311-cp311-win_amd64.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\Desktop\\insightface-0.7.3-cp311-cp311-win_amd64.whl'

**Comment by JorgeR81** [comment]
OK, I read the instructions again, and it seems the file needs to go in to the "ComfyUI" folder
But, now there is a permissions issue ...

Maybe this is an issue to open with the node developer ?

_C:\Users\Desktop>C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl
Acesso negado._

( this is "access denied", in portuguese )
 
There is also a banner saying

_It's not possible to execute this application on my PC
To obtain a version for your PC, contact the software editor_ 

![file2](https://github.com/ltdrdata/ComfyUI-Manager/assets/72734038/85a13228-1c0f-41fa-a984-9fb2613fdd84)

**Comment by JorgeR81** [comment]
I think that broke my Comfy UI install !

After running that cmd, now I can't even open the Comfy UI
I have the same banner, even after removing the "insightface-0.7.3-cp311-cp311-win_amd64.whl" file.

_It's not possible to execute this application on my PC
To obtain a version for your PC, contact the software editor_ 

And the "_Access denied_" msg in the command line

My previous portable install still works.
Do I have to update everything again?!

![Sem Título](https://github.com/ltdrdata/ComfyUI-Manager/assets/72734038/93907f5c-959e-4473-a2ab-f04ef6fe8dee)
![Sem Título2](https://github.com/ltdrdata/ComfyUI-Manager/assets/72734038/7697973e-167f-4e03-8eb5-4e28d8779c3b)

**Comment by JorgeR81** [comment]
Just to be clear, this has nothing to do with [alexbofa](https://github.com/alexbofa) bat file.
I had not tried that yet ( although now I wish I tried that first ... )

It was after running this command. But I guess I made some mistake.

C:\Users\Desktop>C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

**Comment by JorgeR81** [comment]
OK, back to square one.
But I did not had to reinstall !

I just noticed my python.exe, in the "python_embeded" folder, was now 0 bytes !
( I was looking for files that were modified at that time )

I replaced it with a new file, from the original zip folder for that Comfy UI install.
Now, I can open this Comfy UI install, but the node still fails to install.
The starting log seems to be the same.

On a side note, I recall a few years ago my "mpv.com" file was 0 bytes and I had to replace it. 
And It's been fine since then. I was messing with the command line, on mpv, at that time too. 
But, I thought maybe it was Windows Defender or something.
Now, I mostly use lua scripts for mpv, and have not used the command line much since then.

![ptx](https://github.com/ltdrdata/ComfyUI-Manager/assets/72734038/78f38fd9-43ad-4712-bdc7-343bf0d1833c)

**Comment by ltdrdata** [comment]
> I think that broke my Comfy UI install !
> 
> After running that cmd, now I can't even open the Comfy UI I have the same banner, even after removing the "insightface-0.7.3-cp311-cp311-win_amd64.whl" file.
> 
> _It's not possible to execute this application on my PC To obtain a version for your PC, contact the software editor_ 
> 
> And the "_Access denied_" msg in the command line
> 
> My previous portable install still works. Do I have to update everything again?!
> 
> ![Sem Título](https://private-user-images.githubusercontent.com/72734038/286362151-93907f5c-959e-4473-a2ab-f04ef6fe8dee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTY1NjksIm5iZiI6MTcwMTIxNjI2OSwicGF0aCI6Ii83MjczNDAzOC8yODYzNjIxNTEtOTM5MDdmNWMtOTU5ZS00NDczLWEyYWItZjA0ZWY2ZmU4ZGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAwMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZTc3MzQyMmRkNjE1NjQ2OTNiNDZhOWExMTI5Y2IxMTNkNTQ2ZjEzYzQ3ZTA5NDhhZTUwZWQ1N2I4NzJhNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SrP0tcnxAyqKHepngWGHYKW-1dp8mZrJiC0r_MwVAA8) ![Sem Título2](https://private-user-images.githubusercontent.com/72734038/286362205-7697973e-167f-4e03-8eb5-4e28d8779c3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMTY1NjksIm5iZiI6MTcwMTIxNjI2OSwicGF0aCI6Ii83MjczNDAzOC8yODYzNjIyMDUtNzY5Nzk3M2UtMTY3Zi00ZTAzLThlYjUtNGUyOGQ4Nzc5YzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAwMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMDE4MzA0NGY3ZDQ2NmVjNTJkNWE3M2YwMDNmMGEzMDhkYTFjMjFmMjA3MzA4NmExMzQ5MmMzNjIzZGEwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n3cZXea05keWSlt-kWS5hm3Siw1i4dKx8XswjJPZraY)

When considering the symptoms, it is recommended to perform a complete reinstall of the portable version. Also, check if you have sufficient disk space as installation failure may have occurred due to insufficient disk space.

The fact that one file has turned out to be 0 bytes implies that other files may also have the same issue.

**Comment by JorgeR81** [comment]
OK, I will start again with a third portable install, just to be sure.
I will delete the second one, once it's all done.

The larger 500 MB "inswapper_128.onnx" file, needed for this node, was already downloaded in the initial install process, via the Manager.

I still have about 150 GB of free space in my main 512 GB drive. 
Also tested with CrystalDiskInfo and heath is good.

I have like 200 GB of checkpoints, because I'm still testing them, but will plan to archive at least half of them, once I'm done.

**Comment by JorgeR81** [comment]
Success!

I was able to install the node!

Before, was starting the command line from the search menu, in the taskbar, so the command line was being launched from the desktop. 
So all commands need to have "C:\Users\Desktop>" before the cmd, like this:

C:\Users\Desktop>C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

( I also was doing this when my "mpv.com" file was turned into 0 bytes, a while ago ).

Now, I started the cmd, directly in the portable folder.

C:\Cui\cu_121_2\ComfyUI_windows_portable>python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

And I was able to install the node successfully!

But the "insightface-0.7.3-cp311-cp311-win_amd64.whl" file needs to be in the same  "ComfyUI_windows_portable" ( not into the "ComfyUI" subfolder as I thought before )

The 0 bytes issue may  be a combination of these 2 factors: starting the cmd line from the Desktop and the "insightface-0.7.3-cp311-cp311-win_amd64.whl" not being the correct folder.

Because when I launched the cmd from the portable folder and the file was in the "ComfyUI" subfolder, it simply gave an error about not being able to find the file, but nothing got broken.
And the first time, when I launched from the desktop, with the file in the right place, it also gave an error about not being able to find the file, but nothing got broken ( see above ).

So developer instructions worked perfectly. 
And I didn't have to install Visual Studio 2022.
https://github.com/Gourieff/comfyui-reactor-node#installation

You may want to keep this issue open, in case it's possible to automate these steps into the manager installation process. 
Or to add a note about extra manual steps, after the manager installation process.

The node works very well, but I need to use the face restore option, for the result to be good.
This node logs some errors when running a prompt, but I'm not sure if they are related to the node itself or to the issues I had during the install process.
( I tried this on that same portable install )

![react1](https://github.com/ltdrdata/ComfyUI-Manager/assets/72734038/85e58bb5-134c-4bf7-9f65-7b78a72d19f9)


**here is the log:**

( by the way, I do have the file it fails to load,
and it was not modified on the 28th, when the failed install happened )

![file1](https://github.com/ltdrdata/ComfyUI-Manager/assets/72734038/bcf3d771-53fb-42fc-b97d-0243d1fc6eb4)

got prompt
[ReActor] 12:09:53 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 12:09:53 - STATUS - Analyzing Source Image...
2023-11-29 12:09:53.4641646 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-11-29 12:09:54.0004752 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-11-29 12:09:54.0783180 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-11-29 12:09:54.1796989 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-11-29 12:09:54.3106885 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

[ReActor] 12:09:56 - STATUS - Analyzing Target Image...
[ReActor] 12:09:57 - STATUS - Source Face 0: Detected Gender -F-
[ReActor] 12:09:57 - STATUS - OK - Detected Gender matches Condition
2023-11-29 12:09:57.7117145 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Cui\cu_121_2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

[ReActor] 12:09:59 - STATUS - Target Face 0: Detected Gender -F-
[ReActor] 12:09:59 - STATUS - OK - Detected Gender matches Condition
[ReActor] 12:09:59 - STATUS - Swapping...
[ReActor] 12:10:00 - STATUS - --Done!--
[ReActor] 12:10:00 - STATUS - Restoring with codeformer.pth
Prompt executed in 10.61 seconds

**Comment by kodexArg** [comment]
It worked after I reinstalled all my python packages

**Comment by Shraknard** [comment]
Downloading [insightface-0.7.3-cp311-cp311-win_amd64.whl](https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl) and manually installing prebuilt wheel using `ComfyUI_windows_portable\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl` finally solved my problem!

**Comment by JorgeR81** [comment]
> Downloading insightface-0.7.3-cp311-cp311-win_amd64.whl and manually installing prebuilt wheel using ComfyUI_windows_portable\python_embeded\python.exe -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl finally solved my problem!

Yes, I was able to solve the problem that way, but my posts here are a bit confusing, because I made some mistakes during the install, so I had some unrelated issues. 
 
But the solution was actually pretty simple. 
It was all in the developer's instructions here. 
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

**Comment by ChiragDhawan630** [comment]
> -m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl

I tried this and it worked for me as Well Hats off to You Buddy. You're the Absolute Best! 👍

**Comment by sknightq** [comment]
I made a mistake with the version of system python(v3.10) and comfyUI python(v3.11). 
```-m pip install insightface-0.7.3-cp311-cp311-win_amd64.whl``` works for me.

**Comment by myoni00** [comment]
It's really frustrating.
I am Python 3.10
Python 3.10 has been downloaded,

CMD > python.exe -m pip install -U pip > python.exe -m pip install "C:\Program Files\comfyui\ComfyUI\insightface-0.7.3-cp310-cp310-win_amd64.whl"

I've finished everything up to here, but I'm still
0.1 seconds (IMPORT FAILED): C:\Program Files\comfyui\ComfyUI\custom_nodes\comfyui-reactor-node

It's like this. Why is it like this

**Comment by curious-george-is-available** [comment]
I'm trying to deploy a comfy workflow to Baseten Serverless Inference and I'm getting the error 
Cannot import /app/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'insightface'

Can please someone guide me? non-coder here

**Comment by alexbofa** [comment]
> I'm trying to deploy a comfy workflow to Baseten Serverless Inference and I'm getting the error Cannot import /app/ComfyUI/custom_nodes/comfyui-reactor-node module for custom nodes: No module named 'insightface'
> 
> Can please someone guide me? non-coder here

There are many solutions in this topic. For example: https://github.com/ltdrdata/ComfyUI-Manager/issues/188#issuecomment-1826873514

**Comment by ltdrdata** [comment]
This is a fairly well-known issue that varies depending on the installation environment, so there are some limitations to what ComfyUI-Manager can support on its own.

As mentioned earlier, please refer to the following:
https://github.com/Gourieff/comfyui-reactor-node#insightfacebuild

**Comment by dank09** [comment]
This is not working for me.
Still shows (IMPORT FAILED) after I followed all the instructions and I see this when I run ComfyUI

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

my python version:
python_embeded\python.exe -V
Python 3.12.7

I download:
insightface-0.7.3-cp312-cp312-win_amd64.whl

Then I run:
python_embeded\python.exe -m pip install -U pip
python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl

and still getting no luck. ReActor Node won't load. The try fix button doesn't work. I even tried:
python_embeded\python.exe -m pip install insightface-0.7.3-cp312-cp312-win_amd64.whl --force-reinstall

and still nothing.
