### ISSUE TITLE
install failed - cannot locate impact module

### ISSUE THREAD

**Issue by Harebat** [Comfy-Org/ComfyUI-Manager#19]
I was updating ComfyUI and the nodes this morning and was presented with this error:

Install: install script
Traceback (most recent call last):
  File "C:\Users\esraw\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 15, in <module>
    import impact.config
ModuleNotFoundError: No module named 'impact'
install script failed: https://github.com/ltdrdata/ComfyUI-Impact-Pack

After a clean new install and update of ComfyUI, as well as your manager, I'm still presented with the same error code after trying to install via manager. Git pull throws the same error on ComfyUI startup.

Ah yes, it does them see module files are present, though:
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/132880886/209bfa79-1fb8-4c7b-9349-bf1c3de5012b)

The impact pack and your work on the SAM detector and Clipspace are so very central to my workflows, that I'm currently very hampered in using ComfyUI (why go back to A1111 lol). So a huge Thank You! for everything you're doing and making possible.

**Comment by ltdrdata** [comment]
> 

Oh... I missed that bug. Now it will work. Thank you.
