### ISSUE TITLE
setget node can't  load by other's workflow

### ISSUE THREAD

**Issue by xueqing0622** [Comfy-Org/ComfyUI-Manager#196]
I install setget node ./web/extensions/diffus3, 
https://github.com/diffus3/ComfyUI-extensions
I can put setget node by comfyui,
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/114840118/e17896f0-026b-4eb4-833e-e9fba4ee4d95)
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/114840118/82276237-db42-4a7d-a427-017ea7d5b577)

but when I drag other workflow incudle setget node, always say the node's is not found,
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/114840118/5debf437-d158-4213-8805-492a5afefc12)

**Comment by xueqing0622** [comment]
and install miss custom nodes, nothing show!

**Comment by ltdrdata** [comment]
The "front" node cannot be recognized by the manager's scanner, so unless explicitly provided by the custom node creator, the functionality cannot be supported.

**Comment by xueqing0622** [comment]
thx your answer, I write down to creator too!
