### ISSUE TITLE
New Icon is terrible

### ISSUE THREAD

**Issue by sedetweiler** [Comfy-Org/ComfyUI-Manager#197]
The badges are really handy for figuring out what groups nodes belong to.  This new manager icon is so frustrating as it not only undermines that idea, it is also showing how everyone can now make this useless for their own node suite.  Perhaps add a hover hint so we can spend minutes hovering over the ton of new icons people will start using now that they have this silly idea in their heads?

If are you looking for new nodes, we really need some tree management. It is a complete mess and rearranging, renaming, and hiding things would go a long way to helping with the duplication of features that are hitting us every day.

**Comment by sedetweiler** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/8366665/cada39e2-8fa7-467e-a973-8f1e892a8190)
Terrible.

**Comment by ltdrdata** [comment]
The reason it was added is to distinguish between vanilla nodes and unknown nodes. Adding the full text "ComfyUI" to all vanilla nodes seemed excessive, so a single emoji that takes up the least space was assigned for this purpose.

The method of adding ??? to unknown nodes was also considered, but it didn't feel appropriate either.

Anyway, I was considering adding a hide option because some people find it bothersome. I have updated it to version 1.5.2.

edit: But the `Mask To Image (mtb)` seems buggy.. That should not happen.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/578faa73-d448-4c57-a0ce-5cc24c7efd50)


Oh.. I understand why...
mtb node has overrided vanilla node.
It cannot be fixed.

**Comment by sedetweiler** [comment]
Thank you.  Yes, this was amazingly annoying as I had no idea what it meant and it was not documented. Also, it created a visual draw which was bad for trying to keep focused.  I get that you want to keep the vanilla nodes notated, and that makes sense.  I assume if they have no badge, they are base nodes.  Thank you for fixing this so quickly!  Cheers!

**Comment by ltdrdata** [comment]
> Thank you. Yes, this was amazingly annoying as I had no idea what it meant and it was not documented. Also, it created a visual draw which was bad for trying to keep focused. I get that you want to keep the vanilla nodes notated, and that makes sense. I assume if they have no badge, they are base nodes. Thank you for fixing this so quickly! Cheers!

It's the opposite. Nodes with the fox icon are the built-in nodes. If there is no badge, it means there is no information available, making it an unidentifiable node. Due to the variety of updates, documentation has not been completed yet. The documentation will be updated soon.
