### ISSUE TITLE
Error occurred when executing VHS_VideoCombine

### ISSUE THREAD

**Issue by chlowden** [Comfy-Org/ComfyUI-Manager#199]
Hello
I am running comfyui for sdv tests on a rocky linux 8.9 machine. I have downloaded all the latest versions and reinstalled the VHS_VideoCombine twice but I continue to get the error below. ffmpeg is installed and so is imageio-ffmpeg
but I continue to gee the error below

Thank you
`

Error occurred when executing VHS_VideoCombine:

An error occured in the ffmpeg subprocess:
Unrecognized option 'crf'.
Error splitting the argument list: Option not found

  File "/home/admin/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/admin/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/admin/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/admin/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 211, in combine_video
    raise Exception("An error occured in the ffmpeg subprocess:\n" \
`

**Comment by ltdrdata** [comment]
That issue should reported to here:
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues
