### ISSUE TITLE
My ComfyUI Manager Menu interface is not updating

### ISSUE THREAD

**Issue by selim-yildirim** [Comfy-Org/ComfyUI-Manager#208]
Hello friends,
Unfortunately, I cannot update My ComfyUI Manager Menu interface.
I would like to share the following detail with you.
If anyone has a solution to this issue, I would be very happy if you could share it with me.
This is the current Manager Menu.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/59798944/8586c6fe-a5b1-49ec-8b31-241f16b994d7)

Cannot import C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff module for custom nodes: module 'comfy.model_management' has no attribute 'maximum_batch_area'
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
[WARN] ComfyUI-Impact-Pack: `ComfyUI` or `ComfyUI-Manager` is an outdated version.
### Loading: ComfyUI-Inspire-Pack (V0.47.2)
Package diffusers is already installed.

**Comment by ltdrdata** [comment]
Fetch updates isn't updating nodes. You need to update in Install Custom Nodes after uncheck `Skip update check`.

**Comment by selim-yildirim** [comment]
Very very thank you.
All the best.
