### ISSUE TITLE
Feature Request: "Restart ComfyUI" button

### ISSUE THREAD

**Issue by tomhuze** [Comfy-Org/ComfyUI-Manager#210]
Requesting a permanent "Restart ComfyUI" button on the main menu.
One use case I've run into is: after adding adding a custom node that requires a restart it is possible (due to force of habit mostly) to close the custom node's modal that has the "Restart" button in it rendering it permanently inaccessible, at which point a manual restart is needed. If there was always a "Restart ComfyUI" button available it would make restarting ComfyUI at will very simple for the user.

**Comment by tomhuze** [comment]
@ltdrdata I should have mentioned: thank you for the "Restart" button added in the latest release, which does make the install flow much easier, this is a small iteration on that. And thanks for all of your work on ComfyUI-Manager, one of the most *essential* aspects of ComfyUI.

**Comment by ltdrdata** [comment]
> Requesting a permanent "Restart ComfyUI" button on the main menu.
> One use case I've run into is: after adding adding a custom node that requires a restart it is possible (due to force of habit mostly) to close the custom node's modal that has the "Restart" button in it rendering it permanently inaccessible, at which point a manual restart is needed. If there was always a "Restart ComfyUI" button available it would make restarting ComfyUI at will very simple for the user.

I'm currently waiting because there's a possibility that the permanent restart button will be merged into ComfyUI itself.

And this is sort of a experimental feature.
I found that the behavior is little bit awkward on portable's batch file.

**Comment by ltdrdata** [comment]
This is added, already.
