### ISSUE TITLE
Support for Colab Users

### ISSUE THREAD

**Issue by xliry** [Comfy-Org/ComfyUI-Manager#211]
Hi,

Im using colab version of comfyui manager, few features dont work. it will be great if you can fix bugs and i can keep update this title

-install missing custom nodes feature dont work.

**Comment by ltdrdata** [comment]
Can you provide specific details about the situation where it's not working?

**Comment by xliry** [comment]
> Can you provide specific details about the situation where it's not working?

for example when there is missing node
![github-1](https://github.com/ltdrdata/ComfyUI-Manager/assets/76709233/9e351738-70ff-48b5-bfcc-77c1415e158b)

![github-2](https://github.com/ltdrdata/ComfyUI-Manager/assets/76709233/33693194-137c-471f-b994-229c1bbbe02a)
install missing custom nodes feature tab dont show missing notes,

![github-3](https://github.com/ltdrdata/ComfyUI-Manager/assets/76709233/eacd5acb-1b03-4305-b7fd-bb6ea093d2a7)
when i click install models tab is not opened

![github-4](https://github.com/ltdrdata/ComfyUI-Manager/assets/76709233/d2f06d96-af2f-40b4-844f-ff46fefc653e)
install custom nodes tab only show 27 node,

**Comment by ltdrdata** [comment]
> > Can you provide specific details about the situation where it's not working?
> 
> for example when there is missing node ![github-1](https://private-user-images.githubusercontent.com/76709233/287835322-9e351738-70ff-48b5-bfcc-77c1415e158b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzYyNzcsIm5iZiI6MTcwMTczNTk3NywicGF0aCI6Ii83NjcwOTIzMy8yODc4MzUzMjItOWUzNTE3MzgtNzBmZi00OGI1LWJmY2MtNzdjMTQxNWUxNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNjAyZDk0NWRiMmQ1N2YyYWRlOWM2NGQxYmYwYmIyZThmNGEzNTAxYWJiZWI2ZDFmZTdkYzFiNGU0ZTJkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zg0YyycTa_RvjewetZOo2O7ZxZCpseMf8T7gVxZXkPI)
> 
> ![github-2](https://private-user-images.githubusercontent.com/76709233/287835466-33693194-137c-471f-b994-229c1bbbe02a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzYyNzcsIm5iZiI6MTcwMTczNTk3NywicGF0aCI6Ii83NjcwOTIzMy8yODc4MzU0NjYtMzM2OTMxOTQtMTM3Yy00NzFmLWI5OTQtMjI5YzFiYmJlMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNDE5YjI0NmYzOGI0NWU5OTg3MzUzMTM1YWMzZTI4Y2E1Y2VjMTA0MzQzMTljYTVlMjIyZDRlM2IxOTVmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZTylhUyFD96Db6Nnj_9iDee2HlnGfZETVsBKXqXzDYY) install missing custom nodes feature tab dont show missing notes,
> 
> ![github-3](https://private-user-images.githubusercontent.com/76709233/287835670-eacd5acb-1b03-4305-b7fd-bb6ea093d2a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzYyNzcsIm5iZiI6MTcwMTczNTk3NywicGF0aCI6Ii83NjcwOTIzMy8yODc4MzU2NzAtZWFjZDVhY2ItMWIwMy00MzA1LWI3ZmQtYmI2ZWEwOTNkMmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMjM2MDdkYTc1OWNkNDg5YzRlZTIzY2NmNzllN2EyNzY4MzYxZWMzMzcxZTFhNWQwNGFiYjU5Nzk3Njk4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.89znfLSrotSaZoVadWWanEI43IQVhU5aBr0nfCkNfZ4) when i click install models tab is not opened
> 
> ![github-4](https://private-user-images.githubusercontent.com/76709233/287835764-d2f06d96-af2f-40b4-844f-ff46fefc653e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzYyNzcsIm5iZiI6MTcwMTczNTk3NywicGF0aCI6Ii83NjcwOTIzMy8yODc4MzU3NjQtZDJmMDZkOTYtYWYyZi00MGI0LTg0NGYtZmY0NmZlZmM2NTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMDUxYjk0MzQzMjI1OTBjZGUyZWUxMGEzZjFhNWVkM2E5MmYwYmNmNzkzOGQyZjY5Nzc5ZGVlZGFlMjY1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nlfMrJiZErBtSjOefvJ-t1-q0iLjViJuOdCLN4DYN4Q) install custom nodes tab only show 27 node,

Your channel is `dev` change it to `default`

**Comment by xliry** [comment]
> > > Can you provide specific details about the situation where it's not working?
> > 
> > 
> > for example when there is missing node ![github-1](https://private-user-images.githubusercontent.com/76709233/287835322-9e351738-70ff-48b5-bfcc-77c1415e158b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzYyNzcsIm5iZiI6MTcwMTczNTk3NywicGF0aCI6Ii83NjcwOTIzMy8yODc4MzUzMjItOWUzNTE3MzgtNzBmZi00OGI1LWJmY2MtNzdjMTQxNWUxNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNjAyZDk0NWRiMmQ1N2YyYWRlOWM2NGQxYmYwYmIyZThmNGEzNTAxYWJiZWI2ZDFmZTdkYzFiNGU0ZTJkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zg0YyycTa_RvjewetZOo2O7ZxZCpseMf8T7gVxZXkPI)
> > ![github-2](https://private-user-images.githubusercontent.com/76709233/287835466-33693194-137c-471f-b994-229c1bbbe02a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzYyNzcsIm5iZiI6MTcwMTczNTk3NywicGF0aCI6Ii83NjcwOTIzMy8yODc4MzU0NjYtMzM2OTMxOTQtMTM3Yy00NzFmLWI5OTQtMjI5YzFiYmJlMDJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNDE5YjI0NmYzOGI0NWU5OTg3MzUzMTM1YWMzZTI4Y2E1Y2VjMTA0MzQzMTljYTVlMjIyZDRlM2IxOTVmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZTylhUyFD96Db6Nnj_9iDee2HlnGfZETVsBKXqXzDYY) install missing custom nodes feature tab dont show missing notes,
> > ![github-3](https://private-user-images.githubusercontent.com/76709233/287835670-eacd5acb-1b03-4305-b7fd-bb6ea093d2a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzYyNzcsIm5iZiI6MTcwMTczNTk3NywicGF0aCI6Ii83NjcwOTIzMy8yODc4MzU2NzAtZWFjZDVhY2ItMWIwMy00MzA1LWI3ZmQtYmI2ZWEwOTNkMmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMjM2MDdkYTc1OWNkNDg5YzRlZTIzY2NmNzllN2EyNzY4MzYxZWMzMzcxZTFhNWQwNGFiYjU5Nzk3Njk4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.89znfLSrotSaZoVadWWanEI43IQVhU5aBr0nfCkNfZ4) when i click install models tab is not opened
> > ![github-4](https://private-user-images.githubusercontent.com/76709233/287835764-d2f06d96-af2f-40b4-844f-ff46fefc653e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MzYyNzcsIm5iZiI6MTcwMTczNTk3NywicGF0aCI6Ii83NjcwOTIzMy8yODc4MzU3NjQtZDJmMDZkOTYtYWYyZi00MGI0LTg0NGYtZmY0NmZlZmM2NTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDAwMjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMDUxYjk0MzQzMjI1OTBjZGUyZWUxMGEzZjFhNWVkM2E5MmYwYmNmNzkzOGQyZjY5Nzc5ZGVlZGFlMjY1NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nlfMrJiZErBtSjOefvJ-t1-q0iLjViJuOdCLN4DYN4Q) install custom nodes tab only show 27 node,
> 
> Your channel is `dev` change it to `default`

thanks, worked
