### ISSUE TITLE
Tutorial nodes

### ISSUE THREAD

**Issue by Suzie1** [Comfy-Org/ComfyUI-Manager#216]
Hi,

I made some tutorial nodes so it is possible you may get some duplicate nodes from people practicing making nodes.

The original nodes are located in https://github.com/Suzie1/ComfyUI_Guide_To_Making_Custom_Nodes

The nodes are called:
    Print Hello World
    Concatenate Hello World
    Hello World Overlay Text

You may want to create a filter to remove duplicates of these if you start seeing a lot of duplicates.

Suzie

**Comment by ltdrdata** [comment]
Thank you for the notice.
