### ISSUE TITLE
ComfyUI-Manager no longer working on Google Colab

### ISSUE THREAD

**Issue by wordbrew** [Comfy-Org/ComfyUI-Manager#218]
Hi,

I'm trying to problem solve this and having little luck. I have comfy on google colab with ComfyUI-Manager installed. Everything was working fine yesterday. It is no longer working today though. This includes with a completely fresh install of comfy, working off your notebook.

It installs okay and loads dependencies, though with this error noted:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> torchaudio 2.1.0+cu118 requires torch==2.1.0, but you have torch 2.1.1+cu121 which is incompatible.
> torchdata 0.7.0 requires torch==2.1.0, but you have torch 2.1.1+cu121 which is incompatible.
> torchtext 0.16.0 requires torch==2.1.0, but you have torch 2.1.1+cu121 which is incompatible.
> torchvision 0.16.0+cu118 requires torch==2.1.0, but you have torch 2.1.1+cu121 which is incompatible.**

And when trying to run via cloudflare from a completely new install of Comfy with ComfyUI-Manager, I get the following error:
> 
> Prestartup times for custom nodes:
>    0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager
> 
> Total VRAM 15102 MB, total RAM 52221 MB
> xformers version: 0.0.23+cu118
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 Tesla T4 : cudaMallocAsync
> VAE dtype: torch.float32
> Using xformers cross attention
> Traceback (most recent call last):
>   File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1800, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_upscale_model.py", line 2, in <module>
>     from comfy_extras.chainner_models import model_loading
>   File "/content/drive/MyDrive/ComfyUI/comfy_extras/chainner_models/model_loading.py", line 8, in <module>
>     from .architecture.LaMa import LaMa
>   File "/content/drive/MyDrive/ComfyUI/comfy_extras/chainner_models/architecture/LaMa.py", line 15, in <module>
>     from torchvision.transforms.functional import InterpolationMode, rotate
>   File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 6, in <module>
>     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
>   File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 7, in <module>
>     import torchvision.extension  # noqa: F401
>   File "/usr/local/lib/python3.10/dist-packages/torchvision/extension.py", line 92, in <module>
>     _check_cuda_version()
>   File "/usr/local/lib/python3.10/dist-packages/torchvision/extension.py", line 78, in _check_cuda_version
>     raise RuntimeError(
> RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA major versions. PyTorch has CUDA Version=12.1 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
> 
> Cannot import /content/drive/MyDrive/ComfyUI/comfy_extras/nodes_upscale_model.py module for custom nodes: Detected that PyTorch and torchvision were compiled with different CUDA major versions. PyTorch has CUDA Version=12.1 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
> ### Loading: ComfyUI-Manager (V1.6.4)
> Traceback (most recent call last):
>   File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1800, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 86, in <module>
>     from torchvision.datasets.utils import download_url
>   File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 6, in <module>
>     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
>   File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 7, in <module>
>     import torchvision.extension  # noqa: F401
>   File "/usr/local/lib/python3.10/dist-packages/torchvision/extension.py", line 92, in <module>
>     _check_cuda_version()
>   File "/usr/local/lib/python3.10/dist-packages/torchvision/extension.py", line 78, in _check_cuda_version
>     raise RuntimeError(
> **RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA major versions. PyTorch has CUDA Version=12.1 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.
> 
> Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager module for custom nodes: Detected that PyTorch and torchvision were compiled with different CUDA major versions. PyTorch has CUDA Version=12.1 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.**
> 
> Import times for custom nodes:
>    **0.1 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager**
> 
> 
> ComfyUI finished loading, trying to launch cloudflared (if it gets stuck here cloudflared is having issues)

Comfy was failing to import all nodes I had installed through ComfyUI-Manager which was why I tried to do a completely fresh install. Unfortunately that did not work to fix.

Any ideas?

**Comment by ltdrdata** [comment]
Modify this on notebook and retry

From
`
!pip install xformers!=0.0.18 -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121 --extra-index-url https://download.pytorch.org/whl/cu118 --extra-index-url https://download.pytorch.org/whl/cu117
`

To
`
!pip install xformers!=0.0.18 -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118 --extra-index-url https://download.pytorch.org/whl/cu117
`

**Comment by wordbrew** [comment]
Figured out the issue. It was conflicting CUDA install from the comfyui dependencies. Since the requirements.txt file for Comfy only calls out torch, it was uninstalling torch 2.1.0+cu118 and replacing it with torch 2.1.1+cu121 which was causing several custom nodes to fail, including ComfyUI-Manager. Modifying the requirements.txt file to call out the specific torch and cuda version solved it. Mostly. I'm still having some nodes fail to import, so I am going to try to remove them from the directory and install through Manager again.

**Comment by ltdrdata** [comment]
> Figured out the issue. It was conflicting CUDA install from the comfyui dependencies. Since the requirements.txt file for Comfy only calls out torch, it was uninstalling torch 2.1.0+cu118 and replacing it with torch 2.1.1+cu121 which was causing several custom nodes to fail, including ComfyUI-Manager. Modifying the requirements.txt file to call out the specific torch and cuda version solved it. Mostly. I'm still having some nodes fail to import, so I am going to try to remove them from the directory and install through Manager again.

It is preferable to take out `-r requirements.txt` and list the dependencies directly in the pip install command. If you modify that file, issues may arise when updating.

**Comment by f0ster** [comment]
> Modify this on notebook and retry
> 
> From `!pip install xformers!=0.0.18 -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121 --extra-index-url https://download.pytorch.org/whl/cu118 --extra-index-url https://download.pytorch.org/whl/cu117`
> 
> To `!pip install xformers!=0.0.18 -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu118 --extra-index-url https://download.pytorch.org/whl/cu117`

I had to modify the comfyui colab setup in the same way to get it working , fwiw
