### ISSUE TITLE
ComfyUI-Manager (V0.11) not loaded

### ISSUE THREAD

**Issue by SteveM50** [Comfy-Org/ComfyUI-Manager#22]
### ComfyUI Revision: 41 on 'main' [4544078f]
Traceback (most recent call last):
  File "f:\ComfyUI_windows_portable_nvidia_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 985, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable_nvidia_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 240, in <module>
    @server.PromptServer.instance.routes.get("/customnode/getmappings")
AttributeError: type object 'PromptServer' has no attribute 'instance'

Cannot import F:\ComfyUI_windows_portable_nvidia_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: type object 'PromptServer' has no attribute 'instance'
WAS Node Suite: Loaded
Set vram state to: NORMAL VRAM
Starting server

pls help

**Comment by ltdrdata** [comment]
You should update ComfyUI to latest version. Your ComfyUI version is too old.

**Comment by ddeamil** [comment]
Hello dear ltdrdata, in response to :
Is it possible to provide full log output to console when starting ComfyUI?

C:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto
Total VRAM 16384 MB, total RAM 32428 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti Laptop GPU
Using xformers cross attention
Adding extra search path checkpoints C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/hypernetworksAdding extra search path controlnet C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/ControlNet
Requirement already satisfied: GitPython in c:\users\desmo\appdata\roaming\python\python310\site-packages (from -r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (3.1.32)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\desmo\appdata\roaming\python\python310\site-packages (from GitPython->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (4.0.10)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\desmo\appdata\roaming\python\python310\site-packages (from gitdb<5,>=4.0.1->GitPython->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (5.0.0)
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 7, in <module>
    import git
ModuleNotFoundError: No module named 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1509, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 12, in <module>
    import git
ModuleNotFoundError: No module named 'git'

Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: No module named 'git'

Import times for custom nodes:
   1.3 seconds (IMPORT FAILED): C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

**Comment by zayyarroo** [comment]
> Hello dear ltdrdata, in response to : Is it possible to provide full log output to console when starting ComfyUI?
> 
> C:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto Total VRAM 16384 MB, total RAM 32428 MB xformers version: 0.0.20 Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 3080 Ti Laptop GPU Using xformers cross attention Adding extra search path checkpoints C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/Stable-diffusion Adding extra search path configs C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/Stable-diffusion Adding extra search path vae C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/VAE Adding extra search path loras C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/Lora Adding extra search path loras C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/LyCORIS Adding extra search path upscale_models C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/ESRGAN Adding extra search path upscale_models C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/RealESRGAN Adding extra search path upscale_models C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/SwinIR Adding extra search path embeddings C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\embeddings Adding extra search path hypernetworks C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/hypernetworksAdding extra search path controlnet C:\AI\Stable diffusion_Automatic-1111\stable-diffusion-webui\models/ControlNet Requirement already satisfied: GitPython in c:\users\desmo\appdata\roaming\python\python310\site-packages (from -r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (3.1.32) Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\desmo\appdata\roaming\python\python310\site-packages (from GitPython->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (4.0.10) Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\desmo\appdata\roaming\python\python310\site-packages (from gitdb<5,>=4.0.1->GitPython->-r C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\requirements.txt (line 1)) (5.0.0) Traceback (most recent call last): File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager__init__.py", line 7, in import git ModuleNotFoundError: No module named 'git'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1509, in load_custom_node module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager__init__.py", line 12, in import git ModuleNotFoundError: No module named 'git'
> 
> Cannot import C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: No module named 'git'
> 
> Import times for custom nodes: 1.3 seconds (IMPORT FAILED): C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Starting server

same error to me Using Latest Comfy

**Comment by ltdrdata** [comment]
Try update ComfyUI-Manager.
I have patched the installation process, hoping it will work.
This phenomenon is difficult to reproduce because it only occurs in specific environments.

**Comment by Dvorak-Design** [comment]
I'm using the latest version of ComfyUI, manager and Python, and the cmd says that importing custom nodes failed.

**Comment by ltdrdata** [comment]
> I'm using the latest version of ComfyUI, manager and Python, and the cmd says that importing custom nodes failed.

Please, show me the full error log.

**Comment by Dvorak-Design** [comment]
> > I'm using the latest version of ComfyUI, manager and Python, and the cmd says that importing custom nodes failed.
> 
> Please, show me the full error log.

D:\klon\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 8191 MB, total RAM 32665 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
Using xformers cross attention
Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\klon\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'

Cannot import D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\.git module for custom nodes: [Errno 2] No such file or directory: 'D:\\klon\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\.git\\__init__.py'
Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\git_helper.py", line 3, in <module>
    import git
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Cannot import D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\git_helper.py module for custom nodes: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\klon\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\js\\__init__.py'

Cannot import D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\js module for custom nodes: [Errno 2] No such file or directory: 'D:\\klon\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\js\\__init__.py'
Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\klon\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\misc\\__init__.py'

Cannot import D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\misc module for custom nodes: [Errno 2] No such file or directory: 'D:\\klon\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\misc\\__init__.py'
Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\scanner.py", line 4, in <module>
    from git import Repo
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Cannot import D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\scanner.py module for custom nodes: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

Requirement already satisfied: GitPython in d:\klon\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from -r D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\requirements.txt (line 1)) (3.1.32)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\klon\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from GitPython->-r D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\requirements.txt (line 1)) (4.0.10)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\klon\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from gitdb<5,>=4.0.1->GitPython->-r D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\requirements.txt (line 1)) (5.0.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\__init__.py", line 7, in <module>
    import git
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1590, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\__init__.py", line 12, in <module>
    import git
  File "D:\klon\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Cannot import D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\__init__.py module for custom nodes: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\misc
   0.0 seconds (IMPORT FAILED): D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\js
   0.0 seconds (IMPORT FAILED): D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\.git
   0.0 seconds (IMPORT FAILED): D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\scanner.py
   0.0 seconds (IMPORT FAILED): D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\git_helper.py
   0.9 seconds (IMPORT FAILED): D:\klon\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\__init__.py

Starting server

**Comment by ltdrdata** [comment]
It seems you did uncompressed manager into custom_nodes directory, directly.

You can find hidden .git folder inside custom_nodes directory.

Remove that directory and other .py files, too.


And if there is ComfyUI-Manager directory.
Remove it too.
And reinstall through installation[method2].

**Comment by Dvorak-Design** [comment]
> It seems you did uncompressed manager into custom_nodes directory, directly.
> 
> You can find hidden .git folder inside custom_nodes directory.
> 
> Remove that directory and other .py files, too.
> 
> And if there is ComfyUI-Manager directory. Remove it too. And reinstall through installation[method2].

If I use method 2, nothing happens at all. I run install-manager-for-portable-version.bat but nothing gets saved in the custom_nodes folder.

D:\klon\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 8191 MB, total RAM 32665 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
Using xformers cross attention
Starting server

**Comment by Taikakim** [comment]
I have this issue... I've been running the official ComfyUI Colab for some time already, but now started from the Manager notebook. I have ran now both two times with update on, and latest notebooks from GitHub:
```

/tools/node/bin/lt -> /tools/node/lib/node_modules/localtunnel/bin/lt.js
+ localtunnel@2.0.2
added 22 packages from 22 contributors in 2.198s
** ComfyUI start up time: 2023-09-16 15:33:01.787355

Prestartup times for custom nodes:
   0.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 40514 MB, total RAM 85484 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A100-SXM4-40GB : cudaMallocAsync
Using xformers cross attention
2023-09-16 15:33:23.648923: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1596, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/__init__.py", line 1, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.nodes import edge_line, normal_depth_map, pose, semseg, others
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/nodes/semseg.py", line 5, in <module>
    from ..v11 import oneformer
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/oneformer/__init__.py", line 4, in <module>
    from .api import make_detectron2_model, semantic_run
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/oneformer/api.py", line 10, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.v11.oneformer.oneformer import (
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/oneformer/oneformer/__init__.py", line 9, in <module>
    from .oneformer_model import OneFormer
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/oneformer/oneformer/oneformer_model.py", line 24, in <module>
    from custom_nodes.comfy_controlnet_preprocessors.v11.oneformer.oneformer.data.tokenizer import SimpleTokenizer, Tokenize
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors/v11/oneformer/oneformer/data/tokenizer.py", line 32, in <module>
    import ftfy
ModuleNotFoundError: No module named 'ftfy'

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors module for custom nodes: No module named 'ftfy'
## ComfyUI-Manager: installing dependencies
 Collecting GitPython (from -r /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/requirements.txt (line 1))
   Downloading GitPython-3.1.36-py3-none-any.whl (189 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.5/189.5 kB 3.2 MB/s eta 0:00:00
 Collecting gitdb<5,>=4.0.1 (from GitPython->-r /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/requirements.txt (line 1))
   Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 8.1 MB/s eta 0:00:00
 Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython->-r /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/requirements.txt (line 1))
   Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
 Installing collected packages: smmap, gitdb, GitPython
 Successfully installed GitPython-3.1.36 gitdb-4.0.10 smmap-5.0.0
## ComfyUI-Manager: installing dependencies done.
### Loading: ComfyUI-Manager (V0.26.2)


## [WARN] ComfyUI-Manager: Your ComfyUI version (1221) is too old. Please update to the latest version. ##


### ComfyUI Revision: 1221 [95d796fc]
[WARN] ComfyUI-Manager: Your ComfyUI version is outdated. Please update to the latest version.
### ComfyUI-Manager: Copy .js from '/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/js/comfyui-manager.js' to '/content/drive/MyDrive/ComfyUI/web/extensions/comfyui-manager'

Import times for custom nodes:
   1.4 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/comfy_controlnet_preprocessors
  20.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager


ComfyUI finished loading, trying to launch localtunnel (if it gets stuck here localtunnel is having issues)
```

**Comment by ltdrdata** [comment]
`comfy_controlnet_preprocessors` is deprecated remove it. 
And install ComfyUI Auxiliary Preprocessors.
