### ISSUE TITLE
Comfy Stopped Working in Colab 

### ISSUE THREAD

**Issue by cjtri3d** [Comfy-Org/ComfyUI-Manager#225]
The notebook was working fine till a couple of days ago and I was able to use all custom nodes. Now when I run the notebook some new version of torch is being installed. This is causing a chain reaction of dependency issues, All custom nodes are becoming incompatible and are failing to load. Please help me rectify this issue. I tried
1. Deleting the comfy folder from Gdrive and rerunning the notebook
2. . Tried out different notebooks from the internet. 

I'm not very proficient with diagnosing the code and troubleshooting. Some help will be great. 
![unnamed](https://github.com/ltdrdata/ComfyUI-Manager/assets/153291082/f453847c-c124-4187-aa39-6cd32aaf591b)

**Comment by LiesInTheDark** [comment]
I have figured out the solution. You just need to reinstall the previous version of Torch. Sync the cuda version of torch and torchvision.

**Comment by ltdrdata** [comment]
I just updated new notebook. Try this.
Test done.

**Comment by cjtri3d** [comment]
There seems to be a new error in updated colab notebook
![Screenshot_3](https://github.com/ltdrdata/ComfyUI-Manager/assets/153291082/155ed948-d19a-43f4-a0f9-012f8d946f6a)
. Should I be worried about this ?
