### ISSUE TITLE
Manager breaks my ComfyUI installation

### ISSUE THREAD

**Issue by ckombo** [Comfy-Org/ComfyUI-Manager#231]
Hi. When I place the ComfyUI-Manager files within my 'custom_nodes' folder my comfy UI install fails to startup. It gives a 'pause' message and stalls. When I removed the Manager files from 'custom_nodes' it works again. Please help.

**Comment by ltdrdata** [comment]
How did you install ComfyUI-Manager?
And what is your environment?

**Comment by ckombo** [comment]
I resolved the problem: I had installed it by placing the unzipped files in the root of the 'custom_nodes' folder instead of inside it's own folder with that custome_nodes folder.

**Comment by ltdrdata** [comment]
I need to update install guide.
Many user make such mistakes.

**Comment by johnebravo** [comment]
Solution?

**Comment by ltdrdata** [comment]
> Solution?

https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#installation
