### ISSUE TITLE
"FETCH DATA"  take long time every startup , can I close the FETCH DATA every startup

### ISSUE THREAD

**Issue by xueqing0622** [Comfy-Org/ComfyUI-Manager#233]
"FETCH DATA"  take long time every startup , can I close the FETCH DATA every startup

**Comment by ltdrdata** [comment]
It's just a background caching. You can ignore it.

**Comment by WeirdScienceX** [comment]
Is that what's causing the delay? It never happened when I last used it.  I've been experimenting loading different nodes, and every startup it takes around 10 seconds before the manager button appears and the workflow loads

**Comment by ltdrdata** [comment]
> Is that what's causing the delay? It never happened when I last used it. I've been experimenting loading different nodes, and every startup it takes around 10 seconds before the manager button appears and the workflow loads

Please disable all custom nodes except for ComfyUI-Manager and test it.

**Comment by xueqing0622** [comment]
every startup it takes around more than 60 seconds before the manager button appears and the workflow loads, 
I install too many extension, 
 It is hard to test Who takes the most startup time, it would be nice to have a functionality that detects every extentsion takes how many time. just like a little windows startup time counter.

**Comment by ltdrdata** [comment]
> every startup it takes around more than 60 seconds before the manager button appears and the workflow loads, I install too many extension, It is hard to test Who takes the most startup time, it would be nice to have a functionality that detects every extentsion takes how many time. just like a little windows startup time counter.

There is already.
```

Import times for custom nodes:
   0.0 seconds:FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json 
/home/me/github/ComfyUI/custom_nodes/ComfyUI-Impact-ExpFETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

   0.0 seconds:FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json 
/home/me/github/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/stability-ComfyUI-nodes
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/comfyui-tooling-nodes
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyLiterals
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI_experiments
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/comfy_PoP
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/clipseg.py
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/Comfy_KepListStuff
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.0 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI-Manager
   0.3 seconds: /home/me/github/ComfyUI/custom_nodes/NodeGPT
   0.7 seconds: /home/me/github/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.9 seconds: /home/me/github/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
```

The issue is not just that. For nodes like the `mtb` nodes, font caching starts when the browser is first launched, outside of import time, and that process consumes a significant amount of time there.

Anyway this issue isn't related to ComfyUI-Manager. I'll close this issue.

**Comment by xueqing0622** [comment]
yes, It is so quick no so many time every extension,  
but after this to startup up, after "FETCH DATA"  , it takes a lot of time before the manager button appears and the workflow loads! i dont know what takes so many time,

**Comment by ltdrdata** [comment]
> yes, It is so quick no so many time every extension, but after this to startup up, after "FETCH DATA" , it takes a lot of time before the manager button appears and the workflow loads! i dont know what takes so many time,

The "FETCH DATA" message that appears during startup simply indicates that it is being processed in the background and doesn't cause any delays in execution. Even if it takes, for example, 10 minutes, it merely reflects slow caching and doesn't impact the functionality of ComfyUI.

**Comment by WeirdScienceX** [comment]
> > Is that what's causing the delay? It never happened when I last used it. I've been experimenting loading different nodes, and every startup it takes around 10 seconds before the manager button appears and the workflow loads
> 
> Please disable all custom nodes except for ComfyUI-Manager and test it.

It was in fact the amount of nodes which was causing the delay, it starts up instantly now.  I will have to remember to disable any unneeded nodes
