### ISSUE TITLE
ComfyUI Manager not updating properly

### ISSUE THREAD

**Issue by brbbbq** [Comfy-Org/ComfyUI-Manager#240]
I had an issue last week caused by ComfyUI Manager not updating properly. The custom node I was trying to use required the latest version of ComfyUI, but when I updated using the manager, it wouldn't actually update.

I was able to solve the issue by running the update script manually in the "ComfyUI_windows_portable\update" folder on my PC.

I believe it was due to my use of Windows symbolic links in my ComfyUI install folder. I noticed other users on Discord having issues updating, don't know if this might be related to their issues or not.

![231214-182648-cmd](https://github.com/ltdrdata/ComfyUI-Manager/assets/135537138/4c0a478a-6f72-4107-8e74-a8ee54eac14a)

**Comment by ltdrdata** [comment]
You should not change folder to symbolic link. That is a limiation of git system. Symbolic link is regarded as a file. And if you replace it then git think some files in repository were modified.
