### ISSUE TITLE
“comfyUI manager”Sometimes it doesn't show

### ISSUE THREAD

**Issue by Bigleeeo** [Comfy-Org/ComfyUI-Manager#241]
Hello, I don't know if you have such a situation, most of the cases can be displayed plug-in, but occasionally there will be no display, help

**Comment by ltdrdata** [comment]
1. Check if "ComfyUI-Manager" is appearing as an import fail in the terminal logs.
2. Open the browser's devtools and check the console logs for any error messages.

**Comment by Gerkinfeltser** [comment]
@Bigleeeo I've been experiencing similar but find if you just wait it eventually all loads. I'm curious how to debug what's causing the lag though.

**Comment by ltdrdata** [comment]
> @Bigleeeo I've been experiencing similar but find if you just wait it eventually all loads. I'm curious how to debug what's causing the lag though.


There have been cases where someone waited for more than 10 minutes, but it's not a Manager issue. The Manager just loaded the latest.

Try removing all custom nodes except the Manager and test; that should clarify things.

**Comment by Gerkinfeltser** [comment]
Thanks again for the suggestion. fwiw it seems in my case the [Jovimetrix ](https://github.com/Amorano/Jovimetrix) extension was making manager loading super pokey! :( I noticed a huge loading manager lag with that extension installed. This is a shame cause there are some useful nodes in there.

**Comment by ltdrdata** [comment]
It seems advisable to report the performance issue on that repository.

**Comment by Gerkinfeltser** [comment]
Reported & fixed for me! https://github.com/Amorano/Jovimetrix/issues/5
