### ISSUE TITLE
JupyterLab

### ISSUE THREAD

**Issue by iaclaudioia8** [Comfy-Org/ComfyUI-Manager#244]
Hi all

I am trying use the Comfyui-Manager on my JupyterLab, but it is not working:

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/141835147/b51c7928-efc1-46ff-92e6-6c3d38f9052f)

I have launched this commands:

cd custom_nodes
git clone https://github.com/ltdrdata/ComfyUI-Manager.git
Restart ComfyUI

and this one:

sudo apt-get update
sudo apt-get install git

And i just got this:

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/141835147/7755b62e-257f-4f72-8344-7eee33b220e7)

Could you help me, please?
Thankyou so much :)

**Comment by ltdrdata** [comment]
I don't know why. But it is removed partially.

Delete that and git clone again.
If same issue is persistent then you'd better add clean installimg process to notebook script.
