### ISSUE TITLE
Manager UI/UX bug ? 

### ISSUE THREAD

**Issue by hbardak** [Comfy-Org/ComfyUI-Manager#245]
Hi 

I am not sure if this is due to an recent update but my manager UI seems to be broken. 
The close button seems to be on top of others 
Is there any way to get it back as intended ? 

![Screenshot 2023-12-16 212753](https://github.com/ltdrdata/ComfyUI-Manager/assets/26234254/838deb75-59de-46db-8ee7-519ad351fefb)

**Comment by ltdrdata** [comment]
This occurs when the horizontal space is too small or the resolution is low. Are you, by any chance, not using the browser in full screen?

Even when zoomed in browser, this issue may occur if the browser space is limited. Try resolving it by zooming out using Ctrl-wheel on the dialog.

The close button has been fixed to always be visible, and the menu column that lacked space has been moved down.

**Comment by hbardak** [comment]
Thank you ! this did the trick
