### ISSUE TITLE
Manager doesn't update Comfyroll Custom Nodes

### ISSUE THREAD

**Issue by Suzie1** [Comfy-Org/ComfyUI-Manager#248]
Hi,

For the last two weeks, users have been reporting that Comfyroll Custom Nodes doesn't do updates anymore. The update button doesn't appear after each release.

It may have stopped updating after the repository transfer from RockOfFire.

I have been advising users to delete and re-install after each release.

kind regards,
Suzie

**Comment by ltdrdata** [comment]
In theory, such a thing shouldn't happen, but it seems there was a divergence in branches between the repos. 

I've updated the guidance message and safely changed the path in the DB to the new repo.

**Comment by Suzie1** [comment]
Thank you, hopefully this will resolve the issue. Should I close it?

**Comment by Suzie1** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/42118269/e817d6c9-d5f8-4bac-97e3-13e9fb06b5ad)

Users are still reporting issues with updates. Is it possible that fonts installed by users in the folder below are preventing updates?
\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\fonts

The fonts are used by my graphics and text nodes. If this is the case I could potentially change to using the system fonts folder.

Suzie

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/42118269/292647442-e817d6c9-d5f8-4bac-97e3-13e9fb06b5ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNzc0MDMsIm5iZiI6MTcwMzM3NzEwMywicGF0aCI6Ii80MjExODI2OS8yOTI2NDc0NDItZTgxN2Q2YzktZDVmOC00YmFjLTk3ZTMtMTNlOWZiMDZiNWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDAwMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNWM4NGI2NTE0YTllYTE5ZmJjMjc4NmJhNzA0MTNhOWU2MDNiN2Q4ZjU2YWI4ZDJlMTQzYTA0ZGQ2YmIyMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vCVwx4szCZLOpmdn2HlgfIW4eTL99z2uV59FBiai26U)
> 
> Users are still reporting issues with updates. Is it possible that fonts installed by users in the folder below are preventing updates? \ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\fonts
> 
> The fonts are used by my graphics and text nodes. If this is the case I could potentially change to using the system fonts folder.
> 
> Suzie

Is the update failing because the Git file has been modified, or is it due to a lock issue?

**Comment by Suzie1** [comment]
Apologies, it looks like it was an error on my side. I have corrected the init file.

**Comment by Suzie1** [comment]
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/issues/74#issuecomment-1868401558

After the fix, a user reported the above error. I'm still thinking the fonts may be the cause. Is it bad practice to let users save fonts within a subfolder in the node pack?

**Comment by ltdrdata** [comment]
It appears that there might be files in the cr nodes repo that are being modified at runtime. Especially in the case of Windows or Colab, there is a phenomenon where permissions are forcibly modified or are not expressible, making it impossible to handle. Check for this.

`git diff`

**Comment by ltdrdata** [comment]
Ah... However, that's a different issue.

`stderr: 'error: The following untracked working tree files would be overwritten by merge:'`

This occurs when a file, which is not originally in the repo, has been added, and coincidentally, that file already exists in the corresponding location of the repo.

Did you happen to add some of the originally runtime-generated files to the repository?

**Comment by JFg111** [comment]
I have that problem of 

stderr: 'error: The following untracked working tree files would be overwritten by merge:'

You've been illariously cryptic about what it means and what to do about it. 
That sudently happend, and ever since I've not been able to update anything. 

I'm an average user that don't know too much about git and and Python. Like everyone else we just follow instructions
What you are saying above does not help a bit as most people are just user not expert in Python or Git. 

Should I totally erase everything and restart from new .or. there something else I should do??
I also have that font cashing error which as sudently appeared.

**Comment by Suzie1** [comment]
> Ah... However, that's a different issue.
> 
> `stderr: 'error: The following untracked working tree files would be overwritten by merge:'`
> 
> This occurs when a file, which is not originally in the repo, has been added, and coincidentally, that file already exists in the corresponding location of the repo.
> 
> Did you happen to add some of the originally runtime-generated files to the repository?

I really don't understand this enough to know how to answer it. Is it possible to put a trace in to find what is causing the error?

I have a lot of users and they have to re-install each time there is an update.

Is it possible the font files are causing this error? I have a sub-folder that people can add fonts into. If they add a font does this mean they can never update again without re-installing? If this is the case I could change them to use the system folder. Is it likely this is causing the problem?

Is there a way to override the above error and force update?

Suzie

**Comment by ltdrdata** [comment]
> > Ah... However, that's a different issue.
> > `stderr: 'error: The following untracked working tree files would be overwritten by merge:'`
> > This occurs when a file, which is not originally in the repo, has been added, and coincidentally, that file already exists in the corresponding location of the repo.
> > Did you happen to add some of the originally runtime-generated files to the repository?
> 
> I really don't understand this enough to know how to answer it. Is it possible to put a trace in to find what is causing the error?
> 
> I have a lot of users and they have to re-install each time there is an update.
> 
> Is it possible the font files are causing this error? I have a sub-folder that people can add fonts into. If they add a font does this mean they can never update again without re-installing? If this is the case I could change them to use the system folder. Is it likely this is causing the problem?
> 
> Is there a way to override the above error and force update?
> 
> Suzie

The situation where you cannot perform `git pull` is a problem in itself. It's crucial to clearly identify what is causing the issue. Once you identify the environment where the update fails, run `git status` to understand the root cause. This will help determine how to address the issue and proceed accordingly.

In essence, even if files are dynamically created, they should be excluded from the repository to prevent conflicts. The fact that this issue is occurring suggests that something beyond just adding files is taking place.

**Comment by loz2754** [comment]
I have just experienced a similar problem with Comfyroll failing to import when loading Comfyui. I am on 3.51 of comfyui portable (which runs python3.13), and 1.26.8 frontend. This happens every time I load comfyui. My only recourse is choose "try fix" in manager, which will allow comfyroll to load upon restarting comyfui, but only until next time I start comfyui from scratch, then I have to go through the same process again.
When comfyroll fails to import, 2 other nodes also fail to import - Grafting Rayman and InstantID IIRC.
Sorry if I am posting this in the wrong place.
