### ISSUE TITLE
Namespace custom nodes

### ISSUE THREAD

**Issue by ghostsquad** [Comfy-Org/ComfyUI-Manager#250]
Lots of nodes are reporting as "Conflicting". This seems to be because node names are identical either between custom_node installations, or with that of built-in/default nodes. I believe a solution would be to enforce some sort of namespacing, to avoid these conflicts.

**Comment by ghostsquad** [comment]
I'm actually not sure if this should be filed here, or in ComfyUI.

**Comment by ltdrdata** [comment]
That is an issue that each custom node developer needs to manage. ComfyUI-Manager merely about making users aware of issues that were previously hidden.

**Comment by PaulFidika** [comment]
100% agreed; custom nodes should be namespaced
