### ISSUE TITLE
Update Colab notebook for CUDA 12.1

### ISSUE THREAD

**Issue by BlakeOne** [Comfy-Org/ComfyUI-Manager#251]
Now that CUDA 12.1 is available it seems the Colab notebook needs an update... Here is the warning message which can be reproduced by running the notebook on Colab.

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
PyTorch 2.1.2+cu118 with CUDA 1108 (you have 2.1.2+cu121)
Python 3.10.13 (you have 3.10.12)
Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
Memory-efficient attention, SwiGLU, sparse and more won't be available.
Set XFORMERS_MORE_DETAILS=1 for more details

**Comment by ghost** [comment]
Just change in your notebook the line from:

```
!pip3 install xformers!=0.0.18 torch==2.1.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

to:

```
!pip3 install xformers!=0.0.18 torch==2.1.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```

**Comment by ltdrdata** [comment]
> Just change in your notebook the line from:
> 
> ```
> !pip3 install xformers!=0.0.18 torch==2.1.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> to:
> 
> ```
> !pip3 install xformers!=0.0.18 torch==2.1.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
> ```

Is it work? I can't test now.

**Comment by BlakeOne** [comment]
Yep it fixed it, thanks! :)

**Comment by ltdrdata** [comment]
I just updated this.
