### ISSUE TITLE
Manager for M1 computers

### ISSUE THREAD

**Issue by txs** [Comfy-Org/ComfyUI-Manager#253]
I put the manager in the custom node. However, M1 macs seems not loading the manager properly.

**Comment by ltdrdata** [comment]
I don't think that is the M1 and Manager Issue.

Show me the full startup log.

**Comment by JoeGarr2000** [comment]
> Puse el administrador en el nodo personalizado. Sin embargo, los Mac M1 parecen no cargar al administrador correctamente.

Hi, you need to replace the requirements.txt file installed in patch-1 of the Comfyu installation repository.: [https://github.com/savolla/ComfyUI/tree/patch-1](url)

Note that you must select Preview (Nightly) for MPS device acceleration during installation.
 `pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu` and the Manager will reappear.
