### ISSUE TITLE
AttributeError: type object 'KfPGroupProd' has no attribute 'INPUT_TYPES'

### ISSUE THREAD

**Issue by toyxyz** [Comfy-Org/ComfyUI-Manager#260]
At some point, this error occurs. It doesn't break anything. Does anyone else have the same error?

FETCH DATA from: C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'KfPGroupProd' node.
Traceback (most recent call last):
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\server.py", line 418, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\server.py", line 396, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'KfPGroupProd' has no attribute 'INPUT_TYPES'

**Comment by ltdrdata** [comment]
It is `ComfyUI-Keyframed` custom nodes issues.
Report that issue to there.
