### ISSUE TITLE
=== >>> Solved by oneself

### ISSUE THREAD

**Issue by fuckemooncoin** [Comfy-Org/ComfyUI-Manager#262]
It is taking forever to fetch data from Github and it stuck at this.  

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.jsonTo see the GUI go to: http://127.0.0.1:8188

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.jsonFETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**========>> Solved, This is a normal behavior of  ComfyUI-Manager node that is fetching data from ComfyUI-Manager's GUI**

And what are these errors?

[ERROR] ComfyUI-Manager: Failed to install the GitPython package in the correct Python environment. Please install it manually in the appropriate environment. (You can seek help at https://app.element.io/#/room/%23comfyui_space%3Amatrix.org)
ComfyUI-Manager: installing dependencies done.
ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)

========>> **Resolved after the installation of Windows version of Git( PortableGit that I used, caused the error) They said that this is caused by  bad Git.exe.**  Recent portableGit seems to have bad Git.exe issues and be aware of this. 

Consequently ComfyUI update failed. 
 
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/84866643/91fb0972-829e-423b-b33e-b36f52d9f89f)

**Comment by ltdrdata** [comment]
So what is the current error log on terminal?

**Comment by fuckemooncoin** [comment]
**Current log seems OK after the installation of Windows Git to solve bad Git problem caused by Portable Git** 

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/84866643/d849c50b-0952-4e72-9647-4b17a813f590)
