### ISSUE TITLE
Manager Update Fails but do install?

### ISSUE THREAD

**Issue by Piscabo** [Comfy-Org/ComfyUI-Manager#27]
I get a fail message, but If I do a manual git pull it shows as updated. Use to work fine the last Two days this started happening...
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/123719842/205ee81f-6073-4e21-98d8-c2cdc4a53e47)
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/123719842/fe2f1a4c-57eb-4218-a520-2dcc0c95c716)

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/123719842/bbc445a3-02a8-401e-af18-818a3ac1c134)
Update: ['https://github.com/LucianoCirino/efficiency-nodes-comfyui']
Install: pip packages
Update(git-clone) error: https://github.com/LucianoCirino/efficiency-nodes-comfyui / 'int' object has no attribute 'isdigit'
FECTH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by ltdrdata** [comment]
I just patched. 
Update to latest version.

**Comment by Piscabo** [comment]
Today's update fails:
ComfyUI-Manager>git pull
error: cannot lock ref 'refs/remotes/origin/main': is at c0164cc7cd47494b3a8c0597ad247c803e081a37 but expected fd04b65bdc936588353c82f4eb1afd1e7c0312ee
From https://github.com/ltdrdata/ComfyUI-Manager
 ! fd04b65..a361cc1  main       -> origin/main  (unable to update local ref)

**Comment by ltdrdata** [comment]
> Today's update fails:
> ComfyUI-Manager>git pull
> error: cannot lock ref 'refs/remotes/origin/main': is at c0164cc7cd47494b3a8c0597ad247c803e081a37 but expected fd04b65bdc936588353c82f4eb1afd1e7c0312ee
> From https://github.com/ltdrdata/ComfyUI-Manager
>  ! fd04b65..a361cc1  main       -> origin/main  (unable to update local ref)

I am sorry. I messed my repo.
download this into ComfyUI-Manager directory.  (!!never download into scripts dir)
And execute by your python environment.

https://github.com/ltdrdata/ComfyUI-Manager/blob/main/scripts/update-fix.py

or just do..

`git update-ref  refs/remotes/origin/main a361cc1 && git fetch --all && git pull` instead of `git pull`

**Comment by Piscabo** [comment]
> > Today's update fails:
> > ComfyUI-Manager>git pull
> > error: cannot lock ref 'refs/remotes/origin/main': is at [c0164cc](https://github.com/ltdrdata/ComfyUI-Manager/commit/c0164cc7cd47494b3a8c0597ad247c803e081a37) but expected [fd04b65](https://github.com/ltdrdata/ComfyUI-Manager/commit/fd04b65bdc936588353c82f4eb1afd1e7c0312ee)
> > From https://github.com/ltdrdata/ComfyUI-Manager
> > ! [fd04b65](https://github.com/ltdrdata/ComfyUI-Manager/commit/fd04b65bdc936588353c82f4eb1afd1e7c0312ee)..[a361cc1](https://github.com/ltdrdata/ComfyUI-Manager/commit/a361cc17f515fa629e703441a09c415112716ac3)  main       -> origin/main  (unable to update local ref)
> 
> I am sorry. I messed my repo. download this into ComfyUI-Manager directory. (!!never download into scripts dir) And execute by your python environment.
> 
> https://github.com/ltdrdata/ComfyUI-Manager/blob/main/scripts/update-fix.py
> 
> or just do..
> 
> `git update-ref refs/remotes/origin/main a361cc1 && git fetch --all && git pull` instead of `git pull`

Found the fix on Discord, just before this thank you. All good now... amazing work you do! I wish I was that clever!

**Comment by RhodianSK** [comment]
> > > Today's update fails:
> > > ComfyUI-Manager>git pull
> > > error: cannot lock ref 'refs/remotes/origin/main': is at [c0164cc](https://github.com/ltdrdata/ComfyUI-Manager/commit/c0164cc7cd47494b3a8c0597ad247c803e081a37) but expected [fd04b65](https://github.com/ltdrdata/ComfyUI-Manager/commit/fd04b65bdc936588353c82f4eb1afd1e7c0312ee)
> > > From https://github.com/ltdrdata/ComfyUI-Manager
> > > ! [fd04b65](https://github.com/ltdrdata/ComfyUI-Manager/commit/fd04b65bdc936588353c82f4eb1afd1e7c0312ee)..[a361cc1](https://github.com/ltdrdata/ComfyUI-Manager/commit/a361cc17f515fa629e703441a09c415112716ac3)  main       -> origin/main  (unable to update local ref)
> > 
> > 
> > I am sorry. I messed my repo. download this into ComfyUI-Manager directory. (!!never download into scripts dir) And execute by your python environment.
> > https://github.com/ltdrdata/ComfyUI-Manager/blob/main/scripts/update-fix.py
> > or just do..
> > `git update-ref refs/remotes/origin/main a361cc1 && git fetch --all && git pull` instead of `git pull`
> 
> Found the fix on Discord, just before this thank you. All good now... amazing work you do! I wish I was that clever!

Can you elaborate on the fix or where it can be found?

**Comment by ltdrdata** [comment]
> > > > Today's update fails:
> > > > ComfyUI-Manager>git pull
> > > > error: cannot lock ref 'refs/remotes/origin/main': is at [c0164cc](https://github.com/ltdrdata/ComfyUI-Manager/commit/c0164cc7cd47494b3a8c0597ad247c803e081a37) but expected [fd04b65](https://github.com/ltdrdata/ComfyUI-Manager/commit/fd04b65bdc936588353c82f4eb1afd1e7c0312ee)
> > > > From https://github.com/ltdrdata/ComfyUI-Manager
> > > > ! [fd04b65](https://github.com/ltdrdata/ComfyUI-Manager/commit/fd04b65bdc936588353c82f4eb1afd1e7c0312ee)..[a361cc1](https://github.com/ltdrdata/ComfyUI-Manager/commit/a361cc17f515fa629e703441a09c415112716ac3)  main       -> origin/main  (unable to update local ref)
> > > 
> > > 
> > > I am sorry. I messed my repo. download this into ComfyUI-Manager directory. (!!never download into scripts dir) And execute by your python environment.
> > > https://github.com/ltdrdata/ComfyUI-Manager/blob/main/scripts/update-fix.py
> > > or just do..
> > > `git update-ref refs/remotes/origin/main a361cc1 && git fetch --all && git pull` instead of `git pull`
> > 
> > 
> > Found the fix on Discord, just before this thank you. All good now... amazing work you do! I wish I was that clever!
> 
> Can you elaborate on the fix or where it can be found?

This issue is specific to those who updated the manager during a certain period.

Just execute do this command in ComfyUI-Manager dir.
`git update-ref refs/remotes/origin/main a361cc1 && git fetch --all && git pull` instead of `git pull`
