### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by kosh66** [Comfy-Org/ComfyUI-Manager#272]
I cannot install any of the packages via cmd as I get an error  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version.  Googling this seems to indicate  the issue is with an old version of git but I am using the up to date version.  This sems to be happening on any git repository

**Comment by ltdrdata** [comment]
Execute this and retry.

`git config --global --add http.sslVersion tlsv1.2`

**Comment by kosh66** [comment]
NO, same error afterwards.

**Comment by ltdrdata** [comment]
What is your ComfyUI environment?

You need to check the version of Git that is actually invoked from within ComfyUI, not the Git you have installed. There are cases where there might be duplicate installations, leading to the unintended invocation of a different Git version.

**Comment by kosh66** [comment]
Sorry, real noob when it comes to git. How do I find out the environment?

**Comment by ltdrdata** [comment]
> Sorry, real noob when it comes to git. How do I find out the environment?

Simply, show me the `comfyui.log`.

**Comment by kosh66** [comment]
https://pastebin.com/fhavTXJg

Can't  see any git version number and lots of errors.

**Comment by ltdrdata** [comment]
> https://pastebin.com/fhavTXJg
> 
> Can't see any git version number and lots of errors.

The reason I requested the logs is not because of Git. It's because I need information about your Python environment for troubleshooting purposes.

Your environment is `windows + venv + stabilitymatrix`.

Let's check step by step for now.

test1: just execute this

```
git clone https://github.com/ltdrdata/ComfyUI-Manager H:\Stabilitymatric\Packages\clone-test1
```

test2: 

```
H:\Stabilitymatric\Packages\ComfyUI\venv\Scripts\activate.bat

H:\Stabilitymatric\Packages\ComfyUI\venv\Scripts\python.exe H:\Stabilitymatric\Packages\ComfyUI\custom_nodes\ComfyUI-Manager\git_helper.py --clone H:\Stabilitymatric\Packages\clone-test2 https://github.com/ltdrdata/ComfyUI-Manager
```

Show me the screenshot

**Comment by kosh66** [comment]
Here you go.  
![stabilitymatric](https://github.com/ltdrdata/ComfyUI-Manager/assets/83136337/9ca11c51-e5bb-4530-ad1c-4bf7ebf01f5b)

**Comment by kosh66** [comment]
I should point out I got  stability matric and then Comfy to work via gitbash instead. However every time I run stability matric I get the start screen and have to load comfy.  Its as if my system has not seen the install fully.

**Comment by ltdrdata** [comment]
It is very fundamental issue. Your `git` doesn't work at all.

```
git config --global http.sslVersion
git version
```

**Comment by kosh66** [comment]
I am sensing that. Yet gitbash worked fine. 

output from above.

C:\WINDOWS\system32>git config --global http.sslVersion
tlsv1.2

C:\WINDOWS\system32>git version
git version 1.8.4.msysgit.0       which is odd as I have latest version installed according to windows apps.

**Comment by ltdrdata** [comment]
> I am sensing that. Yet gitbash worked fine.
> 
> output from above.
> 
> C:\WINDOWS\system32>git config --global http.sslVersion tlsv1.2
> 
> C:\WINDOWS\system32>git version git version 1.8.4.msysgit.0 which is odd as I have latest version installed according to windows apps.

The current symptoms seem to arise when the git installed in your mingw64 is running instead of the Windows Git. Adjust the path or make the necessary adjustments to ensure that the correct git is executed.

**Comment by kosh66** [comment]
All working now. Thanks.
