### ISSUE TITLE
Comfy-UI not getting updates

### ISSUE THREAD

**Issue by Freemind2115** [Comfy-Org/ComfyUI-Manager#275]
**This is the first cell-**
# #@title Environment Setup

from pathlib import Path

OPTIONS = {}

USE_GOOGLE_DRIVE = True  #@param {type:"boolean"}
UPDATE_COMFY_UI = True  #@param {type:"boolean"}
USE_COMFYUI_MANAGER = True  #@param {type:"boolean"}
INSTALL_CUSTOM_NODES_DEPENDENCIES = True  #@param {type:"boolean"}
OPTIONS['USE_GOOGLE_DRIVE'] = USE_GOOGLE_DRIVE
OPTIONS['UPDATE_COMFY_UI'] = UPDATE_COMFY_UI
OPTIONS['USE_COMFYUI_MANAGER'] = USE_COMFYUI_MANAGER
OPTIONS['INSTALL_CUSTOM_NODES_DEPENDENCIES'] = INSTALL_CUSTOM_NODES_DEPENDENCIES

current_dir = !pwd
WORKSPACE = f"{current_dir[0]}/ComfyUI"

if OPTIONS['USE_GOOGLE_DRIVE']:
    print("Mounting Google Drive...")
    %cd /

    from google.colab import drive
    drive.mount('/content/drive')

    WORKSPACE = "/content/drive/MyDrive/ComfyUI"
    %cd /content/drive/MyDrive

! [ ! -d $WORKSPACE ] && echo "-= Initial setup ComfyUI =-" && git clone https://github.com/comfyanonymous/ComfyUI
%cd $WORKSPACE

if OPTIONS['UPDATE_COMFY_UI']:
  print("-= Updating ComfyUI =-")
  !git pull

print("-= Install dependencies =-")
# Remove cu121 as it causes issues in Colab.
# !pip install xformers!=0.0.18 -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121 --extra-index-url https://download.pytorch.org/whl/cu118 --extra-index-url https://download.pytorch.org/whl/cu117
!pip3 install accelerate
!pip3 install einops 'transformers>=4.25.1' safetensors>=0.3.0 aiohttp pyyaml Pillow scipy tqdm psutil
!pip3 install 'xformers!=0.0.18' torch==1.10.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip3 install torchsde

if OPTIONS['USE_COMFYUI_MANAGER']:
  %cd custom_nodes
  ! [ ! -d ComfyUI-Manager ] && echo "-= Initial setup ComfyUI-Manager =-" && git clone https://github.com/ltdrdata/ComfyUI-Manager
  %cd ComfyUI-Manager
  !git pull

%cd $WORKSPACE

if OPTIONS['INSTALL_CUSTOM_NODES_DEPENDENCIES']:
  print("Current working directory:")
  !pwd
  print("-= Install custom nodes dependencies =-")
  ! [ -f "custom_nodes/ComfyUI-Manager/scripts/colab-dependencies.py" ] && python "custom_nodes/ComfyUI-Manager/scripts/colab-dependencies.py"
  
 **-While running this terminal my comfy-UI is not getting updated its showing the error:**
 -= Updating ComfyUI =-
Updating 656c0b5..144e658
error: Your local changes to the following files would be overwritten by merge:
	.ci/nightly/update_windows/update_comfyui_and_python_dependencies.bat
	.ci/nightly/windows_base_files/run_nvidia_gpu.bat
Please commit your changes or stash them before you merge.
Aborting
Please help me reslove this issue

**Comment by ltdrdata** [comment]
> **This is the first cell-**
> 
> # #@title Environment Setup
> from pathlib import Path
> 
> OPTIONS = {}
> 
> USE_GOOGLE_DRIVE = True #@param {type:"boolean"} UPDATE_COMFY_UI = True #@param {type:"boolean"} USE_COMFYUI_MANAGER = True #@param {type:"boolean"} INSTALL_CUSTOM_NODES_DEPENDENCIES = True #@param {type:"boolean"} OPTIONS['USE_GOOGLE_DRIVE'] = USE_GOOGLE_DRIVE OPTIONS['UPDATE_COMFY_UI'] = UPDATE_COMFY_UI OPTIONS['USE_COMFYUI_MANAGER'] = USE_COMFYUI_MANAGER OPTIONS['INSTALL_CUSTOM_NODES_DEPENDENCIES'] = INSTALL_CUSTOM_NODES_DEPENDENCIES
> 
> current_dir = !pwd WORKSPACE = f"{current_dir[0]}/ComfyUI"
> 
> if OPTIONS['USE_GOOGLE_DRIVE']: print("Mounting Google Drive...") %cd /
> 
> ```
> from google.colab import drive
> drive.mount('/content/drive')
> 
> WORKSPACE = "/content/drive/MyDrive/ComfyUI"
> %cd /content/drive/MyDrive
> ```
> 
> ! [ ! -d $WORKSPACE ] && echo "-= Initial setup ComfyUI =-" && git clone https://github.com/comfyanonymous/ComfyUI %cd $WORKSPACE
> 
> if OPTIONS['UPDATE_COMFY_UI']: print("-= Updating ComfyUI =-") !git pull
> 
> print("-= Install dependencies =-")
> 
> # Remove cu121 as it causes issues in Colab.
> # !pip install xformers!=0.0.18 -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121 --extra-index-url https://download.pytorch.org/whl/cu118 --extra-index-url https://download.pytorch.org/whl/cu117
> !pip3 install accelerate !pip3 install einops 'transformers>=4.25.1' safetensors>=0.3.0 aiohttp pyyaml Pillow scipy tqdm psutil !pip3 install 'xformers!=0.0.18' torch==1.10.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 !pip3 install torchsde
> 
> if OPTIONS['USE_COMFYUI_MANAGER']: %cd custom_nodes ! [ ! -d ComfyUI-Manager ] && echo "-= Initial setup ComfyUI-Manager =-" && git clone https://github.com/ltdrdata/ComfyUI-Manager %cd ComfyUI-Manager !git pull
> 
> %cd $WORKSPACE
> 
> if OPTIONS['INSTALL_CUSTOM_NODES_DEPENDENCIES']: print("Current working directory:") !pwd print("-= Install custom nodes dependencies =-") ! [ -f "custom_nodes/ComfyUI-Manager/scripts/colab-dependencies.py" ] && python "custom_nodes/ComfyUI-Manager/scripts/colab-dependencies.py"
> 
> **-While running this terminal my comfy-UI is not getting updated its showing the error:** -= Updating ComfyUI =- Updating 656c0b5..144e658 error: Your local changes to the following files would be overwritten by merge: .ci/nightly/update_windows/update_comfyui_and_python_dependencies.bat .ci/nightly/windows_base_files/run_nvidia_gpu.bat Please commit your changes or stash them before you merge. Aborting Please help me reslove this issue

That is an issue that needs to be addressed in the ComfyUI main repository. There is an issue where permissions automatically change after cloning due to Colab's permission policy.
Ask to remove the useless execution permission for the `.bat` file.
