### ISSUE TITLE
[Question] Python traceback or Github feature...? Could you kindly help demystify some wizardry?

### ISSUE THREAD

**Issue by ricardofeynman** [Comfy-Org/ComfyUI-Manager#276]
I've noticed a few times recently that people have raised an issue, where from the terminal readout they've posted, it wasn't clear where the error originated and in some cases appeared to be related to the manager. Yet, you've very rapidly been able to point them to the custom node dev who they should report the issue to.

Apologies if this is an incredibly dumb question, but if it's not too difficult an explanation to provide, I'd be grateful to know what methods you're using to identify that certain lines in the terminal originate from specific custom nodes when it's not clear from the terminal readout itself.

I've been communicating with several custom node devs and at times there's probably more groundwork I could be doing on my end before reaching out to help them solve bugs/issue, so it would really help to know how you're able to identify the source of certain opaque issues so quickly.

Thanks.

Edit: Python traceback or some Github feature I'm not yet aware of are my best guesses of what I need to go investigate.

**Comment by ltdrdata** [comment]
I'm not sure which specific cases you're referring to, but generally, I guide based on the custom node names or repositories from the trace log.

Such as this... `KfPGroupProd`
```
FETCH DATA from: C:\Comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'KfPGroupProd' node.
Traceback (most recent call last):
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\server.py", line 418, in get_object_info
out[x] = node_info(x)
^^^^^^^^^^^^
File "C:\Comfy\ComfyUI_windows_portable\ComfyUI\server.py", line 396, in node_info
info['input'] = obj_class.INPUT_TYPES()
^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'KfPGroupProd' has no attribute 'INPUT_TYPES'
```

Or... `/home/admin/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/`
```
File "/home/admin/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/admin/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/admin/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/admin/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 211, in combine_video
raise Exception("An error occured in the ffmpeg subprocess:\n"
```

If it's not one of these cases, it might be a previously identified issue from other reports or finding similar cases through Googling based on the error message.

**Comment by ricardofeynman** [comment]
I see, no wizardry at all. Just some extra elbow grease. Ok thanks for the insight!
