### ISSUE TITLE
Is it possible to add this repository to the manager?

### ISSUE THREAD

**Issue by BoosterCore** [Comfy-Org/ComfyUI-Manager#282]
In my experience, this repository works fine when creating seamless textures because it has the Circular VAEDecode Node：
https://github.com/FlyingFireCo/tiled_ksampler

The asymmetric tiling that currently exists in the manager does not have Circular VAEDecode Node, so there will be problems at the seams.

**Comment by ltdrdata** [comment]
Updated.
