### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by wibur0620** [Comfy-Org/ComfyUI-Manager#287]
I have provided a detailed problem description at this address
https://github.com/comfyanonymous/ComfyUI/issues/2452

So far, I have solved this problem by modifying the code of the pre-start _ script .py.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/131615326/ad45c1f5-d6b2-4c8f-810d-4b153f765e07)

**Comment by ltdrdata** [comment]
This is fixed already.
https://github.com/ltdrdata/ComfyUI-Manager/issues/286
