### ISSUE TITLE
Update fail

### ISSUE THREAD

**Issue by Robson1970** [Comfy-Org/ComfyUI-Manager#293]
The last update fail. It say's it's installed but it´s not.

The VideoHelperSuite fail  the IPadapter fail the TencentARC/motionctrl.pth  hast only 38kb  (html code) it should be ~ 4Gb

![update](https://github.com/ltdrdata/ComfyUI-Manager/assets/138815486/88e455cc-e5f4-4e30-a17e-1056301b9b67)

**Comment by ltdrdata** [comment]
My fault... The model db is updated.

**Comment by ltdrdata** [comment]
let
