### ISSUE TITLE
Colab Notebook Dependency Errors

### ISSUE THREAD

**Issue by cjdop** [Comfy-Org/ComfyUI-Manager#295]
Tried running the latest colab notebook from here. I'm getting this error while running the first block. 
![Screenshot_1](https://github.com/ltdrdata/ComfyUI-Manager/assets/155737935/96b9a98c-7102-4a81-a6cc-345492a20c6a)

**Comment by ltdrdata** [comment]
Some of the custom nodes you have installed are causing conflicts with other custom nodes by forcibly downgrading the dependency packages of transformers. You need to identify which custom node's dependency is causing this issue and disable that custom node.

**Comment by cjdop** [comment]
any pointers on how I can identify these ? straight forward way is to delete all of them and install one by one again. Its time consuming. Any other suggestions would be great.

**Comment by ltdrdata** [comment]
If you examine the logs closely, you can identify the custom nodes that are installing `clip-interrogator` and uninstalling `transformers`, then reinstalling it with a lower version.
