### ISSUE TITLE
RESTART issue

### ISSUE THREAD

**Issue by ZonSoft** [Comfy-Org/ComfyUI-Manager#297]
If there's a SPACE in path, reboot does not work as file is not found.
Not a big issue but can be avoided.

**Comment by soursilver** [comment]
Same here, it's super annoying especially if you're using a remote server.

**Comment by GenArtMad** [comment]
And me.

**Comment by OtakuFra** [comment]
I get the same error, first thought was about a stability matrix issues but no, it's comfy manager. It seem duplicating the path: "D:\Stability: can't open file 'D:\\Stability Matrix\\Data\\Packages\\ComfyUI\**\Matrix\\Data\\Packages\**\ComfyUI\\venv\\Scripts\\python.exe': [Errno 2] No such file or directory"

**Comment by zos474** [comment]
Same here (using Windows.) I had ComfyUI in the path "..\Documents\Python Scripts\ComfyUI" and kept having the Errno 2 issue above. So based on what others are saying about spaces in the path moved ComfyUI to a new folder "..\Documents\Python\ComfyUI" and now all OK.

**Comment by ltdrdata** [comment]
This is fixed.
https://github.com/ltdrdata/ComfyUI-Manager/pull/621
