### ISSUE TITLE
`customnode/getlist?mode=cache&skip_update=true` endpoint took too long (1m42s in my case)

### ISSUE THREAD

**Issue by Trung0246** [Comfy-Org/ComfyUI-Manager#299]
Basically something is wrong when attempting to call this api. The previous update does not take that long (only about like 10s ish).

Im my case when the waiting is done, the total node count returned is `427`.

I'm trying to figure out the issue by myself but not sure if there's anything else.

The actual fetch of `https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json` tooks less than a second.

Edit: looks like the culprit is this: 

https://github.com/ltdrdata/ComfyUI-Manager/blob/66f86d2b409145cb395ca2ceb8987b778e1a4f3c/__init__.py#L732

Edit 2: Looks like changing the thread count from 4 to 64 helps speeding up the check time. So I guess that's the temp fix for now.

**Comment by ltdrdata** [comment]
oh.. That is not the issue. 
It seems `skip_update=true` is ignored.. I need to take a look.

**Comment by ltdrdata** [comment]
This issue is fixed on V1.25.1
