### ISSUE TITLE
Task exception was never retrieved - AssertionError

### ISSUE THREAD

**Issue by Piscabo** [Comfy-Org/ComfyUI-Manager#318]
Facing this problem again, during 'update all'? Or is something else causing this?

Update ComfyUI
CUSTOM NODE PULL: Success
Install: pip packages
Task exception was never retrieved
future: <Task finished name='Task-33' coro=<RequestHandler.start() done, defined at C:\comfyVENV\Lib\site-packages\aiohttp\web_protocol.py:481> exception=AssertionError()>
Traceback (most recent call last):
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_protocol.py", line 524, in start
    request = self._request_factory(message, payload, self, writer, handler)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_app.py", line 485, in _make_request
    return _cls(
           ^^^^^
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_request.py", line 825, in __init__
    super().__init__(*args, **kwargs)
  File "C:\comfyVENV\Lib\site-packages\aiohttp\web_request.py", line 195, in __init__
    assert transport is not None
AssertionError
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

**Comment by ltdrdata** [comment]
For now, install only ComfyUI-Manager on a separated installation and test it.

**Comment by Piscabo** [comment]
There is nothing to update except for the manager itself. Will that help? 
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/123719842/ea34a961-eaaa-44e5-89bf-e785f7d0382a)
No error on a new install with only the manager...

**Comment by Piscabo** [comment]
Found the culprit: comfyui-art-venture
These are a problem for lots of other nodes.

**Comment by ltdrdata** [comment]
> Found the culprit: comfyui-art-venture
> These are a problem for lots of other nodes.

Does installing `comfyui-art-venture` trigger the network error you mentioned?
