### ISSUE TITLE
No close button for the windows opened by the manager.

### ISSUE THREAD

**Issue by ImprobableCrusader** [Comfy-Org/ComfyUI-Manager#32]
ComfyUI-Manager (V0.15.1)
ComfyUI Revision: 1188 [ccb6b70d] (portable)
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/127235785/016dd40f-de1c-4689-a35b-90ef56364da2)
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/127235785/321d8b13-fee5-4b82-874d-910c84e4622e)

**Comment by ltdrdata** [comment]
> ComfyUI-Manager (V0.15.1) ComfyUI Revision: 1188 [ccb6b70d] (portable) ![image](https://user-images.githubusercontent.com/127235785/256157213-016dd40f-de1c-4689-a35b-90ef56364da2.png) ![image](https://user-images.githubusercontent.com/127235785/256160409-321d8b13-fee5-4b82-874d-910c84e4622e.png)

It seems resolution issue. I will fix it.
But, you can close by 'esc' key, for now.

**Comment by ltdrdata** [comment]
This is fixed.
