### ISSUE TITLE
Where is the disable share button at in Linux?

### ISSUE THREAD

**Issue by DarkAlchy** [Comfy-Org/ComfyUI-Manager#320]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/10561690/0468b0fe-3d88-4865-8ad8-40e93faaba76)

On Windows I turned it off, but on Linux I will be darned if I could find it.  Is it done differently than on Windows?

**Comment by ltdrdata** [comment]
It's not different at all. If the way to turn it off is different, it means there is a difference in your manager version.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/3fbc9244-62b0-48e2-b4f9-2ceea9eb51c9)

You can select "Share: None"

**Comment by DarkAlchy** [comment]
Oh, so it moved from settings.  Gotcha.

Thank you.
