### ISSUE TITLE
[Feat] "View Queue" default enabled option

### ISSUE THREAD

**Issue by ghostsquad** [Comfy-Org/ComfyUI-Manager#322]
I'd like to be able to have the "View Queue" as the default view in the manager.

Desired View:

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/903488/15531069-a8c9-4bae-8c98-455098a4ef0d)

Actual Default View:

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/903488/c6edf3b5-e54a-4653-93d7-3d0fbd365998)

Possible Solution:

Add a dropdown in the settings menu for which view is the default, e.g. `View Queue`, `Collapsed`, etc.

**Comment by ltdrdata** [comment]
This is added on V1.26
