### ISSUE TITLE
PLease change the hardness of the blue in manager list !

### ISSUE THREAD

**Issue by AkoZ** [Comfy-Org/ComfyUI-Manager#324]
that's for sure a so easy task! 
here is a sum-up in image 
![comfyUI_manager_colorsNoMorehardBLUE](https://github.com/ltdrdata/ComfyUI-Manager/assets/449844/1fce2fc7-ee63-4cb6-931d-90846eeda52e)

**Comment by ltdrdata** [comment]
This is fixed on V1.26.1
