### ISSUE TITLE
Comfy manager not showing up

### ISSUE THREAD

**Issue by AlexPlom** [Comfy-Org/ComfyUI-Manager#326]
# Issue 
I am using the ComfyUI portable installation and have downloaded the files in 3 ways without any of them working:
- Zip file unzipped to custom_nodes
- git install to custom_nodes
- batch file installation
However, the manager does not show up in any way
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/28866652/598bb9fa-3d5f-4625-bcdd-be4ae0f0f8ce)
I do not get any errors for loading. 
## UI
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/28866652/19a329b1-dbdc-4a4b-a15e-dac91fbf06df)

**Comment by KuroNeko87** [comment]
Having same issue
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/3025021/637b08a3-d44d-485b-bb44-18af061d8926)

**Comment by maz323f** [comment]
Same problem here to!!!


D:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto --output-directory d:\AI\GENERATED_IMAGES\ComfyUi
** ComfyUI startup time: 2024-01-15 09:49:44.907885
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI\python_embeded\python.exe
** Log path: D:\AI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 65240 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints D:/AI/AI-MODELS/Stable-diffusion
Adding extra search path configs D:/AI/AI-MODELS/Stable-diffusion
Adding extra search path vae D:/AI/AI-MODELS/VAE
Adding extra search path loras D:/AI/AI-MODELS/Lora
Adding extra search path loras D:/AI/AI-MODELS/LyCORIS
Adding extra search path upscale_models D:/AI/AI-MODELS/ESRGAN
Adding extra search path upscale_models D:/AI/AI-MODELS/RealESRGAN
Adding extra search path upscale_models D:/AI/AI-MODELS/SwinIR
Adding extra search path upscale_models D:/AI/AI-MODELS/upscale_models
Adding extra search path embeddings D:/AI/AI-MODELS/embeddings
Adding extra search path hypernetworks D:/AI/AI-MODELS/hypernetworks
Adding extra search path controlnet D:/AI/AI-MODELS/ControlNet
### Loading: ComfyUI-Impact-Pack (V4.66.4)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
### Loading: ComfyUI-Inspire-Pack (V0.59)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V1.26.1)
### ComfyUI Revision: 1911 [f9e55d84] | Released on '2024-01-15'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[SD Prompt Reader] Node version: 1.2.1
[SD Prompt Reader] Core version: 1.3.4.post1
Total VRAM 24576 MB, total RAM 65240 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Torch version: 2.1.2+cu121
### Loading: Workspace Manager (V1.0.0)
------------------------------------------
Comfyroll Studio v1.69 :  170 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

[rgthree] Loaded 22 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 204 nodes successfully.



        "The best way to predict the future is to create it." - Peter Drucker


Import times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\save-image-extended-comfyui
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Flowty-LDSR
   0.0 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-dream-project
   0.1 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.2 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.3 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.7 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.1 seconds: D:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Setting output directory to: d:\AI\GENERATED_IMAGES\ComfyUi
Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by xthexder** [comment]
Running into the same thing. This commit adds a reference to a file that doesn't exist: https://github.com/ltdrdata/ComfyUI-Manager/commit/019897eae2773e34a2434a93e1bfc8fadbeb2992#diff-2ccd2560fbac74a605301694d9009ca73e1e25c2d5621a9f822785e634307032R19

**Comment by AlexPlom** [comment]
I opened up the logs of ComfyUI and am getting this: 
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/28866652/ae4b3b01-c17f-4ae1-a225-391959fca5c2)
I will delve a bit into it as it might be a ts issue. Will keep any updates here.

**Comment by AlexPlom** [comment]
Temporary workaround until it's fixed. 
Go into the folder of the manager
open terminal 
git reset --hard 2f3e794 
run 
This will just reset to the commit before it breaks. You will have to update your manager once the issue is resolved.

**Comment by KuroNeko87** [comment]
> Temporary workaround until it's fixed. Go into the folder of the manager open terminal git reset --hard [2f3e794](https://github.com/ltdrdata/ComfyUI-Manager/commit/2f3e7943dfb4dfc3dfa5e8fe0bc0f631363910e7) run This will just reset to the commit before it breaks. You will have to update your manager once the issue is resolved.

I can confirm this makes the manager work again

**Comment by hwamil** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/25888359/35fb0f65-d05b-4d56-9c30-59e2b80728b3)

**Comment by hwamil** [comment]
> Temporary workaround until it's fixed. Go into the folder of the manager open terminal git reset --hard [2f3e794](https://github.com/ltdrdata/ComfyUI-Manager/commit/2f3e7943dfb4dfc3dfa5e8fe0bc0f631363910e7) run This will just reset to the commit before it breaks. You will have to update your manager once the issue is resolved.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/25888359/35fb0f65-d05b-4d56-9c30-59e2b80728b3)

**Comment by AlexPlom** [comment]
You can just type `git log --oneline` and choose some hashcode such as the one I provided, then just use it with the command. This should only be temporary because I believe this will be fixed soon.

**Comment by hwamil** [comment]
> You can just type `git log --oneline` and choose some hashcode such as the one I provided, then just use it with the command. This should only be temporary because I believe this will be fixed soon.

~~Yeah I went back a few commits but still couldn't get the manager button back so I guess I'll just wait. Not in a hurry but I did panic for some reason lol.~~

See below

**Comment by AlexPlom** [comment]
Oh, wait I just saw your issue. You need to navigate to the ComfyUI manager directory. Not the ComfyUI one. Because you are currently trying to reset the ComfyUI software git version and not the managers.

**Comment by hwamil** [comment]
> Oh, wait I just saw your issue. You need to navigate to the ComfyUI manager directory. Not the ComfyUI one. Because you are currently trying to reset the ComfyUI software git version and not the managers.

oOhhh

edit: You da man

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/25888359/8276f50f-881d-49ca-9c3a-bdad7eb15542)

**Comment by maz323f** [comment]
> > Oh, wait I just saw your issue. You need to navigate to the ComfyUI manager directory. Not the ComfyUI one. Because you are currently trying to reset the ComfyUI software git version and not the managers.
> 
> oOhhh
> 
> edit: You da man
> 
> ![image](https://private-user-images.githubusercontent.com/25888359/296717355-8276f50f-881d-49ca-9c3a-bdad7eb15542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTI2MTAsIm5iZiI6MTcwNTMxMjMxMCwicGF0aCI6Ii8yNTg4ODM1OS8yOTY3MTczNTUtODI3NmY1MGYtODgxZC00OWNhLTljM2EtYmRhZDdlYjE1NTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5NTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4N2IzYWZlYzMwZGVkM2IzYTY5M2MwNmRiZjYxYjM4MmU0ZTJmZTY0NDM3MmRmMzI0NmE1ZTgwNzUxNzhjZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vJ6WKkfbJ-8OVVvjSTh2SkzYWG50inPMT-aQ9WDwRSI)

u know how to remove the share button!  i didnt have that before the fix..

**Comment by AlexPlom** [comment]
If you really want to remove the share button, you will have to edit the html, but I believe it would be a detriment to the creator, as its there to help the manager gain popularity. Editing html and such is up to you :)

**Comment by AlexPlom** [comment]
Okay, as of commit 7f10374a9f7bcd9b4e4cf39efef5a580ec1bd277, everything seems fixed. So for anyone that had the issue and used my workaround, just navigate to the manager folder and :
- Open terminal in the manager directory
- git pull
- restart comfyUI

**Comment by maz323f** [comment]
> If you really want to remove the share button, you will have to edit the html, but I believe it would be a detriment to the creator, as its there to help the manager gain popularity. Editing html and such is up to you :)

<img width="262" alt="Screenshot 2024-01-15 110056" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/56172550/b180c312-89b0-46d1-aacc-9aa62356b5b0">

Found it, there was an option in the menu! ;)

**Comment by 1-mo-1** [comment]
Used a fresh install of "ComfyUI_windows_portable_nvidia_cu118_or_cpu" today and it still doesn't work unless I git reset --hard 2f3e794

**Comment by ltdrdata** [comment]
> Used a fresh install of "ComfyUI_windows_portable_nvidia_cu118_or_cpu" today and it still doesn't work unless I git reset --hard [2f3e794](https://github.com/ltdrdata/ComfyUI-Manager/commit/2f3e7943dfb4dfc3dfa5e8fe0bc0f631363910e7)

Show me the `comfyui.log` and browser log (if you are using chrome, press F12).
