### ISSUE TITLE
Custom node IMPORT FAILED

### ISSUE THREAD

**Issue by JeffreyBull76** [Comfy-Org/ComfyUI-Manager#335]
See code below, using this in the cloud but otherwise it all works fine.

The import fails on load.
----------------------------------------
### ComfyUI Revision: 1901 [56d9496b] | Released on '2024-01-12'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /workspace/ComfyUI/custom_nodes/.ipynb_checkpoints
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-SDXL-EmptyLatentImageFETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

   0.0 seconds:FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json 
/workspace/ComfyUI/custom_nodes/cg-use-everywhereFETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_Noise
   0.0 seconds: /workspace/ComfyUI/custom_nodes/comfy-plasma
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /workspace/ComfyUI/custom_nodes/comfyui-tooling-nodes
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /workspace/ComfyUI/custom_nodes/SD-Advanced-Noise
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /workspace/ComfyUI/custom_nodes/PowerNoiseSuite
   0.1 seconds: /workspace/ComfyUI/custom_nodes/comfy-image-saver
   0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.2 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.2 seconds: /workspace/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.2 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_essentials
   0.2 seconds: /workspace/ComfyUI/custom_nodes/rgthree-comfy
   0.7 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager
   1.4 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   1.8 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_smZNodes
   2.9 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   4.3 seconds: /workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux
  10.9 seconds: /workspace/ComfyUI/custom_nodes/was-node-suite-comfyui
------------------------------

Then during operation of the workspace it runs into issues like this 

------------------------------
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/workspace/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 458, in INPUT_TYPES
    font_dir = os.path.join(system_root, 'Fonts')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
-------------------------------

I've tried reinstalling that custom node, but it says its working fine. 
Any help appreciated

**Comment by ltdrdata** [comment]
https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/issues/101

**Comment by JeffreyBull76** [comment]
Awesome thanks for looking into it!
