### ISSUE TITLE
Could it support proxy-setting?

### ISSUE THREAD

**Issue by youyegit** [Comfy-Org/ComfyUI-Manager#34]
It is a helpful tool, but some regions do not well connected to the Internet and need to set up proxy ports, could it support proxy-setting?
Thanks a lot.

**Comment by nyukers** [comment]
Hi, I would like to add my note here: Manager is ok if ComfyUI are using path to models by **extra_models_pack.yaml** ?

**Comment by ltdrdata** [comment]
> Hi, I would like to add my note here: Manager is ok if ComfyUI are using path to models by **extra_models_pack.yaml** ?

Using the extra model configuration is fine, but downloading models from comfyui-manager is only performed in the default directory. The extra model is simply a path for loading additional models and is not the default path, making it unidentifiable.

**Comment by ltdrdata** [comment]
> It is a helpful tool, but some regions do not well connected to the Internet and need to set up proxy ports, could it support proxy-setting?
> Thanks a lot.

If comfyui provides its own proxy functionality along with configuration points, it would be possible. However, if not, it would fall outside the scope of the manager's capabilities.
