### ISSUE TITLE
The manager button cannot be displayed

### ISSUE THREAD

**Issue by mikeyimer** [Comfy-Org/ComfyUI-Manager#345]
The manager button cannot be displayed, whether to use the first method or the second then restart ComfyUI. Is this related to the fact that I have already installed a comfyui and Manager  ?

**Comment by ltdrdata** [comment]
What is your terminal log and browser console log (F12 in chrome)?

**Comment by mikeyimer** [comment]
This is an error reported by the browser an  console. Is it related to the port? I copied the first installed comfyui manager directory and it can be displayed.
![merr](https://github.com/ltdrdata/ComfyUI-Manager/assets/137673481/a7c5ed72-9158-4c93-a88d-7a074380ae30)
![merr1](https://github.com/ltdrdata/ComfyUI-Manager/assets/137673481/4db55e66-0ddf-4c0b-8736-70325dad6293)

**Comment by ltdrdata** [comment]
Try clean setup without AnimateAnyone-Evolved

**Comment by mikeyimer** [comment]
I deleted ComfyUI-AnimateAnyone-Evolved under custom_nodes. The problem still exists, and it is the same in different browsers.
![merr2](https://github.com/ltdrdata/ComfyUI-Manager/assets/137673481/9c124ca6-3128-4129-b21a-629f959a59a7)
![merr3](https://github.com/ltdrdata/ComfyUI-Manager/assets/137673481/9f8938fc-785e-4beb-8a2b-cef063f3913e)

**Comment by ltdrdata** [comment]
Oh.. wow.. your ComfyUI is so much outdated. Update your ComfyUI.

**Comment by mikeyimer** [comment]
Thank you.I forgot to execute update in the new environment, my problem has been solved
