### ISSUE TITLE
Manager button not appearing

### ISSUE THREAD

**Issue by Chessologist** [Comfy-Org/ComfyUI-Manager#349]
For a few weeks, the manager button has disappeared, making Comfyui Manager inaccessible.

This issue has popped up on Reddit.
It was noted that this is due to some recent file changes.
Some people got it working by deleting certain files, but didn't state exactly which ones,
leaving me in the dark.

Please fix this, as currently no clear fix is available on the user end.

**Comment by ltdrdata** [comment]
Maybe that is this issue.
https://github.com/ltdrdata/ComfyUI-Manager/issues/345

Update ComfyUI to latest version.

**Comment by Chessologist** [comment]
> Maybe that is this issue. #345
> 
> Update ComfyUI to latest version.

I use a fresh install every time using Git Clone command on Runpod.

Git clone would install the latest version,  right?

**Comment by ltdrdata** [comment]
> > Maybe that is this issue. #345
> > Update ComfyUI to latest version.
> 
> I use a fresh install every time using Git Clone command on Runpod.
> 
> Git clone would install the latest version, right?

Yup. Then what is terminal log and browser dev console log?

**Comment by Chessologist** [comment]
I have deleted the pod now, so don't have logs.
It's been broken for a few weeks now.
I thought someone else would have reported it.
It's a shame because the extra nodes are really good.

If there was an old version I could try from more than 2 weeks ago,
 That would be helpful,  but I couldn't see any way to install an older version.

**Comment by ltdrdata** [comment]
If symptoms occur in the old version, they may temporarily appear. Issues should always be assessed based on the latest version.

I'll close this issue.

**Comment by mcandre** [comment]
I've had this issue ever since I first started using ComfyUI months ago. I never even knew it had a plugin manager, or metrics charts, or a button to "free model and node cache". None of these UI elements have ever been visible. Using the latest ComfyUI commit.

**Comment by gensyn** [comment]
> I've had this issue ever since I first started using ComfyUI months ago. I never even knew it had a plugin manager, or metrics charts, or a button to "free model and node cache". None of these UI elements have ever been visible. Using the latest ComfyUI commit.

Same. I cloned the Repo today and only knew to look for the buttons because of a manual I was following. Guess I'll have to find another way.

**Comment by gensyn** [comment]
Nevermind. My manual made it sound like the Manager should be installed by default. I since found out that I need to install https://github.com/Comfy-Org/ComfyUI-Manager. Now it works.
