### ISSUE TITLE
Enhancement - consider capturing opt in telemetry data - to help find / align missing dependencies. 

### ISSUE THREAD

**Issue by johndpope** [Comfy-Org/ComfyUI-Manager#350]
this should be easier than it is 

UPDATE

maybe it's a simple as including a button to open website - 

![Screenshot from 2024-01-21 16-08-02](https://github.com/ltdrdata/ComfyUI-Manager/assets/289994/2cfb96d5-114d-43b0-b1c0-32d4e3142ec5)

"have a look here for missing dependencies"
https://ltdrdata.github.io/

Open site
[OK] [cancel]

**Comment by ltdrdata** [comment]
The corresponding popup is displayed by the basic functionality of ComfyUI. To intervene appropriately, the core needs to provide the hook.

**Comment by johndpope** [comment]
checkout comfybox - it hides all the graph stuff.
![Screenshot from 2024-01-22 12-09-32](https://github.com/ltdrdata/ComfyUI-Manager/assets/289994/7c21ca08-2619-4213-9849-642fc69888b5)
