### ISSUE TITLE
Try Fix

### ISSUE THREAD

**Issue by alexbofa** [Comfy-Org/ComfyUI-Manager#354]
Hello
If I click `Try Fix`, the [`requirements.txt`](https://github.com/storyicon/comfyui_segment_anything/blob/main/requirements.txt) are not updated from `0.6.12` to `0.9.12`. For example [issue](https://github.com/storyicon/comfyui_segment_anything/issues/44) **segment_anything**

```cmd
## Execute install/(de)activation script for 'D:\Portable-ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything'
 Requirement already satisfied: segment_anything in d:\portable-comfyui\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (1.0)
 Requirement already satisfied: timm in d:\portable-comfyui\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (0.6.12)
 ```
But if I use `Install PIP packages`, put only `timm` then the fix works fine.
```cmd
 Using cached timm-0.9.12-py3-none-any.whl (2.2 MB)
 Installing collected packages: timm
   Attempting uninstall: timm
     Found existing installation: timm 0.6.12
     Uninstalling timm-0.6.12:
       Successfully uninstalled timm-0.6.12
 Successfully installed timm-0.9.12
 ```

**Comment by ltdrdata** [comment]
`try fix` takes a somewhat conservative approach. If the version is not specified, it does not enforce upgrades unnecessarily.

Forcing an update to the latest version can cause significant issues with other packages. If a specific minimum version is required, it is preferable for the repository maintainer to specify it.

The 'Install PIP packages' is provided for the purpose of forced installation to address such limitations. This installation is more aggressive as users are clearly aware of what packages they are installing.

**Comment by alexbofa** [comment]
Thanks, you're right. I corrected it and sent the [PR](https://github.com/storyicon/comfyui_segment_anything/pull/45/files) to the author.
