### ISSUE TITLE
Manager Button is missiong

### ISSUE THREAD

**Issue by Wagnor53** [Comfy-Org/ComfyUI-Manager#356]
I downloaded ComfyUI, but the manager won't appear. How do I get the manager? Please help me (I would be grateful if you could explain it in a way that's easy for beginners to understand). I checked and i am pretty sure that i got the manager. its just not visible. its also up to date. is there a command or something else to activate it? i trying to find the problem with chat gpt but it cant find it. i also downloaded git, i dont know if i need that...

**Comment by ltdrdata** [comment]
1. How did you installed it?
2. What is displayed on startup terminal log?
3. What is displayed on browser dev console log?

**Comment by Wagnor53** [comment]
> 1. How did you installed it? i downloaded comfi ui by clicking the link on https://github.com/comfyanonymous/ComfyUI/releases
The manager by doing "Installation[method1] (General installation method: ComfyUI-Manager only)
To install ComfyUI-Manager in addition to an existing installation of ComfyUI, you can follow the following steps:

1. cd custom_nodes
2. git clone https://github.com/ltdrdata/ComfyUI-Manager.git
3. Restart ComfyUI"

> 2. What is displayed on startup terminal log?
C:\Users\Patrick\Documents\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 3072 MB, total RAM 16318 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 3GB : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Starting server

To see the GUI go to: http://127.0.0.1:8188


> 3. What is displayed on browser dev console log?

onMessage extension
ial.js:450 Clean the cache of the scraper (new onComplete event)
contentScript.js:2  Uncaught (in promise) Error: Content DefaultConnector: Error when handling response of "IsInPageViewTrackingList": The message port closed before a response was received.
    at o (contentScript.js:2:1453786)
content.js:73  Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
    at g (content.js:73:33710)

i hope thats what you need.

**Comment by Wagnor53** [comment]
if you need different informations please let me know.

**Comment by ltdrdata** [comment]
TBH, your logs are confusing because they consist of elements that do not belong to ComfyUI. It appears that the browser extension is causing the issue.
Disable the browser extensions for now and test it.

**Comment by Wagnor53** [comment]
i deactivated all extensions. the manager bitton still doesnt appear. 

"Failed to load resource: the server responded with a status of 404 (Not Found)" thats now the dev console log (at least i belive im sending you the right log)

**Comment by Wagnor53** [comment]
here are some problems shown to me. i dont know maybe those informations are useful. 
![error](https://github.com/ltdrdata/ComfyUI-Manager/assets/133214282/d8fd8f14-d919-4116-9731-f269a7a08d19)
![error 2](https://github.com/ltdrdata/ComfyUI-Manager/assets/133214282/89fcfd57-8465-459d-b615-b5ea9c5ca682)
![error 3](https://github.com/ltdrdata/ComfyUI-Manager/assets/133214282/b9a0755f-4008-45c7-af03-20b7017f34cd)
![error 4](https://github.com/ltdrdata/ComfyUI-Manager/assets/133214282/bf58d789-dea2-45ed-be8f-731d820679f7)

**Comment by ltdrdata** [comment]
I need this console log of browser.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/9f4b790e-30b7-4ac9-8e5a-30d6d1cab8b0)

**Comment by Wagnor53** [comment]
![log](https://github.com/ltdrdata/ComfyUI-Manager/assets/133214282/62053934-bba6-4074-ab39-f0fcccb31a3b)

"Keine" means "No"

**Comment by ltdrdata** [comment]
Show me this, too.
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/791e2e54-dba4-491d-8de9-cebf9ba0f6fa)

**Comment by Wagnor53** [comment]
![lotegraph](https://github.com/ltdrdata/ComfyUI-Manager/assets/133214282/cc4e6d17-2b74-4e7b-b82d-2d8db5e51baf)

**Comment by ltdrdata** [comment]
> ![lotegraph](https://private-user-images.githubusercontent.com/133214282/300193989-cc4e6d17-2b74-4e7b-b82d-2d8db5e51baf.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTcxNzUsIm5iZiI6MTcwNjM5Njg3NSwicGF0aCI6Ii8xMzMyMTQyODIvMzAwMTkzOTg5LWNjNGU2ZDE3LTJiNzQtNGU3Yi1iODJkLTJkOGRiNWU1MWJhZi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyN1QyMzA3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGQyMzNlOTQwNzY0YmVkNThlZGU1OWY0YjcwNjYxMGJkM2QyZDZkNDNmNDI4YjFjYmQ3YjEzNjA0YTdlOTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.19A2R5k7l4l9WKNV4O2yl_Z48oJnvR2aaag4gPWPUHg)

You need to check startup log. It seems ComfyUI-Manager is not loaded.

**Comment by Wagnor53** [comment]
yeah its not in the comfy ui folders. but im pretty sure its on the pc. but i dont know how and in which folder to put it

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#installation

**Comment by Wagnor53** [comment]
i did that... but i will try again and let you know if it worked.

**Comment by Wagnor53** [comment]
okay with the second method it worked. thank you for your help
