### ISSUE TITLE
Install script for ComfyUI portable not working : bad git executable

### ISSUE THREAD

**Issue by ghost** [Comfy-Org/ComfyUI-Manager#36]
D:\ComfyUI_windows_portable>install-manager-for-portable-version.bat

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s -m pip install gitpython
Requirement already satisfied: gitpython in d:\comfyui_windows_portable\python_embeded\lib\site-packages (3.1.32)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from gitpython) (4.0.10)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from gitdb<5,>=4.0.1->gitpython) (5.0.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

D:\ComfyUI_windows_portable>.\python_embeded\python.exe -c "import git; git.Repo.clone_from('https://github.com/ltdrdata/ComfyUI-Manager', './ComfyUI/custom_nodes/ComfyUI-Manager')"
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\cmd.py", line 392, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\__init__.py", line 91, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by ltdrdata** [comment]
try update "git bash" program to latest version.

**Comment by ghost** [comment]
I have only ComfyUI portable, even running the update script doesn't solve the problem.
Can't find git.exe in the directory.
Maybe Manager can't be installed with ComfyUI portable alone or script must be updated to use pip only.

**Comment by ltdrdata** [comment]
> I have only ComfyUI portable, even running the update script doesn't solve the problem. Can't find git.exe in the directory. Maybe Manager can't be installed with ComfyUI portable alone or script must be updated to use pip only.

Retry after install this.

https://git-scm.com/download/win

I am not sure. But I hope it will solve this problem.

**Comment by ghost** [comment]
It doesn't change anything, I have tried portable git and normal install.

I found other people with same problem here, he doesn't put the .bat in main directory like me but the error is same.
https://www.reddit.com/r/comfyui/comments/15d2ngw/comfy_ui_manager_instalation/

**Comment by ltdrdata** [comment]
Try this solutions

https://github.com/gitpython-developers/GitPython/issues/816

**Comment by ghost** [comment]
I have modified my path in Windows to add D:\Git\bin the git installer forgot to do that.

Now it works thanks.
