### ISSUE TITLE
After reinstalling ComfyUI Manager, I encountered an issue that is causing me anxiety. I hope you can help me check this problem.

### ISSUE THREAD

**Issue by wibur0620** [Comfy-Org/ComfyUI-Manager#362]
I'm experiencing slow network speeds when using ComfyUI, especially during operations that involve downloading data. I have two accelerators, and I used to rely on one with fast internet speed for updating ComfyUI and plugins. However, after reinstalling the manager plugin, I encounter the following issues:

Clicking on "Install Custom Nodes" in the manager takes an exceptionally long time to enter the corresponding operation interface.

When installing plugins, the terminal shows no response for an extended period, and it takes a very long time before the installation process begins.

After installing plugins, restarting ComfyUI results in a lengthy delay if there are dependencies to be installed. The terminal takes a long time before it starts downloading dependencies, even though the download speed is fast. After downloading, there's another prolonged wait before continuing with other package downloads.

When using plugins that require downloading models, there is a significant delay before the download starts. The download speed is fast, but after completion, there is another long wait before proceeding with additional model downloads.

When downloading models in the manager, there is a considerable wait before the download begins. The download speed is fast, but after completion, there is another extended wait before proceeding with other model downloads.

In summary, when using ComfyUI and encountering situations that require network downloads, I experience prolonged waits before operations start. However, the actual download speeds are fast. The primary delay occurs after completing one download, where there is a substantial wait before starting the next one. This situation is causing significant inconvenience. My other accelerator works fine, but it has slower internet speed. I rarely use it for downloading the data required by ComfyUI. I'm unsure whether the issue is with my accelerator or the ComfyUI Manager, as everything was normal before I reinstalled ComfyUI.

**Comment by ltdrdata** [comment]
Please upload the `comfyui??.log` file what the installation messages are logged.

**Comment by wibur0620** [comment]
[comfyui.log](https://github.com/ltdrdata/ComfyUI-Manager/files/14072139/comfyui.log)
[comfyui.prev.log](https://github.com/ltdrdata/ComfyUI-Manager/files/14072140/comfyui.prev.log)
[comfyui.prev2.log](https://github.com/ltdrdata/ComfyUI-Manager/files/14072141/comfyui.prev2.log)

**Comment by wibur0620** [comment]
I also uploaded the log file, just now I installed the plugin through git in the custom_nodes directory, and the speed is very fast, but using ComfyUI-Manager to install the plugin is very slow
Windows PowerShell
版权所有（C） Microsoft Corporation。保留所有权利。

安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS D:\AI\ComfyUI\custom_nodes> git clone https://github.com/11cafe/comfyui-workspace-manager.git
Cloning into 'comfyui-workspace-manager'...
remote: Enumerating objects: 4496, done.
remote: Counting objects: 100% (1994/1994), done.
remote: Compressing objects: 100% (669/669), done.
remote: Total 4496 (delta 1420), reused 1762 (delta 1245), pack-reused 2502
Receiving objects: 100% (4496/4496), 14.44 MiB | 4.21 MiB/s, done.
Resolving deltas: 100% (3135/3135), done.
PS D:\AI\ComfyUI\custom_nodes> ^A

**Comment by wibur0620** [comment]
Comparison of loading speeds using two different VPNs

https://github.com/ltdrdata/ComfyUI-Manager/assets/131615326/90446645-04cb-4617-9432-df41bb491e97

**Comment by ltdrdata** [comment]
edit `config.ini` file 
set `bypass_ssl = True`

**Comment by wibur0620** [comment]
Thank you very much. It's back to normal now.

**Comment by wibur0620** [comment]
Please, I turned off ssl authentication. Is it safe?

**Comment by ltdrdata** [comment]
> Please, I turned off ssl authentication. Is it safe?

Of course, it's not secure. However, in your network environment, using a VPN or nothing else is an option.

**Comment by wibur0620** [comment]
> > Please, I turned off ssl authentication. Is it safe?拜托，我关闭了SSL身份验证。安全吗？
> 
> Of course, it's not secure. However, in your network environment, using a VPN or nothing else is an option.当然，这并不安全。但是，在您的网络环境中，可以选择使用 VPN 或其他任何选项。

Is it possible for me to download and install the plugin and then turn the ssl on, so that I can avoid the danger?

**Comment by ltdrdata** [comment]
> > > Please, I turned off ssl authentication. Is it safe?拜托，我关闭了SSL身份验证。安全吗？
> > 
> > 
> > Of course, it's not secure. However, in your network environment, using a VPN or nothing else is an option.当然，这并不安全。但是，在您的网络环境中，可以选择使用 VPN 或其他任何选项。
> 
> Is it possible for me to download and install the plugin and then turn the ssl on, so that I can avoid the danger?

If you bypass SSL, the assurance of downloading from a legitimate source disappears during the installation process.
Generally, it may not pose significant issues, but it does indeed introduce vulnerability from a security perspective.

Certain ISPs are known to be causing these issues.
