### ISSUE TITLE
Your ComfyUI is too OUTDATED!!!

### ISSUE THREAD

**Issue by kakachiex2** [Comfy-Org/ComfyUI-Manager#367]
Comfyui manager ask to update comfyui but wen I update it it keep saying the same outdated looks like a bug or there is a problem updating comfyui I have the windows portable version.
![Screenshot 2024-01-27 023225](https://github.com/ltdrdata/ComfyUI-Manager/assets/1762112/3e1bad21-40d9-4f1d-96d0-9a8c276d440f)

**Comment by kakachiex2** [comment]
I have the latest comfyui manager 2.4.2

**Comment by ltdrdata** [comment]
> I have the latest comfyui manager 2.4.2

The meaning is that it's ComfyUI that's outdated, not ComfyUI-Manager.

**Comment by kakachiex2** [comment]
It's what I'm saying, wen I update comfyui and reloaded keep the same message and I clarify that I have the latest manager version.

**Comment by ltdrdata** [comment]
> It's what I'm saying, wen I update comfyui and reloaded keep the same message and I clarify that I have the latest manager version.

Show me the startup terminal log.

**Comment by kakachiex2** [comment]
I'll fix it by downloading a new portable version and replace everything know is updated

**Comment by Ovi1kanobe** [comment]
yea I just cloned the latest version of comfyui and the manager at the same time and I see this as well. Im on Debian 12

**Comment by ltdrdata** [comment]
> yea I just cloned the latest version of comfyui and the manager at the same time and I see this as well. Im on Debian 12

Check this.
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/1c1efb61-83ad-4939-b9f7-62030e97aa09)

**Comment by Ovi1kanobe** [comment]
> > yea I just cloned the latest version of comfyui and the manager at the same time and I see this as well. Im on Debian 12
> 
> Check this. ![image](https://private-user-images.githubusercontent.com/128333288/302146352-1c1efb61-83ad-4939-b9f7-62030e97aa09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTUyODUsIm5iZiI6MTcwNzA5NDk4NSwicGF0aCI6Ii8xMjgzMzMyODgvMzAyMTQ2MzUyLTFjMWVmYjYxLTgzYWQtNDkzOS1iOWY3LTYyMDMwZTk3YWEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwMTAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTg3MWZhZmNiNjU4ZjI5Y2ZlNjZjZDAzNjNhMWJjZGFiNDBhMmQ1YmU2MzgyNTIzMDU2OGYyYTFkNjE2MGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GgKq7bJUYg_4QYfHMY0gXSzWqdHSmeusoB1FOFYXk5A)

<img width="232" alt="Screenshot 2024-02-04 at 8 03 43 PM" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/94891720/51ff64d7-7786-4ea3-8001-c64ab3a3200f">

**Comment by ltdrdata** [comment]
> > > yea I just cloned the latest version of comfyui and the manager at the same time and I see this as well. Im on Debian 12
> > 
> > 
> > Check this. ![image](https://private-user-images.githubusercontent.com/128333288/302146352-1c1efb61-83ad-4939-b9f7-62030e97aa09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTUyODUsIm5iZiI6MTcwNzA5NDk4NSwicGF0aCI6Ii8xMjgzMzMyODgvMzAyMTQ2MzUyLTFjMWVmYjYxLTgzYWQtNDkzOS1iOWY3LTYyMDMwZTk3YWEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwMTAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTg3MWZhZmNiNjU4ZjI5Y2ZlNjZjZDAzNjNhMWJjZGFiNDBhMmQ1YmU2MzgyNTIzMDU2OGYyYTFkNjE2MGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GgKq7bJUYg_4QYfHMY0gXSzWqdHSmeusoB1FOFYXk5A)
> 
> <img alt="Screenshot 2024-02-04 at 8 03 43 PM" width="232" src="https://private-user-images.githubusercontent.com/94891720/302148126-51ff64d7-7786-4ea3-8001-c64ab3a3200f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTU1MTcsIm5iZiI6MTcwNzA5NTIxNywicGF0aCI6Ii85NDg5MTcyMC8zMDIxNDgxMjYtNTFmZjY0ZDctNzc4Ni00ZWEzLTgwMDEtYzY0YWIzYTMyMDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxMDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYzE5NDZmNTk1ZTg3Mzc3YTVhNTdkMjc0NjIwMjEzYzQwNWRjOTY0ODAwMDc2ZWJjZTA5ZjJjMDNkZWRmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GohUOTz9Ec3UyB_5DjxoInSgojR2imYP56BVL1ygXvs">

goto ComfyUI dir and `git log`
What is displayed?

**Comment by Ovi1kanobe** [comment]
> > > > yea I just cloned the latest version of comfyui and the manager at the same time and I see this as well. Im on Debian 12
> > > 
> > > 
> > > Check this. ![image](https://private-user-images.githubusercontent.com/128333288/302146352-1c1efb61-83ad-4939-b9f7-62030e97aa09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTUyODUsIm5iZiI6MTcwNzA5NDk4NSwicGF0aCI6Ii8xMjgzMzMyODgvMzAyMTQ2MzUyLTFjMWVmYjYxLTgzYWQtNDkzOS1iOWY3LTYyMDMwZTk3YWEwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwMTAzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTg3MWZhZmNiNjU4ZjI5Y2ZlNjZjZDAzNjNhMWJjZGFiNDBhMmQ1YmU2MzgyNTIzMDU2OGYyYTFkNjE2MGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GgKq7bJUYg_4QYfHMY0gXSzWqdHSmeusoB1FOFYXk5A)
> > 
> > 
> > <img alt="Screenshot 2024-02-04 at 8 03 43 PM" width="232" src="https://private-user-images.githubusercontent.com/94891720/302148126-51ff64d7-7786-4ea3-8001-c64ab3a3200f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTU1MTcsIm5iZiI6MTcwNzA5NTIxNywicGF0aCI6Ii85NDg5MTcyMC8zMDIxNDgxMjYtNTFmZjY0ZDctNzc4Ni00ZWEzLTgwMDEtYzY0YWIzYTMyMDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxMDY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYzE5NDZmNTk1ZTg3Mzc3YTVhNTdkMjc0NjIwMjEzYzQwNWRjOTY0ODAwMDc2ZWJjZTA5ZjJjMDNkZWRmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GohUOTz9Ec3UyB_5DjxoInSgojR2imYP56BVL1ygXvs">
> 
> goto ComfyUI dir and `git log` What is displayed?

Sorry the image you sent is broken for me but these are the 6 most recent commits when I type git log:
"commit d0e2354c287d306b0559f1e570c79f2fdac064f4 (HEAD -> master, origin/master, origin/HEAD)
Merge: 951a206 f2bae74
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Fri Feb 2 04:38:18 2024 -0500

    Merge branch 'LatentSeed_update' of https://github.com/FizzleDorf/ComfyUI

commit f2bae7463e506048600093e6f0adf90cf89edc86
Author: FizzleDorf <1fizzledorf@gmail.com>
Date:   Fri Feb 2 18:31:35 2024 +0900

    changed default of LatentBatchSeedBehavior to fixed

commit 951a2064a34e3e2ab468942663fa59df6a212af3
Author: Chaoses-Ib <Chaos-es@outlook.com>
Date:   Fri Feb 2 13:27:03 2024 +0800

    Fix frontend webp prompt handling

commit 4c54c2ec0f642ce505980373aae71ed09cb1702c
Merge: 6ab4205 53a22e1
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Thu Feb 1 17:01:21 2024 -0500

    Merge branch 'increment-wrap' of https://github.com/pksebben/ComfyUI

commit 53a22e1ab9df4385aae07d65d7cd2fc157e989c9
Author: pksebben <benmorsillo@gmail.com>
Date:   Wed Jan 31 16:14:50 2024 -0800

    add increment-wrap as option to ValueControlWidget when isCombo, which loops back to 0 when at end of list

commit 6ab42054229cfea7fbab63e6b51ae295c2e3fc49
Author: Lt.Dr.Data <lt.dr.data@gmail.com>
Date:   Wed Jan 31 18:28:36 2024 +0900

    feat: better pen support for mask editor
    - alt-drag: erase
    - shift-drag(up/down): zoom in/out
"

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager and restart and
Show me the full log file `comfyui.log`

**Comment by rachelcenter** [comment]
i had the latest version of everything on an external hard drive, and the external hard drive was acting up so I moved the whole comfyUI to an SSD external hard drive. so I launched comfyui from the SSD for the first and the comfy atmostphere is telling me im missing nodes that I know I have, and manager is saying "Your ComfyUI is too OUTDATED!!!" how is that possible when I had the latest update from this week and all I did was move the comfyui directory to another hard drive?! (same computer) m2 mac silicone.

**Comment by ltdrdata** [comment]
> i had the latest version of everything on an external hard drive, and the external hard drive was acting up so I moved the whole comfyUI to an SSD external hard drive. so I launched comfyui from the SSD for the first and the comfy atmostphere is telling me im missing nodes that I know I have, and manager is saying "Your ComfyUI is too OUTDATED!!!" how is that possible when I had the latest update from this week and all I did was move the comfyui directory to another hard drive?! (same computer) m2 mac silicone.

goto `ComfyUI` dir in terminal. 
And then execute `git log`. What is displayed?

And show me the full log file `comfyui.log`.

**Comment by rachelcenter** [comment]
How do i get to the comfyui directory in terminal? I'm fairly new to comfy and the world of coding. this is what i attempted to do for "git log" but im confident that I dont know how to pull a git log and probably did it incorrectly:

Last login: Tue Aug 20 07:53:04 on ttys000
(base) rachel@RachelsacStudio ~ % cd /Volumes/RachelComfyUI/ComfyUI 
(base) rachel@RachelsacStudio ComfyUI % git log
fatal: not a git repository (or any parent up to mount point /Volumes)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
(base) rachel@RachelsacStudio ComfyUI %

**Comment by ltdrdata** [comment]
> How do i get to the comfyui directory in terminal? I'm fairly new to comfy and the world of coding. this is what i attempted to do for "git log" but im confident that I dont know how to pull a git log and probably did it incorrectly:
> 
> Last login: Tue Aug 20 07:53:04 on ttys000 (base) rachel@RachelsacStudio ~ % cd /Volumes/RachelComfyUI/ComfyUI (base) rachel@RachelsacStudio ComfyUI % git log fatal: not a git repository (or any parent up to mount point /Volumes) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). (base) rachel@RachelsacStudio ComfyUI %

As I've already answered elsewhere, your ComfyUI dir is incomplete. The git-related files have been lost. You need to reinstall it.
