### ISSUE TITLE
Double clicking a node is connecting the node to stuff close to it

### ISSUE THREAD

**Issue by Immac** [Comfy-Org/ComfyUI-Manager#370]
Issue here is that the node already had connections and also that I'm clicking one of the widgets so it's not my intention to change the connections. I'd say double click should only work on the title as well.

**Comment by ltdrdata** [comment]
It was a bug for connections to be made with a double click when connections already existed. It has already been patched, so please update ComfyUI-Manager.

**Comment by ltdrdata** [comment]
This is fixed.
I discovered an issue where litegraph also triggers a dbl click when adjusting widget values.

Now this action will be triggered on title area only.
