### ISSUE TITLE
Conflicted nodes aren't actually conflicting

### ISSUE THREAD

**Issue by shiimizu** [Comfy-Org/ComfyUI-Manager#371]
As seen [here](https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus/blob/b2adae3aeae0c3463f42cad226e28ca74d890c89/photomaker.py#L222-L240)

There aren't any nodes conflicting but ComfyUI Manager will state there's a conflict.

Also, the tooltip (badge nickname) will be incorrect. It should reflect the node that's actually being used, in this case, the node in ComfyUI.

**Comment by ltdrdata** [comment]
DB is updated.
