### ISSUE TITLE
Manager group The length of editable nodes is too short, I need to zoom the page to see more nodes

### ISSUE THREAD

**Issue by whmc76** [Comfy-Org/ComfyUI-Manager#373]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/129386342/0a47a2ce-2b60-42be-b916-93e169bc9375)

Manager group The length of editable nodes is too short, I need to zoom the page to see more nodes

**Comment by ltdrdata** [comment]
That is part of ComfyUI core not ComfyUI-Manager.
