### ISSUE TITLE
Comfyui manager error on Blender addon

### ISSUE THREAD

**Issue by kakachiex2** [Comfy-Org/ComfyUI-Manager#375]
I have comfyUI as an addon for Blender and I recently having a problem loading it and I report the bug to the creator and say that comfyui manager is causing the problem can you take a look.
- here is the github page :: https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node
- The error report :: https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/issues/60
- Here is the console log ::
Read prefs: "C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
register_class(...):
Warning: 'Editor_PT_LayoutPanel' doesn't have upper case alpha-numeric prefix
Registered MACHIN3tools 1.6.0.DeusEx with 16 tools, 9 pie menus
Registered MESHmachine 0.14.1 with 2 plug libraries
• plug library: Examples
• plug library: MyPlugs
Exception in module register(): C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\fluent_power_trip_init_.py
Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
mod.register()
File "C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\fluent_power_trip_init_.py", line 71, in register
auto_load.register()
File "C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\fluent_power_trip\auto_load.py", line 33, in register
bpy.utils.register_class(cls)
ValueError: validating class:: 'REGISTER' not found in ('SEARCH_ON_KEY_PRESS')
register
Registered DECALmachine 2.9.0 with 4 decal libraries, 1 trim sheet libraries and 2 atlases. PIL 10.1.0 Image Module: C:\Users\rafae\AppData\Roaming\Python\Python310\site-packages\PIL\imaging.cp310-win_amd64.pyd
Decals, Trimsheets and Atlases are located in C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\DECALmachine\assets
• decal library: Aircraft
• decal library: Example Panels
• decal library: Examples
• decal library: MyDecals
• trim sheet library: Example Sheet
• atlas: Aircraft Atlas
• atlas: Example Atlas
[SDN-INF]: UnregNode Time: 0.00s
[SDN-INF]: Launch Time: 0.00s
[SDN-WAR]: Parsing Node Start
[SDN-WAR]: Parsing Node Finished!
[SDN-INF]: ParseNode Time: 0.02s
[SDN-INF]: RegNode Time: 0.06s
BlenderAI_Node Launch Time: 0.2658s
BlenderAI_Node Register cost 0.0726s
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\gp_create_materials.py'
Exception in module register(): C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\fluent_power_trip_init.py
Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
mod.register()
File "C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\fluent_power_trip_init_.py", line 71, in register
auto_load.register()
File "C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\fluent_power_trip\auto_load.py", line 33, in register
bpy.utils.register_class(cls)
ValueError: validating class:: 'REGISTER' not found in ('SEARCH_ON_KEY_PRESS')
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\gp_create_materials.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\Users\rafae\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\gp_create_materials.py'
[SDN-INF]: UnregNode Time: 0.00s
[SDN-DBG]: Model Path: K:\ComfyUI\ComfyUI
[SDN-WAR]: Server Launching
[SDN-INF]: ** ComfyUI startup time: 2024-01-26 23:14:21.820633
[SDN-INF]: ** Platform: Windows
[SDN-INF]: ** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct 2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
[SDN-INF]: ** Python executable: K:\ComfyUI\python_embeded\python.exe
[SDN-INF]: ** Log path: K:\ComfyUI\ComfyUI\comfyui.log
[SDN-INF]: [ComfyUI-Manager] Windows event loop policy mode enabled
[SDN-INF]: Prestartup times for custom nodes:
[SDN-INF]: 0.0 seconds: K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Marigold
[SDN-INF]: 0.0 seconds: K:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
[SDN-INF]: 0.1 seconds: K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
[SDN-INF]: Total VRAM 6144 MB, total RAM 65488 MB
[SDN-INF]: Set vram state to: NORMAL_VRAM
[SDN-INF]: Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
[SDN-INF]: VAE dtype: torch.float32
[SDN-INF]: Using pytorch cross attention
[SDN-INF]: Adding extra search path checkpoints K:\Automatic111\stable-diffusion-webui\models/Stable-diffusion
[SDN-INF]: Adding extra search path configs K:\Automatic111\stable-diffusion-webui\models/Stable-diffusion
[SDN-INF]: Adding extra search path vae K:\Automatic111\stable-diffusion-webui\models/VAE
[SDN-INF]: Adding extra search path loras K:\Automatic111\stable-diffusion-webui\models/Lora
[SDN-INF]: Adding extra search path loras K:\Automatic111\stable-diffusion-webui\models/LyCORIS
[SDN-INF]: Adding extra search path upscale_models K:\Automatic111\stable-diffusion-webui\models/ESRGAN
[SDN-INF]: Adding extra search path upscale_models K:\Automatic111\stable-diffusion-webui\models/RealESRGAN
[SDN-INF]: Adding extra search path upscale_models K:\Automatic111\stable-diffusion-webui\models/SwinIR
[SDN-INF]: Adding extra search path embeddings K:\Automatic111\stable-diffusion-webui\embeddings
[SDN-INF]: Adding extra search path hypernetworks K:\Automatic111\stable-diffusion-webui\models/hypernetworks
[SDN-INF]: Adding extra search path controlnet K:\Automatic111\stable-diffusion-webui\models/ControlNet
[SDN-INF]: [Allor]: 0 nodes were overridden.
[SDN-INF]: [Allor]: 12 modules were enabled.
[SDN-INF]: [Allor]: 98 nodes were loaded.
[SDN-INF]: [Crystools INFO] Crystools version: 1.10.1
[SDN-INF]: [Crystools INFO] CPU: AMD Ryzen 7 2700X Eight-Core Processor - Arch: AMD64 - OS: Windows 10
[SDN-INF]: [Crystools INFO] GPU/s:
[SDN-INF]: [Crystools INFO] 0) NVIDIA GeForce RTX 2060
[SDN-INF]: [Crystools INFO] NVIDIA Driver: 546.33
[SDN-INF]: Loading ComfyUI Discopixel nodes!
[SDN-INF]: Comfy-Easy-Use (v1.0.3): Loaded
[SDN-INF]: torch version---------------------- 2.1.2+cu121
[SDN-INF]: K:\ComfyUI\python_embeded\Lib\site-packages\cupy_environment.py:216: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
[SDN-INF]: warnings.warn(
[SDN-INF]: Traceback (most recent call last):
[SDN-INF]: File "K:\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
[SDN-INF]: module_spec.loader.exec_module(module)
[SDN-INF]: File "", line 940, in exec_module
[SDN-INF]: File "", line 241, in call_with_frames_removed
[SDN-INF]: File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-fastblend_init.py", line 25, in
[SDN-INF]: from .interpolatekeyframe import InterpolateKeyFrame
[SDN-INF]: File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-fastblend\interpolatekeyframe.py", line 1, in
[SDN-INF]: from custom_nodes.AInseven.FastBlend.api import interpolate_video
[SDN-INF]: ModuleNotFoundError: No module named 'custom_nodes.AInseven'
[SDN-INF]: Cannot import K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-fastblend module for custom nodes: No module named 'custom_nodes.AInseven'
[SDN-INF]: ### Loading: ComfyUI-Impact-Pack (V4.66.4)
[SDN-INF]: ### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[SDN-INF]: ### Loading: ComfyUI-Inspire-Pack (V0.60)[Impact Pack] Wildcards loading done.
[SDN-INF]: None
[SDN-INF]: ### Loading: ComfyUI-Manager (V2.2.5)
[SDN-INF]: ## [WARN] ComfyUI-Manager: Your ComfyUI version (1840) is too old. Please update to the latest version. ##
[SDN-INF]: ### ComfyUI Revision: 1840 [9a7619b7] | Released on '2023-12-19'
[SDN-INF]: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[SDN-INF]: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[SDN-INF]: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[SDN-INF]: FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[SDN-INF]: [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[SDN-INF]: [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[SDN-INF]: [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[SDN-INF]: [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[SDN-INF]: --------------
[SDN-INF]: ### Mixlab Nodes: Loaded
[SDN-INF]: LaMaInpainting.available True
[SDN-INF]: ClipInterrogator.available True
[SDN-INF]: ## text_generator_model not found: K:\ComfyUI\ComfyUI\models\prompt_generator/text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
[SDN-INF]: ## zh_en_model not found: K:\ComfyUI\ComfyUI\models\prompt_generator/opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
[SDN-INF]: PromptGenerate.available True
[SDN-INF]: ChinesePrompt.available True
[SDN-INF]: RembgNode_.available True
[SDN-INF]: --------------
[SDN-INF]: Total VRAM 6144 MB, total RAM 65488 MB
[SDN-INF]: Set vram state to: NORMAL_VRAM
[SDN-INF]: Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
[SDN-INF]: VAE dtype: torch.float32
[SDN-INF]: Torch version: 2.1.2+cu121
[SDN-INF]: ### Loading: Save img prompt
[SDN-INF]: 3D OpenPose Editor: Loaded
[SDN-INF]: ------------------------------------------
[SDN-INF]: Comfyroll Studio v1.74 : 175 Nodes Loaded
[SDN-INF]: ------------------------------------------
[SDN-INF]: ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
[SDN-INF]: ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
[SDN-INF]: ------------------------------------------
[SDN-INF]: [comfyui_controlnet_aux] | INFO -> Using ckpts path: K:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[SDN-INF]: [comfyui_controlnet_aux] | INFO -> Using symlinks: False
[SDN-INF]: DWPose: Onnxruntime with acceleration providers detected
[SDN-INF]: ### [START] ComfyUI AlekPet Nodes ###
[SDN-INF]: Node -> ArgosTranslateNode [Loading]
[SDN-INF]: Node -> ExtrasNode [Loading]
[SDN-INF]: Node -> PainterNode [Loading]
[SDN-INF]: Node -> PoseNode [Loading]
[SDN-INF]: Node -> TranslateNode [Loading]
[SDN-INF]: ### [END] ComfyUI AlekPet Nodes ###
[SDN-INF]: FizzleDorf Custom Nodes: Loaded
[SDN-INF]: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
[SDN-INF]: [tinyterraNodes] Loaded
[SDN-INF]: [comfy_mtb] | INFO -> loaded 58 nodes successfuly
[SDN-INF]: [comfy_mtb] | INFO -> Some nodes (7) could not be loaded. This can be ignored, but go to http://127.0.0.1:8189/mtb if you want more information.
[SDN-INF]: Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!...
[SDN-INF]: Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.
[SDN-INF]: Total VRAM 6144 MB, total RAM 65488 MB
[SDN-INF]: Set vram state to: NORMAL_VRAM
[SDN-INF]: Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
[SDN-INF]: VAE dtype: torch.float32
[SDN-INF]: K:\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
[SDN-INF]: K:\ComfyUI\ComfyUI\web\extensions\failfast-comfyui-extensions
[SDN-INF]: Patching UNetModel.forward
[SDN-INF]: UNetModel.forward has been successfully patched.
[SDN-INF]: 2024-01-26 23:14:43.293 | WARNING | Jovimetrix:init:456 - module failed K:\ComfyUI\ComfyUI\custom_nodes\Jovimetrix\nodes\create.py
[SDN-INF]: 2024-01-26 23:14:43.293 | WARNING | Jovimetrix:init:457 - No module named 'moderngl'
[SDN-INF]: Traceback (most recent call last):
[SDN-INF]: File "K:\ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
[SDN-INF]: module_spec.loader.exec_module(module)
[SDN-INF]: File "", line 940, in exec_module
[SDN-INF]: File "", line 241, in call_with_frames_removed
[SDN-INF]: File "K:\ComfyUI\ComfyUI\custom_nodes\PowerNoiseSuite_init.py", line 5, in
[SDN-INF]: print(f"\033[1;32m[Power Noise Suite]: \U0001f99a\U0001f99a\U0001f99a \033[93m\033[3m{random.choice(peacock_rambling)}\033[0m \U0001f99a\U0001f99a\U0001f99a")
[SDN-INF]: File "K:\ComfyUI\python_embeded\Lib\site-packages\colorama\ansitowin32.py", line 47, in write
[SDN-INF]: self.__convertor.write(text)
[SDN-INF]: File "K:\ComfyUI\python_embeded\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
[SDN-INF]: self.write_and_convert(text)
[SDN-INF]: File "K:\ComfyUI\python_embeded\Lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
[SDN-INF]: self.write_plain_text(text, cursor, start)
[SDN-INF]: File "K:\ComfyUI\python_embeded\Lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
[SDN-INF]: self.wrapped.write(text[start:end])
[SDN-INF]: File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 193, in write
[SDN-INF]: self.sync_write(message)
[SDN-INF]: File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 207, in sync_write
[SDN-INF]: original_stdout.write(message)
[SDN-INF]: File "encodings\cp1252.py", line 19, in encode
[SDN-INF]: UnicodeEncodeError: 'charmap' codec can't encode characters in position 21-23: character maps to
[SDN-INF]: During handling of the above exception, another exception occurred:
[SDN-INF]: Traceback (most recent call last):
[SDN-INF]: File "K:\ComfyUI\ComfyUI\main-bak.py", line 189, in
[SDN-INF]: init_custom_nodes()
[SDN-INF]: File "K:\ComfyUI\ComfyUI\nodes.py", line 1878, in init_custom_nodes
[SDN-INF]: load_custom_nodes()
[SDN-INF]: File "K:\ComfyUI\ComfyUI\nodes.py", line 1836, in load_custom_nodes
[SDN-INF]: success = load_custom_node(module_path, base_node_names)
[SDN-INF]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[SDN-INF]: File "K:\ComfyUI\ComfyUI\nodes.py", line 1818, in load_custom_node
[SDN-INF]: print(traceback.format_exc())
[SDN-INF]: File "K:\ComfyUI\python_embeded\Lib\site-packages\colorama\ansitowin32.py", line 47, in write
[SDN-INF]: self._convertor.write(text)
[SDN-INF]: File "K:\ComfyUI\python_embeded\Lib\site-packages\colorama\ansitowin32.py", line 177, in write
[SDN-INF]: self.write_and_convert(text)
[SDN-INF]: File "K:\ComfyUI\python_embeded\Lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
[SDN-INF]: self.write_plain_text(text, cursor, len(text))
[SDN-INF]: File "K:\ComfyUI\python_embeded\Lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
[SDN-INF]: self.wrapped.write(text[start:end])
[SDN-INF]: File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 193, in write
[SDN-INF]: self.sync_write(message)
[SDN-INF]: File "K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 207, in sync_write
[SDN-INF]: original_stdout.write(message)
[SDN-INF]: File "encodings\cp1252.py", line 19, in encode
[SDN-INF]: UnicodeEncodeError: 'charmap' codec can't encode characters in position 439-441: character maps to
[SDN-DBG]: STDOUT Listen Thread Exit
[SDN-ERR]: Server Launch Failed
C:\Users\rafae\AppData\Roaming\Python\Python310\site-packages_distutils_hack_init.py:33: UserWarning: Setuptools is replacing distutils.
warnings.warn("Setuptools is replacing distutils.")
[SDN-INF]: Launch Time: 23.47s
[SDN-WAR]: Parsing Node Start
[SDN-WAR]: Parsing Node Finished!
[SDN-INF]: ParseNode Time: 0.01s
[SDN-INF]: RegNode Time: 0.05s

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager and try again.
