### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by fresno808** [Comfy-Org/ComfyUI-Manager#385]
Ive reinstalled Comfyui Portable and Comfyui Manager cleanly but I still keep getting this error when I try to install missing modules.

 ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\Temp Account\Documents\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python311.zip\collections\__init__.pyc)

Manager seems to be able to download models fine, its the nodes where I seem to be getting an error.

**Comment by ltdrdata** [comment]
Your install path is too long. Windows cannot handle such long path.
Install to `C:\ComfyUI_windows_portable` directly
