### ISSUE TITLE
Offline update

### ISSUE THREAD

**Issue by Praecordi** [Comfy-Org/ComfyUI-Manager#387]
With a lot of custom node extensions, start up becomes terribly long. This is not an issue, but if one wants to start up and update ComfyUI and all extensions, this exactly doubles start up time. Is there a quick python script or gui that would allow me to update everything before starting ComfyUI?

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager/blob/main/notebooks/comfyui_colab_with_manager.ipynb

This may help you.
```
if OPTIONS['INSTALL_CUSTOM_NODES_DEPENDENCIES']:
  !pwd
  !echo -= Install custom nodes dependencies =-
  ![ -f "custom_nodes/ComfyUI-Manager/scripts/colab-dependencies.py" ] && python "custom_nodes/ComfyUI-Manager/scripts/colab-dependencies.py"
```
