### ISSUE TITLE
Is it possible to add this custom node ?

### ISSUE THREAD

**Issue by MaraScott** [Comfy-Org/ComfyUI-Manager#388]
https://github.com/davask/ComfyUI-MarasIT-Nodes

**Comment by ltdrdata** [comment]
Already added.

**Comment by MaraScott** [comment]
Fantastic ! thx.

by any chance, do you know how to display an image instead of a text for each nodes ?

I'd like to reproduce ComfyUI style

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/482210/0d8f6b79-48f2-427c-8bbe-200ea8cb0758)

with my logo 

![marasit-logo](https://github.com/ltdrdata/ComfyUI-Manager/assets/482210/6ce88a65-5644-494c-a741-3a740c255363)

I prefer image to text

**Comment by MaraScott** [comment]
in same time, may I suggest the following modification

custom-node-list.json

```
       {
            "author": "davask",
            "title": "MarasIT Nodes",
            "reference": "https://github.com/davask/ComfyUI-MarasIT-Nodes",
            "files": [
                "https://github.com/davask/ComfyUI-MarasIT-Nodes"
            ],
            "install_type": "git-clone",
            "description": "This is a revised version of the Bus node from the [a/Was Node Suite](https://github.com/WASasquatch/was-node-suite-comfyui) to integrate more input/output."
        },
```

in same time,

may I suggest the following modification

custom-node-list.json

```
    "https://github.com/davask/ComfyUI-MarasIT-Nodes": [
        [
            "MarasitBusNode"
        ],
        {
            "title_aux": "MarasIT Nodes" # or the logo
        }
    ],
```

**Comment by ltdrdata** [comment]
> Fantastic ! thx.
> 
> by any chance, do you know how to display an image instead of a text for each nodes ?
> 
> I'd like to reproduce ComfyUI style
> 
> ![image](https://private-user-images.githubusercontent.com/482210/302066999-0d8f6b79-48f2-427c-8bbe-200ea8cb0758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTEwNzAsIm5iZiI6MTcwNzAxMDc3MCwicGF0aCI6Ii80ODIyMTAvMzAyMDY2OTk5LTBkOGY2Yjc5LTQ4ZjItNDI3Yy04YmJlLTIwMGVhOGNiMDc1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMTM5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDFmZmFhNGRjMjY1ZjExYmIxMjExMDlkODU5ZDRkOTljYzdlZjJmMjY2Nzg4MTM0YWVhY2FlN2E5YTU5NGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yGzjzDYJwtKwOUSpXETsjecxs-7gFXOQM8Jo9wzdCIM)
> 
> with my logo
> 
> ![marasit-logo](https://private-user-images.githubusercontent.com/482210/302067105-6ce88a65-5644-494c-a741-3a740c255363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTEwNzAsIm5iZiI6MTcwNzAxMDc3MCwicGF0aCI6Ii80ODIyMTAvMzAyMDY3MTA1LTZjZTg4YTY1LTU2NDQtNDk0Yy1hNzQxLTNhNzQwYzI1NTM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwMTM5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODE4MzliMzU5MjBjZGI4NjUwMzdiMGNmNjgwM2MzMjJhOTc1MmExZjQ0NTJiMjhhOWZmMWE1ZDQxNTY0MTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nisd86H7vywt05pRrz9FjS7Q_s2jPx8CmVF6rq_kJM0)
> 
> I prefer image to text

That is just a emoji

**Comment by MaraScott** [comment]
is it possible to use this then "🐰 MarasIT" - I can do a pull request if you prefer

```
       {
            "author": "davask",
            "title": "🐰 MarasIT Nodes",
            "reference": "https://github.com/davask/ComfyUI-MarasIT-Nodes",
            "files": [
                "https://github.com/davask/ComfyUI-MarasIT-Nodes"
            ],
            "install_type": "git-clone",
            "description": "This is a revised version of the Bus node from the [a/Was Node Suite](https://github.com/WASasquatch/was-node-suite-comfyui) to integrate more input/output."
        },
```

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/482210/3b17c6d0-cfc6-4fbf-ac66-772f7d36aa7d)


```     
    "https://github.com/davask/ComfyUI-MarasIT-Nodes": [
        [
            "MarasitBusNode"
        ],
        {
            "title_aux": "🐰 Mara" # or the logo
        }
    ],
```

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/482210/9067d983-48cd-4081-afbb-b09bb2588ea0)

**Comment by ltdrdata** [comment]
> is it possible to use this then "🐰 MarasIT" - I can do a pull request if you prefer
> 
> ```
>        {
>             "author": "davask",
>             "title": "🐰 MarasIT Nodes",
>             "reference": "https://github.com/davask/ComfyUI-MarasIT-Nodes",
>             "files": [
>                 "https://github.com/davask/ComfyUI-MarasIT-Nodes"
>             ],
>             "install_type": "git-clone",
>             "description": "This is a revised version of the Bus node from the [a/Was Node Suite](https://github.com/WASasquatch/was-node-suite-comfyui) to integrate more input/output."
>         },
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/482210/302105339-3b17c6d0-cfc6-4fbf-ac66-772f7d36aa7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNTQ3MjQsIm5iZiI6MTcwNzA1NDQyNCwicGF0aCI6Ii80ODIyMTAvMzAyMTA1MzM5LTNiMTdjNmQwLWNmYzYtNGZiZi1hYzY2LTc3MmY3ZDM2YWE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxMzQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzVlMDcxZjU1NmNlNzQ1MzNhM2YzMTUzMWVkNzdlMjBmOTA0NzI2YjY3NDM3NDIyODIyZTAyZTdjYWRiMjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pABAvJ_l0oTN8K0DIQJMGu7iBXjeJfZgPnQrxYLHF84)
> 
> ```
>     "https://github.com/davask/ComfyUI-MarasIT-Nodes": [
>         [
>             "MarasitBusNode"
>         ],
>         {
>             "title_aux": "🐰 Mara" # or the logo
>         }
>     ],
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/482210/302105425-9067d983-48cd-4081-afbb-b09bb2588ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNTQ3MjQsIm5iZiI6MTcwNzA1NDQyNCwicGF0aCI6Ii80ODIyMTAvMzAyMTA1NDI1LTkwNjdkOTgzLTQ4Y2QtNDA4MS1hZmJiLWIwOWJiMjU4OGVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxMzQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTRjODVlOTgxMDU1NzhkODQ2N2M5MjA0N2YxZGY2ODI3ZDc0ODVhYzFhNmQ0ZTQxZTE1MWRhZDAwYzgzODgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b4T-BcPx_IFd3n7lWiiXS3frvCNRbaR40tLb1JlH2Uc)

I can update `custom-node-list.json` 
But, `extension-node-map.json` file is not maintained by manually.
You need do declare for that in your code, explicitly.

https://github.com/ltdrdata/ComfyUI-Manager#custom-node-support-guide

**Comment by MaraScott** [comment]
Thx @ltdrdata , I feel like a dumbass, I did not even thought to look at the read me, sorry.
A friend told me to let you know I would like to publish my node and that's it.
Now I read it.

Talking of documentation, do you know a good source to develop custom_node for py and js? so far I'm digging others code but I think I need to find the documentation now cause I have trouble to replicate code by watching others.

anyway, thx.
