### ISSUE TITLE
how to enable aiohttp access log

### ISSUE THREAD

**Issue by xingzhao-tt** [Comfy-Org/ComfyUI-Manager#394]
Hi,

I want to enable AIOHTTP access log just add logging.basicConfig(level=logging.DEBUG)， but the access log does not be showed in comfyui.log? what should I do to enable aiohttp access log?

Really appreciate your help!

Thansk
Felix

**Comment by xingzhao-tt** [comment]
BTW, I also remove "access_log=None" in  web.AppRunner(self.app, access_log=None)

**Comment by ltdrdata** [comment]
The ComfyUI-Manager simply intercepts and redirects all output. It is not the role of the ComfyUI-Manager to determine what logs will actually be produced.
