### ISSUE TITLE
comfyui_seg_viton error

### ISSUE THREAD

**Issue by PLILI729** [Comfy-Org/ComfyUI-Manager#395]
please help me on this errors, try many times still fails, thank you!
![WX20240205-001040@2x](https://github.com/ltdrdata/ComfyUI-Manager/assets/133625274/7f22a885-ddb4-4ff8-ae46-890fce1ef5f8)
![WX20240205-003027@2x](https://github.com/ltdrdata/ComfyUI-Manager/assets/133625274/2072d18b-0544-4c23-a3b0-181ec2e22a81)

**Comment by ltdrdata** [comment]
Ask to here:
https://github.com/StartHua/ComfyUI_Seg_VITON/issues

you need to post your full terminal log.
