### ISSUE TITLE
Install failed: undefined / SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by moonpebbles** [Comfy-Org/ComfyUI-Manager#396]
Hi there! I'm a newbie to ComfyUI and was hoping to get some help with this issue. When I want to install a model, I get this error message. I've attached a screenshot of my ComfyUI-Manager config file too. Any advice on how to resolve this issue would be greatly appreciated! 🙌

ComfyUI-Manager config file:
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/159068475/40bed754-4680-4c65-85ad-1916ce9820ed)

I pressed "Install" on the OpenPose (v2) model:
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/159068475/b86fb76e-1dd3-46c4-a51c-d6d4b084bfd7)

ComfyUI Manager error message (I get the same error message no matter what model I want to install):
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/159068475/8e978e2b-f59f-4329-a8cb-b7a9250854fa)

run_nvidia_gpu.bat window screenshot:
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/159068475/73304974-3b1a-478b-ae53-1dc015785288)

**[ERROR] <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>**

**Comment by ltdrdata** [comment]
It seems you are experiencing network issue.
Try download https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0/resolve/main/OpenPoseXL2.safetensors this directly.

**Comment by moonpebbles** [comment]
> It seems you are experiencing network issue. Try download https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0/resolve/main/OpenPoseXL2.safetensors this directly.

Will do, thank you!

**Comment by danlavie** [comment]
Hey @moonpebbles,
I've just had that error with "SyntaxError: Unexpected end of JSON input", and that's how I solved it. Hope it would help anyone.
You have to make sure that Python 3.11 is the active version without having other versions like 3.12 installed.
In my case, I hade version 3.12 installed and removed, but some dependencies where left and had to be removed.
Once Python 3.11.* was the active one, everything worked as it should.
Here are the steps I took to remove Python 3.12, and after that I just reinstalled the latest Python 3.11.

To uninstall Python 3.12 and use 3.11 instead on macOS, you can follow these steps:

1. **Uninstall Python 3.12**:
   - Go to the "Finder."
   - Click "Applications" in the menu on the left.
   - Find the Python folder with the version number you want to uninstall, right-click it, and select "Move to Trash".
   - Even if you don't have that folder, contintue to the next step.

2. **Remove Residual Files**:
   - Open the Terminal app.
   - Enter the following commands to remove additional Python directories:
     ```bash
     sudo rm -rf /Library/Frameworks/Python.framework
     sudo rm -rf /usr/local/bin/python
     ```
   - These steps will help remove any residual files associated with Python 3.12.

3. **Install Python 3.11**:
   - After uninstalling Python 3.12, you can install Python 3.11 by downloading the installer from the Python website and following the installation instructions.

It's important to note that Apple provides a pre-installed version of Python, which should not be deleted as it is used by some macOS utilities and uninstalling it can cause system errors.

Once the latest Python 3.11 was reinstalled and active, I was able to install any model using the ComfyUI Manager.

Also, check the comments area and that YouTube tutorial: https://www.youtube.com/watch?v=m9jg1fdOiVY

I hope that would help anyone reading this.
Cheers.

**Comment by moonpebbles** [comment]
@danlavie Thank you very much!🙌 I'll certainly give it a try. So far, as a final option, I've been downloading everything directly.

**Comment by 0m0Ding** [comment]
I have a trouble, I had download about 'segment anything'model-GroundingDinoModel:groundingDINO SwinT OGC-CFG file,and I put it in my file, but I try run Comfyui about 'segment anything',it show me about :
downloading https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/GroundingDINO_SwinB.cfg.py to D:\AI\SD\ComfyUI-aki-v1.3\models\grounding-dino\GroundingDINO_SwinB.cfg.py
!!! Exception during processing!!! <urlopen error [WinError 10060] 
I have the file,but it let me to download the file,and prompt error.
so,how I do, please ask me.

**Comment by ltdrdata** [comment]
> I have a trouble, I had download about 'segment anything'model-GroundingDinoModel:groundingDINO SwinT OGC-CFG file,and I put it in my file, but I try run Comfyui about 'segment anything',it show me about : downloading https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/GroundingDINO_SwinB.cfg.py to D:\AI\SD\ComfyUI-aki-v1.3\models\grounding-dino\GroundingDINO_SwinB.cfg.py !!! Exception during processing!!! <urlopen error [WinError 10060] I have the file,but it let me to download the file,and prompt error. so,how I do, please ask me.

You need to ask this issue to related custom node repo.

**Comment by 0m0Ding** [comment]
这是来自GC邮箱的自动回复邮件。
 
您好，我会尽快给您回复。
