### ISSUE TITLE
Refusing to merge unrelated histories?

### ISSUE THREAD

**Issue by Torcelllo** [Comfy-Org/ComfyUI-Manager#40]
This message after git pull on Windows 10

![ComfyUI Manager Fault](https://github.com/ltdrdata/ComfyUI-Manager/assets/114806454/0f4bfcfe-1b60-44b6-8e57-9d1dccd02ee9)

**Comment by ltdrdata** [comment]
I accidentally messed up the repo. Instead of using `git pull`, try using the following command: `git update-ref refs/remotes/origin/main a361cc1 && git fetch --all && git pull`.

If that doesn't work, reinstalling ComfyUI-Manager might be easier.

**Comment by sabahiya** [comment]
After inputing the command above

C:\Users\Lloyd\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes>git update-ref refs/remotes/origin/main a361cc1 && git fetch --all && git pull
Already up to date.

It still wouldn't work.

C:\Users\Lloyd\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes>git pull https://github.com/ltdrdata/ComfyUI-Manager.git
From https://github.com/ltdrdata/ComfyUI-Manager
 * branch            HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories

Don't really get what you mean by reinstalling the manager as it isn't installed in the first place. Please help.

**Comment by ltdrdata** [comment]
> After inputing the command above
> 
> C:\Users\Lloyd\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes>git update-ref refs/remotes/origin/main [a361cc1](https://github.com/ltdrdata/ComfyUI-Manager/commit/a361cc17f515fa629e703441a09c415112716ac3) && git fetch --all && git pull Already up to date.
> 
> It still wouldn't work.
> 
> C:\Users\Lloyd\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes>git pull https://github.com/ltdrdata/ComfyUI-Manager.git From https://github.com/ltdrdata/ComfyUI-Manager
> 
> * branch            HEAD       -> FETCH_HEAD
>   fatal: refusing to merge unrelated histories
> 
> Don't really get what you mean by reinstalling the manager as it isn't installed in the first place. Please 

Just remove `ComfyUI-Manager` dir and `git clone https://github.com/ltdrdata/ComfyUI-Manager` instead of `git pull` in custom_nodes idr.
