### ISSUE TITLE
open link(2-3) from list Gallery - glitch ?

### ISSUE THREAD

**Issue by pvp-by** [Comfy-Org/ComfyUI-Manager#400]
when you open for the first time in a session, everything is fine, opens in a new tab.
But if you don't close it, then reopening ANY link (not just the same service) will open it in an existing tab over your actions in that tab.

If you want to open 2 services or more at once - it is not convenient. I checked in 2 browsers chrome and edge. the behavior is the same.

Any idea if this is a problem or if I understand something wrong ?

PS add test more :
3 link successively open in one tabs, 4 link open(after 3) in new tab - wtf.

**Comment by ltdrdata** [comment]
What link are you referring?

**Comment by pvp-by** [comment]
I apologize, I forgot to attach the picture.
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/10133995/577289e1-1772-4ca1-b762-6047660ad03a)

**Comment by ltdrdata** [comment]
This is fixed.
