### ISSUE TITLE
[Feature] When saving, open up standard file save view

### ISSUE THREAD

**Issue by ghostsquad** [Comfy-Org/ComfyUI-Manager#404]
When I load a workflow, and I want to save an update to it, I have to go find the old workflow filename, so I can properly save it. If ComfyUI Manager just opened up the standard browser file save dialog, I'd be able to do this much quicker.

**Comment by ltdrdata** [comment]
I recommend this extension.

https://github.com/11cafe/comfyui-workspace-manager

**Comment by ghostsquad** [comment]
Thanks. I'll take a look.

**Comment by ghostsquad** [comment]
This does a lot more than what I want. I really just want a standard browser dialog for saving a file.
