### ISSUE TITLE
install failed: ComfyUI Inspire Pack

### ISSUE THREAD

**Issue by unrealovelas** [Comfy-Org/ComfyUI-Manager#408]
I get this mistake when i try to download CUSTOM nodes, with models i don't get it
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/143370620/c03e0566-ce10-4e33-8ec8-4fd71fc1c7b0)
tracebook
[comfyui.log](https://github.com/ltdrdata/ComfyUI-Manager/files/14271851/comfyui.log)
Also tried to update with ComfyUI\update bat.s

**Comment by ltdrdata** [comment]
Some of your python package is damaged. 
You need to reinstall `sympy` package.

Using system Python is not recommended.
If you are using a Windows environment, it is recommended to use a portable version or configure venv.
