### ISSUE TITLE
Would it be possible to have a command line option to disable the 'auto detect missing node' feature?

### ISSUE THREAD

**Issue by stephantual** [Comfy-Org/ComfyUI-Manager#409]
The "Autodetect" missing node feature is very nice but sadly can crash even on a mad rig (4090, i9 14th, pci5, 92gb ram) when opening something like the popular "AP workflow".

When i open it the browser (edge) just hangs and crash due to the sheer amount of missing nodes. There's no way to click 'okay' on the warning box because it's throwing faster than a human can click.

So being able to load a workflow even though nothing works would be nice, as it would allow for carefully selecting the nodes we really want to install and delete the rest, then restart and install. 

PS: I know it's an edge case. But I thought maybe it could be of interest to others, too. Thank you!

**Comment by ltdrdata** [comment]
The missing node detection feature is a part of ComfyUI itself. 

ComfyUI-Manager provides only the functionality to identify which custom nodes pack the missing node belongs to. Additionally, this feature only operates when the "install missing custom nodes" menu is clicked.
