### ISSUE TITLE
Outdated data

### ISSUE THREAD

**Issue by pixelass** [Comfy-Org/ComfyUI-Manager#41]
I am not sure how data is loaded in the manager. One of my extensions is fidable but it references an old file. 

What do I have to do to keep the version in the database updated?

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/1148334/a6c5b6c3-75b6-4c10-851b-979807d9b508)

**Comment by pixelass** [comment]
```
Install custom node 'failfa-st/comfyui-extensions'
Install(copy) error: https://github.com/failfa-st/comfyui-extensions/raw/main/failfastSettings.js / HTTP Error 404: Not Found
```

it references a lingle file but should be the entire repo as subfolder of web/extensions

https://github.com/failfa-st/failfast-comfyui-extensions

**Comment by ltdrdata** [comment]
It seems the structure has changed. This is a different form from the existing custom node, so I'll need to take a closer look.

**Comment by pixelass** [comment]
Is there anything, that I can do to help?

**Comment by ltdrdata** [comment]
> Is there anything, that I can do to help?

The easiest way is to add a dummy `__init__.py` and provide `install.py` to copy extensions and scripts to their respective locations. This way, when installing through the `ComfyUI-Manager`, your extension can be managed smoothly.

Additionally, if you provide scripts `disable.py` and `enable.py` to add and remove your script, the disable/enable functionality can be appropriately implemented.

If this is the case, then unlike before, proper update management through the `ComfyUI-Manager` becomes possible.

**Comment by pixelass** [comment]
ok, I will look into it.

**Comment by ltdrdata** [comment]
> ok, I will look into it.

Once the task is completed, you can manually add the entry to the `custom-node-list.json` in the form of a `git-clone`. Then, you can check the `local DB` and perform installation tests.

**Comment by pixelass** [comment]
OK, updated and tested. I used this config

```json
{
    "author": "failfa.st",
    "title": "failfast-comfyui-extensions",
    "reference": "https://github.com/failfa-st/failfast-comfyui-extensions",
    "files": [
        "https://github.com/failfa-st/failfast-comfyui-extensions"
    ],
    "install_type": "git-clone",
    "description": "node color customization, link rendering options, group freezing, node pinning, automated arrangement of nodes and more..."
}
```

**Comment by ltdrdata** [comment]
Now it works perfectly. Thank you.
