### ISSUE TITLE
Reactor using CPU only

### ISSUE THREAD

**Issue by Matticusnicholas** [Comfy-Org/ComfyUI-Manager#415]
Here is everything up to the point where its running the reactor node on a faceswap with a movie.  My cpu usage is at 60% (14700) and my gpu is basically at nothing.  Any idea what might be going on here?

C:\COMFYUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-02-16 11:57:19.222606
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\COMFYUI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\COMFYUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 65363 MB
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\src\diffusers\src\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade\src\diffusers\src\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
### Loading: ComfyUI-Inspire-Pack (V0.64)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 1973 [7f89cb48] | Released on '2024-02-14'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[SD Prompt Reader] Node version: 1.3.0
[SD Prompt Reader] Core version: 1.3.4.post1
Total VRAM 16376 MB, total RAM 65363 MB
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
VAE dtype: torch.bfloat16
[ReActor] - STATUS - Running v0.4.1-b9 in ComfyUI
Torch version: 2.2.0+cu121
Traceback (most recent call last):
  File "C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\COMFYUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-sampler-lcm-alternative-main\\__init__.py'

Cannot import C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative-main module for custom nodes: [Errno 2] No such file or directory: 'C:\\COMFYUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-sampler-lcm-alternative-main\\__init__.py'
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
hus' utility nodes: loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Total VRAM 16376 MB, total RAM 65363 MB
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
VAE dtype: torch.bfloat16
Patching UNetModel.forward
UNetModel.forward has been successfully patched.

[rgthree] Loaded 33 epic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 212 nodes successfully.

        "Failure is the opportunity to begin again more intelligently." - Henry Ford

Import times for custom nodes:
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_utility.py
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-svd_txt2vid
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SD-Advanced-Noise
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds (IMPORT FAILED): C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative-main
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_hus_utils
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\FreeU_Advanced
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffusersStableCascade
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.1 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved
   0.3 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools
   0.4 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.6 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.2 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.9 seconds: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error. No styles.csv found. Put your styles.csv in C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_hus_utils\styles.csv. Then press "Refresh".

got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
[ReActor] 12:01:35 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 12:01:35 - STATUS - Swap in 0
[ReActor] 12:01:35 - STATUS - Analyzing Source Image...
download_path: C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l
Downloading C:\COMFYUI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
100%|███████████████████████████████████████████████████████████████████████| 281857/281857 [00:04<00:00, 66353.55KB/s]
[ReActor] 12:02:32 - STATUS - Analyzing Target Image...
[ReActor] 12:02:33 - STATUS - Trying to halve 'det_size' parameter
[ReActor] 12:02:35 - STATUS - Swapping...

**Comment by ltdrdata** [comment]
This issue cannot be handled in ComfyUI-Manager.

Ask to here:
https://github.com/Gourieff/comfyui-reactor-node
