### ISSUE TITLE
Custom node DB is currently being updated

### ISSUE THREAD

**Issue by slebed** [Comfy-Org/ComfyUI-Manager#42]
I've installed and reinstalled ComfyUI-Manager several times but I'm stuck at the message 

"The custom node DB is currently being updated, and updates to custom nodes are being checked for.
NOTE: Update only checks for extensions that have been fetched."

I'm not able to get to the list of nodes or models and just have to esc out.  ComfyUI is up to date and fetch updates says the same.

Any idea how this can be fixed?

**Comment by lucille-bellepleure** [comment]
+1

**Comment by ltdrdata** [comment]
> I've installed and reinstalled ComfyUI-Manager several times but I'm stuck at the message
> 
> "The custom node DB is currently being updated, and updates to custom nodes are being checked for. NOTE: Update only checks for extensions that have been fetched."
> 
> I'm not able to get to the list of nodes or models and just have to esc out. ComfyUI is up to date and fetch updates says the same.
> 
> Any idea how this can be fixed?

Do you use colab?

**Comment by lucille-bellepleure** [comment]
using it on my own gpu server, ubuntu + nvidia A5000s

**Comment by ltdrdata** [comment]
> using it on my own gpu server, ubuntu + nvidia A5000s

Can you check console on devtools?

**Comment by slebed** [comment]
> > I've installed and reinstalled ComfyUI-Manager several times but I'm stuck at the message
> > "The custom node DB is currently being updated, and updates to custom nodes are being checked for. NOTE: Update only checks for extensions that have been fetched."
> > I'm not able to get to the list of nodes or models and just have to esc out. ComfyUI is up to date and fetch updates says the same.
> > Any idea how this can be fixed?
> 
> Do you use colab?

No I don't.  Just running it locally in my windows box.

**Comment by YANGlattez** [comment]
the same problem

**Comment by ltdrdata** [comment]
>  the same problem

What messages are displayed on terminal?

**Comment by bukeshui0926** [comment]
Same problem
![屏幕截图 2023-08-06 233213](https://github.com/ltdrdata/ComfyUI-Manager/assets/116459766/f2093575-3e8f-48ab-bd47-1b3f1bd72739)

**Comment by THRLBSSTRD** [comment]
same here

**Comment by ltdrdata** [comment]
> Same problem ![屏幕截图 2023-08-06 233213](https://user-images.githubusercontent.com/116459766/258651912-f2093575-3e8f-48ab-bd47-1b3f1bd72739.png)



> same here

@bukeshui0926, @THRLBSSTRD 

I'd updated. I am not sure this will work. But try this.

**Comment by DreamLoveBetty** [comment]
I have also encountered the same problem. Please try going to the ComfyUI Manager directory and executing the command 'git update ref refs/remote/origin/main a361cc1&&git fetch -- all&&git pull'. I have used the developer provided method to solve this problem and hope it can help you

**Comment by chioulin** [comment]
<img width="855" alt="微信截图_20230903221558" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/42197599/8d67dfd3-98ec-476c-9db6-8cec01ab4f5d">

KeyError: 'custom_nodes'

**Comment by ltdrdata** [comment]
The ComfyUI-Manager you are using is an outdated version. Please change the channel from 'recent' to 'default' and update ComfyUI-Manager.

**Comment by ltdrdata** [comment]
> <img alt="微信截图_20230903221558" width="855" src="https://user-images.githubusercontent.com/42197599/265270045-8d67dfd3-98ec-476c-9db6-8cec01ab4f5d.png">
> KeyError: 'custom_nodes'

The ComfyUI-Manager you are using is an outdated version. Please change the channel from 'recent' to 'default' and update ComfyUI-Manager.
