### ISSUE TITLE
I deleted the extra_model_paths.yaml for Comfy UI how do I get it back

### ISSUE THREAD

**Issue by Sheck20** [Comfy-Org/ComfyUI-Manager#425]
While trying to get Comfy UI to run I deleted the extra_model_paths.yaml folder and kept the example.

How do I get it back? 

FWI that didn't work either

**Comment by ltdrdata** [comment]
I don't understand what it means to delete a folder. Anyway, if you didn't put it in the recycle bin, there is no way to recover what has been deleted
