### ISSUE TITLE
Workflow gallery comes up at random, does this mean my art was shared?

### ISSUE THREAD

**Issue by 311-code** [Comfy-Org/ComfyUI-Manager#432]
I have noticed on random occasions a gallery at the bottom takes up my entire view and is instrusive to what I am working on (can't see). In addition it has options like share, I just want to make sure that when this gallery appears at random that it doesn't mean something was shared.

![2](https://github.com/ltdrdata/ComfyUI-Manager/assets/23625562/a1f80f08-60f0-4c9d-8fed-75c429719f1c)

![1](https://github.com/ltdrdata/ComfyUI-Manager/assets/23625562/ba5e7544-eaa1-47b7-a851-eff05121ed66)

I do not have the pythongosssss/ComfyUI-Custom-Scripts installed, and tied it back to that, so I am not sure if this is built into comfyui manager, but for some reason Share:All is on by default. Does this mean my images or workflows were automatically shared?

**Comment by 311-code** [comment]
I found the clear button for the gallery at bottom, it seems windows display scaling was hiding the red x. I am still not sure if this gallery is a part of comfyui or this node. I'll close issue for now.

**Comment by ltdrdata** [comment]
The gallery feature isn't belongs to Manager nor ComfyUI built-in. You need to  check `ComfyUI/web/extensions`.
