### ISSUE TITLE
Saving a group node as a component doesn't work (GUI glitchy)

### ISSUE THREAD

**Issue by Cedri4** [Comfy-Org/ComfyUI-Manager#443]
Hello, I'm using the latest version of ComfyUI and ComfyUI-Manager. 
But when I select my group node and click on Save As Component, this glitchy GUI appears.

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/93396286/ad7f9d04-87cd-4c6e-8ef0-82417d3a8fbc)

- I also tried using the normal theme.
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/93396286/a22aca7d-37cb-4e75-8ef7-7417bda9e1e9)

- Zooming in and out doesn't work either.
- On another browser it doesn't make it work.

**Comment by Cedri4** [comment]
The problem is there there after updates.

**Comment by ltdrdata** [comment]
> The problem is there there after updates.

Some custom nodes manipulate the web layout. Disable all custom nodes except the manager and test it.
Please leave here if any custom node is identified as causing the issue.
