### ISSUE TITLE
"The installed ComfyUI does not have a Git repository."

### ISSUE THREAD

**Issue by nUser0** [Comfy-Org/ComfyUI-Manager#445]
When i click the "Update ComfyUI", the cmd window throw out "The installed ComfyUI does not have a Git repository."

Notes:
After downloading the zip package, I manually unzipped the installed ComfyUI. And run it by activating the WebUI's environment.

**Comment by ltdrdata** [comment]
Make sure that `ComfyUI/.git` dir is exists.
Downloading and decompressing via zip file is never recommended. Please use git clone directly.

**Comment by nUser0** [comment]
Thank you.  I'll try it  later.



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/29/2024 09:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ltdrdata/ComfyUI-Manager] "The installed ComfyUI does not have a Git repository." (Issue #445) |

Make sure that ComfyUI/.git dir is exists.
