### ISSUE TITLE
Installation of web extensions

### ISSUE THREAD

**Issue by adieyal** [Comfy-Org/ComfyUI-Manager#45]
I may have missed it but I was wondering whether you support installation of web extensions as well? I would prefer to avoid delegate that to ComfyUI-Manager but if that isn't on the roadmap then I'll add a copy in my install script

**Comment by ltdrdata** [comment]
There are cases where web extensions are supported in this manner.
https://github.com/failfa-st/failfast-comfyui-extensions

If implemented in a way that allows git-clone, ComfyUI-Manager can provide update checks and various management functionalities.

In the above case, it ensures setup during the startup of "comfyui" in `__init__.py`. However, if you are delegating the installation to ComfyUI-Manager, you can leave `__init__.py` empty and provide `install.py`, which will only be executed during the initial installation(or update).

For proper disable/enable/uninstall support, it would be even better to provide `disable.py`, `enable.py`, and `uninstall.py`.

**Comment by adieyal** [comment]
Understood - so extensions themselves are responsible for this. I added `shutil.copy` to my `install.py` and `path.unlink` to `uninstall.py` which is what you're suggesting. 

Thanks
