### ISSUE TITLE
Comfy UI Manager _ Custom Node Download Error

### ISSUE THREAD

**Issue by YahyaKadd** [Comfy-Org/ComfyUI-Manager#469]
Every Custom Node i download it shows me an error ... Please let me know what should i do in this case

![Capture11](https://github.com/ltdrdata/ComfyUI-Manager/assets/162612067/a2d2eb32-0e99-4109-99ba-99192f55c849)

**Comment by ltdrdata** [comment]
That's an error caused by a package installation failure occurring only in comfyui-reactor-node.

https://github.com/Gourieff/comfyui-reactor-node
