### ISSUE TITLE
ComfyUI Manager plugin issue - manager button not responding

### ISSUE THREAD

**Issue by miaotouy** [Comfy-Org/ComfyUI-Manager#47]
Title: ComfyUI Manager plugin issue - manager button not responding

Description:
I am experiencing an issue with the ComfyUI Manager plugin where clicking the manager button does not bring up a menu. Additionally, even after deleting the ComfyUI Manager plugin, the manager button is still present on the ComfyUI menu. This issue occurred after using the manager menu to update ComfyUI and restarting. Before updating ComfyUI, the plugin was working normally.

Steps to reproduce:
1. Install the ComfyUI Manager plugin.
2. Verify that the plugin is working normally.
3. Use the manager menu to update ComfyUI and restart.
4. Click on the manager button on the ComfyUI menu.
5. Observe that no menu appears.
6. Delete the ComfyUI Manager plugin.
7. Observe that the manager button is still present on the ComfyUI menu.

Expected behavior:
Clicking on the manager button should bring up a menu. After deleting the ComfyUI Manager plugin, the manager button should no longer be present on the ComfyUI menu.

Actual behavior:
Clicking on the manager button does not bring up a menu. After deleting the ComfyUI Manager plugin, the manager button is still present on the ComfyUI menu.

Additional information:
I have tried several troubleshooting steps, including restarting my computer, installing a new copy of ComfyUI in a different location, and installing the latest version of the Manager plugin, but the issue still persists.

[Attachment Startup log-2023-8-3.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/12246639/Attachment.Startup.log-2023-8-3.txt)

**Comment by infixlabs** [comment]
Same issue here

**Comment by infixlabs** [comment]
In my case I was getting this error:
`## [WARN] ComfyUI-Manager: Your ComfyUI version (1154) is too old. Please update to the latest version. ##`

Fix was:

```
cd ComfyUI_windows_portable\ComfyUI
git pull
```
