### ISSUE TITLE
nodes should let noodles passthru as well without affecting anythin

### ISSUE THREAD

**Issue by 2blackbar** [Comfy-Org/ComfyUI-Manager#48]
for example now i have this setup when i use lora, but when i dont want to use lora node what now ? 
Do i have to reconnect the noodles again or change lora affection to 0 - 0 in both fields?  
This is not nice it takes time everytime i want to do this i have tinker with numbers, what are the ways to just let noodle passthrough with signal without affecting it by the node its passing through ?
Without passthrough functionality of the nodes, we are pretty limited in what we can do , modularity of it cant be expanded by much without clutter and constant tinkering with noodles, id like to just disable some nodes and still have image generated  without reconnecing any noodle.
Any smart rerouting   with on/off switch ? 
A simple switch for this would be nice
Also no "generate forever" button ? This is one of the best things in a11

**Comment by ltdrdata** [comment]
> for example now i have this setup when i use lora, but when i dont want to use lora node what now ? Do i have to reconnect the noodles again or change lora affection to 0 - 0 in both fields? This is not nice it takes time everytime i want to do this i have tinker with numbers, what are the ways to just let noodle passthrough with signal without affecting it by the node its passing through ? Without passthrough functionality of the nodes, we are pretty limited in what we can do , modularity of it cant be expanded by much without clutter and constant tinkering with noodles, id like to just disable some nodes and still have image generated without reconnecing any noodle. Any smart rerouting with on/off switch ? A simple switch for this would be nice Also no "generate forever" button ? This is one of the best things in a11

1. Latest ComfyUI supports **bypass** feature. Select `Load LoRA` node. And `Ctrl-B`. Then it will passthru.
2. And you can do forever through this.
![forever](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/9e6b53f1-a322-4414-86d8-c52faddd67bb)


Though here is ComfyUI-Manager repo not ComfyUI repo....
