### ISSUE TITLE
I am having a strange issue, every time I update comfyui using comfy manager different custom nodes stops working

### ISSUE THREAD

**Issue by RYG81** [Comfy-Org/ComfyUI-Manager#480]
![Fail 01](https://github.com/ltdrdata/ComfyUI-Manager/assets/10570236/f997c9ca-35e5-464f-8cb9-3bbd2b49c33b)
![Fail 02](https://github.com/ltdrdata/ComfyUI-Manager/assets/10570236/a7a9159e-1d2c-4b77-ad15-264a77d9f4b1)
![Fail 03](https://github.com/ltdrdata/ComfyUI-Manager/assets/10570236/11fac61e-859a-4b8d-866f-7396cf34da5c)
Whenever I update comfy using comfy manager, some custom nodes getting import failed. I am not sure what's the issue and how to help developer reproduce it. Please help.
Above are screenshots for last three update/try to fix and Uninstall attempts for fixing issue.
[logs.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/14589742/logs.txt)
Here are the logs from terminal

**Comment by ltdrdata** [comment]
Some of the custom nodes you've installed are causing package dependency conflicts, particularly when installing certain outdated versions of the "transformers" and "diffusers" packages.

It seems that `ComfyUI_Seg_VITON` is the main problematic node. This custom node is consistently installing lower versions of transformers and diffusers.




```
AssertionError: diffusers>=0.25.0 requirement not satisfied. Please install correct diffusers version.

Cannot import D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-layerdiffusion module for custom nodes: diffusers>=0.25.0 requirement not satisfied. Please install correct diffusers version.
```


```
Collecting transformers==4.37.1
...
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\transformers\utils\hub.py", line 398, in cached_file
    )

  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Seg_VITON\checkpoints\segformer_b2_clothes'.

The above exception was the direct cause of the following exception:
```

I would recommend disabling `ComfyUI_Seg_VITON` and reinstalling transformers and diffusers with the latest versions.
You can install them via `Instal PIP packages` menu.
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/bb6811d0-0706-4347-8507-a501dc2e5a53)

**Comment by RYG81** [comment]
I removed all possible custom nodes that I have installed recently.
Even after that, I see some issue with listing nodes
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/10570236/ac2f0b94-795e-4ed4-ba42-3bda6b188639)

Here what is failed in terminal is not listed here in UI, but a next entry is appearing. For example ComfyUI-layerdiffusion has failed in terminal but in UI it shows ComfyUI-VideoHelperSuite and human-parser-comfyui-node has failed in terminal but in UI it's ComfyUI-Crystools. However, both ComfyUI-Crystools and ComfyUI-VideoHelperSuite nodes are usable in comfy.

Also it would be great if you make one tutorial video on installing package using pip package installer in comfy :) for non developer people like me

**Comment by RYG81** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/10570236/71089d8f-426a-459b-ad03-0bb7b21b0c86)
Today when I start comfy and open node manager

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/10570236/312888963-71089d8f-426a-459b-ad03-0bb7b21b0c86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NjQ4NTIsIm5iZiI6MTcxMDQ2NDU1MiwicGF0aCI6Ii8xMDU3MDIzNi8zMTI4ODg5NjMtNzEwODlkOGYtNDI2YS00NTliLWFkMDMtMGJiN2IyMWIwYzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAxMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTMwOGZjOGQ3MDg1NjVhYWNiNGZkYWRkYWJkNGI5MTUwMGI2NmE5ZWUyM2UyMGMyMWUzOWM4OWY4MmE3MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.svpEmUHiCK6osFIpYCnMYi6cOSBemvIkRBCCU7UWGnA) Today when I start comfy and open node manager

You need to check the teminal message.
Also, I don't understand the situation where the ComfyUI-Manager fails and but the dialog pops up. Could it be due to duplicate installations?

**Comment by RYG81** [comment]
no duplicate installation. Please see this one - https://github.com/ltdrdata/ComfyUI-Manager/issues/480#issuecomment-1996579017
here I tried to explain possible issue

**Comment by ltdrdata** [comment]
> no duplicate installation. Please see this one - [#480 (comment)](https://github.com/ltdrdata/ComfyUI-Manager/issues/480#issuecomment-1996579017) here I tried to explain possible issue

The log simply indicates a failure in import, so it's of no help in diagnosis as it's just a symptom. The logs indicating why the failure occurred earlier on are what's important.

**Comment by RYG81** [comment]
No if you see screenshot i have marked things with red line and red arrow, in terminal fail node is different and in ui its different.

**Comment by ltdrdata** [comment]
> No if you see screenshot i have marked things with red line and red arrow, in terminal fail node is different and in ui its different.

That's exactly what I'm saying. It simply shows that there was a failure in import, without any information about why it failed. That's why I always request the full log.

**Comment by RYG81** [comment]
Issue is not with fail, issue is listing wrong node name in UI.
The fail node is different and the node listed in comfy manager list is different.

**Comment by ltdrdata** [comment]
> Issue is not with fail, issue is listing wrong node name in UI. The fail node is different and the node listed in comfy manager list is different.

Oh.. I got it.

**Comment by ltdrdata** [comment]
This is fixed.
