### ISSUE TITLE
FETCH DATA from: /home/pipe/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json

### ISSUE THREAD

**Issue by oqupspipe** [Comfy-Org/ComfyUI-Manager#487]
When I use it, I always say that the base workflow is not running because of this, and the workflow does not respond to the prompt: FETCH DATA from: extension-node-map.json.What is the reason?

**Comment by ltdrdata** [comment]
That has nothing to do with running the workflow. It's simply an indication of what data is being read in the background. It's just the last message displayed, and the issue you're encountering is happening elsewhere.
