### ISSUE TITLE
"Install Missing Custom Nodes" fails with "The custom node DB is currently being updated, and updates to custom nodes are being checked for..."

### ISSUE THREAD

**Issue by spashii** [Comfy-Org/ComfyUI-Manager#49]
"Install Missing Custom Nodes" fails with
```
The custom node DB is currently being updated, and updates to custom nodes are being checked for.
NOTE: Update only checks for extensions that have been fetched.
```

Terminal Output:
```
Prestartup times for custom nodes:
   0.0 seconds: C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiManager_v012

Total VRAM 6144 MB, total RAM 16221 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 Ti : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\Users\sam\Desktop\dev\sd\stable-diffusion-webui\models/ControlNet
### Loading: ComfyUI-Manager (V0.12)
### ComfyUI Revision: 1230 [076d2db6]

Import times for custom nodes:
   0.0 seconds: C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.5 seconds: C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiManager_v012

Starting server

To see the GUI go to: http://127.0.0.1:8188
FECTH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Error handling request
Traceback (most recent call last):
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "asyncio\base_events.py", line 1070, in create_connection
  File "asyncio\base_events.py", line 1054, in create_connection
  File "asyncio\base_events.py", line 963, in _connect_sock
  File "asyncio\proactor_events.py", line 709, in sock_connect
  File "asyncio\windows_events.py", line 821, in _poll
  File "asyncio\windows_events.py", line 608, in finish_connect
OSError: [WinError 121] The semaphore timeout period has expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiManager_v012\__init__.py", line 324, in fetch_customnode_list
    json_obj = await get_data(uri)
  File "C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiManager_v012\__init__.py", line 176, in get_data
    async with session.get(uri) as resp:
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [The semaphore timeout period has expired]
FECTH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Error handling request
Traceback (most recent call last):
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "asyncio\base_events.py", line 1070, in create_connection
  File "asyncio\base_events.py", line 1054, in create_connection
  File "asyncio\base_events.py", line 963, in _connect_sock
  File "asyncio\proactor_events.py", line 709, in sock_connect
  File "asyncio\windows_events.py", line 821, in _poll
  File "asyncio\windows_events.py", line 608, in finish_connect
OSError: [WinError 121] The semaphore timeout period has expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiManager_v012\__init__.py", line 324, in fetch_customnode_list
    json_obj = await get_data(uri)
  File "C:\Users\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyuiManager_v012\__init__.py", line 176, in get_data
    async with session.get(uri) as resp:
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\comfyui\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [The semaphore timeout period has expired]
```

Seems like an openssl issue. Any help would be appreciated. Thanks!

**Comment by spashii** [comment]
Possible duplicate of #42 

@ltdrdata This issue could be due to an openssl issue. I have attached the terminal log above

**Comment by ltdrdata** [comment]
> Possible duplicate of #42 
> 
> @ltdrdata This issue could be due to an openssl issue. I have attached the terminal log above

In that case check "use local db".
Still I am worrying about next steps..

**Comment by spashii** [comment]
> > Possible duplicate of #42
> > @ltdrdata This issue could be due to an openssl issue. I have attached the terminal log above
> 
> In that case check "use local db". Still I am worrying about next steps..

@ltdrdata I checked "use local db" seems like local db is giving empty result. Please suggest alternative method with maybe openssl fix

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/63326129/e5cf52ee-c45b-498e-a2d0-ae3187bb3071)

**Comment by ltdrdata** [comment]
> > > Possible duplicate of #42
> > > @ltdrdata This issue could be due to an openssl issue. I have attached the terminal log above
> > 
> > In that case check "use local db". Still I am worrying about next steps..
> 
> @ltdrdata I checked "use local db" seems like local db is giving empty result. Please suggest alternative method with maybe openssl fix
> 
> ![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/63326129/e5cf52ee-c45b-498e-a2d0-ae3187bb3071)
> 

This feature is not perfect.

These cases are unsupported cases.

1. If they are too new node which is not registered to node DB, yet. Otherwise they are unknown nodes to me.

2. If they are deprecated and removed from latest custom nodes.

3. If they are belongs to undetectable because of irregular form of custom nodes.

4. If they are belongs to workflow component. (the name is start with ##)

But if you post the name of missing nodes. Maybe I can help you.

**Comment by ltdrdata** [comment]
This patch will resolve this issue.
https://github.com/ltdrdata/ComfyUI-Manager/issues/156#issuecomment-1797899960

**Comment by FisherMS** [comment]
I have the same error.
I use your config for https://github.com/ltdrdata/ComfyUI-Manager/issues/156#issuecomment-1797899960
But, It's still error.

I can open https://[raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json](https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json) use edge (by office proxy)

```python
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 1085, in create_connection
  File "asyncio\base_events.py", line 1069, in create_connection
  File "asyncio\base_events.py", line 973, in _connect_sock
  File "asyncio\proactor_events.py", line 726, in sock_connect
  File "asyncio\windows_events.py", line 846, in _poll
  File "asyncio\windows_events.py", line 633, in finish_connect
OSError: [WinError 121] The semaphore timeout period has expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 659, in fetch_customnode_list
    json_obj = await get_data(uri)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 423, in get_data
    async with session.get(uri) as resp:
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 562, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [The semaphore timeout period has expired]

```

**Comment by ltdrdata** [comment]
> I have the same error. I use your config for [#156 (comment)](https://github.com/ltdrdata/ComfyUI-Manager/issues/156#issuecomment-1797899960) But, It's still error.
> 
> I can open https://[raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json](https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json) use edge (by office proxy)
> 
> ```python
> FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> ERROR:aiohttp.server:Error handling request
> Traceback (most recent call last):
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
>     return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "asyncio\base_events.py", line 1085, in create_connection
>   File "asyncio\base_events.py", line 1069, in create_connection
>   File "asyncio\base_events.py", line 973, in _connect_sock
>   File "asyncio\proactor_events.py", line 726, in sock_connect
>   File "asyncio\windows_events.py", line 846, in _poll
>   File "asyncio\windows_events.py", line 633, in finish_connect
> OSError: [WinError 121] The semaphore timeout period has expired
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
>     resp = await request_handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
>     resp = await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\ComfyUI\server.py", line 46, in cache_control
>     response: web.Response = await handler(request)
>                              ^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 659, in fetch_customnode_list
>     json_obj = await get_data(uri)
>                ^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 423, in get_data
>     async with session.get(uri) as resp:
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
>     self._resp = await self._coro
>                  ^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 562, in _request
>     conn = await self._connector.connect(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 540, in connect
>     proto = await self._create_connection(req, traces, timeout)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
>     _, proto = await self._create_direct_connection(req, traces, timeout)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
>     raise last_exc
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
>     transp, proto = await self._wrap_create_connection(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
>     raise client_error(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [The semaphore timeout period has expired]
> ```

It seems like a firewall issue. I'll try adding proxy configuration functionality.

**Comment by WillLam123** [comment]
> > I have the same error. I use your config for [#156 (comment)](https://github.com/ltdrdata/ComfyUI-Manager/issues/156#issuecomment-1797899960) But, It's still error.
> > I can open https://[raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json](https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json) use edge (by office proxy)
> > ```python
> > FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> > ERROR:aiohttp.server:Error handling request
> > Traceback (most recent call last):
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
> >     return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "asyncio\base_events.py", line 1085, in create_connection
> >   File "asyncio\base_events.py", line 1069, in create_connection
> >   File "asyncio\base_events.py", line 973, in _connect_sock
> >   File "asyncio\proactor_events.py", line 726, in sock_connect
> >   File "asyncio\windows_events.py", line 846, in _poll
> >   File "asyncio\windows_events.py", line 633, in finish_connect
> > OSError: [WinError 121] The semaphore timeout period has expired
> > 
> > The above exception was the direct cause of the following exception:
> > 
> > Traceback (most recent call last):
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
> >     resp = await request_handler(request)
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
> >     resp = await handler(request)
> >            ^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
> >     return await handler(request)
> >            ^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\ComfyUI\server.py", line 46, in cache_control
> >     response: web.Response = await handler(request)
> >                              ^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 659, in fetch_customnode_list
> >     json_obj = await get_data(uri)
> >                ^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 423, in get_data
> >     async with session.get(uri) as resp:
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
> >     self._resp = await self._coro
> >                  ^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 562, in _request
> >     conn = await self._connector.connect(
> >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 540, in connect
> >     proto = await self._create_connection(req, traces, timeout)
> >             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
> >     _, proto = await self._create_direct_connection(req, traces, timeout)
> >                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
> >     raise last_exc
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
> >     transp, proto = await self._wrap_create_connection(
> >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
> >     raise client_error(req.connection_key, exc) from exc
> > aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [The semaphore timeout period has expired]
> > ```
> 
> It seems like a firewall issue. I'll try adding proxy configuration functionality.

I can confirm this could be a proxy issue. I turned off proxy and this problem disappear right away.

**Comment by jerrychoux** [comment]
> > > I have the same error. I use your config for [#156 (comment)](https://github.com/ltdrdata/ComfyUI-Manager/issues/156#issuecomment-1797899960) But, It's still error.
> > > I can open https://[raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json](https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json) use edge (by office proxy)
> > > ```python
> > > FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> > > ERROR:aiohttp.server:Error handling request
> > > Traceback (most recent call last):
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
> > >     return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
> > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "asyncio\base_events.py", line 1085, in create_connection
> > >   File "asyncio\base_events.py", line 1069, in create_connection
> > >   File "asyncio\base_events.py", line 973, in _connect_sock
> > >   File "asyncio\proactor_events.py", line 726, in sock_connect
> > >   File "asyncio\windows_events.py", line 846, in _poll
> > >   File "asyncio\windows_events.py", line 633, in finish_connect
> > > OSError: [WinError 121] The semaphore timeout period has expired
> > > 
> > > The above exception was the direct cause of the following exception:
> > > 
> > > Traceback (most recent call last):
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
> > >     resp = await request_handler(request)
> > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
> > >     resp = await handler(request)
> > >            ^^^^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
> > >     return await handler(request)
> > >            ^^^^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\ComfyUI\server.py", line 46, in cache_control
> > >     response: web.Response = await handler(request)
> > >                              ^^^^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 659, in fetch_customnode_list
> > >     json_obj = await get_data(uri)
> > >                ^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 423, in get_data
> > >     async with session.get(uri) as resp:
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
> > >     self._resp = await self._coro
> > >                  ^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 562, in _request
> > >     conn = await self._connector.connect(
> > >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 540, in connect
> > >     proto = await self._create_connection(req, traces, timeout)
> > >             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
> > >     _, proto = await self._create_direct_connection(req, traces, timeout)
> > >                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
> > >     raise last_exc
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
> > >     transp, proto = await self._wrap_create_connection(
> > >                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   File "D:\AI\ComfyUI_win_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
> > >     raise client_error(req.connection_key, exc) from exc
> > > aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host raw.githubusercontent.com:443 ssl:default [The semaphore timeout period has expired]
> > > ```
> > 
> > 
> > It seems like a firewall issue. I'll try adding proxy configuration functionality.
> 
> I can confirm this could be a proxy issue. I turned off proxy and this problem disappear right away.

I turn off lantern proxy, and set hosts, and every thing are ok. turn on lantern and will fail again
