### ISSUE TITLE
*feature request* sort by Popularity and "like" a node and multi-select models for install

### ISSUE THREAD

**Issue by ricperry** [Comfy-Org/ComfyUI-Manager#497]
It would be great if we could get some sort of rating system included in the custom nodes list. Sorting the custom nodes in general needs implemented (alphabetical by author/name, by popularity, by # of downloads, etc...). I don't really care what the Node ID is, and it's completely irrelevant unless I'm looking for a particular ID (but that's never happened). What I'd really like to be able to do is install the node lots of people have either installed or upvoted.

Also it would be better if we could select more than 1 model at a time to queue up for install the same way we can for custom nodes.

**Comment by ltdrdata** [comment]
The system for receiving user feedback requires hosting, which complicates matters. Currently, I am not considering this aspect. I aim to maintain this project in a decentralized form as much as possible.

**Comment by clayne** [comment]
> The system for receiving user feedback requires hosting, which complicates matters. Currently, I am not considering this aspect. I aim to maintain this project in a decentralized form as much as possible.

I don't think the manager should support rating or liking nodes from the interface itself but adding fork count, likes, and repo update time GitHub into the json data isn't that difficult. There are a couple ways it could be done:

1. As an auxiliary data file alongside existing jsons, said file is updated once a day using the GH api to fetch repo stats en masse, and checked into the main repo. It could also be stored in the main json data files but perhaps that data would be desired to be kept separate.
2. As a client side feature requiring the user to have a GH api key and either run manually (e.g. update ratings) or if the data is older than 24h.

Either solution would simply use the GH graphql API and repo stats can be fetched in 128 or 256 repo chunks for efficiency. I use a similar approach for figuring out forked repos that have changed and it handles 8000+ repos without an issue. I doubt there's anywhere close that many nodes.

As far as sorting that seems like a separate feature that could be implemented for existing columns.

**Comment by ltdrdata** [comment]
> > The system for receiving user feedback requires hosting, which complicates matters. Currently, I am not considering this aspect. I aim to maintain this project in a decentralized form as much as possible.
> 
> I don't think the manager should support rating or liking nodes from the interface itself but adding fork count, likes, and repo update time GitHub into the json data isn't that difficult. There are a couple ways it could be done:
> 
> 1. As an auxiliary data file alongside existing jsons, said file is updated once a day using the GH api to fetch repo stats en masse, and checked into the main repo. It could also be stored in the main json data files but perhaps that data would be desired to be kept separate.
> 2. As a client side feature requiring the user to have a GH api key and either run manually (e.g. update ratings) or if the data is older than 24h.
> 
> Either solution would simply use the GH graphql API and repo stats can be fetched in 128 or 256 repo chunks for efficiency. I use a similar approach for figuring out forked repos that have changed and it handles 8000+ repos without an issue. I doubt there's anywhere close that many nodes.
> 
> As far as sorting that seems like a separate feature that could be implemented for existing columns.

Using an approach based on the number of stars is worth considering.

**Comment by DrJKL** [comment]
I'd love to be able to sort by Stars and Most Recent Commit, especially if we're already getting them from the GitHub queries.

**Comment by liusida** [comment]
https://github.com/liusida/ComfyUI-Manager-CustomNodes-Ranked

I've made myself a patch and hope the official one will come soon.
(Also, I've realized that star numbers are rising quickly, which is a good sign.)

**Comment by liusida** [comment]
> Either solution would simply use the GH graphql API and repo stats can be fetched in 128 or 256 repo chunks for efficiency. I use a similar approach for figuring out forked repos that have changed and it handles 8000+ repos without an issue. I doubt there's anywhere close that many nodes.

I wish I had known it earlier! Thanks for this cool trick!

**Comment by liusida** [comment]
> > Either solution would simply use the GH graphql API and repo stats can be fetched in 128 or 256 repo chunks for efficiency. I use a similar approach for figuring out forked repos that have changed and it handles 8000+ repos without an issue. I doubt there's anywhere close that many nodes.
> 
> I wish I had known it earlier! Thanks for this cool trick!

**Comment by ltdrdata** [comment]
> https://github.com/liusida/ComfyUI-Manager-CustomNodes-Ranked
> 
> I've made myself a patch and hope the official one will come soon. (Also, I've realized that star numbers are rising quickly, which is a good sign.)

That is nice.

However, rather than modifying `custom-node-list.json`, it seems better to create separate information files like `stats.json`. `custom-node-list.json` is directly modified, whereas star information should be automatically managed through the scanner. 

Additionally, it would be beneficial to collect recent update date information alongside stars.

**Comment by liusida** [comment]
> > https://github.com/liusida/ComfyUI-Manager-CustomNodes-Ranked
> > I've made myself a patch and hope the official one will come soon. (Also, I've realized that star numbers are rising quickly, which is a good sign.)
> 
> That is nice.
> 
> However, rather than modifying `custom-node-list.json`, it seems better to create separate information files like `stats.json`. `custom-node-list.json` is directly modified, whereas star information should be automatically managed through the scanner.
> 
> Additionally, it would be beneficial to collect recent update date information alongside stars.

Thanks for the input. I'll work on this.

What do you think about the filename `github-stats.json`? And I might need to modify some py/js file to read this file in and use the star number.

I'll let you know if I have any question.

**Comment by liusida** [comment]
@ltdrdata, I've modified `scanner.py` to generate a `github-stats.json` file. I believe submitting this first would be beneficial, as the interface and sorting functionalities can be implemented in JavaScript subsequently.

**Comment by liusida** [comment]
I've added sorting to the "Install Custom Nodes" screen as well.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager/pull/533
