### ISSUE TITLE
Diffusion\\ComfyUI_windows_portable\\python_embeded\\python.exe': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dduongtrandai** [Comfy-Org/ComfyUI-Manager#499]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/100944029/eb0def03-82c9-4acd-9e01-7f0db439daef)

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/100944029/0b7aecaa-0c0a-41ad-b10d-79c11508e914)

When performing Update/Fix custom node and Restart ComfyUI, the error occurs Diffusion\ComfyUI_windows_portable\python_embeded\python.exe': [Errno 2] No such file or directory

**Comment by ltdrdata** [comment]
When there is a space in the path, the restart function does not work properly.

**Comment by dduongtrandai** [comment]
> When there is a space in the path, the restart function does not work properly.
Thanks you, I removed the spaces in the path and the problem was resolved.
