### ISSUE TITLE
Many failed nodes today after updating comfyui through Manager

### ISSUE THREAD

**Issue by RYG81** [Comfy-Org/ComfyUI-Manager#504]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/10570236/e257fafe-ccae-4aef-89ee-949b03545e30)
After I update comfy using update all in Manager so many nodes failed.
what can be done to solve this, how can I o avoid it? please some one help

**Comment by ltdrdata** [comment]
What is the terminal log?
In such cases, there is a high likelihood that package dependencies have been broken.

**Comment by RYG81** [comment]
[LOG.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/14652440/LOG.txt)
Here it is since I started today evening

**Comment by RYG81** [comment]
[LOG.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/14652624/LOG.txt)
This one is just with last run where I tried to uninstall and re install failed nodes. Just in case it helps.

**Comment by ltdrdata** [comment]
Based on the log inspection, it appears that those nodes are not compatible with the latest ComfyUI update. Please reach out to each custom node developer for assistance.

**Comment by RYG81** [comment]
OK, Thanks.

**Comment by RYG81** [comment]
I just reupdate comfy and all got fixed automatically
