### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by PetitPrinceb612** [Comfy-Org/ComfyUI-Manager#525]
Recently, during a daily zoom-in and zoom-out operation to view all workflows, the vector UI suddenly failed. After restarting the server and updating manager, the UI bug still exists. How can I solve it?![屏幕截图 2024-03-29 021115](https://github.com/ltdrdata/ComfyUI-Manager/assets/46679983/8b320219-9d0c-4f3a-82c6-5350be8f30e4)

**Comment by ltdrdata** [comment]
First of all, this is not an issue related to the Manager but rather a problem associated with the native functionality of ComfyUI.

Also, it's not clear what you mean by 'fail'. Please provide more details about the situation and ask here.
https://github.com/comfyanonymous/ComfyUI/issues
