### ISSUE TITLE
Install unlisted Huggingface models

### ISSUE THREAD

**Issue by davide445** [Comfy-Org/ComfyUI-Manager#530]
Want to use a SD Krita plugin so needing to install these models

[https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup](https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup)

i.e. [https://huggingface.co/Acly/Omni-SR](https://huggingface.co/Acly/Omni-SR) is not listed in ComfyUI Manager Install Models UI

Wanted to ask if it's actually possible to install specific unlisted models in some other way under ComfyUI-Manager.

**Comment by ltdrdata** [comment]
The model installation feature provided by ComfyUI-Manager simply offers a download function. Users can directly download and place the model in the appropriate directory without manager.
