### ISSUE TITLE
Different Version of Python Reported?

### ISSUE THREAD

**Issue by CaseyHaralson** [Comfy-Org/ComfyUI-Manager#532]
I'm using the ComfyUI portable version which comes with python_embeded. When I run the comfyui run_nvidia_gpu.bat file it calls the python.exe that is in the python_embeded folder.

When the Comfyui Manager runs during startup, it reports the version of python as being 3.11.8 and the executable as coming from the embeded folder. BUT, if I go to that folder and run "python.exe -V" it reports that the version is 3.10.6.

Can anyone help me understand? I'm not sure what is going on here.

Ultimately, a package isn't installing so I'm trying to install it manually, but it won't install the 3.11 version and the 3.10 version doesn't seem to be working.

**Comment by ltdrdata** [comment]
```
** Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
** Python executable: /mnt/backup/venv/bin/python
```

The 'python executable:' output indicates the path to the python executable that you actually ran when launching ComfyUI.

Running `python.exe -V` and running `path\to\the\python.exe -V` are different in meaning.

**Comment by CaseyHaralson** [comment]
You are right! Something from the path was picked up before the file in the current folder.

I should have been doing `.\python.exe`. 

Thanks a bunch!
