### ISSUE TITLE
How can i add my custom node to ComfyUI-Manager?

### ISSUE THREAD

**Issue by frankchieng** [Comfy-Org/ComfyUI-Manager#535]
https://github.com/frankchieng/ComfyUI_Aniportrait 

i just saw the pull request and add an entry in custom-node-list.json requirement, but it seemed i can't create a new pull request
        {
            "author": "FrankChieng",
            "title": "ComfyUI_Aniportrait",
            "reference": "https://github.com/frankchieng/ComfyUI_Aniportrait",
            "files": [
                "https://github.com/frankchieng/ComfyUI_Aniportrait"
            ],
            "install_type": "git-clone",
            "description": "implementation of Aniportrait's self driven,audio driven and Face reenacment in ComfyUI"
        },

**Comment by ltdrdata** [comment]
Your node has already been registered. I just updated the description to yours.

**Comment by frankchieng** [comment]
> Your node has already been registered. I just updated the description to yours.

thx,can u help me change the description from <html>
>This is unofficial implementation of [AniPortrait](https://github.com/Zejun-Yang/AniPortrait) in ComfyUI custom_node,cuz i have routine jobs,so i will update this project when i have time

to:
> implementation of AniPortrait generating of videos ,includes self driven,face reenacment and audio driven with a reference image

**Comment by ltdrdata** [comment]
> > Your node has already been registered. I just updated the description to yours.
> 
> thx,can u help me change the description from
> 
> > This is unofficial implementation of [AniPortrait](https://github.com/Zejun-Yang/AniPortrait) in ComfyUI custom_node,cuz i have routine jobs,so i will update this project when i have time
> 
> to:
> 
> > implementation of AniPortrait generating of videos ,includes self driven,face reenacment and audio driven with a reference image

Done.
