### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by K-O-N-B** [Comfy-Org/ComfyUI-Manager#538]
I don't know what node I have installed, the menu shows this thing:

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/152141077/c232ae42-4ed8-459f-bb1f-2cb5e9cbfe9b)

and because my screen is not big, so I can't see the whole menu and can't move and click Queue button now.

**Comment by ltdrdata** [comment]
I also don't know about that extension. I recommend testing by moving half of the nodes installed in `ComfyUI/custom_nodes` to a different directory and removing them gradually.

**Comment by K-O-N-B** [comment]
Could I request a "customizeable menu" function in future?

**Comment by ltdrdata** [comment]
> Could I request a "customizeable menu" function in future?

The main menu is a basic feature of ComfyUI and cannot be managed by ComfyUI-Manager. ComfyUI provides appropriate APIs, and custom node developers must adhere to them.
