### ISSUE TITLE
Any reason custom model paths are not supported ?

### ISSUE THREAD

**Issue by piyushK52** [Comfy-Org/ComfyUI-Manager#542]
I am installing multiple models in a different comfy instance manually through a script (this requires updating extra_model_paths.yaml as well) but when I install models through comfy manager (API), custom paths are not supported.. Is there any reason for this ?

![Screenshot 2024-04-06 at 7 44 18 PM](https://github.com/ltdrdata/ComfyUI-Manager/assets/34690994/02ae7110-5625-4318-813d-67773695a08b)

**Comment by ltdrdata** [comment]
There are complex issues involved. While it is possible to simply support the custom_nodes path, doing so could increase the likelihood of unexpected problems arising. Current approach is a conservative way.

https://github.com/ltdrdata/ComfyUI-Manager/issues/420#issuecomment-1958646418

**Comment by piyushK52** [comment]
Thanks for the quick response but I am talking about "custom models" not "custom nodes"..

**Comment by ltdrdata** [comment]
> Thanks for the quick response but I am talking about "custom models" not "custom nodes"..

Oh... I see.. 
The extra model path of ComfyUI is not to replace the existing model path but to add to it. More than two model paths can be registered. Therefore, using a policy to download to the path specified by the extra model path becomes ambiguous.

**Comment by piyushK52** [comment]
In the screenshot that I have shared, you have added checks to prevent downloading models to paths starting with ".." or "/" (basically preventing the providing of custom paths).. can't we simply allow this? so the user can provide whatever path they require the model to be downloaded at ?

**Comment by ltdrdata** [comment]
> In the screenshot that I have shared, you have added checks to prevent downloading models to paths starting with ".." or "/" (basically preventing the providing of custom paths).. can't we simply allow this? so the user can provide whatever path they require the model to be downloaded at ?

Not allowing relative paths is a measure for security. The basic policy is to prevent writing or reading anything outside of ComfyUI as much as possible.

**Comment by piyushK52** [comment]
yeah makes sense. just a closing remark, maybe you can allow the users to write in paths provided through extra_models_path but I understand if it requires some other considerations. Feel free to close this ticket.
