### ISSUE TITLE
ComfyUI-Manager: Your ComfyUI is too OUTDATED!!!

### ISSUE THREAD

**Issue by digizhu** [Comfy-Org/ComfyUI-Manager#553]
ComfyUI: Unknown[-](1900-01-01)
Manager: V2.16.1
<img width="1047" alt="Screenshot 2024-04-10 at 22 30 06" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/8264002/f39fde5a-cb65-4334-b62b-a67d2d0f965c">
（CPU is APPLE M1）Unable to update, even if the latest version is downloaded and viewed using Manager, it still shows this. Additionally, the version number cannot be viewed, and there is still an error message:
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 436, in load_models
    is_sdxl = isinstance(model.model, (comfy.model_base.SDXL, comfy.model_base.SDXLRefiner, comfy.model_base.SDXL_instructpix2pix))
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'

**Comment by ltdrdata** [comment]
It doesn't seem like you've installed ComfyUI via `git clone`. To support the update feature from the manager, it needs to be in the form of a git repository.

**Comment by digizhu** [comment]
> It doesn't seem like you've installed ComfyUI via `git clone`. To support the update feature from the manager, it needs to be in the form of a git repository.您似乎没有通过 `git clone` 安装 ComfyUI。为了支持管理器的更新功能，需要采用git存储库的形式。

Do I need to delete the previous ComfyUI folder and reinstall comfyUI through git clone?

**Comment by ltdrdata** [comment]
> > It doesn't seem like you've installed ComfyUI via `git clone`. To support the update feature from the manager, it needs to be in the form of a git repository.您似乎没有通过 `git clone` 安装 ComfyUI。为了支持管理器的更新功能，需要采用git存储库的形式。
> 
> Do I need to delete the previous ComfyUI folder and reinstall comfyUI through git clone?

Yup. That is the best solution.

**Comment by digizhu** [comment]
Thx!!! It works!
