### ISSUE TITLE
Manager works, but slow as hell...

### ISSUE THREAD

**Issue by Dieterbohlisch** [Comfy-Org/ComfyUI-Manager#555]
![slowly](https://github.com/ltdrdata/ComfyUI-Manager/assets/122730655/2de77bd2-37db-4c3b-a62a-88b428ee65f5)

everytime I want to install models, custom nodes or update comfy it takes 5 up to ten minutes to fetch the data. (see the screenshot). what can be the issue?

if I want to install 5 missing nodes, the process will take an hour to complete^^

it works fine after that, but why it takes so much time?

best regarts!

**Comment by ltdrdata** [comment]
Is your ComfyUI installed in a local environment?

**Comment by Dieterbohlisch** [comment]
I use the portable version of comfyui on a win10 computer.

**Comment by Dieterbohlisch** [comment]
I really don´t know the issue, so I left windows and use linux instead. Now it works fine!
