### ISSUE TITLE
Unauthorized node entry, modification request.

### ISSUE THREAD

**Issue by chaosaiart** [Comfy-Org/ComfyUI-Manager#556]
**Someone has submitted** my custom node to your platform **without my knowledge.** 
Unfortunately, the person has chosen an **incorrect description** for my node.

Is it possible for you to **change** my custom node **description** as follows:

**"LowVRAM Animation : txt2video - img2video - video2video , Frame by Frame, compatible with LowVRAM GPUs , Included : Prompt Switch, Checkpoint Switch, Cache, Number Count by Frame, Ksampler txt2img & img2img ..."**

**Information:**
ID: 661 
Author: chaosaiart
Name: [Chaosaiart-Nodes](https://github.com/chaosaiart/Chaosaiart-Nodes)
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/140610788/665f44c6-7a34-4846-91f7-2fb899998d31)

 
_

I intended to submit my node to your platform anyway, but I wanted to upload example results beforehand. Well, someone took advantage of that time window.

**Thank you for your good work. I hope the change is possible.**

**Comment by ltdrdata** [comment]
Oops! Looks like I assigned the wrong description by mistake. 
I've modified it now.
Thank you.

**Comment by chaosaiart** [comment]
thank you, have a nice day
