### ISSUE TITLE
New custom node: Load styles.csv (from automatic1111)

### ISSUE THREAD

**Issue by theUpsider** [Comfy-Org/ComfyUI-Manager#56]
May it be possible to add this node to the [custom-node-list.json](https://github.com/ltdrdata/ComfyUI-Manager/blob/main/custom-node-list.json)?
I wrote it for migration purposes from automatic1111 webui to comfyui: https://github.com/theUpsider/ComfyUI-Styles_CSV_Loader

[Apparently](https://github.com/comfyanonymous/ComfyUI/issues/1145#issuecomment-1668303200) there is a node suite which includes this single feature as well. But for everyone who doesnt want a whole bloated node suite in their project but simply load their old styles, my csv loader should be enough.

**Comment by ltdrdata** [comment]
added

**Comment by philcoraz** [comment]
Hello, Thanks for this very good plugin, but I really can't figure out how to load my own csv file in the node do you have any clue about it, thanks very much.
