### ISSUE TITLE
how to solve this Cannot import /kaggle/working/ui/custom_nodes/ComfyUI-Manager module for custom nodes: No module named 'git'

### ISSUE THREAD

**Issue by jjiikkkk** [Comfy-Org/ComfyUI-Manager#567]
Using xformers cross attention
Registered sys.path: ['/kaggle/working/ui/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/kaggle/working/ui/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/kaggle/working/ui/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/kaggle/working/ui/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/kaggle/working/ui/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/kaggle/working/ui/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/kaggle/working/ui/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/kaggle/working/ui/custom_nodes/comfyui_controlnet_aux/src', '/kaggle/working/ui/comfy', '/kaggle/working/ui', '/kaggle/lib/kagglegym', '/kaggle/lib', '/opt/conda/envs/colabui/lib/python310.zip', '/opt/conda/envs/colabui/lib/python3.10', '/opt/conda/envs/colabui/lib/python3.10/lib-dynload', '/root/.local/lib/python3.10/site-packages', '/opt/conda/envs/colabui/lib/python3.10/site-packages', '/kaggle/working/ui/custom_nodes/ComfyUI-Manager/glob']
Traceback (most recent call last):
  File "/kaggle/working/ui/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/kaggle/working/ui/custom_nodes/ComfyUI-Manager/__init__.py", line 18, in <module>
    from .glob import manager_core as core
  File "/kaggle/working/ui/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 9, in <module>
    import git
ModuleNotFoundError: No module named 'git'

Cannot import /kaggle/working/ui/custom_nodes/ComfyUI-Manager module for custom nodes: No module named 'git'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /kaggle/working/ui/custom_nodes/ComfyUI-Manager
   0.0 seconds: /kaggle/working/ui/custom_nodes/comfyui_controlnet_aux

thanks.

**Comment by jjiikkkk** [comment]
and unable to find 
Build Blended Face Model 
ReActor-Fast Face Swap
after I # 切换到克隆的仓库目录
%cd ComfyUI-Manager

# 切换到指定的commit
!git checkout 3edb3586b7077f9d6d495d48caa79b20d1572ece

is the checkout 3edb is unable to use such nodes above?

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by Soul-OMON** [comment]
When running the Run ComfyUI with cloudflared (Recommended Way) block in Kaggle
at the end the command is called:
This is the URL to access ComfyUI: https://default-hopkins-muslim-strategy.trycloudflare.com/ |
^C

Stopped server

Which causes the server to stop. Can this be fixed somehow?
