### ISSUE TITLE
NameError: name 'comfy_ui_revision' is not defined

### ISSUE THREAD

**Issue by wujm424606** [Comfy-Org/ComfyUI-Manager#570]

**Comment by wujm424606** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/38379474/a6c34e8c-9410-43a8-9058-837d7e2d4276)

**Comment by wujm424606** [comment]
After I update the manager today, it occurs this issue

**Comment by Gileanxxx** [comment]
same

**Comment by rovo79** [comment]
same here

**Comment by ltdrdata** [comment]
This is patched.
Update it again.
