### ISSUE TITLE
Reboot/Restart Leaks VRAM on Ubuntu Linux

### ISSUE THREAD

**Issue by liusida** [Comfy-Org/ComfyUI-Manager#576]
The function that uses `os.execv` to reboot the server is located here:
https://github.com/ltdrdata/ComfyUI-Manager/blob/742fd380b236c159c572f46fc224679d32d7fc54/__init__.py#L1187

Very interestingly, this `os.execv` replaces current process with the new one, however, on Ubuntu, the VRAM allocated would not be freed completely, causing a leak of VRAM.

This is not a problem of ComfyUI, but I think CUDA on Ubuntu in general, because I wrote two test scripts to show that pytorch and pycuda both have the same issue (I'll attach my test scripts below).

So I think the current solution should be finding another method to reboot instead of `os.execv()` on Ubuntu.

Windows is completely fine, tested.

-------------
Here are two test scripts that will eat all VRAM if we don't stop it.

```py
import torch
import os
import sys

def print_vram_usage():
    # Optionally check VRAM usage via nvidia-smi (uncomment if nvidia-smi is installed)
    print("VRAM usage before allocation:")
    os.system('nvidia-smi')

def allocate_vram():
    # Allocate a tensor of size 1GB on the GPU
    tensor = torch.rand((256, 1024, 1024), device='cuda:0')
    print("Allocated a tensor on GPU.")

def restart_script():
    print("Restarting the script...")
    os.execv(sys.executable, ['python'] + sys.argv)

if __name__ == "__main__":
    print_vram_usage()
    allocate_vram()
    print_vram_usage()  # Uncomment to check VRAM after allocation if needed
    restart_script()
```

```py
import pycuda.driver as cuda
import pycuda.autoinit  # Automatically initializes CUDA
import os
import sys

def print_vram_usage():
    print("VRAM usage:")
    os.system('nvidia-smi')

def allocate_vram():
    # Allocate 1GB of VRAM
    size = 1024 * 1024 * 1024  # 1 Gigabyte in bytes
    gpu_memory = cuda.mem_alloc(size)
    print(f"Allocated {size} bytes on GPU.")

def restart_script():
    print("Restarting the script...")
    os.execv(sys.executable, ['python'] + sys.argv)

if __name__ == "__main__":
    print_vram_usage()  # Show VRAM usage before allocation
    allocate_vram()
    print_vram_usage()  # Show VRAM usage after allocation
    restart_script()
```

**Comment by ltdrdata** [comment]
Oh, it seems like a solution that completely terminates the process and starts anew is needed for this issue.
It doesn't seem feasible to tackle this solely within ComfyUI-Manager; I'll need to collaborate with others to explore solutions.

**Comment by liusida** [comment]
Yeah. Cool. Please let me know if there's any progress. My current workaround is to restart my docker container every morning. :)

**Comment by ltdrdata** [comment]
FYI, Although it is currently in the early stages, launching through `comfy-cli` supports a perfect reboot feature.

https://github.com/Comfy-Org/comfy-cli#launch-comfyui

**Comment by liusida** [comment]
Hi @ltdrdata. I took another dive into the 384 MiB of VRAM that CUDA allocates for itself by default. There's no way to free these 384 MiB unless kill CUDA entirely. Also, it seems that `torch.cuda.empty_cache()` cannot free all the VRAM allocated by CUDA. Eventually, ChatGPT suggests using multiprocessing to completely clear the VRAM used by CUDA. Here is the Python demo that demonstrates this behavior on Ubuntu:

```py
from multiprocessing import Process
import torch
import gc

def run_your_code():
    print(torch.cuda.memory_summary())
    print("Now, nvidia-smi shows usage = 0 MB")

    m = torch.cuda.mem_get_info(0)
    print("Now, nvidia-smi shows usage = 384 MB")

    tensor = torch.rand((1, 1), device='cuda')
    print("Now, nvidia-smi shows usage = 448 MB")
    
    del tensor
    gc.collect()
    torch.cuda.empty_cache()
    print("Now, nvidia-smi shows usage = 446 MB")

if __name__ == '__main__':
    p = Process(target=run_your_code)
    p.start()
    p.join()
    print("Now, nvidia-smi shows usage = 0 MB")
```

**Comment by liusida** [comment]
ComfyUI reboot properly after I switch to `comfy-cli`

the only issue is to create a virtual python environment for it to properly reboot:
https://github.com/yoland68/comfy-cli/issues/83

**Comment by psc0606** [comment]
same issue
```python
import gc
import os
import sys
import time

import torch


xxs = []


def alloc_gpu():
    for i in range(20):
        x = torch.zeros((1, 1024, 1024), dtype=torch.float32, device='cuda')
        print(x.shape)
        xxs.append(torch.zeros((1, 1024, 1024), dtype=torch.float32, device='cuda'))
        time.sleep(0.2)


def main():
    alloc_gpu()
    sys_argv = sys.argv.copy()
    if sys_argv[0].endswith("__main__.py"):  # this is a python module
        module_name = os.path.basename(os.path.dirname(sys_argv[0]))
        cmds = [sys.executable, '-m', module_name] + sys_argv[1:]
    else:
        cmds = [sys.executable] + sys_argv
    print(f"Command: {cmds}", flush=True)
    print("allocated: ", torch.cuda.memory_allocated() / 1024 / 1024, "M", flush=True)
    print("reserved: ", torch.cuda.memory_reserved() / 1024 / 1024, "M", flush=True)
    global xxs
    xxs = []
    gc.collect()
    torch.cuda.empty_cache()
    print("allocated: ", torch.cuda.memory_allocated() / 1024 / 1024, "M", flush=True)
    print("reserved: ", torch.cuda.memory_reserved() / 1024 / 1024, "M", flush=True)
    return os.execv(sys.executable, cmds)


if __name__ == "__main__":
    main()

```
