### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by derpmagician** [Comfy-Org/ComfyUI-Manager#578]
I can use the manager with no problem but got that message instead of the updates when i open the manager
![chrome_5k0CB4T5B6](https://github.com/ltdrdata/ComfyUI-Manager/assets/5251673/1722ea2f-a097-4767-aec6-a0de9cf0fb0c)

**Comment by ltdrdata** [comment]
It seems that you are experiencing network issue.
See the terminal log.

**Comment by derpmagician** [comment]
i updated the manager today and got resolved
