### ISSUE TITLE
Extension request: Latent Interposer

### ISSUE THREAD

**Issue by city96** [Comfy-Org/ComfyUI-Manager#58]
Hi. Some people asked me about adding my [latent interposer](https://github.com/city96/SD-Latent-Interposer) extension to the manager. It does what the name implies, converting XL latents to V1 (or the other way around).

For my repo, both cloning it and copying `comfy_latent_interposer.py` should work. Not sure which one is preferred, I guess cloning might make updates easier?

Anyway, here's the JSON entires, assuming I read your code right (haven't tested it since I still manually manage my extensions...).

```json
        {
            "author": "city96",
            "title": "Latent-Interposer",
            "reference": "https://github.com/city96/SD-Latent-Interposer",
            "files": [
                "https://github.com/city96/SD-Latent-Interposer"
            ],
            "install_type": "git-clone",
            "description": "Custom node to convert the lantents between SDXL and SD v1.5 directly without the VAE decoding/encoding step."
	},
```
```json
    "https://github.com/city96/SD-Latent-Interposer": [
        "LatentInterposer",
    ],
```

LMK if you need me to do anything like adding a `requirements.txt`, etc.

**Comment by ltdrdata** [comment]
I though that I'd added already.. Maybe I didn't pushed it.
Just it is updated.
