### ISSUE TITLE
NO MANAGER BUTTON   botocore.exceptions.NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by Amit30swgoh** [Comfy-Org/ComfyUI-Manager#586]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/42430868/d739e5ab-e1aa-442b-a851-97570c237aa2)
botocore.exceptions.NoCredentialsError: Unable to locate credentials

please help

**Comment by ltdrdata** [comment]
Remove the `ComfyUI-Bedrock` custom node.

**Comment by Amit30swgoh** [comment]
> Remove the `ComfyUI-Bedrock` custom node.

Trying now ty so much for quick respond and for all that you do Dr.! we love you
