### ISSUE TITLE
Manager uses directory names in custom_nodes to check for installed items

### ISSUE THREAD

**Issue by wyrde** [Comfy-Org/ComfyUI-Manager#6]
Since I remove the "comfy" from most node folders, the manager doesn't realize I have these already.

```console
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          5/6/2023  11:42 AM                ADV_CLIP_emb
d-----          5/7/2023   9:26 AM                Cutoff
d-----          5/9/2023  10:38 AM                Impact-Pack
d-----          5/7/2023   9:26 AM                Manager
d-----          5/6/2023  11:42 AM                Noise
d-----          5/6/2023  12:21 AM                Saveaswebp
d-----          5/7/2023   9:26 AM                TiledKSampler
d-----          5/5/2023   2:53 PM                __pycache__
-a----          4/8/2023   7:38 PM           3952 example_node.py.example
-a----          5/5/2023   2:42 PM           1409 sampler_tonemap.py
```

Not a big deal since most users won't do this. But some thoughts for future improvement:
* diving into the folders and checking file names.
* a checkbox in the manager UI so users can indicate they have a node installed in a non-standard way. The manger can then ignore those nodes.

**Comment by ltdrdata** [comment]
A certain identifying feature is required by the manager tool, but it is currently not available. Improvement in this aspect may be possible once standard specifications are determined.
