### ISSUE TITLE
ComfyUI manager options never open

### ISSUE THREAD

**Issue by zono50** [Comfy-Org/ComfyUI-Manager#601]
When I click custom nodes, it gives me the following output - 
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/8764705/b8d2e9f4-4671-4b23-93b5-643b0f6d126b)

Also getting the following error - Exception in thread Thread-1 (<lambda>):
Traceback (most recent call last):
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1615, in <lambda>
    threading.Thread(target=lambda: asyncio.run(default_cache_update())).start()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1612, in default_cache_update
    await asyncio.gather(a, b, c, d)
  File "/home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 1600, in get_cache
    json_obj = await core.get_data(uri, True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/glob/manager_core.py", line 570, in get_data
    async with session.get(uri) as resp:
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/home/zono50/anaconda3/envs/comfy/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> 
FETCH DATA from: /home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/custom-node-list.json
[ComfyUI-Manager] Due to a network error, switching to local mode.
=> model-list.json
=> 
FETCH DATA from: /home/zono50/Applications/ComfyUI/custom_nodes/ComfyUI-Manager/model-list.json

I've already deleted comfyui-manager and reinstalled it. Also tried in multiple browsers. I can't seem to install custom nodes or install models, and don't know why.

**Comment by ltdrdata** [comment]
[test.py.txt](https://github.com/ltdrdata/ComfyUI-Manager/files/15077915/test.py.txt)

Download attached file and rename to `test.py`
And execute `python test.py`

What is displayed?

**Comment by zono50** [comment]
It worked, it just took a while to open.

**Comment by zono50** [comment]
When i run python test.py in the comfyui conda environment, nothing happens, or atleast i don't see any output

I did finally get some output but it was a timeout message. What can I do to resolve this issue? Evertying else on my network is blazing fast

**Comment by ltdrdata** [comment]
> When i run python test.py in the comfyui conda environment, nothing happens, or atleast i don't see any output
> 
> I did finally get some output but it was a timeout message. What can I do to resolve this issue? Evertying else on my network is blazing fast

Are you saying that not even `[method1] ok` appeared? This is a bit problematic. It means that even a very basic Python web API is not working. I wonder if it might be blocked by a firewall.

If the firewall is applied selectively depending on the application, it is entirely possible that this could happen.

**Comment by zono50** [comment]
Yeah idk my manjaro firewall is disabled and i did a fresh install of pfsense but the firewall is allowing all traffic except for a few ipv6 requests

**Comment by zono50** [comment]
if i'm the only one having this issue, than i'll try a clean install and see what happens

**Comment by LukasM937** [comment]
I have a similar issue..
when starting it seems it loaded correctly:

```
Import times for custom nodes:
   0.0 seconds: <user>/Developer/Github/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: <user>/Developer/Github/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds (IMPORT FAILED): /Users/lmuehrke/Developer/Github/ComfyUI/custom_nodes/test.py
   1.1 seconds: <user>/Developer/Github/ComfyUI/custom_nodes/was-node-suite-comfyui
   2.0 seconds (IMPORT FAILED): /Users/lmuehrke/Developer/Github/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
```

but even after multiple restarts, (page wise and from comfyUI) there is no "management"-button on the UI panel.
The test.py, that was mentioned above returns `[method1] ok` and `[method2] ok`.

**Comment by ltdrdata** [comment]
> but even after multiple restarts, (page wise and from comfyUI) there is no "management"-button on the UI panel.
> The test.py, that was mentioned above returns `[method1] ok` and `[method2] ok`.

What is your full log?

**Comment by LukasM937** [comment]
> > but even after multiple restarts, (page wise and from comfyUI) there is no "management"-button on the UI panel.
> > The test.py, that was mentioned above returns `[method1] ok` and `[method2] ok`.
> 
> What is your full log?

while cleaning the log I saw that there was an error that ComfyUI needs to be updated to use the Comfy UI manager
So thank you!
