### ISSUE TITLE
An error is reported when restart

### ISSUE THREAD

**Issue by zpengcom** [Comfy-Org/ComfyUI-Manager#608]
I recently switched to a new version of comfyui, and when I click restart from the ComfyUI-Manager admin interface I get the following error problem：

.\python_embeded\python.exe
turn into
C:\Users\pengi\AppData\Roaming\Python\Python311\..   ??

`
I:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-04-24 15:17:25.041725
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: I:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: I:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.2 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16375 MB, total RAM 48993 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4080 SUPER
[Crystools INFO] NVIDIA Driver: 552.22
### ComfyUI Revision: 2121 [831511a1] | Released on '2024-04-09'
['I:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
OpenPose Editor: Loaded
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> DeepTranslatorNode [Loading]
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###

[rgthree] Loaded 37 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

Import times for custom nodes:
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Sidebar
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.2 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   1.9 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-ollama
   2.8 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   5.7 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

Restarting... [Legacy Mode]

I:\AI\ComfyUI_windows_portable>pause
Please press any key to continue. . . ** ComfyUI startup time: 2024-04-24 15:17:46.698921
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: I:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: I:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.3 seconds: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "I:\AI\ComfyUI_windows_portable\ComfyUI\main.py", line 76, in <module>
    import execution
  File "I:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "I:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "I:\AI\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "I:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "I:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "I:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pengi\AppData\Roaming\Python\Python311\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "C:\Users\pengi\AppData\Roaming\Python\Python311\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
`

**Comment by ltdrdata** [comment]
That's weired

```
** Python executable: I:\AI\ComfyUI_windows_portable\python_embeded\python.exe
```

This is pointing right python executable.
Anyway you'd better uninstall torch package from system python.

**Comment by ltdrdata** [comment]
Can you test with this code?

Insert this code to `ComfyUI-Manager/prestartup_script.py`.

```
import sys

for path in sys.path:
    print(path)
```

**Comment by zpengcom** [comment]
> Can you test with this code?你能用这段代码进行测试吗？
> 
> Insert this code to `ComfyUI-Manager/prestartup_script.py`.将此代码插入 `ComfyUI-Manager/prestartup_script.py` 。
> 
> ```
> import sys
> 
> for path in sys.path:
>     print(path)
> ```

I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager>prestartup_script.py
** ComfyUI startup time: 2024-04-24 17:46:09.516431
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: C:\Program Files\Python311\python.exe
** Log path: I:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\comfyui.log

**Comment by zpengcom** [comment]
I deleted python under %USERPROFILE%\AppData\Roaming and then it was normal. 
My python system environment is in the C:\Program Files\Python311 directory;
I don’t know how python under %USERPROFILE%\AppData\Roaming is installed, and I don’t know why it affects ComfyUI-Manager.

**Comment by ltdrdata** [comment]
> I deleted python under %USERPROFILE%\AppData\Roaming and then it was normal. My python system environment is in the C:\Program Files\Python311 directory; I don’t know how python under %USERPROFILE%\AppData\Roaming is installed, and I don’t know why it affects ComfyUI-Manager.

It may have been installed along with another program previously.
There might be something in the restart mechanism causing the Python environment to behave abnormally.
