### ISSUE TITLE
Feature Request: Node Search

### ISSUE THREAD

**Issue by Suzie1** [Comfy-Org/ComfyUI-Manager#61]
Feature: Ability to search packages to find nodes where the node name contains the search string.

Example:
A search using 'Lucy' returns a list of node names that include this string and the associated packages.

Result:
Node | Author | Package Name
Image Lucy Sharpen | WASasquatch | WAS Node Suite

kind regards
Suzie

**Comment by ltdrdata** [comment]
I've been thinking about implementing this feature for a while now, but it's been continually postponed due to other development tasks.

**Comment by ltdrdata** [comment]
Now you can search nodes from here:
https://ltdrdata.github.io/
