### ISSUE TITLE
Restart fails if Python executable path contains blanks

### ISSUE THREAD

**Issue by DukeSniper** [Comfy-Org/ComfyUI-Manager#620]
Windows installation, System wide Python312 executable is at "C:\Program Files\Python312\python.exe"

Error message on clicking Restart ist

`C:\Program: can't open file 'C:\\stable\\ComfyUI\\Files\\Python312\\python.exe': [Errno 2] No such file or directory`

**Comment by DukeSniper** [comment]
#621 fixes it for me

**Comment by ltdrdata** [comment]
> #621 fixes it for me 

I'll merge it after test on linux environment.
