### ISSUE TITLE
Please add my project to your DB because it will not work on Chinese platform due to character encoding.

### ISSUE THREAD

**Issue by Nestorchik** [Comfy-Org/ComfyUI-Manager#627]
{
            "author": "NStor",
            "title": "ComfyUI-RUS localization",
            "reference": "https://github.com/Nestorchik/NStor-ComfyUI-Translation",
            "install_type": "git-clone",
            "description": "Russian localization of ComfyUI, ComafyUI-Manager & more..."
        },

**Comment by ltdrdata** [comment]
This is added.
