### ISSUE TITLE
prestartup_script.py fails on windows when running without Admin privilege

### ISSUE THREAD

**Issue by DukeSniper** [Comfy-Org/ComfyUI-Manager#636]
```shell
`C:\stable\ComfyUI>python main.py

## ComfyUI-Manager: installing dependencies. (GitPython)
ERROR: Could not install packages due to an OSError: [WinError 5] Access denied: 'C:\\Program Files\\Python312\\Lib\\site-packages\\wrapt'
Consider using the `--user` option or check the permissions.

Failed to execute startup-script: C:\stable\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Command '['C:\\Program Files\\Python312\\python.exe', '-s', '-m', 'pip', 'install', '-r', 'C:\\stable\\ComfyUI\\custom_nodes\\ComfyUI-Manager\\requirements.txt']' returned non-zero exit status 1.
```

From what I can see in the code and gathered from [check_output documentation](https://docs.python.org/3/library/subprocess.html#subprocess.check_output), it raises an exception that the code fails to catch. Currently working on a fix in my fork, will submit PR again when done. Already managed to catch the initial exception due to missing permissions, but there's still an issue with the `import git` when there's no actual git client installed on the system

**Comment by ltdrdata** [comment]
Thank you for the patch.
