### ISSUE TITLE
manager button is disappeared

### ISSUE THREAD

**Issue by U-Smiles** [Comfy-Org/ComfyUI-Manager#646]
related question #345 #349 
![issues](https://github.com/ltdrdata/ComfyUI-Manager/assets/105765048/0a36a524-093c-4c0b-abac-695d1c80cfb3)

I saw it may be caused by the low version so run the `C:\ComfyUI_windows\update`

![Snipaste_2024-05-06_11-05-05](https://github.com/ltdrdata/ComfyUI-Manager/assets/105765048/9fc3646c-fad1-45cd-8d93-688ccb552bff)
---
after it shows
![Snipaste_2024-05-06_11-05-53](https://github.com/ltdrdata/ComfyUI-Manager/assets/105765048/efe0cb57-486c-4ff6-9ca6-70f0b12f88b6)

then open comfyui , still can't see manager button
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/105765048/aaf97e26-7cf3-44b5-a1b9-0a18ee6b7f70)

**Comment by ltdrdata** [comment]
I'm not sure why, but you've installed ComfyUI additionally within custom_nodes. Delete the `ComfyUI/custom_nodes/ComfyUI` path.

**Comment by U-Smiles** [comment]
ok fine, finally i figured out this issue <how to make manager button work>

1. delete everything in  `C:\ComfyUI_windows\ComfyUI\custom_nodes` except `example_node.py.example`
2. if u use `git clone`&`cmd` installed in `custom_nodes`  and run comfyui manager button is dissapear , u may try download the `Manager zip` from github and unpack it in`custom_nodes`
----
good luck~ thank author
