### ISSUE TITLE
Security Issue: when in multiple users, someone hijack my machine from PIP

### ISSUE THREAD

**Issue by MorrisLu-Taipei** [Comfy-Org/ComfyUI-Manager#668]
**Please help to provide admin login / password**
Now, my workaround solution is REMOVE ComfyUI-Manger, when provide server url to my students.

this is real case,
I am teacher, providing my comfyui server url for our students.

but someone install lolminer into our machine, see picture.
<img width="960" alt="Clipboard01" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/22585297/bbfd77c6-8c1e-4403-a0af-5a9051519d91">

**Comment by ltdrdata** [comment]
Can you send me the `comfyui.log` files?

In a system like yours that is open to the general public, it is not recommended to use ComfyUI-Manager.
I should patch the system to allow for an option that disables the functionality related to custom node installations.

**Comment by ltdrdata** [comment]
You can disable unsecure features.
set   `disable_unsecure_features = True` in `config.ini`

https://github.com/ltdrdata/ComfyUI-Manager#troubleshooting

**Comment by ltdrdata** [comment]
Security feature is updated.
https://github.com/ltdrdata/ComfyUI-Manager#security-policy
