### ISSUE TITLE
[FEATURE] When loading "Load Checkpoint" nodes, make Comfy go search for the closest model name, and make it search sub directories

### ISSUE THREAD

**Issue by StableInfo** [Comfy-Org/ComfyUI-Manager#67]
Hello,
I have my SDXL base inside a directory called "/sdxl/.." Whenever I load an external flow I had to manually select the correct model, 
furthermore, whenever the model name used has been slightly changed, the flow needs intervention from you aswell. This Applies to LORAS especially or embeddings and such.
For example: add_detail or add_detailXL or adddetail, there must be a way to let comfy go find the closest name to the one being loaded (when loading a flow) IF that name does NOT exist already.

Does tat make sens? 
Thx

**Comment by ltdrdata** [comment]
This request should be posted to ComfyUI instead of here.

https://github.com/comfyanonymous/ComfyUI

**Comment by StableInfo** [comment]
Sorry, it was a mistake. You are right.
