### ISSUE TITLE
Fix \ Uninstall failed 

### ISSUE THREAD

**Issue by razvanab** [Comfy-Org/ComfyUI-Manager#677]
I get Uninstall \ Fix failed after the last update.

**Comment by ltdrdata** [comment]
goto `custom_nodes/ComfyUI-Manager` in cmd and execute `git pull`

https://github.com/ltdrdata/ComfyUI-Manager/issues/673

**Comment by razvanab** [comment]
I tried that too.
Nevermind, I had to delete and reinstall ComfyUI-Manager. If you have the same problem, it would be worth trying the same.

**Comment by ltdrdata** [comment]
> I tried that too. Nevermind, I had to delete and reinstall ComfyUI-Manager. If you have the same problem, it would be worth trying the same.

Update again. I just fixed one more time.

**Comment by ltdrdata** [comment]
wait...

**Comment by ltdrdata** [comment]
now it is fixed.

**Comment by razvanab** [comment]
It is working now. 
Thank you
