### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by bixianzai** [Comfy-Org/ComfyUI-Manager#685]
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> DeepTranslatorNode [Loading]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 444, in select
RuntimeError: <_overlapped.Overlapped object at 0x000001E8F3C8DEF0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 444, in select
RuntimeError: <_overlapped.Overlapped object at 0x000001E8F3C8DBF0> still has pending operation at deallocation, the process may crash
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_windows\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: E:\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.4 seconds: E:\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Manager
   5.5 seconds: E:\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Starting server

**Comment by ltdrdata** [comment]
See troubleshooting section
https://github.com/ltdrdata/ComfyUI-Manager#troubleshooting

You need to set `windows_selector_event_loop_policy`
