### ISSUE TITLE
 [HELP with __init__.py] I have the problem with the following Custom Nodes, which when I want to install manually, I get an error #3498 

### ISSUE THREAD

**Issue by metahades18892** [Comfy-Org/ComfyUI-Manager#687]
I have the problem with the following Custom Nodes, which when I want to install manually, I get an error:

- Clip-interrogator-ext

- ComfyUI-AnimateDiff-Evolved-main

- distill2

- LAMA

_______________________________________________________________

Total VRAM 6144 MB, total RAM 16334 MB

Set vram state to: NORMAL_VRAM

Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync

VAE dtype: torch.float32

Using pytorch cross attention

Traceback (most recent call last):

File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI[nodes.py](https://nodes.py/)", line 1879, in load_custom_node

module_spec.loader.exec_module(module)

File "", line 936, in exec_module

File "", line 1073, in get_code

File "", line 1130, in get_data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip-interrogator-ext\init.py'

Cannot import C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip-interrogator-ext module for custom nodes: [Errno 2] No such file or directory: 'C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip-interrogator-ext\init.py'

Traceback (most recent call last):

File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI[nodes.py](https://nodes.py/)", line 1879, in load_custom_node

module_spec.loader.exec_module(module)

File "", line 936, in exec_module

File "", line 1073, in get_code

File "", line 1130, in get_data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-main\init.py'

Cannot import C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-main module for custom nodes: [Errno 2] No such file or directory: 'C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-main\init.py'

Adding C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path

Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

Loaded Efficiency nodes from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui

Loaded ControlNetPreprocessors nodes from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux

Loaded AdvancedControlNet nodes from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet

Loaded AnimateDiff from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py

Could not find IPAdapter nodes

Loaded VideoHelperSuite from C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite

Could not load ImpactPack nodes Could not find ImpactPack nodes

Total VRAM 6144 MB, total RAM 16334 MB

Set vram state to: NORMAL_VRAM

Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync

VAE dtype: torch.float32
Loading: ComfyUI-Manager (V2.34)
ComfyUI Revision: 2186 [https://github.com/comfyanonymous/ComfyUI/commit/46daf0a9a7c02e7652e60f3a7af898e2f6594c2e] | Released on '2024-05-16'

#fix sys.stdout.isatty

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Mixlab Nodes: Loaded

LaMaInpainting.available True

ClipInterrogator.available True

PromptGenerate.available True

ChinesePrompt.available True

RembgNode_.available True

Comfyroll Studio v1.76 : 175 Nodes Loaded

** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md

** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki

Traceback (most recent call last):

File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI[nodes.py](https://nodes.py/)", line 1879, in load_custom_node

module_spec.loader.exec_module(module)

File "", line 936, in exec_module

File "", line 1073, in get_code

File "", line 1130, in get_data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\distill2\init.py'

Cannot import C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\distill2 module for custom nodes: [Errno 2] No such file or directory: 'C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\distill2\init.py'

Traceback (most recent call last):

File "C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI[nodes.py](https://nodes.py/)", line 1879, in load_custom_node

module_spec.loader.exec_module(module)

File "", line 936, in exec_module

File "", line 1073, in get_code

File "", line 1130, in get_data

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\LAMA\init.py'

**Comment by ltdrdata** [comment]
Install ComfyUI to  `C:\ComfyUI_windows_portable` 
instead  `C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable` 

Windows cannot handle long path.

Due to the issue of not handling long paths, your custom node files are likely already corrupted, so simply moving them will not suffice, and a reinstallation is required.

**Comment by metahades18892** [comment]
> Install ComfyUI to `C:\ComfyUI_windows_portable` instead `C:\Users\kevin\Desktop\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable`
> 
> Windows cannot handle long path.
> 
> Due to the issue of not handling long paths, your custom node files are likely already corrupted, so simply moving them will not suffice, and a reinstallation is required.

SOLVED!
