### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by metahades18892** [Comfy-Org/ComfyUI-Manager#690]
hello, solution for this?

  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\motion_module_ad.py", line 1112, in forward
    x = x + self.pe[:, : x.size(1)]
        ^~~~~~~
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by ltdrdata** [comment]
This issue is not related to ComfyUI-Manager.
