### ISSUE TITLE
Update node pack description for Comfyroll Custom Nodes

### ISSUE THREAD

**Issue by Suzie1** [Comfy-Org/ComfyUI-Manager#70]
Please can you update the decsription for ComfyUI_Comfyroll_CustomNodes to:

Custom nodes for SDXL and SD1.5 including Multi-ControlNet, LoRA, Aspect Ratio, Process Switches, and many more nodes.

The old description doesn't really apply anymore because we make nodes for more than just our templates.
thanks Akatsuzi

**Comment by ltdrdata** [comment]
I'd updated description.

**Comment by Suzie1** [comment]
Thank you!
