### ISSUE TITLE
There was a small problem building the component

### ISSUE THREAD

**Issue by LAOGOU-666** [Comfy-Org/ComfyUI-Manager#709]
![2222222222](https://github.com/ltdrdata/ComfyUI-Manager/assets/164337292/5546342a-f305-421c-a81b-3c1edfbf567e)
When I built the component and opened it, I found that all the values ​​​​of the component were restored to the default. Can every value be the same as the original when it is called up like a node preset?

**Comment by ltdrdata** [comment]
This is a limitation of group node.
I need to do additional work to handle this issue.

**Comment by LAOGOU-666** [comment]
I'm sorry for causing you any trouble.
