### ISSUE TITLE
Install multiple extension

### ISSUE THREAD

**Issue by razvanab** [Comfy-Org/ComfyUI-Manager#71]
Installing extensions one by one is time consuming. Let us choose multiple extensions to install and update.
![Screenshot 2023-08-18 005327](https://github.com/ltdrdata/ComfyUI-Manager/assets/2854730/d0c34914-f080-4108-b264-4276436dce14)

**Comment by ltdrdata** [comment]
I have plan for that.

**Comment by ltdrdata** [comment]
This is implemented.

**Comment by razvanab** [comment]
Great Thanks!! :D
