### ISSUE TITLE
When loading the graph, the following node types were not found

### ISSUE THREAD

**Issue by metahades18892** [Comfy-Org/ComfyUI-Manager#712]
I installed Stylegan, but when I click on Install Missing Custom Nodes or Install Custom Nodes, the missing nodes do not appear

![zxczxczxczxcxc](https://github.com/ltdrdata/ComfyUI-Manager/assets/163777886/74bb6488-674f-405b-a07d-33fff1851641)

**Comment by ltdrdata** [comment]
Select `dev` channel in ComfyUI-Manager. 
Then you can install through missing nodes menu.

Don't forget to back to `default` channel after then.
