### ISSUE TITLE
Model search by filename

### ISSUE THREAD

**Issue by imperator-maximus** [Comfy-Org/ComfyUI-Manager#713]
Hello,

When entering the full file name of a model into the search input, no results are displayed.

Example:
t2i-adapter-depth-midas-sdxl-1.0.fp16.safetensors

However, searching for a partial name works correctly as it searches only within the "Name" field.

Screenshot:
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/4406586/da43c69b-94d3-4f69-bb8f-bdc823f76e70)

Suggested Improvement
It would be more effective if the search function queried both the "Name" and "File Type" fields. This way, entering the full file name or any part of it would yield accurate results.

Thank you for considering this enhancement!

**Comment by ltdrdata** [comment]
This is fixed.
