### ISSUE TITLE
How to blacklist/ignore certain packages

### ISSUE THREAD

**Issue by thjan** [Comfy-Org/ComfyUI-Manager#718]
Hi, 
 I am using the `comfy-cli` to install my workflow dependencies with `comfy node install-deps --workflow <myworkflow.json>` which worked perfectly until this morning. It seems that during one of the recent db updates, a node named `ComfyUI_MaraScott_Nodes` appeared which declares many (many) nodes. A bunch of these nodes are shipped as included third parties from other node packages. 

What I mean by that is that in `ComfyUI_MaraScott_Nodes/py/vendor` the following packages are included: 
 ```
ComfyUI_Impact_Pack
ComfyUI_LayerStyle
ComfyUI_tinyterraNodes
mikey_nodes
was_node_suite_comfyui
```

These packages are also available to be downloaded by the manager itself and present in the `extension-node-map.json` file. This creates a situation where some node names are duplicated between several packages: Text Concatenate is now defined by was_node_suite AND ComfyUI_MaraScott_Nodes 

Is there a way to either specify a preference, blacklist, whitelist or any kind of mechanism that could allow going for the package I want and not the first in the list providing the custom node I need ?

**Comment by ltdrdata** [comment]
That is a fault of scanner script.
It is fixed.
