### ISSUE TITLE
求救求救，我更新了管理器后，结果我的很多插件直接失效了，怎么安装都报错，然后我删掉管理器也是这样

### ISSUE THREAD

**Issue by 52Hz-p** [Comfy-Org/ComfyUI-Manager#721]
我更新了管理器后，结果我的很多插件直接失效了，怎么安装都报错，然后我删掉管理器也是这样

**Comment by ltdrdata** [comment]
If there's no information, there's nothing I can do to help.

**Comment by 52Hz-p** [comment]
> 如果没有信息，我就无能为力。

我解决了，我发现当我更新了最新的管理器，在插件目录下用pig更新的，然后他会把我很多插件的依赖环境全部卸载掉了，并且还会卸掉一个spandrel模块。我手动把所有插件重新安装了就好了，
