### ISSUE TITLE
ComfyUI TAESD Preview speedup seems to break ComfyUI Manager integrated Latent preview

### ISSUE THREAD

**Issue by DukeSniper** [Comfy-Org/ComfyUI-Manager#723]
[This ComfyUI change](https://github.com/comfyanonymous/ComfyUI/commit/58c9838274f53c6aa8912992db9f73e9a0721227) seems to break ComfyUI Mangager integrated Latent preview. Running a KSampler with that patch applied gives a nothing but a white box in the KSampler preview (but everything else works), reverting only that commit works as expected. Did remove all other custom nodes to make sure it's actually a Manager issue

**Comment by ltdrdata** [comment]
Are you saying that when you remove the ComfyUI-Manager and run `python main.py --preview-method=taesd`, there are no issues?

ComfyUI-Manager does not include a latenet preview. It only changes the settings of ComfyUI.

What is your GPU?

**Comment by DukeSniper** [comment]
Let's file this under "freak coincidence". I've re-applied the ComfyUI patch, restored ComfyUI Manager into my setup and - as I expected - the preview broke again. However, after accessing the manager's menu once and setting preview to `None` and then back to `TAESD` again, it started working normally again. Can't even reproduce the white preview anymore. I'll close here

**Comment by ltdrdata** [comment]
> Let's file this under "freak coincidence". I've re-applied the ComfyUI patch, restored ComfyUI Manager into my setup and - as I expected - the preview broke again. However, after accessing the manager's menu once and setting preview to `None` and then back to `TAESD` again, it started working normally again. Can't even reproduce the white preview anymore. I'll close here

I understand that ComfyUI recently introduced non-blocking to improve the performance of the preview. This might be causing race conditions, which could randomly trigger issues.

**Comment by DukeSniper** [comment]
Was eventually able to reproduce, definitely not triggered by something Manager does. ComfyUI's command line flag `--deterministic` is what reliably breaks previews. And not just TAESD, but also Latent2RGB. Will open an issue with ComfyUI maintainers
