### ISSUE TITLE
Adding `About` to this repo

### ISSUE THREAD

**Issue by liusida** [Comfy-Org/ComfyUI-Manager#733]
I was making [a list of comfy-related repos](https://github.com/liusida/top-100-comfyui/tree/main?tab=readme-ov-file#top-1---5), when I discovered that the famous ComfyUI-Manager project doesn't have a description.

@ltdrdata you can add the description here (just in case you don't know ;)

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/14249458/e842d455-e477-4ef2-8a3b-948849e84779)

**Comment by ltdrdata** [comment]
Thank you. I added description.
