### ISSUE TITLE
Manager not Showing up in Menu.

### ISSUE THREAD

**Issue by jpsjoberg** [Comfy-Org/ComfyUI-Manager#739]
I have installed and reinstalled twice. Still no Manager showing up.
GET
net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

Error loading extension /extensions/ComfyUI-Manager/comfyui-manager.js TypeError: Failed to fetch

**Comment by jpsjoberg** [comment]
<img width="474" alt="Screenshot 2024-06-03 at 17 16 10" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/35001956/964d2f39-154c-46b0-a930-8fd28672641e">
<img width="308" alt="Screenshot 2024-06-03 at 17 15 56" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/35001956/3c9b3d8c-9ea2-4d2a-9018-5f030de17fb8">

**Comment by ltdrdata** [comment]
That seems network or firewall or antivirus issue. Check them.

**Comment by jpsjoberg** [comment]
It was a Permission on nginx/proxy folder
