### ISSUE TITLE
Cloning specific commit version of a node

### ISSUE THREAD

**Issue by piyushK52** [Comfy-Org/ComfyUI-Manager#741]
Are there any plans to add support for cloning a specific commit version of a node? right now it installs the latest commit present on the main branch. If you guys are busy atm I can make a small PR for it.

**Comment by ltdrdata** [comment]
I do not plan to support checking out specific commits. This will only be provided through the snapshot feature. 
(However, you can manually check out commits in the command line.)

Version control will be offered through custom nodes registered in the [comfyregistry](https://www.comfyregistry.org/).
The implementation to support `comfyregistry` is currently in progress.
