### ISSUE TITLE
managere not loading

### ISSUE THREAD

**Issue by raochinmay6** [Comfy-Org/ComfyUI-Manager#743]
[comfyui.log](https://github.com/user-attachments/files/15568869/comfyui.log)
see this log file

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only

You have to install git

**Comment by raochinmay6** [comment]
Yaah I did it and problem solve. Thanks
