### ISSUE TITLE
hi friends which !pip i should run to fix this please

### ISSUE THREAD

**Issue by Amit30swgoh** [Comfy-Org/ComfyUI-Manager#755]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/42430868/28314898-b783-4d30-a66a-d19d84e3d702)

**Comment by ltdrdata** [comment]
You cannot fix that. That should be fixed by custom node developer or another dependent pacakge developer.

**Comment by Amit30swgoh** [comment]
> You cannot fix that. That should be fixed by custom node developer or another dependent pacakge developer.

Thanks friend!
