### ISSUE TITLE
"This action is not allowed with this security level configuration."

### ISSUE THREAD

**Issue by Mozoloa** [Comfy-Org/ComfyUI-Manager#756]
I'm just trying to instal https://github.com/shadowcz007/comfyui-sound-lab via git url and get this as a popup:

`This action is not allowed with this security level configuration.`

**Comment by Mozoloa** [comment]
Apparently this is because I had set comfyui to --listen, opening it up to the network which triggers some security so people don't install extensions

**Comment by ltdrdata** [comment]
yup...
https://github.com/ltdrdata/ComfyUI-Manager#security-policy

**Comment by bdjiaoksjs1** [comment]
> 显然这是因为我将 comfyui 设置为 --listen，将其打开到网络，这会触发一些安全性，因此人们不会安装扩展

So how can we solve this problem. Please tell me the detailed steps, because I am Chinese and cannot understand the meaning of English very well, even if I open the translation

**Comment by Mozoloa** [comment]
It depends on how you launch comfyui, but you can launch it with launch arguments, one of them is --listen, which makes it available on the network. This will also block extension installation so you need to remove it

**Comment by bdjiaoksjs1** [comment]
> It depends on how you launch comfyui, but you can launch it with launch arguments, one of them is --listen, which makes it available on the network. This will also block extension installation so you need to remove it

ok I will try this ，thank u  so much

**Comment by Matthew1176** [comment]
https://www.reddit.com/r/comfyui/comments/1egv9t9/disable_comfyui_security_settings_so_i_can/

**Comment by Alvinperson** [comment]
> > 这取决于你如何启动 comfyui，但你可以使用启动参数来启动它，其中一个是 --listen，这使得它在网络上可用。这也将阻止扩展安装，因此您需要将其删除
> 
> 好的，我会试试这个，非常感谢你

怎么解决的，是删除了什么东西吗？

**Comment by 1247862674** [comment]
I'm going to use --listen, how do I need to configure it. This is my configuration
[default]
preview_method = none
badge_mode = none
git_exe = 
channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main
share_option = all
bypass_ssl = False
file_logging = True
default_ui = none
component_policy = workflow
double_click_policy = copy-all
windows_selector_event_loop_policy = False
model_download_by_agent = False
downgrade_blacklist = 
security_level = weak

**Comment by David731154103** [comment]
> > > 这取决于你如何启动 comfyui，但你可以使用启动参数来启动它，其中一个是 --listen，这使得它在网络上可用。这也将阻止扩展安装，因此您需要将其删除
> > 
> > 
> > 好的，我会试试这个，非常感谢你
> 
> 怎么解决的，是删除了什么东西吗？

这是因为安全级别太高导致的报错，可以把安全级别设置的低一些。在comfyUI\custom_nodes\comfyUI-Manager\config.ini 里把
security_level = normal改为 security_level=weak后，重启ComfyUl就可以了

**Comment by David731154103** [comment]
This error is caused by a high security level setting. You can lower the security level by opening the config.ini file in comfyUI\custom_nodes\comfyUI-Manager\, changing security_level = normal to security_level = weak. After saving the changes, restart ComfyUI to apply the settings.

**Comment by gee666** [comment]
> This error is caused by a high security level setting. You can lower the security level by opening the config.ini file in comfyUI\custom_nodes\comfyUI-Manager, changing security_level = normal to security_level = weak. After saving the changes, restart ComfyUI to apply the settings.

this helped!

**Comment by KLL535** [comment]
> This error is caused by a high security level setting. You can lower the security level by opening the config.ini file in comfyUI\custom_nodes\comfyUI-Manager, changing security_level = normal to security_level = weak. After saving the changes, restart ComfyUI to apply the settings.

In folder ComfyUI\custom_nodes\comfyui-manager NO file config.ini

![image](https://github.com/user-attachments/assets/141603c5-ded6-4041-9a39-db8fa6998f81)

**Comment by mcpeakm-0** [comment]
> In folder ComfyUI\custom_nodes\comfyui-manager NO file config.ini

It's in ComfyUI\user\default\ComfyUI-Manager

**Comment by ltdrdata** [comment]
File paths are moved to user directory since ComfyUI-Manager V3.

https://github.com/ltdrdata/ComfyUI-Manager#paths

**Comment by Axlfc** [comment]
> > In folder ComfyUI\custom_nodes\comfyui-manager NO file config.ini
> 
> It's in ComfyUI\user\default\ComfyUI-Manager

🔝

**Comment by 1310362193** [comment]
Thank you for helping us.

**Comment by DeepSeaCatz** [comment]
> It's in ComfyUI\user\default\ComfyUI-Manager

I should have kept scrolling further, was editing the one under custom nodes and didn't know why it was not working. Thanks!

**Comment by rconstantine** [comment]
When Comfy starts, I see this as the config location in the log: 

ComfyUI-Manager config path: C:\AI\ComfyUI_GUI\user\default\ComfyUI-Manager\config.ini

I changed this line:

security_level = weak 

Restarted. Still get the error when trying to install from git.

Any ideas?

I'm using ComfyUI 0.3.27, ComfyUI_desktop 0.4.32, ComfyUI_frontend 1.14.5 and ComfyUI-Manager 3.30.4

**Comment by ltdrdata** [comment]
> When Comfy starts, I see this as the config location in the log:
> 
> ComfyUI-Manager config path: C:\AI\ComfyUI_GUI\user\default\ComfyUI-Manager\config.ini
> 
> I changed this line:
> 
> security_level = weak
> 
> Restarted. Still get the error when trying to install from git.
> 
> Any ideas?
> 
> I'm using ComfyUI 0.3.27, ComfyUI_desktop 0.4.32, ComfyUI_frontend 1.14.5 and ComfyUI-Manager 3.30.4

What exactly were you trying to do when the error occurred?

**Comment by rconstantine** [comment]
Thanks for the reply. I dug in and realized that somewhere along the way - initial installation maybe? - that the directory for the models got set, but I couldn't find anything in the GUI to see where it was pointed, nor change it. I found it in a file, and it was pointed to my old portable installation. I recall that when I installed the ComfyUI app, I initially didn't want to move my models, nor duplicate them, so at installation (I think) I just pointed the GUI app to the old location. After spending time with the new app, I decided I wouldn't need the old portable app, so I moved all of the models to the new app's model folder, then got rid of the portable app. That must be when it broke and I was getting my error. In any case, I found the config file with the model path and updated it and now all is well. It might be good to have a way in the GUI to change that.

**Comment by TrillStones** [comment]
Thanks Fahd. Just to clarify ComfyUI-Manager has been updated. It actually uses one of two possible paths depending on the version:
Below V3:               ComfyUI_windows_portable\ComfyUI\custom_nodes\config.ini
V3 and above:       ComfyUI\user\default\ComfyUI-Manager\config.ini


https://www.youtube.com/watch?v=tHoi-12W3Ek

**Comment by Woisek** [comment]
<img width="987" height="787" alt="Image" src="https://github.com/user-attachments/assets/c85bd5ed-54e8-463b-95a4-9b0a865b83ee" />

Trolling... ?
Why doesn't it work?

**Comment by Qupad** [comment]
Now It's in /path/to/ComfyUI/user/__manager/config.ini

https://github.com/Comfy-Org/ComfyUI-Manager/blob/main/docs/en/v3.38-userdata-security-migration.md#finding-your-paths

**Comment by Code4SAFrankie** [comment]
Not finding any of the above paths on my local install of ComfyUI
