### ISSUE TITLE
Error occurred when executing KSampler

### ISSUE THREAD

**Issue by monscat** [Comfy-Org/ComfyUI-Manager#759]
I have an error when using Inpaint:

```
Error occurred when executing KSampler:
'NoneType' object is not subscriptable
....
```
![Screenshot 2024-06-11 011344](https://github.com/ltdrdata/ComfyUI-Manager/assets/28523517/9378f338-a4e2-47c8-8764-71aeeee4cd8f)

**Comment by ltdrdata** [comment]
This issue is not related to ComfyUI-Manager. Please contact the ComfyUI repository with your workflow.
