### ISSUE TITLE
[FEATURE REQUEST] Load/save workflow buttons

### ISSUE THREAD

**Issue by d8ahazard** [Comfy-Org/ComfyUI-Manager#76]
If at all possible, I would humbly request that you consider adding an option to save/load workflows directly from the UI...perhaps from something like a "custom_workflows" directory in the app. This way, we wouldn't need to invoke the local file browser in order to load custom workflows, and would have a handy spot to store them all.

Bonus points if you can make it auto-load a default workflow from said directory?

**Comment by ltdrdata** [comment]
It sounds like a useful feature, but the duplication of save/load-related buttons is a concern. Figuring out a UI representation that avoids confusion while ensuring ease of use will require thoughtful consideration.

**Comment by d8ahazard** [comment]
> It sounds like a useful feature, but the duplication of save/load-related buttons is a concern. Figuring out a UI representation that avoids confusion while ensuring ease of use will require thoughtful consideration.

Something as simple as "Workflow manager" would probably do it. Just like with models or configs or outputs, we have a predefined place where the .json files live, and the button invokes doing things in there. Maybe add a pane to display the workflows and some useful info, and a button to load and one to save. This way the UI isn't too cluttered, and you have a nifty new addition to the manager.

**Comment by ltdrdata** [comment]
The current Workflow Component is in an experimental stage and is an unpolished extension. The buttons themselves are attached for minimal functionality, and when it's eventually released as version 1.0, there are plans to organize it properly.

**Comment by ltdrdata** [comment]
I am planning to implement workflow management functionality. I am still figuring out how exactly to approach the management aspect. I'm not just looking to manage local workflows; I also want a feature that allows sharing.

**Comment by ltdrdata** [comment]
I recommend pythongosssss' custom scripts.
https://www.youtube.com/watch?v=QoLv5wLFkVg
