### ISSUE TITLE
Manager fails to update Comfyui

### ISSUE THREAD

**Issue by egaryw2011** [Comfy-Org/ComfyUI-Manager#761]
Not sure if this is an issue with or its me?
I am trying to update comfyui via the manager and the manager comes up with an error (I am using a Mac) "failed to update ComfyUI"
I get the following from the log:
Update ComfyUI
ComfyUI update fail: Cmd('git') failed due to: exit code(1)
  cmdline: git stash
  stderr: 'error: 'output/_output_images_will_be_put_here' is beyond a symbolic link
fatal: Unable to process path output/_output_images_will_be_put_here
Cannot save the current worktree state'

**Comment by ltdrdata** [comment]
You should not replace output folder to symbolic link.
Use `--output-directory` argument instead symbolic link.
