### ISSUE TITLE
Unable to use automatic execution

### ISSUE THREAD

**Issue by LAOGOU-666** [Comfy-Org/ComfyUI-Manager#762]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/164337292/6bcb7c00-4d88-4216-bb34-4bb190c7e1e6)
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/164337292/688f7a48-864b-48e9-a10f-317d8ad21223)
I only connected these two nodes, and then clicked on the queue. The queue could be loaded every time. It would have been cached before and would not continue to load. As a result, I could not use the automatic execution function.

**Comment by ltdrdata** [comment]
Please contact the rgthree repo.

**Comment by ltdrdata** [comment]
I misread your question.
That’s a given. It’s pointless to rerun the same workflow that yields identical results.
It would be dreadful to think about reloading the checkpoint every time you execute it.

If you are trying to replicate what you want to do using the API, you are missing the point.
When using the API, you can force a re-execution by running it once to initialize with an empty workflow and then running it again.

**Comment by LAOGOU-666** [comment]
I don’t know how to operate it, so I had to reinstall ComfyUI. It’s not a problem with RGthree and Manager. I just find it strange that when I select the function of automatically executing the queue when the status changes, the queue will also be executed when I click on the interface next to the node, and There are several executions, and sometimes there is no execution queue, but the time displayed on my queue will change. It may sound complicated, but it seems like a bug and I don't know how to solve it.
