### ISSUE TITLE
Import Failed with some custom nodes, need to "Try Fix" to run it

### ISSUE THREAD

**Issue by dreamlogic-X** [Comfy-Org/ComfyUI-Manager#763]
Hi, I'm having an issue that every time I start up ComfyUI, some of my custom nodes fail to load.

For example: ComfyUI_FizzNodes and comfy-dynamicprompts.

I run "Try Fix" in the manager and then after restarting it works.

I was advised by the developer for FizzNodes that it was an issue with the manager. 

Thanks for your help.

**Comment by ltdrdata** [comment]
`Try Fix` is a feature that forcibly sets the pip package to the one required by the node. If there are nodes with dependencies that conflict with each other, one of them will not work depending on which one you prioritize.
