### ISSUE TITLE
bumping version of installed package in requirements.txt does not automatically install the required version

### ISSUE THREAD

**Issue by ljleb** [Comfy-Org/ComfyUI-Manager#772]
I just bumped the version of the library that I use for my node pack:
https://github.com/ljleb/comfy-mecha/commit/4569a8bbeea08809800800f47e5b51183ed405f9

after trying to update the pack from before to after this commit, I see this in the console:
```
 ### ComfyUI-Impact-Pack: Check basic models
 Install: pip packages for 'D:\src\ComfyUI\custom_nodes\comfy-mecha'

[ComfyUI-Manager] Startup script completed.
#######################################################################
```

So it does not try to update the newer required version 0.0.17 of the backing lib, even though an older version 0.0.16 is currently installed.

Is this the expected behavior by manager? I would expect it to try to honor the versions specified in requirements.txt

**Comment by ltdrdata** [comment]
Need to be checked.

**Comment by ljleb** [comment]
I can confirm the new version of `is_installed` does the job! thanks for the quick work on this issue. I'm closing this as it seems to be good enough for my use case.
