### ISSUE TITLE
Latest version of the manager is installed but the interface of it still showed as the old version and in Chinese

### ISSUE THREAD

**Issue by chonglou1988** [Comfy-Org/ComfyUI-Manager#773]
<img width="1046" alt="image" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/137148372/9252057e-8fe2-45df-b59d-f6e652736736">
<img width="845" alt="image" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/137148372/a182f9b7-6e33-4b3b-b6cf-011de494c722">
The latest version of the manager is installed but the interface it still shows as the old version and in Chinese. i have try to debug it for more than 4 days. really need help! Thanks in advance!

**Comment by ltdrdata** [comment]
Chinese is not a feature of the ComfyUI-Manager.
You need to check following node:
https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation
