### ISSUE TITLE
Question about DB updates

### ISSUE THREAD

**Issue by coreyryanhanson** [Comfy-Org/ComfyUI-Manager#78]
I ended up modifying the name/links of my custom node repo before I lose the chance to do so without leaving a giant mess of broken links. Does the automatic github scanner remove any broken links or would it be necessary for me to make a pull request to ensure that there will be no duplicate nodes accidentally showing up from this change?

**Comment by ltdrdata** [comment]
If you submit a PR, I will apply the changes.

**Comment by coreyryanhanson** [comment]
Just made the request. Thanks!
