### ISSUE TITLE
`update DB` grab the wrong node author

### ISSUE THREAD

**Issue by liusida** [Comfy-Org/ComfyUI-Manager#782]
ComfyUI-Manager now can automatically grab new nodes from GitHub! What a nice helper! 
(How do you do it? I don't see any grabbing code.)

However, it made a mistake on the author of the node, this should be me:

https://github.com/ltdrdata/ComfyUI-Manager/blame/0bf650c901a45c85671de2d884ebd48119ce3afb/custom-node-list.json#L8077

Thanks~

**Comment by ltdrdata** [comment]
oh my mistake.
this is fixed.
