### ISSUE TITLE
Highlight issue

### ISSUE THREAD

**Issue by viperyl** [Comfy-Org/ComfyUI-Manager#786]
I only installed personal nodes and ComfyUI-Manger. 
During the exectuion of workflow, the loguru logger cannot correctly print it's color. and loguru logger colored correctly after removed ComfyUI-Manager.
a sample code is here
```
from loguru import logger

logger.debug(f"XXXXX")
```
the screen print with ComfyUI-Manager

<img width="1324" alt="Screenshot 2024-06-17 at 18 25 16" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/45485217/8eb836bd-b21b-46bd-b575-35b7508ac333">

the screen print without  ComfyUI-Manager
<img width="1653" alt="Screenshot 2024-06-17 at 18 26 16" src="https://github.com/ltdrdata/ComfyUI-Manager/assets/45485217/2b94d71f-3589-4c39-b722-17c4fc467c48">

**Comment by ltdrdata** [comment]
ComfyUI-Manager is intercepting stdout to capture all output logs and create a log file. That's the reason.
Some modules like tqdm have limited functionality when stdout is intercepted.
