### ISSUE TITLE
No module named 'manager_core'

### ISSUE THREAD

**Issue by davedaverave** [Comfy-Org/ComfyUI-Manager#789]
I've got ComfyUI-Manager import failed, and read this error in console .... Cannot import /notebooks/ComfyUI/custom_nodes/ComfyUI-Manager module for custom nodes: No module named 'manager_core'

My enviroment is in python 3.9 and can't get update, i don't know if that's causing the issue
Thanks

**Comment by ltdrdata** [comment]
It seems that your ComfyUI-Manager installation isn't valid. 
Remove and reinstall it.

**Comment by gadams999** [comment]
I'm getting this also when attempting to install ComfyUI-Manager into [stable diffusion webui docker](https://github.com/AbdBarho/stable-diffusion-webui-docker). Is there a specific version of ComfyUI needed for Manager?

**Comment by ctxwing** [comment]
i got just same as @gadams999 mentioned.  i am installing ans setting just as "install ComfyUI-Manager into [stable diffusion webui docker](https://github.com/AbdBarho/stable-diffusion-webui-docker). Is there a specific version of ComfyUI needed for Manager?" got bumped same error. any solution or workaround ?

**Comment by ltdrdata** [comment]
> I'm getting this also when attempting to install ComfyUI-Manager into [stable diffusion webui docker](https://github.com/AbdBarho/stable-diffusion-webui-docker). Is there a specific version of ComfyUI needed for Manager?

Unless your ComfyUI is a very old version, this typically doesn't cause problems.
What command did you use to install ComfyUI-Manager?

**Comment by freeo** [comment]
This issue was fixed for me by installing the python package `spandrel`.

This here was my initial error output, which doesn't mention it, the error was higher up in the startup log.

```
pytorch version: 2.1.1+cu121
xformers version: 0.0.23
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
Traceback (most recent call last):
  File "/mnt/S870P1/comfyui/nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/S870P1/comfyui/custom_nodes/ComfyUI-Manager/__init__.py", line 6, in <module>
    from .glob import manager_server
  File "/mnt/S870P1/comfyui/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 18, in <module>
    import manager_core as core
ModuleNotFoundError: No module named 'manager_core'

Cannot import /mnt/S870P1/comfyui/custom_nodes/ComfyUI-Manager module for custom nodes: No module named 'manager_cor
e'
```

**Comment by ltdrdata** [comment]
> This issue was fixed for me by installing the python package `spandrel`.
> 
> This here was my initial error output, which doesn't mention it, the error was higher up in the startup log.
> 
> ```
> pytorch version: 2.1.1+cu121
> xformers version: 0.0.23
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
> Traceback (most recent call last):
>   File "/mnt/S870P1/comfyui/nodes.py", line 1931, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/mnt/S870P1/comfyui/custom_nodes/ComfyUI-Manager/__init__.py", line 6, in <module>
>     from .glob import manager_server
>   File "/mnt/S870P1/comfyui/custom_nodes/ComfyUI-Manager/glob/manager_server.py", line 18, in <module>
>     import manager_core as core
> ModuleNotFoundError: No module named 'manager_core'
> 
> Cannot import /mnt/S870P1/comfyui/custom_nodes/ComfyUI-Manager module for custom nodes: No module named 'manager_cor
> e'
> ```

Because `spandrel` is a basic dependency package for ComfyUI, there should not be any issues if ComfyUI was installed or updated correctly.

I've learned about the situation where this error message occurs. Thanks

**Comment by pfmephisto** [comment]
For me, the fix was changing the import to be relative.

```
diff --git a/glob/manager_server.py b/glob/manager_server.py
index e2f8989..ecfd8a0 100644
--- a/glob/manager_server.py
+++ b/glob/manager_server.py
@@ -13,7 +13,7 @@ import shutil
 import git
 
 from server import PromptServer
-import manager_core as core
+from . import manager_core as core
 import cm_global
 
 print(f"### Loading: ComfyUI-Manager ({core.version_str})")

```
