### ISSUE TITLE
Control Lora Issue

### ISSUE THREAD

**Issue by bulutharbeli** [Comfy-Org/ComfyUI-Manager#80]
Hello i am trying to use new workflow of control lora. But it always gives error withred sections. "Install missing nodes" doesn't help.

![dgdg](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/e9267372-69c3-4c5a-9ec7-3501d12b6c0f)
![etewrt](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/392d6d5c-071a-4b81-b0c4-a3b40d538662)
![Screenshot_122](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/864115a1-84ac-4e35-86e3-f615f803bed4)

**Comment by ltdrdata** [comment]
> Hello i am trying to use new workflow of control lora. But it always gives error withred sections. "Install missing nodes" doesn't help.
> 
> ![dgdg](https://user-images.githubusercontent.com/30212464/262280849-e9267372-69c3-4c5a-9ec7-3501d12b6c0f.png) ![etewrt](https://user-images.githubusercontent.com/30212464/262280856-392d6d5c-071a-4b81-b0c4-a3b40d538662.png) ![Screenshot_122](https://user-images.githubusercontent.com/30212464/262280859-864115a1-84ac-4e35-86e3-f615f803bed4.png)

Did you changed channel other than 'default'?

**Comment by bulutharbeli** [comment]
Sorry but i did not get your question ? What do you mean by "chanel" ?

**Comment by ltdrdata** [comment]
> Sorry but i did not get your question ? What do you mean by "chanel" ?

oh... Maybe your ComfyUI-Manager version is outdated..
Update Manager and retry it.

**Comment by bulutharbeli** [comment]
> > Sorry but i did not get your question ? What do you mean by "chanel" ?
> 
> oh... Maybe your ComfyUI-Manager version is outdated.. Update Manager and retry it.

Thanks but i already updated but still the same.

**Comment by ltdrdata** [comment]
> > > Sorry but i did not get your question ? What do you mean by "chanel" ?
> > 
> > 
> > oh... Maybe your ComfyUI-Manager version is outdated.. Update Manager and retry it.
> 
> Thanks but i already updated but still the same.

No. Your version is outdated version. If your version is latest version. You can see checkbox.
(like this: https://www.youtube.com/watch?v=Sh2axf4XSqg)
I'd updated this feature several days ago.

Updates are only possible after fetching updates first. If you've done that and it still doesn't work, then the updates might not have occurred due to some error.

**Comment by bulutharbeli** [comment]
I followed exactly the same process which is given in the video. It maked a lof updates but at the end the same result. Probably i am doing something wrong but idk
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/bf249bc3-7811-4e18-9b8a-769f4c8e3889)


![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/2a1a9518-c823-4925-8ac3-5a5d14f4599d)
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/ac7efd98-2bb3-4e8e-9369-d69499435ae3)
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/44335361-433d-4215-a0c3-b43f7028e539)

**Comment by bulutharbeli** [comment]
Ok finally i fixed. I removed comfyui manager and install it from the scratch. Now it's working ! Thank you

Edit: When queue the prompt, gives me such error
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/a0add00d-ee2f-4d96-ad20-38b7cf5d38ea)

**Comment by ltdrdata** [comment]
> I followed exactly the same process which is given in the video. It maked a lof updates but at the end the same result. Probably i am doing something wrong but idk ![image](https://user-images.githubusercontent.com/30212464/262358761-bf249bc3-7811-4e18-9b8a-769f4c8e3889.png)
> 
> ![image](https://user-images.githubusercontent.com/30212464/262358169-2a1a9518-c823-4925-8ac3-5a5d14f4599d.png) ![image](https://user-images.githubusercontent.com/30212464/262358260-ac7efd98-2bb3-4e8e-9369-d69499435ae3.png) ![image](https://user-images.githubusercontent.com/30212464/262358326-44335361-433d-4215-a0c3-b43f7028e539.png)


Follow the steps below to update ComfyUI-Manager:

1. Goto manager menu
2. click: Fetch Updates
3. click: Install Custom Nodes
4. click: Install of `ComfyUI-Manager`

After the update, make sure that the ComfyUI-Manager version displays as 0.26.1 or higher.

**Comment by bulutharbeli** [comment]
Well done.  Everything is working now. Thank you

Here is final image
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/30212464/f004ecb8-c614-4fd9-96db-571c14c02794)
