### ISSUE TITLE
Not A Directory Error

### ISSUE THREAD

**Issue by myprivacygithub** [Comfy-Org/ComfyUI-Manager#803]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/125949094/8293c16e-836b-4c3f-afd9-a96709fd467c)
How to solve this?

**Comment by ltdrdata** [comment]
It seems that your python environment is invalid.
Don't you use portable version?

**Comment by myprivacygithub** [comment]
I am not using portable version, now changing environment with python 3.11. Anyway thanks.

**Comment by ltdrdata** [comment]
You should not use system python. Use portable version or venv/conda.
And the issue came from blank in directory name of the system python.

**Comment by myprivacygithub** [comment]
In the system eenvironment variable path i've added both. Is there any way to config python path for venv version of comfyui?
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/125949094/2ac8d417-d076-487e-96b1-bd122e07985b)
