### ISSUE TITLE
Trying to install things through the ComfyUI Manager all throw the error:  Bad Request

### ISSUE THREAD

**Issue by NicTanghe** [Comfy-Org/ComfyUI-Manager#816]
Hello i cant seem to install anything trough the manager ui.

Everything throws the error bad request
Logs
```sh
FETCH DATA from: /home/tanghe/tools/comfy/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
FETCH DATA from: /home/tanghe/tools/comfy/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/4245046894_model-list.json [DONE]
Install model 'diffusers/stable-diffusion-xl-1.0-inpainting-0.1 (UNET/fp16)' into '/home/tanghe/tools/comfy/ComfyUI/models/unet/xl-inpaint-0.1/diffusion_pytorch_model.fp16.safetensors'
[ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
Install model 'diffusers/stable-diffusion-xl-1.0-inpainting-0.1 (UNET/fp16)' into '/home/tanghe/tools/comfy/ComfyUI/models/unet/xl-inpaint-0.1/diffusion_pytorch_model.fp16.safetensors'
[ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
Install model 'diffusers/stable-diffusion-xl-1.0-inpainting-0.1 (UNET/fp16)' into '/home/tanghe/tools/comfy/ComfyUI/models/unet/xl-inpaint-0.1/diffusion_pytorch_model.fp16.safetensors'
[ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

EDIT seems like i just need ti install an ssl setificate somewhere ?

Also got:

0it [00:00, ?it/s]Install(git-clone) error: https://github.com/ltdrdata/ComfyUI-Impact-Pack / Cmd('git') failed due to: exit code(128)

EDIT:
the downloading models got solved by:

export SSL_CERT_FILE=$installlocation/ComfyUI/venv_comfyui/lib/python3.10/site-packages/certifi/cacert.pem

importing the nodes still fails with a weird exit code:

Download: git clone 'https://github.com/ltdrdata/ComfyUI-Inspire-Pack'
0it [00:00, ?it/s]Install(git-clone) error: https://github.com/ltdrdata/ComfyUI-Inspire-Pack / Cmd('git') failed due to: exit code(128)

OS:ROCKY 9.4

**Comment by ltdrdata** [comment]
What message is displayed when execute this?
`git clone 'https://github.com/ltdrdata/ComfyUI-Inspire-Pack'`

**Comment by NicTanghe** [comment]
I can download the packs manually without any issue.
```
❯ git clone 'https://github.com/ltdrdata/ComfyUI-Inspire-Pack'
Cloning into 'ComfyUI-Inspire-Pack'...
remote: Enumerating objects: 1171, done.
remote: Counting objects: 100% (240/240), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 1171 (delta 191), reused 186 (delta 155), pack-reused 931
Receiving objects: 100% (1171/1171), 251.83 KiB | 1.26 MiB/s, done.
Resolving deltas: 100% (852/852), done.
```

**Comment by vrie4433** [comment]
I had the sam problem. I found this on goole.
go to ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager.
Find in the ComfyUI-Manager the config.ini file
find the line: bypass_ssl = Falls
cnange in: bypass_ssl = True

and it will work

**Comment by Creat-qc** [comment]
> I had the sam problem. I found this on goole. go to ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager. Find in the ComfyUI-Manager the config.ini file find the line: bypass_ssl = Falls cnange in: bypass_ssl = True
> 
> and it will work


it helps me, thanks
but 
not falls, its false,
then restart,
