### ISSUE TITLE
The custom node cannot be installed

### ISSUE THREAD

**Issue by Franks001** [Comfy-Org/ComfyUI-Manager#82]
E:\AI\SD\ComfyUI\O\zero>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --port 8190
** ComfyUI start up time: 2023-08-22 23:05:10.429264

Prestartup times for custom nodes:
   0.0 seconds: E:\AI\SD\ComfyUI\O\zero\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 11264 MB, total RAM 32725 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/Stable-diffusion
Adding extra search path configs E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/Stable-diffusion
Adding extra search path vae E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/VAE
Adding extra search path loras E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/Lora
Adding extra search path loras E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/LyCORIS
Adding extra search path upscale_models E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/ESRGAN
Adding extra search path upscale_models E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/RealESRGAN
Adding extra search path upscale_models E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/SwinIR
Adding extra search path embeddings E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\embeddings
Adding extra search path hypernetworks E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/hypernetworks
Adding extra search path controlnet E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.2\models/ControlNet
### Loading: ComfyUI-Manager (V0.25.4)
[WARN] ComfyUI-Manager: channel_url_list is invalid format
### ComfyUI-Manager: Copy .js from 'E:\AI\SD\ComfyUI\O\zero\ComfyUI\custom_nodes\ComfyUI-Manager\js\comfyui-manager.js' to 'E:\AI\SD\ComfyUI\O\zero\ComfyUI\web\extensions\comfyui-manager'

Import times for custom nodes:
   0.3 seconds: E:\AI\SD\ComfyUI\O\zero\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.4 seconds: E:\AI\SD\ComfyUI\O\zero\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8190
FETCH DATA from: E:\AI\SD\ComfyUI\O\zero\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
FETCH DATA from: E:\AI\SD\ComfyUI\O\zero\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json
Error handling request
Traceback (most recent call last):
  File "E:\AI\SD\ComfyUI\O\zero\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "E:\AI\SD\ComfyUI\O\zero\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "E:\AI\SD\ComfyUI\O\zero\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "E:\AI\SD\ComfyUI\O\zero\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "E:\AI\SD\ComfyUI\O\zero\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 500, in fetch_customnode_list
    json_obj = await get_data(uri)
  File "E:\AI\SD\ComfyUI\O\zero\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 330, in get_data
    json_text = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 6223: illegal multibyte sequence

**Comment by ltdrdata** [comment]
This is just fixed.
