### ISSUE TITLE
The main menu button reappears

### ISSUE THREAD

**Issue by Glzchat-liang** [Comfy-Org/ComfyUI-Manager#834]
![7bb1b705de7e0a4c45c32443dd53c86a](https://github.com/ltdrdata/ComfyUI-Manager/assets/173697827/d1cfcd6d-7c20-4937-bafe-9843fc89c56c)

**Comment by ltdrdata** [comment]
That is not a feature of ComfyUI-Manager.
Report it to core repo.

And before reporting, disable all custom nodes and test it.
