### ISSUE TITLE
cm-cli: why install python packages of custom node one by one

### ISSUE THREAD

**Issue by Maslino** [Comfy-Org/ComfyUI-Manager#838]
rather than use pip install -r requirements.txt ?

**Comment by ltdrdata** [comment]
> rather than use pip install -r requirements.txt ?

If installed all at once, when pip fails to solve dependencies, it results in a complete failure.
Installing packages individually is a measure to prevent frequent failures caused by strict dependencies, which can often be resolved when installed separately.
