### ISSUE TITLE
[Feature Request] Import/Export Installed Custom Nodes

### ISSUE THREAD

**Issue by d8ahazard** [Comfy-Org/ComfyUI-Manager#84]
Sorry, not trying to overwhelm you with requests.

Another one that would really be useful is to allow import/export of custom nodes in one-shot. You've already got the methods to install various packages - if we could dump a JSON file with all the "stuff" needed to automate this re-installation process, it'd be incredibly handy in the event someone needs to re-build their environment or even just share multiple custom workflows without having to do the "install missing" for each one.

**Comment by ltdrdata** [comment]
Oh.. That is a nice idea.

**Comment by alessandroperilli** [comment]
I second this. So much needed.

**Comment by ltdrdata** [comment]
Currently, this feature is implemented in the form of a `Snapshot Manager`, and it can be managed through .json files in the snapshots directory.

**Comment by alessandroperilli** [comment]
That's great, @ltdrdata, thank you. Hopefully, in the future, will see some QoL improvements, like the capability to set a custom directory for snapshots, the import of snapshots without having to go to the file system, or the renaming of the snapshots directly from ComfyUI Manager.
