### ISSUE TITLE
[BUG] download_url function needs three params but only two passed when called in copy_install function

### ISSUE THREAD

**Issue by Maslino** [Comfy-Org/ComfyUI-Manager#848]
As the following code shows

```python
def copy_install(files, js_path_name=None):
    for url in files:
        if url.endswith("/"):
            url = url[:-1]
        try:
            if url.endswith(".py"):
                download_url(url, core.custom_nodes_path)                           # this call
            else:
                path = os.path.join(core.js_path, js_path_name) if js_path_name is not None else core.js_path
                if not os.path.exists(path):
                    os.makedirs(path)
                download_url(url, path)                                             # and this call

        except Exception as e:
            print(f"Install(copy) error: {url} / {e}", file=sys.stderr)
            return False

    print("Installation was successful.")
    return True
```

**Comment by MAkC8** [comment]
ComfyUI does not load Manager as usual. May this bug disappear Manager button ?
![Screenshot 2024-07-09 at 5 40 54 PM](https://github.com/ltdrdata/ComfyUI-Manager/assets/14121746/d0e84dba-67fc-44de-b36f-ba572ccb839e)

**Comment by ltdrdata** [comment]
I have no problem. What is your terminal log?

**Comment by MAkC8** [comment]
I using Vast.ai with docker image of "ghcr.io/ai-dock/comfyui:latest-jupyter" which install ComfyUI-Manager by default. Always it is ok , but today it's button didn't visible ...
I couldn't find the log of loading ComfyUI-Manager from server. I just have these logs from panel :
```
### Loading: ComfyUI-Manager (V2.46.1)
### ComfyUI Revision: 2129 [719fb2c8] *DETACHED | Released on '2024-04-14'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
==> /var/log/supervisor/serviceportal.log <==
INFO:     185.124.108.178:0 - "POST /ajax/processes/restart HTTP/1.1" 200 OK
INFO:     185.124.108.178:0 - "POST /ajax/logs HTTP/1.1" 200 OK
==> /var/log/supervisor/supervisor.log <==
2024-07-09 13:54:41,407 INFO success: comfyui entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
==> /var/log/supervisor/serviceportal.log <==
INFO:     ('185.124.108.178', 0) - "WebSocket /ai-dock/logtail.sh" [accepted]

```

**Comment by ltdrdata** [comment]
Why are you using old version of ComfyUI? `ComfyUI Revision: 2129 [719fb2c8] *DETACHED `
Btw, press F12 and see browser console log if your are using chrome browser.

**Comment by MAkC8** [comment]
Is there any shortcut for command to show manager window without touching button of "Manager" from right panel ?

**Comment by ltdrdata** [comment]
I confirmed that issue is the problem of the old ComfyUI version (the specific commit hash 719fb2c8).
You have to update ComfyUI.

**Comment by MAkC8** [comment]
I just run the last version right now, I thought maybe it related to new version.
this is the console log of browser for the latest version:
![Screenshot 2024-07-09 at 6 12 06 PM](https://github.com/ltdrdata/ComfyUI-Manager/assets/14121746/d7c60deb-ce31-43e3-99c6-cd92b68d768d)

**Comment by ltdrdata** [comment]
> I just run the last version right now, I thought maybe it related to new version. this is the console log of browser for the latest version: ![Screenshot 2024-07-09 at 6 12 06 PM](https://private-user-images.githubusercontent.com/14121746/346990535-d7c60deb-ce31-43e3-99c6-cd92b68d768d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzQ3NzcsIm5iZiI6MTcyMDUzNDQ3NywicGF0aCI6Ii8xNDEyMTc0Ni8zNDY5OTA1MzUtZDdjNjBkZWItY2UzMS00M2UzLTk5YzYtY2Q5MmI2OGQ3NjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE0MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYTdlMmY3YWQ1NjY4NGU4Yzg2NWEwM2U3ZTA3ZWIwNDcyZmFiMTcwZDY4MzA0ZjgyNjkwMzFiZmY1YzUwMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bimzxd7gU8EGPx-_F_ofsaWhOHoy6Gec0XPowWHo3SQ)

That issue is fixed now.

**Comment by MAkC8** [comment]
Maybe it related to ComfyUI version?

**Comment by ltdrdata** [comment]
> Maybe it related to ComfyUI version?
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/128333288/4fa40c5c-68be-40e3-bfe4-edb6f23b938a)

While ComfyUI-Manager now supports a new style menu, a backward compatibility feature was included for users of older versions of ComfyUI. However, this feature had an error, causing issues for those using older ComfyUI versions.

The problem can be resolved by either updating ComfyUI-Manager to the latest version or by updating ComfyUI itself to the most recent version.
