### ISSUE TITLE
live preview not showing batch size.

### ISSUE THREAD

**Issue by Shaistrong** [Comfy-Org/ComfyUI-Manager#85]
when doing batch size>1 it show only one out of the X amount of images in batch.

**Comment by ltdrdata** [comment]
> when doing batch size>1 it show only one out of the X amount of images in batch.

That is a restriction of ComfyUI.

**Comment by Shaistrong** [comment]
> > when doing batch size>1 it show only one out of the X amount of images in batch.
> 
> That is a restriction of ComfyUI.

damn. me and FizzleDorf figured batch size for AIT, so it would be nice to have preview for it, as well as maintain the times 2.something speed boost.
