### ISSUE TITLE
Group node components do not preserve node values

### ISSUE THREAD

**Issue by lokimckay** [Comfy-Org/ComfyUI-Manager#853]
EDIT: sorry I have just realised this is a duplicate of https://github.com/ltdrdata/ComfyUI-Manager/issues/826
Please close if desired

### Expected Behavior

Group node component values should match the values that are saved in their JSON file

### Actual Behavior

Group node component values are reset to the defaults of the inner node(s)

### Steps to Reproduce

1. Create two `Empty Latent Image` nodes
1. Change the widths of both to `1024`
1. Convert these nodes to a Group Node
1. Note that widths are `1024` as expected
1. Save the Group Node as a component
1. Clear/create a new workflow
1. Add the component node to the workflow
1. Observe that widths have been reset to `512`

### Version

```
ComfyUI: 2280[73ca78](2024-06-23)
Manager: V2.41
```

### Screenshots

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/14341953/f0f8d4a3-12cf-461a-ac01-6b154fcbe9e4)

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/14341953/c7f90c9b-9e80-416e-8132-4cd09ad81375)

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/14341953/c0d96005-3074-4f92-b6fc-b18378b73c1d)

**Comment by ltdrdata** [comment]
Currently, this is due to the characteristics of the group node. 
I am already aware of this issue and plan to address it in the future.

Same issue:
https://github.com/ltdrdata/ComfyUI-Manager/issues/826#issuecomment-2220961387
