### ISSUE TITLE
Nodes added automatically without consent - Requesting removal

### ISSUE THREAD

**Issue by Grant-CP** [Comfy-Org/ComfyUI-Manager#854]
Hi @ltdrdata it looks like my nodes at https://github.com/Grant-CP/ComfyUI-LivePortraitKJ-MPS got added through one of your commits. I did not submit a pull request and my repo was just intended to be a temporary fix to get some of Kijai's nodes working on macbooks.

As you may guess, my nodes give every single node from Kijai's repo a conflict in the manager, which is confusing for new folks.

I've worked with Kijai and their nodes are now as functional as mine for MPS, so there is no need for my nodes to exist. If it's possible to replace to "origin" of my nodes with https://github.com/kijai/ComfyUI-LivePortraitKJ that would also be helpful, but I figure that's probably not a thing. 

I was wondering if you could shed some light on how the nodes got added in the first place so I can avoid it happening by accident again. I know someone shared a workflow with my node on openart. I also got some automated pull requests from comfy-org's bots which I denied.

**Comment by ltdrdata** [comment]
Oh. It was my fault. I removed it already.
Thank you for the notice.

I am preparing delcartion method to avoid registering.

**Comment by Grant-CP** [comment]
@ltdrdata No problem! I'm looking forward to the comfy registry being more fully fleshed out.

Thanks a bunch for the fast change and all the other stuff you do!
