### ISSUE TITLE
duplicated /snapshot/get_current api request handler

### ISSUE THREAD

**Issue by Maslino** [Comfy-Org/ComfyUI-Manager#855]
In **manager_server.py**,

https://github.com/ltdrdata/ComfyUI-Manager/blob/5509734a10faec806dd315ec7896dbb401dad0ea/glob/manager_server.py#L582-L585

https://github.com/ltdrdata/ComfyUI-Manager/blob/5509734a10faec806dd315ec7896dbb401dad0ea/glob/manager_server.py#L640-L645

**Comment by ltdrdata** [comment]
oops...

**Comment by ltdrdata** [comment]
fixed.
