### ISSUE TITLE
Installed ckpts undetected if in installer 

### ISSUE THREAD

**Issue by Amsmolfish** [Comfy-Org/ComfyUI-Manager#86]
For quality of life I have moved SDXL models into a sub folder, which is a useful layout in the checkpoint loader
![Installed in subfolder](https://github.com/ltdrdata/ComfyUI-Manager/assets/115925329/ff57e8b2-10d3-4429-9343-0a18bd4f6a38)

Unfortunately, the checkpoint installer flags them as uninstalled now.
![Models not installed](https://github.com/ltdrdata/ComfyUI-Manager/assets/115925329/e0acc4a8-4293-49d5-a8d9-2295bb99e5eb)

**Comment by ltdrdata** [comment]
The manager's model resource management serves solely to assist with downloads and is restricted to specific locations. Since model names can be duplicated, unless the manager itself has designated subfolders, it does not identify user subfolders.
