### ISSUE TITLE
[Feature Request] PyTorch version used.

### ISSUE THREAD

**Issue by razvanab** [Comfy-Org/ComfyUI-Manager#868]
Some node extensions require a different version of PyTorch than the one already installed. I would like to suggest a new field in the Custom node manager that shows if a node extension requires the same or a different version of PyTorch as the one installed, or at least the version of PyTorch used by the extension. The reason being that if I install a node extension that uses a different version of PyTorch than the one that is installed, then I need to reinstall PyTorch again for comfyui to start.

**Comment by ltdrdata** [comment]
The latest version of ComfyUI-Manager prevents the reinstallation of torch and other basic requirements of ComfyUI.

**Comment by razvanab** [comment]
Good to know. Thank you.
