### ISSUE TITLE
The ComfyUI-Manager has been successfully installed, but the management and sharing buttons are not displayed.

### ISSUE THREAD

**Issue by onlingai** [Comfy-Org/ComfyUI-Manager#869]
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-15 21:33:27.921047
** Platform: Darwin
** Python version: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 21:00:12) [Clang 16.0.6 ]
** Python executable: /Users/OnLing/miniconda3/envs/onling/bin/python3
** ComfyUI Path: /Users/OnLing/ComfyUI
** Log path: /Users/OnLing/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Marigold
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/rgthree-comfy
   2.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Manager

NumExpr defaulting to 8 threads.
['/Users/OnLing/ComfyUI/custom_nodes']
### ComfyUI Revision: 2364 [7914c47d] | Released on '2024-07-14'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

<img width="545" alt="image" src="https://github.com/user-attachments/assets/28f7c586-e6c9-4111-bfd8-bf00167d0714">
<img width="536" alt="image" src="https://github.com/user-attachments/assets/0ebfdf6f-e50c-4f54-9fba-6503f4c4457a">

**Comment by ltdrdata** [comment]
Please show the list of files in the `/Users/OnLing/ComfyUI/custom_nodes` directory.

**Comment by onlingai** [comment]
Import times for custom nodes:
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/rembg-comfyui-node
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/Cup-ClipBoard
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/sdxl_utility.py
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Depth-Visualization
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Book-Tools
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-gligengui-node
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/canvas_tab
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/style_aligned_comfy
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyUI_TJ_NormalLighting
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-text-overlay
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_SimpleMath
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_TGate
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-IC-Light
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-StableDiffusion3-API
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/sdxl-recommended-res-calc
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/LCMSampler-ComfyUI
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-BRIA_AI-RMBG
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb-master
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfy-image-saver
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/sdxl_prompt_styler-main
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUi_NNLatentUpscale
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-sampler-lcm-alternative
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-N-Sidebar
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/stability-ComfyUI-nodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/StableZero123-comfyui
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-post-processing-nodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Logic
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Lora-Auto-Trigger-Words
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/masquerade-nodes-comfyui
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_Noise
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Prompt-Expansion
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_Cutoff
   0.0 seconds (IMPORT FAILED): /Users/OnLing/ComfyUI/custom_nodes/content
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUi_PromptStylers
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Eagle-PNGInfo
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_experiments
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-AutomaticCFG
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/SD-Advanced-Noise
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_InstantID
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-tooling-nodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-ELLA
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/CharacterFaceSwap
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-PhotoMaker-ZHO
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-LCM
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/mikey_nodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_Dave_CustomNode
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-inpaint-nodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Flowty-TripoSR
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Marigold
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Dev-Utils
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-LCM-main
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts-main
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyMath
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-CUP
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/clipseg.py
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/cg-image-picker
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-IC-Light-Wrapper
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-various
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/Comfy_KepListStuff
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/hd_node
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Text_Image-Composite
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-BrushNet
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-layerdiffusion
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-sixgod_prompt
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Studio
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-animatediff
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-depth-fm
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Allor
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/OneButtonPrompt
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-PhotoMaker-Plus
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_MagicClothing
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-SUPIR
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/facerestore_cf
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-ollama
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_smZNodes
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/Comfyui_ALY
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/eden_comfy_pipelines
   0.1 seconds (IMPORT FAILED): /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_LayerStyle
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Mana-Nodes
   0.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui_segment_anything
   0.2 seconds: /Users/OnLing/ComfyUI/custom_nodes/PuLID_ComfyUI
   0.2 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_Lam
   0.3 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_MileHighStyler
   0.3 seconds: /Users/OnLing/ComfyUI/custom_nodes/steerable-motion
   0.5 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Flowty-CRM
   0.6 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-IF_AI_tools
   0.6 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-APISR
   0.7 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_FaceAnalysis
   0.8 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   1.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Gemini
   1.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfy_PoP
   1.6 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-mixlab-nodes
   2.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/was-node-suite-comfyui
   2.5 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   2.8 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Crystools
   3.5 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_zfkun
   3.7 seconds: /Users/OnLing/ComfyUI/custom_nodes/Jovimetrix
   4.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/comfyui-reactor-node
   7.0 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-GPT_SoVITS
   8.6 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet
  10.1 seconds: /Users/OnLing/ComfyUI/custom_nodes/ComfyUI-HiDiffusion

**Comment by ltdrdata** [comment]
As expected, you're encountering an issue where nodes you installed manually are duplicating those installed through ComfyUI-Manager.

The following nodes are ones you installed by downloading as zip files.
Installing nodes this way can cause various problems. Delete them.

```
/Users/OnLing/ComfyUI/custom_nodes/sdxl_prompt_styler-main
/Users/OnLing/ComfyUI/custom_nodes/ComfyUI-LCM-main
/Users/OnLing/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts-main
```

And this directory should not exists

```
/Users/OnLing/ComfyUI/custom_nodes/content
```

**Comment by onlingai** [comment]
Thank you very much, the issue has been resolved, it has been a long-standing trouble.
