### ISSUE TITLE
After updating getting so many issues, do not understand what the cause is. Please help

### ISSUE THREAD

**Issue by RYG81** [Comfy-Org/ComfyUI-Manager#874]
So many errors that it was not even allowed in message.
[errors.txt](https://github.com/user-attachments/files/16254886/errors.txt)

**Comment by ltdrdata** [comment]
Your numpy is updated to 2.0. And it makes much much problems.
I recommend downgrade numpy.

**Comment by RYG81** [comment]
plrase guide how to do that i am not good at coding

**Comment by RYG81** [comment]
got it solved following another thread here- https://github.com/LykosAI/StabilityMatrix/issues/689
