### ISSUE TITLE
Implement Console Do Not Track

### ISSUE THREAD

**Issue by allo-** [Comfy-Org/ComfyUI-Manager#883]
ComfyUI-Manager implements tracking via Mixpanel, that seems to be enabled and disabled only by a config value of ComfyUI-Manager itself:
https://github.com/Comfy-Org/comfy-cli/blob/176d2deb805ef8b955568c906c5d1ba9d34c64a8/comfy_cli/tracking.py#L50

It would be good, if it could also respect the Console Do Not Track standard described here: https://consoledonottrack.com

Here is an example implementation:
https://github.com/huggingface/huggingface_hub/blob/f77c1c9f90b462727c581fec349e6c781c886265/src/huggingface_hub/constants.py#L121

**Comment by ltdrdata** [comment]
`config_manager` and `comfyui-manager` are totally different thing.
The only way to use ComfyUI-Manager's functionality in `comfy-cli` is by executing `cm-cli.py`.

**Comment by allo-** [comment]
Sorry, I guess I've got confused between the tabs when looking up the respective code links. I'll open the issue in the right repo.

**Comment by allo-** [comment]
You may also want to look at this Reddit post: https://old.reddit.com/r/StableDiffusion/comments/1e65b21/watch_out_for_comfycli_on_comfyuimanager_repo_it/

It looks like the whole post confuses different repos, pointing at `cm-cli` docs when talking about `comfy-cli`.

**Comment by ltdrdata** [comment]
> You may also want to look at this Reddit post: https://old.reddit.com/r/StableDiffusion/comments/1e65b21/watch_out_for_comfycli_on_comfyuimanager_repo_it/
> 
> It looks like the whole post confuses different repos, pointing at `cm-cli` docs when talking about `comfy-cli`.

I've already checked on that issue, actually.
Thank you for the notice.
