### ISSUE TITLE
Letters in context menu too small

### ISSUE THREAD

**Issue by lunatico67** [Comfy-Org/ComfyUI-Manager#887]
right-click and access the menu: Add Node; Node Templates... You have to have very good eyesight to distinguish its contents, is there any way to increase their size?

**Comment by ltdrdata** [comment]
It seems that your browser zoom level is too low.
Ant this issue is not related to ComfyUI-Manager.

**Comment by lunatico67** [comment]
Please, and where can I configure the browser zoom level?

**Comment by lunatico67** [comment]
> It seems that your browser zoom level is too low. Ant this issue is not related to ComfyUI-Manager.

Please, and where can I configure the browser zoom level?

**Comment by ltdrdata** [comment]
> > It seems that your browser zoom level is too low. Ant this issue is not related to ComfyUI-Manager.
> 
> Please, and where can I configure the browser zoom level?

You can set it in your browser menu.
My favorite method is to move the mouse cursor to the menu window and adjust it with ctrl+mouse wheel.

**Comment by lunatico67** [comment]
> > > It seems that your browser zoom level is too low. Ant this issue is not related to ComfyUI-Manager.
> > 
> > 
> > Please, and where can I configure the browser zoom level?
> 
> You can set it in your browser menu. My favorite method is to move the mouse cursor to the menu window and adjust it with ctrl+mouse wheel.

Thanks for your help. I must be doing something wrong because it doesn't work, ctrl + mouse wheel as you suggest but the menu and its context remain the same size.
![Menu](https://github.com/user-attachments/assets/6b03c73d-004e-44db-987d-cdb47a593fc4)

**Comment by ltdrdata** [comment]
> Thanks for your help. I must be doing something wrong because it doesn't work, ctrl + mouse wheel as you suggest but the menu and its context remain the same size.

The important point is that you shouldn't use the wheel on the canvas. That only adjusts the zoom of the canvas, not the browser's zoom.
That's why I suggested putting the mouse cursor over the menu.

**Comment by lunatico67** [comment]
> > Thanks for your help. I must be doing something wrong because it doesn't work, ctrl + mouse wheel as you suggest but the menu and its context remain the same size.
> 
> The important point is that you shouldn't use the wheel on the canvas. That only adjusts the zoom of the canvas, not the browser's zoom. That's why I suggested putting the mouse cursor over the menu.

I'm sorry but I don't understand you. I do it on the browser and the size remains the same.
![browser](https://github.com/user-attachments/assets/f6a15515-c95e-4b04-860c-85d3aa8c7083)

**Comment by ltdrdata** [comment]
https://github.com/user-attachments/assets/6eea1dbf-7213-47dd-a9a5-488a4d160baa

**Comment by lunatico67** [comment]
Hi! A lot of thanks for the video. In the last update it works
