### ISSUE TITLE
No close button on the "a1111 alternatives" window

### ISSUE THREAD

**Issue by alexopus** [Comfy-Org/ComfyUI-Manager#89]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/25933468/a6edbc2f-2b8b-41c4-869f-0b5ec56465b1)

Models & custom nodes windows do have it.

**Comment by ltdrdata** [comment]
This is fixed on 9b535f163cb1f1a7dc3c3c0f09ab0dc9412fbc6f
