### ISSUE TITLE
[Feature request] Accelerating Network Access Using Mirror Sites

### ISSUE THREAD

**Issue by hben35096** [Comfy-Org/ComfyUI-Manager#893]
I noticed that due to network issues in my region, using the Manager to install nodes often encounters instability. However, I can run the following command in advance:

`git config --global url."https://mirror.ghproxy.com/https://github.com/".insteadOf https://github.com/`

Then start ComfyUI, so that when using the Manager to install nodes, it uses the mirror site of Github for installation.
For example, installing:

`https://github.com/ltdrdata/ComfyUI-Inspire-Pack`
will become:  
 `https://mirror.ghproxy.com/https://github.com/ltdrdata/ComfyUI-Inspire-Pack`

achieving faster installation.

---

However, the node list and model list files of the Manager, such as:

`https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json`
`https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json`

I have no way to change them to:

`https://mirror.ghproxy.com/https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json`
`https://mirror.ghproxy.com/https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json`

for network acceleration.

---

So, is there a way, such as a configuration file, where users can fill in some content themselves, like in a yaml file:

`"https://github.com/": "https://mirror.ghproxy.com/https://github.com/"`
`"https://raw.githubusercontent.com/": "https://mirror.ghproxy.com/https://raw.githubusercontent.com/"`

**Comment by planb788** [comment]
如果是能够自动下载模型的插件，你可以通过简单地在环境变量里面添加一个名为HF_ENDPOINT的环境变量来实现镜像加速，它的值需要设置为https://hf-mirror.com
If it's a plugin capable of automatically downloading models, you can achieve mirror acceleration by simply adding an environment variable named HF_ENDPOINT in your environment variables, with its value set to https://hf-mirror.com

**Comment by Leo-Mu** [comment]
@planb788 Not working. 并不行，这样做在 ComfyUI-Manager 里并不会把模型下载地址切换到 hf-mirror

**Comment by ltdrdata** [comment]
This will be handled in manager-core.

**Comment by tianlinzx** [comment]
> [@planb788](https://github.com/planb788) Not working. 并不行，这样做在 ComfyUI-Manager 里并不会把模型下载地址切换到 hf-mirror

+1
