### ISSUE TITLE
Error uninstalling 'git-clone' type node packs:

### ISSUE THREAD

**Issue by TinyTerra** [Comfy-Org/ComfyUI-Manager#9]
> Uninstall custom node 'ComfyUI Impact Pack'
uninstall: ['https://github.com/ltdrdata/ComfyUI-Impact-Pack']
Uninstall(git-clone) error: https://github.com/ltdrdata/ComfyUI-Impact-Pack / [WinError 5] Access is denied: 'T:\\AI\\Comfy\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\.git\\objects\\pack\\pack-e93eb23f657ade456d5985ea3fbd532b34236f83.idx'

> FECTH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Uninstall custom node 'WAS Node Suite'
uninstall: ['https://github.com/WASasquatch/was-node-suite-comfyui']
Uninstall(git-clone) error: https://github.com/WASasquatch/was-node-suite-comfyui / [WinError 5] Access is denied: 'T:\\AI\\Comfy\\ComfyUI\\custom_nodes\\was-node-suite-comfyui\\.git\\objects\\04\\fe42466017979281ac12ede624dd6902fc9adf'
FECTH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

etc

**Comment by ltdrdata** [comment]
oh... this is related to file system of Windows.
I need to find someway to avoid that issue.
Thanks for the report.

**Comment by ltdrdata** [comment]
> > Uninstall custom node 'ComfyUI Impact Pack'
> > uninstall: ['https://github.com/ltdrdata/ComfyUI-Impact-Pack']
> > Uninstall(git-clone) error: https://github.com/ltdrdata/ComfyUI-Impact-Pack / [WinError 5] Access is denied: 'T:\AI\Comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\.git\objects\pack\pack-e93eb23f657ade456d5985ea3fbd532b34236f83.idx'
> 
> > FECTH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> > Uninstall custom node 'WAS Node Suite'
> > uninstall: ['https://github.com/WASasquatch/was-node-suite-comfyui']
> > Uninstall(git-clone) error: https://github.com/WASasquatch/was-node-suite-comfyui / [WinError 5] Access is denied: 'T:\AI\Comfy\ComfyUI\custom_nodes\was-node-suite-comfyui\.git\objects\04\fe42466017979281ac12ede624dd6902fc9adf'
> > FECTH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> 
> etc

Finally, this issue patched.
Try that.

**Comment by TinyTerra** [comment]
Uninstall works now 👍

getting this on install instead:
> Download: git clone 'https://github.com/ltdrdata/ComfyUI-Impact-Pack'
T:\AI\Comfy\python_embeded\python.exe: can't open file 'T:\\AI\\Comfy\\ComfyUI\\custom_nodes\\ComfyUI-Manager\\git_helper.py': [Errno 2] No such file or directory
Installation was successful.

_(it wasnt)_

**Comment by ltdrdata** [comment]
> Uninstall works now 👍
> 
> getting this on install instead:
> 
> > Download: git clone 'https://github.com/ltdrdata/ComfyUI-Impact-Pack'
> > T:\AI\Comfy\python_embeded\python.exe: can't open file 'T:\AI\Comfy\ComfyUI\custom_nodes\ComfyUI-Manager\git_helper.py': [Errno 2] No such file or directory
> > Installation was successful.
> 
> _(it wasnt)_

OMG.. My mistake... patched.

**Comment by TinyTerra** [comment]
No stress :)
Thanks for the patches!
