### ISSUE TITLE
Feature Request: Place new Nodes at the top or bottom

### ISSUE THREAD

**Issue by tusharbhutt** [Comfy-Org/ComfyUI-Manager#90]
Maybe I'm missing something but it seems new nodes are somewhat randomly placed in the list of exiting nodes which makes it hard to find the more current ones.  I know for sure that some new ones have appeared above older ones.  For example, the embedding picker is four days old but appears above comfy-meh which is much older.  

How are these being sorted?

**Comment by ltdrdata** [comment]
> Maybe I'm missing something but it seems new nodes are somewhat randomly placed in the list of exiting nodes which makes it hard to find the more current ones. I know for sure that some new ones have appeared above older ones. For example, the embedding picker is four days old but appears above comfy-meh which is much older.
> 
> How are these being sorted?

Currently, a separate sorting feature is not provided. However, if you select "recent" in the channel, only the recently added nodes will be displayed, and in the manager, the most recently added nodes will be shown at the top.

The default channel does organize nodes from the same author together when newly added, prioritizing a git-clone approach over a copy approach. However, it can still be considered an arbitrary order.

The recently added `recent channel` is managed with the purpose of introducing new custom nodes. After a certain period of time, older items will be removed starting from the oldest ones.

**Comment by tusharbhutt** [comment]
Excellent, I'll give that a shot ... except, where does one find "recent" in the manager?

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/26264462/40f69bce-465c-482f-bda1-17cdefeae19c)

**Comment by tusharbhutt** [comment]
Ah never mind, found it...

![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/26264462/704ed295-4585-4832-a291-205f49b09518)
