### ISSUE TITLE
Request: Release/Tags ?

### ISSUE THREAD

**Issue by lawschlosser** [Comfy-Org/ComfyUI-Manager#902]
Hello,
In the README, I see that version numbers (for the ComfyUI-Manager) are used/referenced (e.g. _V2.48.1: Security policy has been changed..._), but I don't see any github releases or tags that these numbers corresponds with them.  I see that `manager_core.py` [provides](https://github.com/ltdrdata/ComfyUI-Manager/blob/a2fa3390f9a3acf91c9b7acb04f92c10dbfecbfd/glob/manager_core.py#L26-L27) the version, and perhaps that's where users are supposed to check which version they have, but I was wondering if there was an intention to add github releases/tags at some point?  This would be very helpful when trying to get a specific version of ComfyUI-Manager, e.g. `git clone -b v2.48.1 https://github.com/ltdrdata/ComfyUI-Manager.git`

Thank you

**Comment by ltdrdata** [comment]
I added annotated tags starting from 2.48.1.

Now you can use `git describe` and `git tag`

**Comment by lawschlosser** [comment]
> I added annotated tags starting from 2.48.1.

Excellent, thank you so much!  I appreciate your work!
