### ISSUE TITLE
[BUG] Latest ComfyUI-Manager update will change IPAdapter nodes labeled as Bizyair nodes

### ISSUE THREAD

**Issue by TiptopFunk** [Comfy-Org/ComfyUI-Manager#913]
Today, I discovered that all IPAdapter Nodes are labeled as 'Bizyair node'.

1. I verified that I haven't installed the Bizyair node.
2. Additionally, I tried uninstalling and reinstalling IPAdapter_plus, but the issue persists.
3. After I downgraded the ComfyUI manager to a previous commit, this issue was resolved.

![2024-07-31 10_09_02-ComfyUI](https://github.com/user-attachments/assets/5d8e9d4c-e1b0-4c20-bbee-41f09153ce2d)

**Comment by ltdrdata** [comment]
This is fixed.
