### ISSUE TITLE
Executing git_helper.py script is slow

### ISSUE THREAD

**Issue by Maslino** [Comfy-Org/ComfyUI-Manager#914]
In git_helper.py script, there is an import:

```python
from torchvision.datasets.utils import download_url
```

which will import torchvision and torch and this import procedure costs about 2 seconds on my desktop.

Only the download_url function from the big torch package is used. Maybe we should avoid this import and take other measures to improve performance. Because  git_helper.py is widely used in ComfyUI-Manager as subprocess.

**Comment by ltdrdata** [comment]
Oh.. Yeah.. I need to patch this.

**Comment by Maslino** [comment]
How to visualize import time:

```bash
python -X importtime  ComfyUI-Manager/git_helper.py  --apply-snapshot 2024-07-31_11-19-36_snapshot.json 2>import.log

pip install tuna

tuna import.log
```
![git_helper_import_time](https://github.com/user-attachments/assets/222b132b-9f16-43e5-876b-e59d98ef2181)

**Comment by ltdrdata** [comment]
This is patched.
