### ISSUE TITLE
Unable to download SAM2 nodes due to security and cant figure out how to disable

### ISSUE THREAD

**Issue by tristan22mc** [Comfy-Org/ComfyUI-Manager#917]
![Screenshot 2024-07-31 145652](https://github.com/user-attachments/assets/f1cd0eb6-a593-4e2f-b7e1-bfaa22c143f7)
Cant figure out how to disable settings.

Trying to download kijai SAM2 nodes here: https://github.com/kijai/ComfyUI-segment-anything-2

**Comment by ltdrdata** [comment]
Take a look at this:
https://github.com/ltdrdata/ComfyUI-Manager#security-policy

I'll add it to default channel soon. Then, you can install it without change settings.
