### ISSUE TITLE
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:

### ISSUE THREAD

**Issue by Amit30swgoh** [Comfy-Org/ComfyUI-Manager#926]
![image](https://github.com/user-attachments/assets/2b449a4b-b416-46d5-81e2-69ccbb069b4c)
Total VRAM 15102 MB, total RAM 52217 MB
pytorch version: 2.3.1+cu121
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.3.1+cu121)
    Python  3.10.14 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.27.post2
Forcing FP16.
Set vram state to: HIGH_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /content/drive/MyDrive/ComfyUI/web
### Loading: ComfyUI-Manager (V2.48.5)

**Comment by ltdrdata** [comment]
You have installed invalid version of xformers.
Just uninstall it.
