### ISSUE TITLE
Change the Flux "Save Path", for the 17.2 GB models. 

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI-Manager#933]
These 17.2 GB models got into the "checkpoints" folder, not the "unet" folder.
https://comfyanonymous.github.io/ComfyUI_examples/flux/#simple-to-use-fp8-checkpoint-version

I haven't used the Model Manager for this, but think it's causing issues. 
https://github.com/comfyanonymous/ComfyUI/issues/4221
https://github.com/comfyanonymous/ComfyUI/issues/4220

![manager](https://github.com/user-attachments/assets/5e4050b0-fffd-47b7-a26b-2a0eca024729)

**Comment by ltdrdata** [comment]
Fixed.
