### ISSUE TITLE
loading stopped, what's the matter?

### ISSUE THREAD

**Issue by jasoncow007** [Comfy-Org/ComfyUI-Manager#94]
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints D:\sd-webui-aki-v4\models/Stable-diffusion
Adding extra search path configs D:\sd-webui-aki-v4\models/Stable-diffusion
Adding extra search path vae D:\sd-webui-aki-v4\models/VAE
Adding extra search path loras D:\sd-webui-aki-v4\models/Lora
Adding extra search path loras D:\sd-webui-aki-v4\models/LyCORIS
Adding extra search path upscale_models D:\sd-webui-aki-v4\models/ESRGAN
Adding extra search path upscale_models D:\sd-webui-aki-v4\models/RealESRGAN
Adding extra search path upscale_models D:\sd-webui-aki-v4\models/SwinIR
Adding extra search path embeddings D:\sd-webui-aki-v4\embeddings
Adding extra search path hypernetworks D:\sd-webui-aki-v4\models/hypernetworks
Adding extra search path controlnet D:\sd-webui-aki-v4\models/ControlNet

**Comment by ltdrdata** [comment]
1. First, try starting by removing all custom nodes.
2. It's not related to this issue, but your Impact-Pack version is too low. I also recommend updating it.

**Comment by jasoncow007** [comment]
seem relate with comfyui manager,,,after removing comfyui manager it can be laughed normally,,,,,

**Comment by jasoncow007** [comment]
updated imapct，issue still exist，，，，seems impact conflict with manager，remove any of them, laungh works well

**Comment by ltdrdata** [comment]
> updated imapct，issue still exist，，，，seems impact conflict with manager，remove any of them, laungh works well

Does it mean that it operates correctly when one of either **Impact** or **Manager** is removed, but when both are installed, it doesn't transition to " anymore?" without any errors?

Additionally, please remove all other custom nodes and test it with only **Manager** and **Impact** nodes.
