### ISSUE TITLE
[BUG] model type checkpoint should be checkpoints in https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json?

### ISSUE THREAD

**Issue by Maslino** [Comfy-Org/ComfyUI-Manager#949]
For example:

![image](https://github.com/user-attachments/assets/b583d4b4-6afd-4ddf-a545-b294ede4c904)

**Comment by ltdrdata** [comment]
Oh... you have to update ComfyUI-Manager.

https://github.com/ltdrdata/ComfyUI-Manager/pull/942/files
