### ISSUE TITLE
plugin list load seems to take forever.

### ISSUE THREAD

**Issue by Ferniclestix** [Comfy-Org/ComfyUI-Manager#95]
Not sure if its a comfyUI manager issue as I have a node which takes like 80 seconds to load on start for some reason but when its getting the custom nodes list it takes AGES.

**Comment by ltdrdata** [comment]
Try testing it with "use local db" checked.

**Comment by Ferniclestix** [comment]
mm instant on local db

**Comment by ltdrdata** [comment]
> mm instant on local db

Are you seeing the following (exactly same) log in the console when "use local db" is not used?
`FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json`

**Comment by Ferniclestix** [comment]
yep `https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json`

its suspiciously similar to the last node that loads in that they seem to take almost exactly the same time to load. 
`  81.5 seconds: D:\othercomfy\origin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes`

**Comment by ltdrdata** [comment]
> yep `https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json`
> 
> its suspiciously similar to the last node that loads in that they seem to take almost exactly the same time to load. ` 81.5 seconds: D:\othercomfy\origin\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes`

Oh, are you referring to the list of custom nodes being loaded, not the manager's node list? 

In that case, you should reach out to the repository of the specific custom node for inquiries. Additionally, during the initial run, processes like model downloads or package installations may take some time as they typically occur together with the first execution.

If it's consistently taking a long time, it's advisable to contact the developer for assistance.

**Comment by Ferniclestix** [comment]
no, i just noted that one taks 86 seconds during load and comfymanager takes around 80 seconds to open install menu
thought maybe there was some kind of shared issue as the time is so similar.

**Comment by kalkal11** [comment]
Same, seems like a problem with the remote file loading.

Trying to load the url to the file manually in browser times out too.

**Comment by ltdrdata** [comment]
> Same, seems like a problem with the remote file loading.
> 
> Trying to load the url to the file manually in browser times out too.

Does this issue only occur when `ComfyUI-Manager` is installed?

**Comment by kalkal11** [comment]
> > Same, seems like a problem with the remote file loading.
> > Trying to load the url to the file manually in browser times out too.
> 
> Does this issue only occur when `ComfyUI-Manager` is installed?

No no, I mean the actual file itself - ComfyUI manager aside, wouldn't load even in a web browser - for me at least.

Looks to have been a temporary issue with wherever it was hosted, all good now.

**Comment by Ferniclestix** [comment]
installed and tested on a fresh comfyUI, same issue. checking for custom nodes takes roughly 1 minute and 20 seconds. definitely something borked, this time It was clean with no other custom nodes.

**Comment by ltdrdata** [comment]
> installed and tested on a fresh comfyUI, same issue. checking for custom nodes takes roughly 1 minute and 20 seconds. definitely something borked, this time It was clean with no other custom nodes.

try open this link in your brower
`https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json`

it seems network issue.

**Comment by Ferniclestix** [comment]
instant load, seems fine.
hang on ill check it in another browser in case cached.

-nope all good, instant load in both.

**Comment by Ferniclestix** [comment]
Ok... now its working, computer restart fixed it.... what? o.0
restarted browser, server and all that... restart computer fixes it.  (brain explodes)

**Comment by ltdrdata** [comment]
> Ok... now its working, computer restart fixed it.... what? o.0 restarted browser, server and all that... restart computer fixes it. (brain explodes)

It has been reported that last night, others were also experiencing difficulties accessing GitHub. The instability of the GitHub website appears to be the issue.
