### ISSUE TITLE
Big Brother, help me change the name of the plugin

### ISSUE THREAD

**Issue by yiwangsimple** [Comfy-Org/ComfyUI-Manager#951]
https://github.com/yiwangsimple/ComfyUI_DW_Chat.  It's been a long time since I changed the name of the plugin I wrote, but when I search from the admin, it's still the same name as before, please help me fix it. It used to be called "groqchat". Thank you very, very much!

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by yiwangsimple** [comment]
thanks
