### ISSUE TITLE
Invalid Version Number reported when its NOT invalid

### ISSUE THREAD

**Issue by Amorano** [Comfy-Org/ComfyUI-Manager#953]
![image](https://github.com/user-attachments/assets/dae2af4d-4630-4ac3-bf98-5fb97d17719b)

My requirements is well formed with the proper version numbers:

![image](https://github.com/user-attachments/assets/3b9095a4-e596-4d89-9bd4-e619b90b8968)

The installer is doing some weird thing with version ranges and refuses to see the official `opencv-contrib-python>=4.10.0.84` as a valid version.

When doing a clean install, everything seems to install.

**Comment by ltdrdata** [comment]
This is fixed.
