### ISSUE TITLE
'distutils' package not found

### ISSUE THREAD

**Issue by artbymbesares** [Comfy-Org/ComfyUI-Manager#954]
I've recently updated Comfy and all my nodes and started getting this message on the top of my console, what does it mean? I tried pip install but it didn't do anything.
![image](https://github.com/user-attachments/assets/8ad716ba-ab48-48fc-a10c-f3b29b685b2a)

**Comment by teanhow** [comment]
me too

**Comment by ltdrdata** [comment]
I discovered that a feature being used in `distutils` was not compatible with the usability of ComfyUI-Manager, and this issue arose in the process of making it always operate as a fallback. That message can be ignored.

Anyway, I've modified it so that the message is no longer displayed.
