### ISSUE TITLE
[Request repo] Please add NF4 to list for FLUX

### ISSUE THREAD

**Issue by Milor123** [Comfy-Org/ComfyUI-Manager#960]
Civitai link: https://civitai.com/models/638572/nf4-flux1
Github ComfyUI Node: https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4
requirements: pip install -U bitsandbytes

Description: Checkpoint for NF4 models for Flux
Thank u very much

**Comment by ltdrdata** [comment]
It is added into Dev channel, already.

**Comment by ltdrdata** [comment]
oh... you are referring to NF4 model not a node.

**Comment by Milor123** [comment]
> oh... you are referring to NF4 model not a node.

Oh bro both, but i refer to node, because in the normal people is not using dev branch, and it works as stable, I have a client and he cant install requirements T_T and also cant help with teamviewer. I really dont know how explain that must load venv and use pip, he dont understand it, but need use NSF4, and this manager tool saves us!

Could you please set is in normal branch? or share me a method, I am not developer but i can build simple things in python, How can i add a snipet to the example node .py for install a library in python in comfyui? (I tried to google things about this, but hopefully I get something about how to develop very basic nodes, there is very little information)

Thank u very much.

**Comment by Milor123** [comment]
Ohh excuse me, i dont know this options!!
![image](https://github.com/user-attachments/assets/e465b593-198b-4ede-a74f-5bf98ad59a3a)

Thank u very much

**Comment by ltdrdata** [comment]
> Ohh excuse me, i dont know this options!! ![image](https://private-user-images.githubusercontent.com/14153649/358237226-e465b593-198b-4ede-a74f-5bf98ad59a3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzQwMTMsIm5iZiI6MTcyMzczMzcxMywicGF0aCI6Ii8xNDE1MzY0OS8zNTgyMzcyMjYtZTQ2NWI1OTMtMTk4Yi00ZWRlLWE3NGYtNWJmOThhZDU5YTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE0NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MjA3YjY4YmY5ZTg4ODU0YzkzYzlhZDdiYTY5NzU1NDExNGZmMWI3OGQ2OGVmOWZlODA2YzI0OTEyNDcwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yg3mnRkKc4yBW3bQc4FrWGUKKwy-EGPkNTo64iP6GnM)
> 
> Thank u very much

And you can change `Channel: default` to `Channel: dev`.

**Comment by Void2258** [comment]
It's been a while. If this is stable, why is the node still only in dev?
