### ISSUE TITLE
Duplicaded Repo ( ComfyUI-GGUF )

### ISSUE THREAD

**Issue by JorgeR81** [Comfy-Org/ComfyUI-Manager#963]
Thre are 2 ComfyUI-GGUF repos by city96

Also, after switching from "dev" to "default" Channel, the list still indicates dev channel in the top right corner, although I can see all the default nodes.

![gguf](https://github.com/user-attachments/assets/c2dbce2a-1d26-448e-9722-d67dd6de315c)

**Comment by ltdrdata** [comment]
This is fixed.
