### ISSUE TITLE
Remove broken and duplicate nodes package

### ISSUE THREAD

**Issue by mesbahmilad** [Comfy-Org/ComfyUI-Manager#965]
This package https://github.com/neverbiasu/ComfyUI-SAM2 duplicates the name of nodes from the existing SAM package and is suggested during install missing nodes. If installed, it will break the working and existing SAM package. The package now breaks the entire ComfyUi as it is trying to change torch version. https://github.com/neverbiasu/ComfyUI-SAM2/issues/16

**Comment by ltdrdata** [comment]
Previously, only the downgrade of torch, torchsde, and torchvision was blocked. Now, upgrades have also been prevented.
Issues caused by reinstalling torch should no longer occur.

**Comment by hben35096** [comment]
Yes, it's really terrifying. I've seen some people whose entire runtime environment became unusable after installing this plugin. I tried it myself and found that if I removed all version information from the requirements.txt file before installing, there was no issue at all.
