### ISSUE TITLE
This URL is not displayed in the terminal

### ISSUE THREAD

**Issue by minilulubai** [Comfy-Org/ComfyUI-Manager#970]
Hi maintainer，

I just downloaded this comfyui plugin that you maintained. But in the terminal, it doesn't show this address. [127.0.0.1:8188]

I'm using it on a Linux platform. I hope you can help me see what the problem is?

Here's some info. 
ComfyUI: 1[05e831](2024-06-29)
ComfyUI Manager: V2.49

The terminal message when comfyui is running looks like this:
![截图_deepin-terminal_20240816112545](https://github.com/user-attachments/assets/02af9448-91d6-4375-855e-c37e73a4950b)

**Comment by ltdrdata** [comment]
s the following message displayed correctly when ComfyUI-Manager is not installed?
```
To see the GUI go to: http://127.0.0.1:8188
```

**Comment by minilulubai** [comment]
> s the following message displayed correctly when ComfyUI-Manager is not installed?
> 
> ```
> To see the GUI go to: http://127.0.0.1:8188
> ```

Yes. I tested it and took a screenshot. 
![new](https://github.com/user-attachments/assets/5a64d3e6-0dbc-47d5-9a07-9fe2e4c2c18b)

**Comment by ltdrdata** [comment]
Is it simply not displaying on the screen? Or are you unable to connect to https://127.0.0.1:8188/?
Since it takes time for the server to start up, please test again after allowing sufficient time for the server to initialize normally.

**Comment by minilulubai** [comment]
> Is it simply not displaying on the screen? Or are you unable to connect to https://127.0.0.1:8188/? Since it takes time for the server to start up, please test again after allowing sufficient time for the server to initialize normally.

Thank you very much. 
I attempted numerous times. It turns out that when I input this string of addresses into my browser, it functions perfectly. It merely fails to display in the terminal.

**Comment by ltdrdata** [comment]
> > Is it simply not displaying on the screen? Or are you unable to connect to https://127.0.0.1:8188/? Since it takes time for the server to start up, please test again after allowing sufficient time for the server to initialize normally.
> 
> Thank you very much. I attempted numerous times. It turns out that when I input this string of addresses into my browser, it functions perfectly. It merely fails to display in the terminal.

How about comfy.log File?

**Comment by ltdrdata** [comment]
Make sure your ComfyUI is up to date.

**Comment by minilulubai** [comment]
> > > Is it simply not displaying on the screen? Or are you unable to connect to https://127.0.0.1:8188/? Since it takes time for the server to start up, please test again after allowing sufficient time for the server to initialize normally.
> > 
> > 
> > Thank you very much. I attempted numerous times. It turns out that when I input this string of addresses into my browser, it functions perfectly. It merely fails to display in the terminal.
> 
> How about comfy.log File?

Sorry for replying you so late.My local version of the ComfyUI is  2.49.
I tried it several times these days and it eventually worked. I don't understand how it became normal.
Sincere thanks to you.

This is the latest log file and comfyUI is running very stable and normal.
[comfyui.log](https://github.com/user-attachments/files/16656126/comfyui.log)

**Comment by ltdrdata** [comment]
> > > > Is it simply not displaying on the screen? Or are you unable to connect to https://127.0.0.1:8188/? Since it takes time for the server to start up, please test again after allowing sufficient time for the server to initialize normally.
> > > 
> > > 
> > > Thank you very much. I attempted numerous times. It turns out that when I input this string of addresses into my browser, it functions perfectly. It merely fails to display in the terminal.
> > 
> > 
> > How about comfy.log File?
> 
> Sorry for replying you so late.My local version of the ComfyUI is 2.49. I tried it several times these days and it eventually worked. I don't understand how it became normal. Sincere thanks to you.
> 
> This is the latest log file and comfyUI is running very stable and normal. [comfyui.log](https://github.com/user-attachments/files/16656126/comfyui.log)

Your ComfyUI is very outdated version.
```
[2024-08-19 13:04] ### ComfyUI Revision: 1 [05e83169] | Released on '2024-06-29'
```

There is an issue with older versions of ComfyUI where logs are not displayed on the terminal.
