### ISSUE TITLE
"ERROR: This installation is not allowed in this security_level.  Please contact the administrator."

### ISSUE THREAD

**Issue by metsweet999** [Comfy-Org/ComfyUI-Manager#975]
i am trying to install an extension from "https://github.com/comfyanonymous/ComfyUI_bitsandbytes_NF4",
it says i need to set channel to be "channel : dev" to install it in comfyui-manager,
i did this setting, and tried to install it in comfyui-manager,
when clicking install button, info displays in console:
"ERROR: This installation is not allowed in this security_level.  Please contact the administrator."
![屏幕截图 2024-08-17 173418](https://github.com/user-attachments/assets/e55644a7-f96c-434b-b080-3f74e6bac339)

i tried to open comfyui with identity of administrator, tried every thing i could think of, didn't work.

maybe this extension is now just simply not allowed to be installed via comfyui-manager for security reasons, it is okay, but if so, just show the info :"this extension is now not allowed to  install for security reasons, please install via git clone" can make me more clear about the situation.

the issue is to look for an answer for the following question: does this error info means there is a setting option that i can use to set the "security_level", or i should just install this extension via "git clone"?

**Comment by metsweet999** [comment]
found the same issue: https://github.com/ltdrdata/ComfyUI-Manager/issues/756
sorry i did the search before upload this issue, but didn't find #756 .
i think i solved my problem with info inside #756,
but maybe adding "refer: https://github.com/ltdrdata/ComfyUI-Manager#security-policy " to the error info can give user some more help.

**Comment by ltdrdata** [comment]
> found the same issue: #756 sorry i did the search before upload this issue, but didn't find #756 . i think i solved my problem with info inside #756, but maybe adding "refer: https://github.com/ltdrdata/ComfyUI-Manager#security-policy " to the error info can give user some more help.

Fixed.
