### ISSUE TITLE
update all with local changes deletes all local changes

### ISSUE THREAD

**Issue by ljleb** [Comfy-Org/ComfyUI-Manager#976]
Sometimes I work in comfyui with uncommited local changes in a node pack I maintain when I'm testing new features. Pressing on "Update all" should absolutely not reset the directory tree of a nodepack, it should raise an error if there are local changes and give up on updating that particular nodepack.

**Comment by ltdrdata** [comment]
ComfyUI-Manager never deletes anything. Your changes have been stashed.
Go to the path and run `git stash pop`.

**Comment by ljleb** [comment]
I see, thanks and my bad for not knowing.

The only comment I would have is that it should be clear from the console logs that a stash entry is getting pushed (did I miss this info? I tried reproducing the situation again but I can't spot it in the logs)

Without this information in the logs, I am not sure how anyone can be informed that their local changes are getting stashed on update. Is it something everybody just knows?

I have the impression that this is a pretty low priority issue if an issue at all at this point. I won't insist on making any change.

**Comment by ltdrdata** [comment]
I agree. I need to add that message.
