### ISSUE TITLE
Update Animatediff custom node to maintained repo

### ISSUE THREAD

**Issue by peteromallet** [Comfy-Org/ComfyUI-Manager#98]
Current Animatediff custom node is unmaintained and not up-to-date - put in a PR to update it to the maintained repo by Kosinkadink https://github.com/ltdrdata/ComfyUI-Manager/compare/main...peteromallet:ComfyUI-Manager:patch-1

**Comment by ltdrdata** [comment]
The **extension map** is not manually managed through updates. It is automatically generated by scanning the repositories listed in the `custom-node-list.json` file. 

Additionally, it appears that there have been updates in the `AnimateDiff` repository within the past week, so there doesn't seem to be any maintenance issues, yet. If it remains in an unusable state without maintenance for over a month, I will consider moving it to the legacy channel and replacing it. However, that is not the current situation.

However, for convenience, I have added the `channel: forked` option and registered that repository there.

**Comment by peteromallet** [comment]
Hi there,

There are issues with the repo you currently include that make it non-functional - for example, every clip it produces flickers. This is because they ported the plugin from A1111 meaning it inherited its issues. 

The one I linked fixes those issues so would encourage you to replace it for the sake of user experience - see people on Reddit, etc. using the wrong repo and think it’s for this reason.

**Comment by ltdrdata** [comment]
> Hi there,
> 
> There are issues with the repo you currently include that make it non-functional - for example, every clip it produces flickers. This is because they ported the plugin from A1111 meaning it inherited its issues.
> 
> The one I linked fixes those issues so would encourage you to replace it for the sake of user experience - see people on Reddit, etc. using the wrong repo and think it’s for this reason.

If it's not a completely independent project, I believe it's preferable to submit a PR to the original repo first.

If the original author is not maintaining it at all and it's truly abandoned, then there might be a need to switch. However, it doesn't seem entirely abandoned yet. Nevertheless, since there's a repository that addresses compatibility issues more quickly than the original repo, providing access to the forked channel is an option.

In fact, there is a slight concern about potential difficulties when switching back if the original repo is eventually restored in the future.

**Comment by Kosinkadink** [comment]
To give some context for the original repo's updates, in the past month after August 6th the only PR's submitted to the repo were by alexbofa to fix imports whenever ComfyUI updates would implement breaking changes to where certain functions and classes were located.
https://github.com/ArtVentureX/comfyui-animatediff/commits/main

Other than that, there was no further development of the code in the OG repo.

The main reason I am not submitting PRs to the original repo is I've been pushing code, bug fixes, etc. almost every day for the past two weeks, and it would become a big roadblock in terms of propagating the updates to users by not being one of the maintainers of the repo and having creative control.

If we need to come up with some compromise in terms of how to handle this, i.e. me attempting to become a maintainer of the OG repo, I am open to it, but core parts of the code have diverged in my version, and every big bug present in the original repo has been fixed in my fork. There has been confusion lately with people pulling the OG AnimateDiff extension using ComfyUI-Manager in an attempt to get my version, and reference my fork's README but reporting issues about the original repo that are no longer present in my fork.

**Comment by Kosinkadink** [comment]
Or, we could have a duplicate AnimateDiff entry and have mine be "AnimateDiff (Kosinkadink version)" or something along those lines to distinguish it and still keep the old one in - that way, we don't straight up replace it. This would also prevent any node-related confusion if users were to do an update and suddenly get my version.

**Comment by Kosinkadink** [comment]
I'm not sure of the best practices in terms of updating/replacing/having duplicates of entries for ComfyUI-Manager, so my apologies if I missed something about the proper way of requesting a fork to be added to the db! I appreciate you looking at this 👍

**Comment by Kosinkadink** [comment]
I just reread your last reply and realized you already suggested the forked channel solution and added it there... my bad, I missed that somehow.

I'll try to document that in my repo's readme for the ComfyUI-Manager installation, but not having it be in the default channel is going to keep the confusion as I don't think the channel function in the first place is well known. If having it be a duplicate entry in the default channel is an option (with the "Kosinkadink version" suffix as it already is), that would help visibility a ton.

**Comment by ltdrdata** [comment]
> To give some context for the original repo's updates, in the past month after August 6th the only PR's submitted to the repo were by alexbofa to fix imports whenever ComfyUI updates would implement breaking changes to where certain functions and classes were located. https://github.com/ArtVentureX/comfyui-animatediff/commits/main
> 
> Other than that, there was no further development of the code in the OG repo.
> 
> The main reason I am not submitting PRs to the original repo is I've been pushing code, bug fixes, etc. almost every day for the past two weeks, and it would become a big roadblock in terms of propagating the updates to users by not being one of the maintainers of the repo and having creative control.
> 
> If we need to come up with some compromise in terms of how to handle this, i.e. me attempting to become a maintainer of the OG repo, I am open to it, but core parts of the code have diverged in my version, and every big bug present in the original repo has been fixed in my fork. There has been confusion lately with people pulling the OG AnimateDiff extension using ComfyUI-Manager in an attempt to get my version, and reference my fork's README but reporting issues about the original repo that are no longer present in my fork.

If you want to take a completely different direction in development without contributing to the original repo, it might be a good idea to change the node name altogether and proceed as an independent project. Maintaining the same node name for an independent project could lead to confusion.

Additionally, you should consider changing the repository name as well. Custom nodes managed by ComfyUI are typically identified by the repository name.

**Comment by ltdrdata** [comment]
> > To give some context for the original repo's updates, in the past month after August 6th the only PR's submitted to the repo were by alexbofa to fix imports whenever ComfyUI updates would implement breaking changes to where certain functions and classes were located. https://github.com/ArtVentureX/comfyui-animatediff/commits/main
> > Other than that, there was no further development of the code in the OG repo.
> > The main reason I am not submitting PRs to the original repo is I've been pushing code, bug fixes, etc. almost every day for the past two weeks, and it would become a big roadblock in terms of propagating the updates to users by not being one of the maintainers of the repo and having creative control.
> > If we need to come up with some compromise in terms of how to handle this, i.e. me attempting to become a maintainer of the OG repo, I am open to it, but core parts of the code have diverged in my version, and every big bug present in the original repo has been fixed in my fork. There has been confusion lately with people pulling the OG AnimateDiff extension using ComfyUI-Manager in an attempt to get my version, and reference my fork's README but reporting issues about the original repo that are no longer present in my fork.
> 
> If you want to take a completely different direction in development without contributing to the original repo, it might be a good idea to change the node name altogether and proceed as an independent project. Maintaining the same node name for an independent project could lead to confusion.

Additionally, you should consider changing the repository name as well. Custom nodes managed by ComfyUI are typically identified by the repository name.

**Comment by Kosinkadink** [comment]
Thanks for the feedback, I agree that making the name different makes the most sense at this point. I've renamed my repository to ComfyUI-AnimateDiff-Evolved: https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved

**Comment by ltdrdata** [comment]
> Thanks for the feedback, I agree that making the name different makes the most sense at this point. I've renamed my repository to ComfyUI-AnimateDiff-Evolved: https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved

There is still node name conflict.
`AnimateDiffUnload`, `AnimateDiffCombine`

Since you're planning to rename them anyway, how about adding a consistent prefix or postfix to the node names in `NODE_CLASS_MAPPINGS` this time?

such as ...

```
NODE_CLASS_MAPPINGS = {
    "KS_CheckpointLoaderSimpleWithNoiseSelect": CheckpointLoaderSimpleWithNoiseSelect,
    "KS_AnimateDiffLoader": AnimateDiffLoader,
...
```

This naming will prevent potential name conflict.

**Comment by Kosinkadink** [comment]
Gotcha, I've now updated the mapping names of the conflicting nodes as well as one of the least-used nodes, the legacy one. I kept CheckpointLoaderSimpleWithNoiseSelect and AnimateDiffLoaderV1 the same as those are the most commonly used nodes, and would be the most frustrating to replace for existing users. They do not conflict with the OG AnimateDiff nodes, so I think it's a fair compromise between ComfyUI-Manager compatibility and old workflow reuse. Had to replace all the example workflows too on the README to make sure the old id'ed nodes would not be included.

**Comment by ltdrdata** [comment]
> Gotcha, I've now updated the mapping names of the conflicting nodes as well as one of the least-used nodes, the legacy one. I kept CheckpointLoaderSimpleWithNoiseSelect and AnimateDiffLoaderV1 the same as those are the most commonly used nodes, and would be the most frustrating to replace for existing users. They do not conflict with the OG AnimateDiff nodes, so I think it's a fair compromise between ComfyUI-Manager compatibility and old workflow reuse. Had to replace all the example workflows too on the README to make sure the old id'ed nodes would not be included.

I'd moved your repo from forked channel to default channel.

**Comment by Kosinkadink** [comment]
Awesome, thanks!
