### ISSUE TITLE
hello I hope you are all well I am running into this isssue on comftui

### ISSUE THREAD

**Issue by mannix97** [Comfy-Org/ComfyUI-Manager#989]
![2024-08-19 (2)](https://github.com/user-attachments/assets/bd25bf10-72f9-4978-9cf3-e5f9a678ee8c)
I am wondering any of you lot could help me please

**Comment by ltdrdata** [comment]
This issue should be handled in following repo.
https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues
