### ISSUE TITLE
controlnet disabled

### ISSUE THREAD

**Issue by Reallge** [Comfy-Org/ComfyUI-Manager#99]
controlnet cannot be installed in A1111 list, it`s disabled, please fix this. thx

**Comment by ltdrdata** [comment]
Are you saying there is an issue when installing `ControlNet Auxiliary Preprocessors` through `ComfyUI-Manager` in `sd-webui-comfyui`?

**Comment by qq675413020** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Manager/assets/74399646/bed53c13-b223-4d11-89c8-c1c0a4d7cce1)
