### ISSUE TITLE
Some errors in Model list

### ISSUE THREAD

**Issue by tiptinker** [Comfy-Org/ComfyUI-Manager#993]
![image](https://github.com/user-attachments/assets/993505f2-c9f7-477c-adb3-e2db73e8e510)

https://huggingface.co/xinsir/controlnet-union-sdxl-1.0/tree/main

Could you pls add this one?
https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union/tree/main

**Comment by tiptinker** [comment]
![image](https://github.com/user-attachments/assets/9f27b8ec-896a-4211-ac77-f87b177b09c3)


This should be FLUX VAE for both dev and sch ?

**Comment by tiptinker** [comment]
![image](https://github.com/user-attachments/assets/29cdfee1-e9be-4443-a40c-d383818bc125)


This should be checkerpoint ?


Also pls add **flux1-dev.safetensors**

https://huggingface.co/black-forest-labs/FLUX.1-dev/tree/main

**Comment by ltdrdata** [comment]
1. InstantX's union controlnet is added and typo fixed.
2. `ae.sft` for dev and schnell is same. So I just modified description.
3. I didn't add `flux1-dev.safetensors` because it requires 'log in' and 'agree' the agreement.

**Comment by tiptinker** [comment]
Thank you!

I found something else that might be similar.

VAE and vae, should be the same?
![image](https://github.com/user-attachments/assets/78b90667-0b82-4ea0-808c-51076172d238)

SDXL and SDXL 1.0, should be the same?
![image](https://github.com/user-attachments/assets/cd642cf3-dcde-4e89-97bf-041ce0e91a58)

vit-g and ViT-G, shoudlbe the same?
![image](https://github.com/user-attachments/assets/82924534-7c43-4701-ba89-c9ac207b67e5)

Maybe combine them into one make things cleaner.

**Comment by ltdrdata** [comment]
> Thank you!
> 
> I found something else that might be similar.
> 
> VAE and vae, should be the same? ![image](https://private-user-images.githubusercontent.com/32961592/361101035-78b90667-0b82-4ea0-808c-51076172d238.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NzY5NjIsIm5iZiI6MTcyNDQ3NjY2MiwicGF0aCI6Ii8zMjk2MTU5Mi8zNjExMDEwMzUtNzhiOTA2NjctMGI4Mi00ZWEwLTgwOGMtNTEwNzYxNzJkMjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDA1MTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZmU3YjU4OGQ3Y2FlOWI4ZmY4MjcwYjExZThmOGVmYTMyN2Q5N2Q1NWI1NTkxY2M2ZjRhNDBlYTAzYjMzZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xaudwKTXj68SopjahX7ZiO-kmiLqsu_Aq3Cr1X24YwM)
> 
> SDXL and SDXL 1.0, should be the same? ![image](https://private-user-images.githubusercontent.com/32961592/361101077-cd642cf3-dcde-4e89-97bf-041ce0e91a58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NzY5NjIsIm5iZiI6MTcyNDQ3NjY2MiwicGF0aCI6Ii8zMjk2MTU5Mi8zNjExMDEwNzctY2Q2NDJjZjMtZGNkZS00ZTg5LTk3YmYtMDQxY2UwZTkxYTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDA1MTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMTY2MmIzMmIxZTRjNjk0MzQxYmVmYzg2ZTVmMWI5MzhlMGNkNTAyYjRlNTc2NDA4ZjU2ZWYwMzRkY2E1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.er1xezqCpi7vZXqWdZiWhkpZefo4OxZiB4d8yIkGlVI)
> 
> vit-g and ViT-G, shoudlbe the same? ![image](https://private-user-images.githubusercontent.com/32961592/361101116-82924534-7c43-4701-ba89-c9ac207b67e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NzY5NjIsIm5iZiI6MTcyNDQ3NjY2MiwicGF0aCI6Ii8zMjk2MTU5Mi8zNjExMDExMTYtODI5MjQ1MzQtN2M0My00NzAxLWJhODktYzlhYzIwN2I2N2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDA1MTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NjAzY2VkMjI3MThmOTQxYmQ1MDAyYzNlM2ZlYjc5M2Q2NDI3YmRmMTc5ZmI5MjYyMmQ0YTNkNGU5N2JiOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YtFAGvoT4_Dk4wXluZKK1NAUUpDiuorvkKdaal6q47c)
> 
> Maybe combine them into one make things cleaner.

That is fixed.

**Comment by tiptinker** [comment]
Hi, can SDXL and SDXL 1.0 combined too?

![image](https://github.com/user-attachments/assets/cadcb039-f315-4bdf-a55f-f3eff59350e9)


Can you add this? it's a sdxl speedup lora, better than Lightning and Hyper.
https://huggingface.co/tianweiy/DMD2/tree/main

dmd2_sdxl_4step_lora.safetensors
dmd2_sdxl_4step_lora_fp16.safetensors

**Comment by ltdrdata** [comment]
fixed.

**Comment by tiptinker** [comment]
Can you add Hyper lora and DMD2 lora? they are better than lightning lora.

https://huggingface.co/ByteDance/Hyper-SD/tree/main
https://huggingface.co/tianweiy/DMD2/tree/main



![image](https://github.com/user-attachments/assets/3d7ffabc-2932-4706-9c31-0d50b3184c57)

**Comment by ltdrdata** [comment]
They are added.

**Comment by tiptinker** [comment]
![image](https://github.com/user-attachments/assets/b5e8871e-7b9b-47ac-b159-9ffe896270ec)


[flux1-schnell.safetensors](https://huggingface.co/black-forest-labs/FLUX.1-schnell/blob/main/flux1-schnell.safetensors)   it contains clips, should be categorized as checkpoint?

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/32961592/361243623-b5e8871e-7b9b-47ac-b159-9ffe896270ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDIwMTksIm5iZiI6MTcyNDYwMTcxOSwicGF0aCI6Ii8zMjk2MTU5Mi8zNjEyNDM2MjMtYjVlODg3MWUtN2I5Yi00N2FjLWIxNTktOWZmZTg5NjI3MGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE2MDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYWYyNDc1MThlNTU1ZGM3OTA2MWM1ZTIxY2RmZmVlZmY2NTZjMzQ2ZGM1NzgzNDE1ZDFkNjNhZTcwNmNiMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xekshIydZJqUghtYvHzzWoTmlm7wdCIV1M5H3qrJvF8)
> 
> [flux1-schnell.safetensors](https://huggingface.co/black-forest-labs/FLUX.1-schnell/blob/main/flux1-schnell.safetensors) it contains clips, should be categorized as checkpoint?

Nope. It's not. It is just a diffusion model. That model doesn't contains textencoder.

**Comment by tiptinker** [comment]
![image](https://github.com/user-attachments/assets/28c32229-db12-4ea5-b43c-7f019f33c2df)


You're right.

**Comment by tiptinker** [comment]
https://huggingface.co/ByteDance/Hyper-SD/tree/main

![image](https://github.com/user-attachments/assets/de0083f8-2e3b-44e8-8644-059b060eccd5)


Just updated.

**Comment by ltdrdata** [comment]
Added.

**Comment by tiptinker** [comment]
Pls add this 

https://huggingface.co/Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro/tree/main

FLUX.1-dev-ControlNet-Union-Pro

**Comment by tiptinker** [comment]
Pls add long clip_l 
https://huggingface.co/zer0int/CLIP-GmP-ViT-L-14/tree/main

![image](https://github.com/user-attachments/assets/526b32cb-91e5-47ed-aa86-fc3ddced2b6f)

![image](https://github.com/user-attachments/assets/d1c64758-75ae-457f-bd5a-8d0cb68562d4)

**Comment by ltdrdata** [comment]
long clip is added.

**Comment by tiptinker** [comment]
> Pls add this
> 
> https://huggingface.co/Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro/tree/main
> 
> FLUX.1-dev-ControlNet-Union-Pro

Pls add fp8 version of this contronet model, reduced the size by half.
https://huggingface.co/Kijai/flux-fp8/blob/main/flux_shakker_labs_union_pro-fp8_e4m3fn.safetensors

**Comment by ltdrdata** [comment]
The model is added.

**Comment by tiptinker** [comment]
https://huggingface.co/jasperai/Flux.1-dev-Controlnet-Upscaler/tree/main

Hi, pls add this upscaler model for flux.

**Comment by ltdrdata** [comment]
This is added.

**Comment by tiptinker** [comment]
Can we optimize the save path of controlnet models?

for SD1.5, save path:  controlnet/SD1.5
![image](https://github.com/user-attachments/assets/99f322ee-af01-45d5-91e2-588ed46f35f6)

for SDXL, save path:  controlnet/SDXL
![image](https://github.com/user-attachments/assets/70eecf59-1bc8-4226-b958-5151a294e733)

You have already perfect save path for flux:
![image](https://github.com/user-attachments/assets/7778118f-5561-4325-a493-ca7537c09ade)


Things will be well organized like this:

![image](https://github.com/user-attachments/assets/84f45d34-149b-476a-9994-1041c6e999a8)

**Comment by pandayummy** [comment]
Hi, pls add pulid model

https://huggingface.co/guozinan/PuLID/tree/main

as seen in
https://github.com/ToTheBeginning/PuLID/blob/main/docs/pulid_for_flux.md
![image](https://github.com/user-attachments/assets/8992196e-143c-4bd1-8b94-bc26f08d38a1)

**Comment by pandayummy** [comment]
[T2I-Style model](https://huggingface.co/TencentARC/T2I-Adapter)

T2I-Style model should be put in models\style_models
![image](https://github.com/user-attachments/assets/98ffe6e0-8423-4d0c-80ed-80b0f0fae4e4)

it's downloaded to controlnet folder now.

**Comment by tiptinker** [comment]
![image](https://github.com/user-attachments/assets/68978443-ca49-484d-8efe-afe95af72ce9)

https://huggingface.co/openai/clip-vit-large-patch14/tree/main
It's better to use the safetentor format:

![image](https://github.com/user-attachments/assets/6cf5fce7-d820-4d91-bb53-0094e328cce3)

**Comment by ltdrdata** [comment]
That is modified.

**Comment by tiptinker** [comment]
https://huggingface.co/lightx2v/Qwen-Image-Lightning

Can we have these speedup loras in the manager? thanks
