### ISSUE TITLE
Install model 'ESRGAN x4' into 'C:\ComfyUI_windows_portable\ComfyUI\models\upscale_models\ESRGAN [ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

### ISSUE THREAD

**Issue by DiXfeb** [Comfy-Org/ComfyUI-Manager#998]
Good day! When I try to install any upscaler via "Model manager" button, I get the following message: 
Install model 'ESRGAN x4' into 'C:\ComfyUI_windows_portable\ComfyUI\models\upscale_models\ESRGAN_4x.pth'
[ERROR] <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

Could you help, please?

**Comment by ltdrdata** [comment]
Take a look following section:
https://github.com/ltdrdata/ComfyUI-Manager#troubleshooting
